### ISSUE TITLE
Form icon glitch

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#1825] opened 2019-09-09 11:12 UTC
* .NET Core Version: Preview9
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

Issue with drawing main form Icon on windows 7, 10 x64.

**Actual behavior and Expected behavior:**
![Snipaste_2019-09-09_13-58-20](https://user-images.githubusercontent.com/17767561/64526138-35123f00-d30b-11e9-8e23-13af8d233668.png)

**Minimal repro:**
[WinFormsCoreTest.zip](https://github.com/dotnet/winforms/files/3590143/WinFormsCoreTest.zip)

**Comment by RussKie** [comment] 2019-09-09 14:11
@Olina-Zhang could you please confirm the issue.
Thank you

**Comment by Olina-Zhang** [comment] 2019-09-10 08:10
@Russkie, this issue can repro in simple core app, the display of form icon using the icon from kirsan31's app is different from .Net framework app. Although size of Icons are same, but their bitDepth are different. Please see following screenshot:
![image](https://user-images.githubusercontent.com/26474449/64595700-154f4980-d3e5-11e9-8534-a2deb74a48ea.png)
.net Core and .net Framework apps:
[CoreApp.zip](https://github.com/dotnet/winforms/files/3594513/CoreApp.zip)
[FrameworkApp.zip](https://github.com/dotnet/winforms/files/3594515/FrameworkApp.zip)

**Comment by RussKie** [comment] 2019-09-10 14:33
Thank you Olina.
Just to confirm, does the issue only appear on W7? I tried it locally on W10 and I couldn't repro it.

**Comment by kirsan31** [comment] 2019-09-10 14:48
@RussKie 
> Just to confirm, does the issue only appear on W7? I tried it locally on W10 and I couldn't repro it.

As I mentioned in first post, I can repro it on win7 and win10 (pro for Workstation 1903).

**Comment by RussKie** [comment] 2019-09-10 14:52
My apoligies, I misread the original report

**Comment by RussKie** [comment] 2019-09-10 17:04
I can reproduce it with the supplied icon:
![image](https://user-images.githubusercontent.com/4403806/64634104-332ca680-d405-11e9-9d37-b7b9bf77e5cd.png)




However using other icons (from https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design) everything is working as expected on  W10E 1903:

* the current release/3.0 (b88058ce22a6773455e508acbb6c23093506e932):
![image](https://user-images.githubusercontent.com/4403806/64630802-85b69480-d3fe-11e9-9915-406f68db819a.png)
* the release/3.0-rc1 (59ef5c56a4c9f94abaada724b9e3d4bd35ab2df6)
![image](https://user-images.githubusercontent.com/4403806/64633738-75a1b380-d404-11e9-9f2a-278b240f3ed1.png)

**Comment by kirsan31** [comment] 2019-09-10 17:38
@RussKie I think that it's very strange, that I didn't notice this in previous previews (I was using 5 and 7 before 9)...
I uninstalled preview**9** and installed preview**7**. And yes on preview7 this icon displayed correctly!
Then I tried preview8 - same as preview9. So regression was introduce in preview**8**.

**Comment by RussKie** [comment] 2019-09-10 17:40
> Then I tried preview8 - same as preview9. So regression was introduce in preview**8**.

Thank you for testing it

**Comment by RussKie** [comment] 2019-09-11 11:56
It looks like a regression in CoreFx in the way `Icon` loads the information from a stream of bytes.

I have used the repro app provided (thank you) and extended it to show-case the problem.
I have serialiesd two icons - the one provided with the repro (icon.ico) and another [one from WinForms repo](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/256_1.ico) (good.ico) using the VS designer.
I have then used the base64 encoded strings to re-create icons.

My repro app can be found here - https://github.com/RussKie/Test-IconDeserialiser


@danmosemsft @ericstj could you please move the issue to the CoreFx repo

**Comment by RussKie** [comment] 2019-09-11 12:05
Looking at the changes I wonder if https://github.com/dotnet/corefx/commit/b75421a0035bf3a44e1f68447255470d57074dbb/src/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs has introduced the regression, as it fits with the timeline

/cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment] 2019-09-11 18:39
> Looking at the changes I wonder if dotnet/corefx@b75421a/src/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs has introduced the regression, as it fits with the timeline

Might have. I'll look into it.

**Comment by JeremyKuhne** [comment] 2019-09-12 02:31
Yep, I messed it up. :/ It's picking the first one that comes closest to the desired size, which in the case of this icon is the black and white 32x32 icon (which matches `SM_CXICON` x `SM_CYICON`). I'm fixing it, but I'm not entirely sure when it will make it to official builds.

You can hack around it by stripping the other colors out or making sure the 32bit one is first in the icon.

**Comment by JeremyKuhne** [comment] 2019-09-12 03:29
https://github.com/dotnet/corefx/pull/41048

**Comment by kirsan31** [comment] 2019-09-12 07:36
> You can hack around it by stripping the other colors out or making sure the 32bit one is first in the icon.

Thanks for workaround, it's working.

**Comment by RussKie** [comment] 2019-09-19 16:33
@JeremyKuhne do you know if the fix has been ported to 3.0?

**Comment by ericstj** [comment] 2019-09-19 16:40
https://github.com/dotnet/corefx/issues/41068 is tracking getting this fix in post GA.  It will be one of the first servicing fixes we take.

**Comment by RussKie** [comment] 2019-09-19 16:41
Thank you Eric.

**Closed by RussKie** 2019-09-19 16:41 UTC
Labels: Regression, bug, won't fix: external

**Comment by Thea-Zhao** [comment] 2019-09-25 08:15
Verified this bug in .Net Core SDK 3.1.100-preview1-014066 build from release branch. This bug is fixed. Please see following screenshot:
![09 25](https://user-images.githubusercontent.com/53589182/65582241-9c88e980-dfaf-11e9-8a74-711cfc1d34a2.png)

**Comment by JeremyKuhne** [comment] 2019-09-30 17:51
This has been merged into .NET Core 3.0 and will show up in the next servicing release.
