### ISSUE TITLE
(Loading Designer...) Form Designer Fails to Display

### ISSUE THREAD

**Issue by Njoro007** [dotnet/winforms#6492] opened 2022-01-11 14:18 UTC
* .NET Core Version: 6.0.101

* Visual Studio 2022 Version 17.0.4

When opening a Form Designer it Displays the Message "Loading Designer..."(Image Attached) and completely doesn't display the Form Designer. What should one do to have the Form Designer Displayed? Form Designer sometimes shows after a few VS Restarts or sometimes lucky to have it displayed the first time VS starts. I didn't experience this using VS 2019 NET 5
![Screenshot 2022-01-11 171702](https://user-images.githubusercontent.com/22431006/148959516-04912444-3582-4112-8fda-d463212f69b3.png)

**Comment by dreddy-work** [comment] 2022-01-11 17:59
@Shyam-Gupta, can you follow-up here?

**Comment by Shyam-Gupta** [comment] 2022-01-11 19:53
@Njoro007 Could you please provide following information:

1. Do you see this issue for any specific project or does it happen even for new projects ?
2. Please confirm if you can build the project successfully.
3. When this issue occurs, please check [Windows EventVwr logs](https://www.windowscentral.com/how-use-event-viewer-windows-10) and check if you see any errors with `devenv.exe`, `DesignToolsServer.exe` or `.NET runtime`. Please share them with us.
4. WinForms .NET Designer output window logs. Steps:

> 1. Launch Visual Studio and open tab: `Tools -> Options -> Windows Forms Designer -> General`
> 2. Set `.NET Core` -> `Logging level` to `Verbose`
> 3. Press Ok to save the changes
> 4. Open Output Window: `View -> Output`
> 5. Repro the issue
> 6. In the `Output` window, select `Windows Forms` for `Show output from` option
> 7. Copy the contents to a txt file and share it with us
> 8. Use steps 1 and 2 to change `Logging level` back to `None`

**Comment by Njoro007** [comment] 2022-01-12 12:43
1.  The issue is very random. It happens in any Project (Old or New), NET 5 or NET 6. I sometimes get lucky to have the Windows Form Designer Display the Form. Sometimes even with numerous VS restarts doesn't work.

2. Yes All Projects Build Successfully, I'm able to debug as well

3. I'm finding a number of errors only on DesignerToolsServer.exe 

4. [15:13:42.6740614] [Foresight Property]: Launching design tools server process...
[15:13:43.6684551] Creating VSCodeDomDesignerLoader
[15:13:52.7278373] [Foresight Property]: Timed out while connecting to named pipe: DesignToolsServer.340e7bf1-6d59-4c76-bbd8-318bea1b56bf
[15:13:52.9539640] Microsoft.DotNet.DesignTools.Client.ServerException: Timed out while connecting to named pipe.
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<ConnectToStreamAsync>d__30.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<LaunchAsync>d__25.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__35.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[15:14:10.1764439] Creating VSCodeDomDesignerLoader

**Comment by kirsan31** [comment] 2022-01-12 13:54
I can add my 50 cents on this.

For me most of the time (if not all)  this happens when you open solution with remembered (opened) forms designers (like we see in video above). And the more such forms there are, the higher the likelihood that they will not open.
As a result, I got used to always closing the form after using the designer.

Also when using designer VS frequently silently crashing (exit all processes).
As a result, I got used to always save my work before using designer and in the process of using it.

**Comment by Shyam-Gupta** [comment] 2022-01-12 21:38
@Njoro007 Thank you for sharing the information. From the logs, I can confirm that its happening because `DesignToolsServer` process is exiting on launch. If you could share the EventVwr logs for this process, then it will help me identify the root cause.

Also let me know the project `Target Framework` and output of following command when executed in Visual Studio Developer Command prompt: `"c:\Program Files\dotnet\dotnet.exe" --list-runtimes`.

**Comment by Shyam-Gupta** [comment] 2022-01-12 21:41
@kirsan31 Whenever the issue reproes for you, could you please share `WinForms output window logs`, and `EventVwr` logs for `devenv.exe` and `DesignToolsServer.exe`. Thanks.

**Comment by Arcalise08** [comment] 2022-01-13 23:03
I am effected by the same bug. I leave windows forms designer on verbose mode. I have virtually the same error as the OP here. It does it randomly. There are no EventVwr logs pertaining to the event either.  Frustratingly, It isnt enough to close the form and reopen it. After getting the named_pipe timeout you must restart visual studio for it to try again.

**Comment by Shyam-Gupta** [comment] 2022-01-13 23:08
@Arcalise08 What is the `Visual Studio` version you are using ? Did it work for you in earlier versions ?

**Comment by foller** [comment] 2022-01-14 04:13
I had the same problem today.
By taking a good look at the errors and things I messed with before the error started happening. I verified that it is looking for the file from the temp folder. One of my projects has a reference to a project with a higher version and that caused an error when loading the logger. I tested it by deleting the contents of the Temp folder and creating a new project. That solved the problem. I went back in the project and removed the references to packages with a higher version. I deleted the data from the temp folder and ran it again. Worked perfectly.
Before that I had tried reinstalling windows, installed VS 2022, went back pc updates and nothing worked.


The solution was to upgrade the project's version from .net 5 to .net 6 or remove the reference project with the highest version and delete the contents of the temp folder.

**Comment by Arcalise08** [comment] 2022-01-14 05:06
> @Arcalise08 What is the `Visual Studio` version you are using ? Did it work for you in earlier versions ?

I confirmed this issue in 17.0.4, 17.0.5 and 17.1.0

The code base on question was recently upgraded from .net framework 4.6. It is a legacy codebase. And the designer was originally not happy because the project was stuck on x86 builds. And just about no forms would load no matter how many times I tried. I made some adjustments that allowed me to build in x64 bit and now the designer works sometimes. 

@foller I'm not sure how you were able to reference a project with a higher .net version in the first place. But it sounds like not the same root cause as our case. Our entire solution is the same .net version

**Comment by Shyam-Gupta** [comment] 2022-01-14 08:18
@Arcalise08 Could you please check if appropriate runtime versions are installed with `Visual Studio`. These options are available in `Visual Studio Installer` -> `Modify` -> `Individual Components` tab. If they are not installed then try installing them and see if problem gets resolved.

![image](https://user-images.githubusercontent.com/24871676/149474152-f7e249a7-38ac-4fc2-a523-b17e3227660b.png)

**Comment by Shyam-Gupta** [comment] 2022-01-14 08:25
@Arcalise08 We have made some fixes related to x86 projects in .NET (Core) designer and they should be available in an upcoming 17.1 Preview release.

**Comment by foller** [comment] 2022-01-14 11:24
@Arcalise08 let me explain better. The error is the same. 

in my case it copies the App.designer.deps.json and App.designer.runtimeconfig.json files to the Local\temp folder. In my case, I believe there was a larger version of Microsoft.Extensions.Logging installed inside one of the packages with a version greater than my project version 5.0.
![image](https://user-images.githubusercontent.com/4506339/149504408-5939bc5a-921f-4426-9bc7-eb84f99c48f3.png)
referring to how I was using a larger version than my project. I have created a nuget package to use dependency injection  with entityFramework on all my projects.
https://www.nuget.org/packages/HyperCrud
in this package I made some references to preview versions, which works perfectly in windows forms and other types of projects, but causes the preview error.

![image](https://user-images.githubusercontent.com/4506339/149505698-9acd7178-e212-4723-9359-0d461774a014.png)
![image](https://user-images.githubusercontent.com/4506339/149505806-b711792b-8a62-4667-be28-355bdc4895cc.png)

by changing the project to the .net 6 version and using VS 2022 it copies the file with a updated version to the temp folder which is used to run the named pipe.
![image](https://user-images.githubusercontent.com/4506339/149507232-493f33db-9542-455d-80d4-908bd343cf71.png)

if you open the files you will see that inside it there are references to the packages used inside all the packages referenced by your project. including versions being replaced by major versions that are within a referenced package.
![image](https://user-images.githubusercontent.com/4506339/149507617-30f89eae-3c4c-40b5-8e5f-b19b172ab18c.png)

**Comment by Arcalise08** [comment] 2022-01-14 15:44
@Foller 

Although the symptoms are the same (designer not loading) the root cause is different. We are seeing a `Timed out while connecting to named pipe: DesignToolsServer.340e7bf1-6d59-4c76-bbd8-318bea1b56bf` with no other errors and nothing pointing to a cause. 

@Shyam-Gupta  I've yet to have this issue happen again after installing .net core 3.1 runtimes. However since the issue is intermittent im hesitant to say that fixed it. It also seems very odd to me that a missing runtime would cause an issue only sometimes. I would imagine that would cause an issue all the time would it not?

**Comment by foller** [comment] 2022-01-14 15:56
in VS2022 i also getting time out. i cood only get the error in the VS 2019.

**Comment by Arcalise08** [comment] 2022-01-14 16:21
@foller we are talking about a VS2022 error

**Comment by kirsan31** [comment] 2022-01-15 07:29
We have [this topic](https://github.com/dotnet/winforms/discussions/6460#discussion-3777116) in discussions with some possible explanation...

**Comment by thomasmiko** [comment] 2022-01-17 10:49
I'm receiving the same error for all .net 5 / .net 6 winforms projects within vs2022 (tried 17.0.4 / 17.0.5 and 17.1.0 Preview).
No relevant errors in the event log.

If i activate the winforms designer logging, i will see the following exception within the output window:

[11:43:30.4038611] Added 'System.Windows.Forms'
[11:43:30.4038611] Loaded System in 00:00:00.0000155 [thread 57]
[11:43:30.4058607] Processed 'System' in 00:00:00.0015471
[11:43:30.4268607] Added 'System'
[11:43:30.4268607] Loaded System.Drawing in 00:00:00.0000154 [thread 63]
[11:43:30.4268607] Processed 'System.Drawing' in 00:00:00.0000990
[11:43:30.4298593] Added 'System.Drawing'
[11:43:30.4298593] Loaded System.Design in 00:00:00.0000148 [thread 63]
[11:43:30.4508616] Processed 'System.Design' in 00:00:00.0206714
[11:43:30.4518627] Creating VSCodeDomDesignerLoader
[11:43:30.4688629] Added 'System.Design'
[11:43:30.4688629] Loaded System.Drawing.Design in 00:00:00.0000225 [thread 43]
[11:43:30.4688629] Processed 'System.Drawing.Design' in 00:00:00.0003160
[11:43:30.4698632] Added 'System.Drawing.Design'
[11:43:30.6208970] Start processing enqueued assemblies
[11:43:30.6208970] Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000155 [thread 43]
[11:43:30.6228620] Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.0016770
[11:43:30.6268617] Added 'Microsoft.WinForms.DesignTools.Protocol'
[11:43:30.6268617] Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000111 [thread 43]
[11:43:30.6601409] Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.0330709
[11:43:30.6618655] Added 'Microsoft.WinForms.DesignTools.Client'
**[11:43:32.0278654] System.ArgumentException: Illegal characters in path.
                      at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)**
                      at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
                      at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder..ctor()
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.<CreateAsync>d__8.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<CreateAsync>d__18.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__35.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

It's an exception with illegal characters in path, but i don't know which path is meant. The source file is at the following location (also tried other locations):

%USER%\source\repos\WinFormsApp5\WinFormsApp5\Form1.cs

**Comment by thomasmiko** [comment] 2022-01-17 12:18
> [11:43:32.0278654] System.ArgumentException: Illegal characters in path.
> at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)

I've solved it for my kind of error via an workaround. 

Looked via referencesource at the source of EmulateFileIOPermissionChecks and saw that the checks are only performed when the UseLegacyPathHandling switch is active. I have disabled the switch via devenv.exe.config and now the designer for .net 5 / .net 6 is working.

**Closed** 2022-02-17 07:01 UTC
Labels: area: VS designer
