### ISSUE TITLE
[Accessibility] After selecting ListView item with mouse and then space selected, Narrator can't display and read out the current status

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#10354] opened 2023-11-22 07:56 UTC
### .NET version

9.0.100-alpha.1.23564.26

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this issue also repro's on .NET 6.0/7.0/8.0.

### Issue description

Narrator can't display and read out the current state of a ListView item when it is selected with mouse and then space-selected, but Narrator can display and read out the current state of a ListView item when it is selected with keyboard and then space-selected.

**The behavior for .NET 9.0:**
![space](https://github.com/dotnet/winforms/assets/104609169/a9be8f4d-78da-4351-9858-34bf407bde27)

https://github.com/dotnet/winforms/assets/104609169/1ca4e6aa-217f-4408-9ba5-2f8de046e3a0

**The behavior for .Net framework:**
![framework](https://github.com/dotnet/winforms/assets/104609169/2348b3cd-b904-43ed-96d2-c61d227a97f1)

https://github.com/dotnet/winforms/assets/104609169/8c58afaa-f865-42b3-8664-1f5dd76dbe36

### Steps to reproduce
[WinFormsApp28.zip](https://github.com/dotnet/winforms/files/13435385/WinFormsApp28.zip)

1. Create a WinForms .NET Core application with ListView control.
2. Add some columns and items to it and set the checkbox property to true.
3. Set ListView's View as Details.
4. Build and run the application.
5. Launch the Narrator tool, try to focus on the first item of the ListView with the mouse.
6. Type the space bar.
7. Press up/down keyboard to focus on the next item.
8. Type the space bar.

**Comment by merriemcgaw** [comment] 2023-12-14 00:49
I don't think there's any requirements around Narrator with Mouse vs Keyboard. We'll Won't Fix for this issue (maybe by design even)

**Closed by merriemcgaw** 2023-12-14 00:49 UTC
Labels: tenet-accessibility, untriaged
