### ISSUE TITLE
An error pops up when adding new items(Form, Winforms UserControl…) to ConsoleApp and Class Library .net core application

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1130] opened 2019-06-14 10:09 UTC
* Visual Studio Version: 16.2.0 Preview 3.0 [29013.64.d16.2]
* .NET Core Version:  .NET Core 3.0.100-preview7-012395
* Have you experienced this same bug with .NET Framework?: No

**More info**: This issue cannot repro on Winforms .net core application.

**Steps to Reproduce**:
1. Install .NET Core 3.0 SDK available from https://github.com/dotnet/core-sdk.
2. Create a ConsoleApp .Net Core application.
3. Open the project and right click project to choose ‘Add’, then click ‘New Item’ to choose Windows Form/Winforms User Control..

**Actual Behavior**:
An error pops up. Please see the below screenshot:
![error](https://user-images.githubusercontent.com/49627022/59501400-06ccc100-8ece-11e9-9ecc-a7f35009949a.png)

**Expected Behavior**:
A new form/User Control can be added successfully in this project.

**Comment by RussKie** [comment] 2019-06-17 00:22
Looks like a regression, I've tested the same scenario against the .NET Fx and it worked.

**Comment by merriemcgaw** [comment] 2019-10-04 00:08
@davkean is this something that would land on your team's plate?

**Comment by merriemcgaw** [comment] 2019-10-11 00:00
This is a console app and the project file doesn't have the `<UseWinForms>True</UseWinForms>`
@drewnoakes do you think this is something project system might be interested in picking up?

**Comment by merriemcgaw** [comment] 2019-10-11 00:06
Sorry - we double checked and the behavior seems to be as we'd expect. Closing this issue

**Closed by merriemcgaw** 2019-10-11 00:06 UTC
