### ISSUE TITLE
Leak of NativeImageList

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#3567] opened 2020-07-13 01:10 UTC
The finalizer asserted when I was fiddling around in WinFormsControlTest. Here is the dumped originating stack:

```
   at System.Windows.Forms.ImageList.NativeImageList..ctor(IStream pstm)
   at System.Windows.Forms.ImageListStreamer..ctor(SerializationInfo info, StreamingContext context)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at System.Resources.Extensions.DeserializingResourceReader.ReadBinaryFormattedObject()
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName)
   at WinformsControlsTest.TreeViewTest.InitializeComponent()
   at WinformsControlsTest.TreeViewTest..ctor()
   at WinformsControlsTest.MainForm.<>c.<GetButtonsInitInfo>b__1_9(Object obj, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WinformsControlsTest.Program.Main()
```

**Comment by weltkante** [comment] 2020-07-13 08:59
Yes, the `ImageListStreamer` you get from deserialization needs to be disposed, I had to fix this in several unit tests as well. However from the call stack this instance looks like a WinForms framework bug and not a user code bug.

The problem seems to be that `ComponentResourceManager.FillResources` deserializes a disposable `ImageListStreamer` and assigns it to an `ImageList` control, but neither the `ImageList` nor the `ComponentResourceManager` feels responsible for taking ownership, so nobody disposes it and its left for the GC to release the NativeImageList.

**Comment by RussKie** [comment] 2020-07-13 11:40
Hmm... This is nasty. We don't own [`ComponentResourceManager`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ComponentResourceManager.cs), so it's a pretty much a black box to us. At some point it creates an instance of `ImageListStreamer` that creates an instance of `NativeImageList`. 
I suspect `ImageListStreamer` isn't getting disposed either, else it would dispose the owned instance of `NativeImageList`:
https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs#L262-L272.

It feels that `ComponentResourceManager` is responsible for disposing the streamer 🤔

**Comment by weltkante** [comment] 2020-07-13 11:53
> It feels that `ComponentResourceManager` is responsible for disposing the streamer 🤔

I don't think so, then it would also dispose deserialized `Bitmap` images, wouldn't it? That would mean everyone has to clone resources assigned through `ComponentResourceManager` if they are immediately disposed. Feels like unnecessary overhead.

In my opinion the ownership of the `ImageListStreamer` should be passed on to the `ImageList` control.

**Comment by kirsan31** [comment] 2021-05-19 07:29
We already know two use cases (#4913, #4928) where GDI leak appear due to `NativeImageList` destructor removal.  I wonder, is this doable work - to check for proper disposing of all existing `ImageList` references? And even if so, we still can have cases like #4928...

**Comment by weltkante** [comment] 2021-05-19 10:09
`NativeImageList` doesn't necessarily need a destructor, but `ImageListStreamer` and `ImageList` need to be handling it properly if it doesn't have one.

Note that this is actually two issues, `ImageListStreamer` has the additional issue that its not clear who is "owning" it and should dispose of it in the first place.

Generally I agree _some_ Finalizer needs to be in place, either `ImageListStreamer` and `ImageList`, or on `NativeImageList`. You cannot assume Dispose will be called. Things like Bitmaps don't have a clear owner either, WinForms always needs to have a Finalizer to handle cleanup when the user doesn't.

**Comment by RussKie** [comment] 2021-05-20 06:33
I've spent a little time wading through the ListView test sample with have - it trips on undisposed `NativeImageList` instances (run in DEBUG).
https://github.com/dotnet/winforms/blob/cb8eb664e55af0a0ac0638d491ddf763c8015cec/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs#L33-L145


I observed two different issues:

1. Leaks caused by `this.imageList1.ImageStream = (System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream"));`
I _think_ we can address this leak by the following changes:
    ```diff
    diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs b/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
    index 656058094..1655ee370 100644
    --- a/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
    +++ b/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
    @@ -216,7 +216,7 @@ namespace System.Windows.Forms
                         return;
                     }
     
    -                NativeImageList himl = value.GetNativeImageList();
    +                using NativeImageList himl = value.GetNativeImageList();
                     if (himl != null && himl != _nativeImageList)
                     {
                         bool recreatingHandle = HandleCreated; // We only need to fire RecreateHandle if there was a previous handle
    @@ -250,6 +250,8 @@ namespace System.Windows.Forms
                             OnRecreateHandle(EventArgs.Empty);
                         }
                     }
    +
    +                value.Dispose();
                 }
             }
    ```

    This _may quite likely_ a breaking change, but I think we can make it because `ImageListStreamer` class can't be instantiated nor subclassed, and is more an infrastructural type than a client-facing type. So I think the likelihood of our customers manually tinkering with it is pretty low.

2. Leaks caused by `resources.ApplyResources(...);` calls.
I was unable not find how the created instance of `NativeImageList` is assigned and managed (I haven't had enough time to dig deep). So here I think we should just add a finalizer to `ImageListStreamer`.
❕  This will also help with the 1st issue above.

**Comment by kirsan31** [comment] 2021-05-20 16:18
@RussKie 

We already have a **big silent breaking change** - removal of `NativeImageList` finalizer. That's lead to **critical** problem - GDI leak, even in Winforms repo itself  (#4913, #4928). May be this is not so important for small brief time running apps, but for big and long running it's a pain (due to crush after hard limit gg). GDI leaks are difficult to debug, especial not managed one and if it's not repro on local machine )))
So, this 2 known leaks are only in WinForms itself, and how many we didn't catch yet (for example `TreeView` uses `ImageList` very tightly)? I'm afraid to even think how many of them will be in the user code after migration from .net framework and .net core? And I don't understand how this breaking change silently goes live after assert here and then in #4316?

> 1. Leaks caused by this.imageList1.ImageStream = (System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream"));
> I think we can address this leak by the following changes:

A quick google om `ImageList.ImageStream` return that folks using it time to time. So it will be second breaking change (not that big like first one, but any way). On the other hand, I do not know how to properly solve this problem so as not to rely on the finalizer. The only way I see is designer generated code change - designer need to take care about disposing of `ImageListStreamer`. Or may be some change in `ImageList`,  like:
`this.imageList1.ImageStreamDirect = (System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream"));` Where `ImageStreamDirect` will not duplicate `NativeImageList` (or disposing it like you suggested). But this also require designer change. I think all of this is somehow complicated...

> 2. Leaks caused by resources.ApplyResources(...); calls.
> I was unable not find how the created instance of NativeImageList is assigned and managed (I haven't had enough time to dig deep). So here I think we should just add a finalizer to ImageListStreamer.
> ❕ This will also help with the 1st issue above.

Here and overall  I am totally agree with @weltkante : 

> Generally I agree some finalizer needs to be in place, either `ImageListStreamer` and `ImageList`, or on `NativeImageList`. You cannot assume Dispose will be called. Things like Bitmaps don't have a clear owner either, WinForms always needs to have a Finalizer to handle cleanup when the user doesn't.

To not break existing code, We need 2 finalizers in `ImageListStreamer` **and** `ImageList` or one in `NativeImageList`.

**Comment by RussKie** [comment] 2021-05-21 00:38
> We already have a **big silent breaking change** - removal of `NativeImageList` finalizer.

A fair call, we regressed in https://github.com/dotnet/winforms/pull/3526.

> A quick google om `ImageList.ImageStream` return that folks using it time to time.

Can you please share an example? I couldn't find anything specific that could break by the proposed change.

**Comment by kirsan31** [comment] 2021-05-21 07:35
> Can you please share an example? I couldn't find anything specific that could break by the proposed change.

All usage I found was like this: _get images from serialized ImageList_. [For example](https://stackoverflow.com/a/52645521/6075536).
The problems can happens if you (for some strange reason) need to populate 2 ImageLists with the same images. I modified a bit code from the link above:
```cs
BinaryFormatter formatter = new BinaryFormatter();
string base64 = File.ReadAllText(source);
byte[] bytes = Convert.FromBase64String(base64);
using (Stream stream = new MemoryStream(bytes))
{
    ImageListStreamer streamer = (ImageListStreamer)formatter.Deserialize(stream);
    this.imageList1.ImageStream = streamer;
    this.imageList2.ImageStream = streamer; // problems here
}
```

But I agree, the probability of such a usage is not very high :)

**Closed** 2021-05-25 02:59 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress, tenet-performance
