### ISSUE TITLE
TreeView flickering

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4883] opened 2021-05-08 17:13 UTC
* .NET Core Version: all up to latest (5.0.5).

* Have you experienced this same bug with .NET Framework?:  yes

**Problem description:**
TreeView is flickering (especially on large amount of data):
Native control has [ex. style](https://docs.microsoft.com/en-us/windows/win32/controls/tree-view-control-window-extended-styles) `TVS_EX_DOUBLEBUFFER` that fix the problem:
```cs
private class TreeViewEx : TreeView
{
    private const int TVM_SETEXTENDEDSTYLE = 0x1100 + 44;
    private const int TVS_EX_DOUBLEBUFFER = 0x0004;

    [System.Runtime.InteropServices.DllImport("user32.dll", SetLastError = true)]
    private static extern IntPtr SendMessage(IntPtr HWnd, int Msg, IntPtr Wp, IntPtr Lp);

    protected override void OnHandleCreated(EventArgs e)
    {
        SendMessage(this.Handle, TVM_SETEXTENDEDSTYLE, (IntPtr)TVS_EX_DOUBLEBUFFER, (IntPtr)TVS_EX_DOUBLEBUFFER);
        base.OnHandleCreated(e);
    }
}
```
Left default `TreeView`, Right with `TVS_EX_DOUBLEBUFFER`:
![TreeView](https://user-images.githubusercontent.com/17767561/117547611-224c9200-b039-11eb-8782-a49848dce38b.gif)
[stackoverflow](https://stackoverflow.com/a/10364283/6075536).

**Expected behavior:**
Ability to avoid flickering without Pinvoke  and deriving own class from `TreeView`.
P.s. protected `DoubleBuffered` doesn't solve the problem.
P.p.s. May be _API request_ is more suitable here?

**Minimal repro:**
[TreeViewFlickering.zip](https://github.com/dotnet/winforms/files/6446248/TreeViewFlickering.zip)

**Comment by KlausLoeffelmann** [comment] 2021-05-11 17:22
Well, Double Buffering is something that we should not give up too soon (as a general improvement). It's not only the flickering which is people driving crazy, in my opinion in some cases we even come to a point, where it is _so_ bad that it can become as accessibility problem for folks who want to search by paging throw data, and having a hard time to synchronize the flickering content with their abilities to see.

This is true here and all the more for DataGridViews with large amount of data, so I am +1ing a lot here.

Since we cannot make binary changes and therefore change the scope for the `DoubleBuffered` property, I am wondering if we can introduce something like a `RequestDoubleBuffering` method on control, and then it's up to the control to fulfill that request (returns `true`) or not (returns `false`)?

**Comment by KlausLoeffelmann** [comment] 2021-05-11 17:33
Well, we could make it work that way, couldn't we? What I am saying is, we shouldn't consider DoubleBuffered for this, but...what I wrote.

**Comment by RussKie** [comment] 2021-05-12 00:29
> As i pointed out in 1 post, that in case of `TreeView` `DoubleBuffered` is not helping (with `DataGridView` it does).
> Am I miss something?

I think so :) The point is that we can fix the fact that `DoubleBuffered=true` doesn't do anything. The logical place to me seems fixing it here:
https://github.com/dotnet/winforms/blob/9f61c5569b3b7a7388fbeffdeaefb6bc8ceb9182/src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs#L315-L418

**Comment by RussKie** [comment] 2021-05-12 00:33
> I am wondering if we can introduce something like a `RequestDoubleBuffering` method on control, and then it's up to the control to fulfill that request (returns `true`) or not (returns `false`)?

I left some comments related to this question here: https://github.com/dotnet/winforms/issues/4654#issuecomment-814632604. I'm still open to the idea of making it easy (not _easier_) to enable double-buffering, but we'll need a new well thought proposal for this.

**Comment by KlausLoeffelmann** [comment] 2021-05-12 00:40
A proposal it is.

**Comment by RussKie** [comment] 2021-05-12 03:57
Setting as up for grabs.

**Comment by kirsan31** [comment] 2021-07-18 14:27
@RussKie 
> I left some comments related to this question here: [#4654 (comment)](https://github.com/dotnet/winforms/issues/4654#issuecomment-814632604). I'm still open to the idea of making it easy (not _easier_) to enable double-buffering, but we'll need a new well thought proposal for this.

While I totally agree with your [#4654 (comment)](https://github.com/dotnet/winforms/issues/4654#issuecomment-814632604). But from other side `DoubleBuffered` has always been and is a very specific and inconvenient (I hope don't need to list why). And the `TreeView` situation is one example of this. So, I think implementing `TVS_EX_DOUBLEBUFFER` through protected `DoubleBuffered` is something nearly useless :( You still have to use your inherited control, or reflection.

Why native control can use `TVS_EX_DOUBLEBUFFER` and other [Extended Styles](https://docs.microsoft.com/en-us/windows/win32/controls/tree-view-control-window-extended-styles) directly, but WinForms control no?

**Comment by RussKie** [comment] 2021-07-19 07:55
> So, I think implementing `TVS_EX_DOUBLEBUFFER` through protected `DoubleBuffered` is something not really useful :( You still have to use your inherited control, or reflection anyway.

At least this way it will be consistent with other controls.

> Why native control can use `TVS_EX_DOUBLEBUFFER` and other [Extended Styles](https://docs.microsoft.com/en-us/windows/win32/controls/tree-view-control-window-extended-styles) directly, but WinForms control not?

The only possible explanation I can offer is that our `TreeView` control was implemented back when `TVS_EX_*` properties weren't available, all of them came in Vista.
Which brings us to the point, I'm sure, you're well aware by now - we can add new API that will close the gap, and we're accepting proposals for those :)

**Comment by kirsan31** [comment] 2021-07-19 11:18
@RussKie 
> > So, I think implementing `TVS_EX_DOUBLEBUFFER` through protected `DoubleBuffered` is something not really useful :( You still have to use your inherited control, or reflection anyway.
> 
> At least this way it will be consistent with other controls.

Exactly...


> 
> > Why native control can use `TVS_EX_DOUBLEBUFFER` and other [Extended Styles](https://docs.microsoft.com/en-us/windows/win32/controls/tree-view-control-window-extended-styles) directly, but WinForms control not?
> 
> The only possible explanation I can offer is that our `TreeView` control was implemented back when `TVS_EX_*` properties weren't available, all of them came in Vista.
> Which brings us to the point, I'm sure, you're well aware by now - we can add new API that will close the gap, and we're accepting proposals for those :)

It's subject to discuss...
So we can move 2 way here:
1. Implement only TVS_EX_DOUBLEBUFFER through protected `DoubleBuffered`.
2. Implement all Extended Styles. And then may be use it in `DoubleBuffered`.  
   - Need to discuss which of Extended Styles to implement. I really don't understand some of them. For example: **TVS_EX_DRAWIMAGEASYNC** - *Retrieves calendar grid information.*???
   - Need to discuss how to implement them - bool properties or Some EX_Style property with enum?

**Comment by gabparrot** [comment] 2021-09-21 13:20
How did third party control developers deal with this? Perhaps we should look into how Krypton TreeViews approached the issue considering their extended class does not flicker at all, and they are open source now

**Comment by kirsan31** [comment] 2021-09-21 13:25
> How did third party control developers deal with this? Perhaps we should look into how Krypton's TreeView (or another) approached the issue considering their extended class does not flicker at all, and they are open source now

We exactly know how, all in 1 post ;)

**Comment by Cassie-Li01** [comment] 2022-06-21 08:45
Hi @kirsan31 verified this issue on .NET SDK 5.0, 6.0 & 7.0, we all cannot reproduce this issue with attached project, please correct us if we have done anything wrong, if you also don't reproduce it any longer, we will close this.
![Not repro](https://user-images.githubusercontent.com/96758262/174751908-5fc0626c-b0aa-4a91-bd59-a7f57f9b082e.gif)

**Comment by kirsan31** [comment] 2022-06-21 08:48
@Cassie-Li01 left treeview is clearly flickering on your gif.

**Closed** 2022-07-27 00:19 UTC
Labels: enhancement, up-for-grabs, good first issue, :construction: work in progress
