### ISSUE TITLE
Timed out while connecting to named pipe: DesignToolsServer

### ISSUE THREAD

**Issue by nathan130200** [dotnet/winforms#6420] opened 2021-12-25 19:43 UTC
* .NET Core Version:
.NET 6.0.100

* .NET Info Command
```cs
SDK do .NET (refletindo qualquer global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.207 [c:\program files\dotnet\sdk]
  6.0.100 [c:\program files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Attemt to open winforms designer on NET6 fail everytime.

If i both add `<TargetPlatforms>net472;net6.0-windows</TargetPlatforms>` for both net6.0-windows and net472, the designer open, but open old .NET Framework designet (that works too for .net 6), but i must be forced to reference net framework in csproj.

Since .net core/net 6 desktop support, the designer NEVER WORKED.

Stuck on this:
![image](https://user-images.githubusercontent.com/14365254/147392370-b18afc01-2afd-48a3-b43a-48932f9e3c91.png)

**Expected behavior:**
Open winform designer.

**Minimal repro:**
Create empty winform project on VS2022 and try open `Form1` designer.

**Output from VS2022:**
```cs
[16:30:43.1921519] Creating VSCodeDomDesignerLoader
[16:30:45.1771483] Processed 'System.Design' in 00:00:04.1270162
[16:30:45.2051489] Added 'System.Design'
[16:30:45.2051489] Loaded System.Drawing.Design in 00:00:00.0000212 [thread 10]
[16:30:45.2091460] Processed 'System.Drawing.Design' in 00:00:00.0042542
[16:30:45.2101469] Added 'System.Drawing.Design'
[16:30:45.3011495] Start processing enqueued assemblies
[16:30:45.3021480] Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000206 [thread 10]
[16:30:45.4881486] Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.1868933
[16:30:45.4941472] Added 'Microsoft.WinForms.DesignTools.Protocol'
[16:30:45.4951483] Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000363 [thread 87]
[16:30:45.7031461] Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.2081947
[16:30:45.7081489] Added 'Microsoft.WinForms.DesignTools.Client'
[16:30:54.2412176] [CraftMonitor]: Preparing shadow cache folder
[16:30:54.2442114] [CraftMonitor]: Copying design tools server common files from: 'c:\program files\microsoft visual studio\2022\preview\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\Common'
[16:31:03.1555740] [CraftMonitor]: Copying design tool server platform-specific files from: 'c:\program files\microsoft visual studio\2022\preview\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\x64'
[16:31:03.3375745] [CraftMonitor]: Copying 'C:\Users\natha\source\repos\CraftMonitor\CraftMonitor\obj\Debug\net6.0-windows\CraftMonitor.designer.deps.json' to 'DesignToolsServer.deps.json'
[16:31:03.3495751] [CraftMonitor]: Copying 'C:\Users\natha\source\repos\CraftMonitor\CraftMonitor\obj\Debug\net6.0-windows\CraftMonitor.designer.runtimeconfig.json' to 'DesignToolsServer.runtimeconfig.json'
[16:31:03.6065745] [CraftMonitor]: Launching design tools server process...
[16:31:14.6486408] [CraftMonitor]: Timed out while connecting to named pipe: DesignToolsServer.f02e0df7-a9d3-43a5-952b-8d79b383c9b1
[16:31:14.9206458] Microsoft.DotNet.DesignTools.Client.ServerException: Timed out while connecting to named pipe.
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<ConnectToStreamAsync>d__30.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<LaunchAsync>d__25.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__35.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Sometimes in Output window only display first line:

`[16:30:43.1921519] Creating VSCodeDomDesignerLoader`

* CSProj file created by `dotnet new` command targeting windows desktop:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

### Steps i tried:
- Reinstall VS and .NET SDK
- Open both regular version or preview from VS2022
- Reopen file

None of these worked.

https://user-images.githubusercontent.com/14365254/147392615-cd09e099-d44e-48f6-b807-8a4855b5901b.mp4

**Comment by dreddy-work** [comment] 2021-12-27 19:10
@Shyam-Gupta / @RussKie can you guys take a look here and map it to the issue in designer repo?

**Comment by nathan130200** [comment] 2022-01-13 22:44
Hello, someone?

**Comment by dreddy-work** [comment] 2022-01-13 22:47
Linking the similar bugs together #6492. I am guessing they both have same root cause.

**Comment by Shyam-Gupta** [comment] 2022-01-13 22:55
@nathan130200 Could you please share `Windows EventVwr` logs for `DesignToolsServer.exe` when this issue occur.

**Comment by foller** [comment] 2022-01-14 04:13
I had the same problem today.
By taking a good look at the errors and things I messed with before the error started happening. I verified that it is looking for the file from the temp folder. One of my projects has a reference to a project with a higher version and that caused an error when loading the logger. I tested it by deleting the contents of the Temp folder and creating a new project. That solved the problem. I went back in the project and removed the references to packages with a higher version. I deleted the data from the temp folder and ran it again. Worked perfectly.
Before that I had tried reinstalling windows, installed VS 2022, went back pc updates and nothing worked.


The solution was to upgrade the project's version from .net 5 to .net 6 or remove the reference project with the highest version and delete the contents of the temp folder.

**Comment by Bajotumn** [comment] 2022-01-14 15:48
I was able to successfully work around this issue for myself and my team in a 110 project solution.

We added the DesignToolsServer.exe to Windows Defender exceptions so that it is not slowed down by the system call hooks Defender uses to provide real-time protection. The issue has not gone away completely but is now only a minor inconvenience since once the server has started it persists for the lifetime of the Visual Studio run.

```powershell
Add-MpPreference -ExclusionProcess 'DesignToolsServer.exe'
```

**Comment by nathan130200** [comment] 2022-01-14 22:48
@Shyam-Gupta i had same issue, first time show exception "Timeout while connecting remote pipe", next time i try open form, don't show up any logs, neither on Windows Event Viewer also:

https://user-images.githubusercontent.com/14365254/149594961-d2fda802-43f7-44b3-97ae-1f2f0bc2c3a6.mp4

**Comment by nathan130200** [comment] 2022-01-14 22:50
Also in taskmgr don't show up, DesigntToolsServer trying to start

https://user-images.githubusercontent.com/14365254/149595351-22625731-ac94-4400-9b75-db6c19f0b885.mp4

.

**Comment by Shyam-Gupta** [comment] 2022-01-15 04:02
@nathan130200 Thank you so much for sharing the videos. The error regarding `DesignerRuntimeImplementationProjectOutputGroup` is different. Due to this error, WinForms designer will not try to launch `DesignToolsServer` process. Also it tries to launch process for the first time designer is opened. Subsequent closing and reopening of designer will not trigger `DesignToolsServer` process launch. 

I created a new `Windows 10` virtual machine and installed `Visual Studio 2022, 17.0.5 version`. I created both `net5.0-windows` and `net6.0-windows` projects but couldn't repro the issue. Hence I think there is something in the environment I am missing.

Please let me know if you have other Visual Studio versions installed side by side on the same machine. You mentioned that the error reproes even for new WinForms projects. Let me know if you are using Visual Studio new project creation wizard or dotnet.exe command line tool to create the project.

Do you see any error if you create a 6.0 WinForms project, build it and then try to launch the project exe directly from its `bin\debug` directory ? If it fail then check `EventVwr` for errors.

In mean time, I will try to add more diagnostic logs in the product and get back. 

Thanks again for working with me to get to the root cause of this problem.

FYI: @merriemcgaw

**Comment by nathan130200** [comment] 2022-01-16 03:50
I just have VS2022 preview installed, also i did some tests, if i close and reopen project DesignToolsServer was able to start. But its a bit confused.

**Comment by violarulan** [comment] 2022-01-22 04:19
Happened in Current(stable) sersion visual studio 2022 with a C# project and I believe it is the same issue.
In current: open solution, open designer, looks fine but some attributes drag down menu shows nothing (![imgur](https://imgur.com/reEJtIl)), then VS crashes.

After switching to Preview, it shows `Timed out while connecting to named pipe ...` exact the same message.

**Comment by danelec-hpm** [comment] 2022-01-26 12:39
I solved this by removing this section from the csproj file:
`  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>`

**Comment by nathan130200** [comment] 2022-01-26 12:51
In my situation, i just type `dotnet new winforms` and used default csproj created, nothing different packages, and still same problem.

An workaround is close and reopen entire solution to make designer works, but isn't correct specially for big projects.

**Comment by merriemcgaw** [comment] 2022-01-27 01:20
@nathan130200 I wasn't able to repro on my machine - `dotnet new winforms` works perfectly and the project loads just how I'd expect. That said, we are increasing the timeout before DesignToolsServer gives up. Hopefully that will help your situation, and it will be out in the next Preview or 2. We're also spinning up some investments around diagnostics and helping both our users and us collect the information we need to troubleshoot problems. Keep checking out each new Preview and things will improve.

**Comment by nathan130200** [comment] 2022-01-27 10:40
The problem, is VS don't launch design tools server for the first time, idk what cause this. But at second time (after unload/reload entire solution), vs was able to copy design tools server and start.

**Comment by merriemcgaw** [comment] 2022-01-27 21:53
Thanks for the update. Given that this isn't happening to everyone I'm very curious about why it is happening on your installs. We will be adding more logging coverage and other diagnostic services so that we can better figure out what is impacting our customers. We'll let you know when that work is in a Preview so we can test it out together.

**Comment by RussKie** [comment] 2022-02-03 02:16
As an update. 
As a tactical fix we have increase the connection timeout from 10 seconds to 2 minutes. This fix is expected to land in 17.1p5. The team is also working on a more strategic solution, that includes better error reporting and diagnostics, and perf improvements.

**Closed by RussKie** 2022-02-03 02:16 UTC
Labels: area: VS designer

**Comment by smohanty05** [comment] 2022-02-17 09:52
I have a solution file with 100+ projects. It is taking 1-5 to 2 minutes load a designer for a project. Other WinForm of the same project then loads quickly. But if we restart VS or reload project or make any changes to the project, then next WinForm load again taking 1-5 to 2 minutes.
Also I saw one case where it is not loading at all. Open one WinForm of Project1. While waiting, load another WinForm of Project2. After waiting for around 2 minutes, Project2 form designer opens. But Project1 form designer does not open at all. Even closing both forms and reopening Project1 form also does not solve it.
Wokaround: reload Project1 and open the designer.

Hope you will resolve such issues.

**Comment by nathan130200** [comment] 2022-02-19 19:28
Ok, so i got new error (updated to latest preview version from VS2022)

```cs
[16:25:46.8925168] Creating VSCodeDomDesignerLoader
[16:25:47.6300184] Processed 'System.Design' in 00:00:02.4840523
[16:25:47.6830170] Added 'System.Design'
[16:25:47.6840173] Loaded System.Drawing.Design in 00:00:00.0000227 [thread 56]
[16:25:47.6890185] Processed 'System.Drawing.Design' in 00:00:00.0055732
[16:25:47.6900189] Added 'System.Drawing.Design'
[16:25:48.8251525] [Thread 1] Creating design-time ITypeResolutionService.
[16:25:50.5392459] Start processing enqueued assemblies
[16:25:50.5392459] Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000178 [thread 79]
[16:25:50.7015014] Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.1625103
[16:25:50.7055005] Added 'Microsoft.WinForms.DesignTools.Protocol'
[16:25:50.7055005] Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000282 [thread 61]
[16:25:50.8610191] Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.1546868
[16:25:50.8630155] Added 'Microsoft.WinForms.DesignTools.Client'
[16:25:51.3873048] [Thread 68] Launching server...
[16:26:53.4778102] OutputGroupService didn't return output group DesignerRuntimeImplementationProjectOutputGroup.
[16:26:53.4778102] Could not retrieve DesignerRuntimeImplementationProjectOutputGroupPaths for current project.
[16:26:54.1809027] System.InvalidOperationException: Designer load encountered an error. Please ensure that the project can be built successfully.
                      at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.<GetProjectInfoAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__28.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[16:26:54.3889082] Cannot update selection in server process as Session is not connected.
```
