### ISSUE TITLE
Advanced Databinding Editor doesn't show SelectedIndex property for TabControl

### ISSUE THREAD

**Issue by KoenVanExem** [dotnet/winforms#9969] opened 2023-09-21 08:33 UTC
### Environment

Version 17.8.0 Preview 2.0

### .NET version

net8.0-windows

### Issue description

![advanced-databinding-editor](https://github.com/dotnet/winforms/assets/3371452/3912a6b6-6dc2-446e-8502-183b5a9ceb31)

The advanced databinding editor doesn't show the SelectedIndex property for a TabControl.

### Steps to reproduce

If I create another binding and then change it to SelectedIndex, then it still doesn't show up in the advanced databinding editor, but It does show up in the properties grid

![properties](https://github.com/dotnet/winforms/assets/3371452/1bcf2b18-c1e2-4319-8a3c-c7239ac911e4)

This is the line of generated code in my InitializeComponent() method

> this.searchTabControl.DataBindings.Add(new Binding("SelectedIndex", this.viewModelBindingSource, "TabIndex", true, DataSourceUpdateMode.OnPropertyChanged));

**Comment by KlausLoeffelmann** [comment] 2024-07-23 19:43
This is not a regression from Framework.
If you want to make this work, you could subclass the TabControl, and implement a new property (Like `int SelectedTab`), which also provides a `SelectedTabChanged` event. _Then_, you should see the Binding Dialog to pick this up. 

It's by Design. Closing this.

**Closed by KlausLoeffelmann** 2024-07-23 19:43 UTC
Labels: area-Binding
