### ISSUE TITLE
Form.ActiveForm does not return null when an owned model window should not be "active"

### ISSUE THREAD

**Issue by AraHaan** [dotnet/winforms#3003] opened 2020-03-21 16:07 UTC
* .NET Core Version: 

.NET Core 3.1

* Have you experienced this same bug with .NET Framework?: 

Yes

**Problem description:**

When a form is showed the ``ActiveForm`` property on a form returns the form (if main form returns that), or ``null`` when a window from another process is active. However when on a ``Model`` form with the main form as the owner, doing that results in the property always returning that ``Model`` form instead of ``null`` like I think it should. Not even the ``Deactivate`` nor the ``Activated`` events fire when this happens.

**Expected behavior:**
for ``ActiveForm`` to return ``null`` when no forms (including model forms with the main form as owner) when a window from another application is active. Same for the Activated/Deactivate events should also fire as well when this happens or when reclicked on that should make it become Activated again.

**Minimal repro:**

1. Create a new winforms project.
2. Create a in the ``Form1`` code make the form create another form a button in it is clicked making that form the owner of another instance of itself.
3. Do some painting work that uses the ``Paint`` event on the form code that changes colors when 
```cs
// this.active is an added attempt to double check and make sure it is
// active using the Activated/Deactivate events.
if (Equals(ActiveForm, this) && this.active)
{
    // e.Graphics stuff.
}
else
{
    // e.Graphics stuff.
}
```

**Comment by AraHaan** [comment] 2020-03-21 16:23
cc: @RussKie

**Comment by weltkante** [comment] 2020-03-21 16:28
> Have you experienced this same bug with .NET Framework?: Yes

Then you are doing something wrong, I just tested this and `ActiveForm` goes to `null` on Desktop Framework when I put focus to another processes window.

**Comment by AraHaan** [comment] 2020-03-21 16:43
I mean model form as in a form as an owner that when you try to click on the owner of it it will flicker with a sound on windows and diassallow focus on the owner form until that model form is closed.
and I meant on the Form1 code make the form create another instance of it when the button on it is clicked. I remember that when ``dotnet new winforms`` is called it creates ``Form1`` At first I was trying to type to create the 1st form before I remembered that it automatically does it for you.

**Comment by weltkante** [comment] 2020-03-21 16:50
Yeah ok so you mean showing a [modal](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.modal?view=netcore-3.1) form. Unfortunately I cannot replicate what you describe, please share a snippet.

With this example code the `ActiveForm` goes to null when focus leaves the modal form.
<details>
<summary>example</summary>
```csharp
    public partial class Form3 : Form
    {
        public Form3()
        {
            InitializeComponent();

            Name = "Form #" + Application.OpenForms.Count;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (var f3 = new Form3())
                f3.ShowDialog(this);
        }

        private void Form3_Activated(object sender, EventArgs e)
        {
            Debug.WriteLine("Form3_Activated");
        }

        private void Form3_Deactivate(object sender, EventArgs e)
        {
            Debug.WriteLine("Form3_Deactivate");
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            Debug.WriteLine("Active Form: " + (Form.ActiveForm?.Name ?? "<null>"));
        }
    }
```
</details>

**Comment by AraHaan** [comment] 2020-03-21 17:05
Alright so since I got it on github as well the problem github is: https://github.com/Elskom/Els_kom_new
(just pushed the commit with the issue in particular) The issue is in ``Controls/ThemedForm`` which the forms in ``Forms`` subclass from that.

But it depends on packages from: ``https://github.com/AraHaan/MyPackages`` that needs to be cloned recursively and built with ``dotnet build --configuration Release --ignore-failed-sources``

**Comment by weltkante** [comment] 2020-03-21 18:29
Hmm I tried to take a look but you depend on preview packages not present in the normal nuget feeds and I don't know what to add to get things like `Microsoft.Build.Framework` version `16.6.0-preview-20162-03` to resolve. If its nontrivial to build your project on a machine not set up for it you might want to try reducing the problem into a standalone project by removing or stubbing out unnecessary operations while still keeping the problematic behavior intact.

**Comment by RussKie** [comment] 2020-03-22 01:09
@arahaan please provide a small repro that does not involve 3rd party packages.

**Comment by AraHaan** [comment] 2020-03-22 15:30
[TestFormActiveForm.zip](https://github.com/dotnet/winforms/files/4365485/TestFormActiveForm.zip)
Alright here is a zip without any nuget packages. It seems for me that now on this project when trying to reproduce it that now it does that bug on the initial instance as well for some reason too.

**Comment by weltkante** [comment] 2020-03-22 17:08
Thanks, for easier discussion then sending zips back and forth I put it [in a repo](https://github.com/weltkante/TestFormActiveForm) (going to delete it after this issue is resolved)

I [added some diagnostics](https://github.com/weltkante/TestFormActiveForm/commit/eb5223de1989ce546e6d4b50cce8a49d51e8c2dc) similar to what I posted in my snippet above and everything seems to behave as expected. When I click outside the form (e.g. on the taskbar) I get a deactivation event and ActiveForm goes to null. This happens regardless of whether the initial form is open or I clicked on the button and a modal form shows.

Maybe you can point me at what you think is behaving incorrectly?

**Comment by AraHaan** [comment] 2020-03-23 13:46
Interesting it seems that activeform code works perfectly in the timer, it might just by my if checking if it is an active window or not is messing up in the ``Paint`` event code.

**Comment by weltkante** [comment] 2020-03-23 14:35
Added [code to log paint events](https://github.com/weltkante/TestFormActiveForm/commit/108a58af2ef46a010903f2e6b8dc0d09c56fdc4e). Looks like (de)activation doesn't trigger a paint, which makes sense, because it only affects the frame and painting that goes by a different window message.

Adding [explicit invalidation](https://github.com/weltkante/TestFormActiveForm/commit/9037ebc7ae38a624582a8bf1253f57f17d71ca10) seems to make your forms change color appropriately?

The behavior seems sensible to me, since native theme is implemented outside `WM_PAINT` messages it makes little sense to request a repaint of the client area when the activation changes.

**Comment by AraHaan** [comment] 2020-03-23 16:21
Also I noticed as well that it seems while the result code is 0 from ``NativeMethods.SendMessage`` that the sent message does nothing on the form (on the close and help buttons). I changed the MouseDown event to:

```cs
        private void ThemedForm_MouseDown(object sender, MouseEventArgs e)
        {
            if (this.ControlBox)
            {
                // todo: do what the buttons originally did.
                if (this.MinimizeHitbox.Contains(e.Location) && this.MinimizeBox)
                {
                    this.WindowState = FormWindowState.Minimized;
                }
                else if (this.MaximizeHitbox.Contains(e.Location) && this.MaximizeBox)
                {
                    this.WindowState = FormWindowState.Maximized;
                }
                else if (this.HelpHitbox.Contains(e.Location) && this.HelpButton)
                {
                    var result = NativeMethods.SendMessage(this.Handle, (uint)WindowsMessages.SYSCOMMAND, (int)SYSCOMMANDS.SC_CONTEXTHELP, 0);
                    Debug.WriteLineIf(result != 0, $"NativeMethods.SendMessage() failed with error code {result}");
                }
                else if (this.CloseHitbox.Contains(e.Location))
                {
                    var result = NativeMethods.SendMessage(this.Handle, (uint)WindowsMessages.SYSCOMMAND, (int)SYSCOMMANDS.SC_CLOSE, 0);
                    Debug.WriteLineIf(result != 0, $"NativeMethods.SendMessage() failed with error code {result}");
                }
            }
        }
```

If you debug the close button and placed a breakpoint on the ``WriteLineIf`` you will see it returns no issues but does nothing to close the form (with the events for it being broadcasted). Same way for the help button to broadcast those events and to show that ? at the bottom of the cursor.

**Comment by weltkante** [comment] 2020-03-23 17:37
You're right, WM_SYSCOMMAND+SC_CLOSE doesn't work in WinForms, kinda weird since it seems to work in a C/C++ application. Not sure what prevents it from working. I'll see if I can do a quick debug session later today and see if .NET suppresses anything. Its unrelated to your code since I can repro in a fresh project.

PS: your SendMessage is defined wrong, `WPARAM` and `LPARAM` are `IntPtr`, not `int` - will cause bugs if your process is 64 bit. Its not the cause of the problem though.

**Comment by weltkante** [comment] 2020-03-23 18:25
You cannot do `WM_SYSCOMMAND` from WinForms mouse events, might have been possible in the past, but current source uses mouse capture both [in Desktop Framework](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,13380) and [in .NET Core](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Control.cs,12123) to track the mouse - and while mouse capture is on you can't send `WM_SYSCOMMAND`.

Easiest workaround is to turn capture off, before you call `WM_SYSCOMMAND+SC_CLOSE`:
```csharp
this.Capture = false;
SendMessage(this.Handle, WM_SYSCOMMAND, (IntPtr)SC_CLOSE, (IntPtr)0);
```

For `SC_CONTEXTHELP` and other commands it might be more complicated because the window isn't going to be closed immediately and you might confuse WinForms if you mess with the capture state and then continue operation as if nothing happened. You'll have to review (or trial-and-error) that yourself, maybe WinForms is robust enough to not care that capture got lost in the middle of a click.

**Comment by AraHaan** [comment] 2020-03-24 17:03
@weltkante it seems to not care if I switch it to ``false`` and then right after sending the message and debugging it on the ``WriteLineIf`` to switch it back to ``true``.

**Comment by weltkante** [comment] 2020-03-24 18:08
> Also why (IntPtr)0 and not IntPtr.Zero?
no particular reason, just what I happened to type

**Comment by RussKie** [comment] 2020-03-26 23:57
@AraHaan has @weltkante answered your questions?

**Comment by AraHaan** [comment] 2020-03-27 13:50
yes he has. However I have a other slight issue sadly with this though. It seems when one double clicks the said hitbox for the icon (that for me case now simulates the ``WM_SYSCOMMAND`` menu thing by basically querying it for the handle, manipulating it, and then finally getting the information needed to clone it to a ``ContestMenuStrip`` that supports custom renderers) does not send an ``SC_CLOSE`` (unlike what windows does when you do that).

**Comment by weltkante** [comment] 2020-03-27 14:34
As far as I understand [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmenu), Windows does not send an `SC_CLOSE` - the menu item _is the SC_CLOSE_. Getting a WM_SYSCOMMAND is just Windows telling you someone clicked a menu item in the system menu, SC_CLOSE is just the ID of the menu item.

So if you create a custom menu then obviously it no longer is identical to the SC_CLOSE menu item and there won't be any default behavior.

If you meant to say you were manually sending WM_SYSCOMMAND+SC_CLOSE from a ContextMenuStrip and it didn't work, then it likely is the same reason it didn't work for the form click, someone probably has mouse capture on. The WinForms API only allows you to reset mouse capture if you access it through the property of the control which currently holds capture. If the capture is not held by WinForms or you can't access the control which holds it you could try using [native API](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-releasecapture) to force release of the capture.

**Comment by AraHaan** [comment] 2020-03-30 14:26
I was talking on the event that the form icon is double clicked. By default when the icon of a window is double clicked windows closes the program. On my boarder code I wanted to replicate said functionality however that part does not work. But ye double clicking the icon in the window might actually be ``WM_CLOSE`` as well.

**Comment by weltkante** [comment] 2020-03-30 16:29
Double clicking the system menu icon is not implemented by the menu, this is a plain double click event handler checking the result from [WM_NCHITTEST](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest) to determine on what you double clicked. As far as I can tell the double click handler sends WM_SYSCOMMAND+SC_CLOSE to fake a click on the menu item.

If you try to handle WM_NCHITTEST note the warning in the doc that you may have to call DwmDefWindowProc to stay compatible with the builtin implementation. Also if you report HTSYSMENU for an area you opt in for all mouse handling, not just double clicks.

Otherwise just do your own double click handling and send WM_SYSCOMMAND+SC_CLOSE (after releasing mouse capture if necessary)

**Comment by AraHaan** [comment] 2020-04-14 15:37
Alright looking into this further, been working on trying to simlify the building of the packages I made that my things depend on too.

**Comment by RussKie** [comment] 2020-05-07 04:33
Closing as I don't believe there is anything outstanding from our side. @AraHaan holler back, if it is not the case.

@weltkante thank you for your help!

**Closed by RussKie** 2020-05-07 04:33 UTC
