### ISSUE TITLE
Couldn't edit collection property in designer if collection editor is implemented to process with different class types

### ISSUE THREAD

**Issue by AmalRajUmapathySelvam** [dotnet/winforms#6193] opened 2021-11-17 11:11 UTC
* .NET Core Version: **.NET 5.0**

* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**

Collection editor for a custom collection is not shown in NET 5.0, whereas it is shown and is working fine in NET Framework, if the custom collection class has different derived classes. 

**Expected behavior:**
Collection editor in the CustomCollection property should be visible and should properly in NET 5.0 like in NET Framework.

**Screenshot for Reference:**
<img width="222" alt="CustomCollectionEditor" src="https://user-images.githubusercontent.com/44425449/142191041-c29e3d35-7800-4d7f-b3a6-72798c6ebd11.png">

**Minimal repro:**
* Open the attached samples in VS.
* Each has a CustomControl added in the form.
* CustomControl has a property called CustomCollection which is of type implemented from ObservableCollection of BaseClass. And two more sub classes are derived from BaseClass called Derived1 and Derived2.
* Move to CustomCollection property in designer and try to add a objects in type from both Derived1 and Derived2 types.
* Collection editor icon itself not shown in NET 50 and working fine in NET Framework.

**Samples:**
[NETFramework_App.zip](https://github.com/dotnet/winforms/files/7554123/NETFramework_App.zip)
[NETCORE_App.zip](https://github.com/dotnet/winforms/files/7554125/NETCORE_App.zip)

**Comment by Amy-Li03** [comment] 2021-11-18 05:59
Verified this issue on .NET 5.0 & 6.0 & 7.0, this issue all reproduced on these versions. And if we add a winforms user control to WinForms .NET core project, then add custom property for this user control, collection editor icon of custom property also **doesn’t show** in properties window.
In addition, we found an issue: [2655 ](https://github.com/dotnet/winforms-designer/issues/2655) in GH designer repo, it seems to have relevance to this issue.

**Comment by AmalRajUmapathySelvam** [comment] 2021-11-18 10:50
> Verified this issue on .NET 5.0 & 6.0 & 7.0, this issue all reproduced on these versions. And if we add a winforms user control to WinForms .NET core project, then add custom property for this user control, collection editor icon of custom property also **doesn’t show** in properties window. In addition, we found an issue: [2655 ](https://github.com/dotnet/winforms-designer/issues/2655) in GH designer repo, it seems to have relevance to this issue.

@Amy-Li03 - I couldn't view the above mentioned issue.

**Comment by zkost** [comment] 2021-12-30 23:47
Is there a fix for this yet?

**Comment by AvaSharkawy** [comment] 2022-02-02 01:50
Any solution?

**Comment by RussKie** [comment] 2022-02-02 02:05
Unfortunately in .NET this is no longer possible - the designer is run as .NET process, and editors are run in the context of VS (net472 process). You can find more information in our latest blog post ["State of the Windows Forms Designer for .NET Applications"](https://devblogs.microsoft.com/dotnet/state-of-the-windows-forms-designer-for-net-applications/).
You'll need to modify your code and use [the designer extensibility SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK). We will be publishing more information in the near future, including how to author custom controls for the OOP designer.

**Comment by RussKie** [comment] 2022-02-02 02:06
Duplicate of https://github.com/dotnet/winforms/discussions/6581

**Closed by RussKie** 2022-02-02 02:06 UTC
Labels: area: VS designer, area: designer support
