### ISSUE TITLE
Cannot get the expected result when set "\r\r\n" to RichTextBox.Text property

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10528] opened 2023-12-25 06:35 UTC
### .NET version

9.0.0-alpha.1.23621.3

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

This issue can reproduce from .NET Core 3.1 ~ .NET 9.0

### Issue description

Cannot get the expected result when set "\r\r\n" to RichTextBox.Text property, **but set "\r\n" to RichTextBox.Text property which can get expected results,**

### Steps to reproduce

1. Launch the attached project in VS.
2. Run it and observe the value for richTextBox1.Text in debugging.
[Repo_Application.zip](https://github.com/dotnet/winforms/files/13764392/Repo_Application.zip)

**Actual Results:**
There is “\ r \ n” in the string that the RichTextBox control can display line breaks normally.
There is “\ r\r \ n” in the string that the RichTextBox control cannot display line breaks.
![image](https://github.com/dotnet/winforms/assets/38325459/626f7eca-1520-4ee3-85ea-bd32b679340a)

**Expected Results:**
There is “\ r\r \ n” in the string that the RichTextBox control can display line breaks normally.

**More info:**
1. There is “\ r\r \ n” in the string that the TextBox control cannot display line breaks.
2.  This issue can reproduce from  .NET Framework 4.5 to 4.8.1.

**Comment by Zheng-Li01** [comment] 2023-12-25 06:36
Original feeback https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1924303

**Comment by Tanya-Solyanik** [comment] 2023-12-25 21:17
@Zheng-Li01  - would you be able to find workaround for this issue?

**Comment by Tanya-Solyanik** [comment] 2024-01-02 05:21
@Zheng-Li01 - does this reproduce in an MFC app?

**Comment by Zheng-Li01** [comment] 2024-01-02 09:01
@Tanya-Solyanik , The issue also can reproduce MFC app, see below screenshot.

![image](https://github.com/dotnet/winforms/assets/38325459/1ff19edb-98ab-42e0-8513-805294fc3440)

**Comment by merriemcgaw** [comment] 2024-01-11 01:46
Closing this issue since it's an issue with the underlying RichTextBox control, which is owned by another team and we just wrap and expose.

**Closed by merriemcgaw** 2024-01-11 01:46 UTC
Labels: untriaged, external-OS-issue, area-Controls-RichEdit
