### ISSUE TITLE
PropertyTab Bitmap icon

### ISSUE THREAD

**Issue by panost** [dotnet/winforms#2625] opened 2020-01-04 13:13 UTC
* .NET Core Version: 3.1
* Have you experienced this same bug with .NET Framework?: No

**Problem description:** Overriding a PropertyTab, you should provide an icon embedded resource without an ".ico" extension or else an exception of ArgumentException is thrown

**Actual behavior:** if you provide an embedded resource, with the same name as the class and extension ".ico" an exception of ArgumentException is thrown

**Expected behavior:** No exception, load the embedded icon resource

**Cause:** This [line](https://github.com/dotnet/winforms/blob/ab6730e76538c28f598bbac2bb009725e9ab69bc/src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs#L32) calls the DpiHelper.GetBitmapFromIcon, using the current type name without adding the ".ico" extension. 

.NET Framework is not using icons but bitmaps and in the same method **adds** the ".bmp" extension to the type name.

**Comment by RussKie** [comment] 2020-01-05 23:26
@dreddy-work could you please have a look?

**Comment by merriemcgaw** [comment] 2020-09-02 00:03
@dreddy-work is this work done already? It sounds very familiar. If not, let's move the milestone over to 6.0

**Comment by dreddy-work** [comment] 2021-02-13 08:49
We will be looking into these in 6.0 time frame.

**Comment by RussKie** [comment] 2021-02-15 07:41
@panost if you have a fix in mind, feel free to send a pull request ;)

**Comment by panost** [comment] 2021-03-03 08:03
It's just a single line change
```csharp
_bitmap = DpiHelper.GetBitmapFromIcon(GetType(), bmpName);
```

to
```csharp
_bitmap = DpiHelper.GetBitmapFromIcon(GetType(), bmpName + ".ico" );
```

but I am unfamiliar with the pull request methodology and the requirements that this repository has.

**Comment by willibrandon** [comment] 2021-03-03 23:37
It might be more than a 1 line change if we add to or update the `PropertyTabTests`, but I believe @panost is on the right track.

The proposed solution would also require that the `EmbeddedResource` CustomPropertyTab `LogicalName` metadata in System.Windows.Forms.Tests.csproj be updated to reflect the change.

Are we correct that this should behave like the .NET Framework?

**Comment by RussKie** [comment] 2021-03-03 23:41
> but I am unfamiliar with the pull request methodology and the requirements that this repository has.

If you're willing to give it a go, I'm happy to guide :)

We have few guides that explains steps to build and test. In essence the steps are as follows:
1. fork the repo
2. clone
3. [configure your workstation](https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md)
4. [build](https://github.com/dotnet/winforms/blob/main/docs/building.md)
5. create a git branch
6. run `.\start-vs.cmd`
5. create a repro test case in WinformsControlsTest project
6. fix the bug, and see the fixed behaviour
7. create a pull-request (a draft, if you don't feel confident)

**Comment by dreddy-work** [comment] 2021-03-04 01:31
@panost , I do not think we need extension to be passed onto the name. In core, we got rid of extension name from the resource names. It should be able to find embedded resources based on the name ( no extension). Did you verify your proposed fix here? I didn't look in detail but extension should not be needed in the name.

**Comment by panost** [comment] 2021-03-04 10:45
@dreddy-work No, I didn't know those details and I don't have an environment suitable to build and test this WinForms repository.
What I know is this:
I have a WinForms project where I have a custom PropertiesTab named ObjectPropertiesTab (the code is in ObjectPropertiesTab.cs) . In this project you have to provide an icon but without an .ico extension 
As I do here (see the extensionless file ObjectPropertiesTab )
![ObjProps](https://user-images.githubusercontent.com/8362022/109947144-abfe7d00-7ce1-11eb-8eae-f674c5e27d98.png)

If I rename the resource to ObjectPropertiesTab.ico
![TabErr](https://user-images.githubusercontent.com/8362022/109948705-414e4100-7ce3-11eb-9ee6-f685b13153c4.png)
an exception is thrown when your are using this ObjectPropertiesTab,

System.ArgumentException: 'Resource 'ObjectPropertiesTab' cannot be found in class '....Controls.ObjectPropertiesTab'.'
with this call stack
```
System.Drawing.Common.dll!System.Drawing.Icon.Icon(System.Type type, string resource)	Unknown
System.Windows.Forms.Primitives.dll!System.Windows.Forms.DpiHelper.GetBitmapFromIcon(System.Type t, string name)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Design.PropertyTab.Bitmap.get()	Unknown
System.Windows.Forms.dll!System.Windows.Forms.PropertyGrid.CreateTab(System.Type tabType, System.ComponentModel.Design.IDesignerHost host)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.PropertyGrid.AddRefTab(System.Type tabType, object component, System.ComponentModel.PropertyTabScope type, bool setupToolbar)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.PropertyGrid.PropertyGrid()	Unknown

```

So assumed that changing [this line](https://github.com/dotnet/winforms/blob/ab6730e76538c28f598bbac2bb009725e9ab69bc/src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs#L29), and adding an ".ico" suffix, the same that [this line](https://referencesource.microsoft.com/#system.windows.forms/winforms/Managed/System/WinForms/Design/PropertyTab.cs,43) (in .NET framework) adds a ".bmp" suffix, would fix the problem. I didn't know all the details you mentioned.

**Comment by RussKie** [comment] 2021-03-04 10:55
Can you provide a sample app that shows the issue?

**Comment by panost** [comment] 2021-03-04 11:34
Sure,
[PropertyTabIssue.zip](https://github.com/dotnet/winforms/files/6083217/PropertyTabIssue.zip)

Is a Winforms net5.0 project that works just fine, because the embedded resource named ObjectPropertiesTab is extensionless (this file is actually an icon).
If you rename it to ObjectPropertiesTab.ico (or select "Build Action" to "None") and run it, several exceptions are throw (with first, the one I mention above) and the app terminates

**Comment by willibrandon** [comment] 2021-03-04 17:01
I am able to reproduce the issue with the sample app that @panost has provided with ObjectPropertiesTab.ico (with the .ico file exntension), Debugging options - Enable Just My Code - unchecked, and Exception Settings - Common Language Runtime Exceptions - checked.

![PropertyTab_Icon_ArgumentException](https://user-images.githubusercontent.com/5017479/109999059-b1020300-7cc6-11eb-873f-08155f1d5c71.png)

![PropertyTab_PropertyGrid_CreateTab_ArgumentException](https://user-images.githubusercontent.com/5017479/109999115-bcedc500-7cc6-11eb-8b85-70952cf91449.png)

**Comment by willibrandon** [comment] 2021-03-04 17:19
If we got rid of resource filename extensions in core, I can't imagine this behavior is by design. This scenario, with a resource filename extension, should be properly handled, and the application should not terminate.

**Comment by dreddy-work** [comment] 2021-03-04 19:40
@panost  and @willibrandon , you can always give logical name to resource ( as shown in screenshot below). adding ".Ico"  extension in the runtime still breaks if you embed ".bmp" in your test project. 
![image](https://user-images.githubusercontent.com/36968667/110020480-71dfac00-7cde-11eb-987c-d620f798618e.png)

**Comment by panost** [comment] 2021-03-06 12:23
@dreddy-work It is not clear to me if your suggestion is a temporary workaround until this is fixed or a permanent that should be included in the documentation of the PropertiesTab class as a warning to anyone inheriting from this class.

If it is the former, I already have a workaround that works, if it is the latter then I have nothing else to say and you can close this issue.

**Comment by dreddy-work** [comment] 2021-03-07 09:02
> @dreddy-work It is not clear to me if your suggestion is a temporary workaround until this is fixed or a permanent that should be included in the documentation of the PropertiesTab class as a warning to anyone inheriting from this class.
> 
> If it is the former, I already have a workaround that works, if it is the latter then I have nothing else to say and you can close this issue.

I looked at your sample app again. In .Net core, we moved to Icons to enable support for higher DPI screens and make the embedded resource extension-less by giving alias. A right solution may be checking for both ".bmp"  for applications migrating from .NET framework and ".ico"  for any new applications passing Icons.  But, given that work around is simple and embedding resource with alias is always better, I am closing this issue for now. Will revisit  to prioritize if there is a complex scenario.

**Closed by dreddy-work** 2021-03-07 09:02 UTC

**Comment by weltkante** [comment] 2021-03-11 09:58
> given that work around is simple and embedding resource with alias is always better, I am closing this issue for now

It probably should be documented then?

**Comment by dreddy-work** [comment] 2021-03-11 18:11
> > given that work around is simple and embedding resource with alias is always better, I am closing this issue for now
> 
> It probably should be documented then?

That should help. Let me follow up on that.
