### ISSUE TITLE
An exception pops up when using the method GetData(Type format) of IDataObject

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1064] opened 2019-05-29 10:16 UTC
* .NET Core Version: .NET Core 3.0.100-preview6-012101 from master branch
* Have you experienced this same bug with .NET Framework?: No

**Minimal repro:**
1. Create a Winforms .Net Core application.
2. Write code to Form1.cs.
 IDataObject o = Clipboard.GetDataObject();
 string got = (String)o.GetData(typeof(String));
3. Build and run the application.

**Actual behavior:** 
When debugging to _string got = (String)o.GetData(typeof(String))_, the exception pops up.
![error](https://user-images.githubusercontent.com/49627022/58549157-7b043500-823d-11e9-951a-f4b49bc61fd0.PNG)

**Expected behavior:**
No exception pops up, application runs successfully.

**Comment by Tanya-Solyanik** [comment] 2019-05-29 17:24
@Amy-Li02  - Could you please add a couple details?
1. This used to work a while back, is this a regression in preview5?
2. Could you please provide the exception stack from the "view details" link?
3. does it matter if the clipboard is "clear'd" or actually has a string data?
4. do any clipboard formats work?

**Comment by weltkante** [comment] 2019-05-29 20:17
@Tanya-Solyanik is probably a duplicate of #1060 which is fixed by dotnet/coreclr#24818

**Comment by merriemcgaw** [comment] 2019-05-29 23:41
@Amy-Li02 can you confirm this is good now and we can close this issue as a duplicate.

**Comment by Zheng-Li01** [comment] 2019-05-30 01:47
Verified the issue with the latest .NET Core SDK 3.0.100.12121 -preview6 from master branch, the issue has been fixed. So closed it.

**Closed by Zheng-Li01** 2019-05-30 01:47 UTC
Labels: bug, tenet-compatibility
