### ISSUE TITLE
DPIUNAWARE registry key does not work

### ISSUE THREAD

**Issue by johanstrand** [dotnet/winforms#9803] opened 2023-08-29 14:05 UTC
### Environment

Win 11, Visual Studio 2022 17.7.2

### .NET version

Core 7

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It worked in Visual Studio 17.6.x.

### Issue description

Designer will not start for projects targeting .net Core 7. I get the message 
"failed to set process dpi mode value to: dpiunaware"  when starting the forms editor.
This is the same as #7609. In 17.6 the suggested solution to add a registry key worked, but after upgrading to 17.7.1 and 17.7.2 it fails again.
The forms editor works if I remove the registry key and start VS with the /NoScale flag. /NoScale does not work with the registry key set.

### Steps to reproduce

Add the registry key:
`C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE` to `\HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers` with the value `DPIUNAWARE`

Create a Winforms application targeting .NET Core 7. 

Try to open the forms editor.

**Comment by Shyam-Gupta** [comment] 2023-08-29 18:35
It's a dupe of bug #9714. Fix for this bug has been implemented already and should be available in next 17.8 Preview release.

I would also like to mention that starting with 17.8 Preview 1, a new project property `ForceDesignerDpiUnaware` has been introduced which will help launch WinForms out-of-process designer in `DPIUnaware` mode. More details about this property are available [here](https://aka.ms/winforms/designer/unaware-mode). Thanks.

**Comment by johanstrand** [comment] 2023-08-29 19:06
Thanks!

Looking forward to 17.8.

**Closed** 2023-08-29 19:11 UTC
Labels: area-VSDesigner
