### ISSUE TITLE
Designer Never Opens

### ISSUE THREAD

**Issue by MissyGH** [dotnet/winforms#9574] opened 2023-07-26 23:52 UTC
### Environment

Microsoft Visual Studio Community 2022
Version 17.6.5
VisualStudio.17.Release/17.6.5+33829.357
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA975
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.6.326.62524
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.6.326.62524
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.21 (main@8f226a8)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JustMock   2023.2.601.35
Telerik JustMock Extension.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.6.41 (790a401)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Progress Telerik UI for WinForms Extension   2023.2.714.61
Progress® Telerik® UI for WinForms Extension

Progress Telerik UI for WPF Extension   2023.2.714.61
Progress® Telerik® UI for WPF Extension

Progress Telerik WinForms Converter   2023.2.606.53
Progress® Telerik® UI for WinForms Converter

Razor (ASP.NET Core)   17.6.0.2327201+a6a61fdfa748eaa65aab53dab583276e26af4a3e
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.6.13.0
Microsoft SQL Server Data Tools

Telerik Reporting Tools   3.44.11.0
Complete .NET Reporting Solution for Web, Mobile and Desktop Applications. For more information please visit http://www.telerik.com/reporting. 

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20329.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.6.0.251 (d17-6@318364c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.6.6.0 (remotes/origin/d17-6@cb430751d1)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.0.6 (d17-5/a200af1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

### .NET version

	  <TargetFramework>net7.0-windows</TargetFramework>
	  <PlatformTarget>x64</PlatformTarget>
	  <UseWindowsForms>true</UseWindowsForms>
	  <UseWPF>true</UseWPF> 

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes - it worked in the last release of VS Community 2022 under Net 7.   

### Issue description

It gets stuck on Loading Designer

### Steps to reproduce

Right click on View Designer and it just hangs.    

I spent several hours looking for troubleshooting guides on this.    It seems like the missing file errors are the issue but I didn't add or remove those files from the system.

### Diagnostics

```text
15:32:06:392	[15:32:06.381638] info: Shadow caching completed.
15:32:06:392	[15:32:06.387622] info: IServerConnectionTimeoutProvider: Starting execution of winFormsOptions task.
15:32:06:392	[15:32:06.388619] info: IServerConnectionTimeoutProvider: WinFormsOptions task completed.
15:32:06:392	[15:32:06.388619] info: Obtained ServerConnectionTimeout value: 120000.
15:32:06:392	[15:32:06.389617] info: Obtained OutputWindowLoggingService.
15:32:06:508	[15:32:06.398594] info: [UIProject]: Launching design tools server process...
15:32:07:070	[15:32:06.968072] info: [UIProject]: Connected to named pipe: DesignToolsServer.33aa362c-cda9-4f23-a526-ebce77af649b
15:32:07:070	[15:32:06.988019] info: [UIProject]: Connecting to pipe: DesignToolsServer.33aa362c-cda9-4f23-a526-ebce77af649b... 
15:32:07:070	[15:32:06.988019] info: [UIProject]: Successfully connected to pipe: DesignToolsServer.33aa362c-cda9-4f23-a526-ebce77af649b
15:32:07:070	[15:32:06.989045] info: [UIProject]: Creating DesignToolsServer [thread 1]
15:32:07:070	[15:32:06.993005] info: [UIProject]: Starting UI thread [thread 1]
15:32:07:070	[15:32:06.994003] info: [UIProject]: Performing start up tasks [thread 6]
15:32:07:316	[15:32:07.082763] info: [UIProject]: UI thread started
15:32:07:316	[15:32:07.087752] info: [UIProject]: Wait for start up tasks to complete... [thread 6]
15:32:07:366	[15:32:07.145596] info: [UIProject]: Loaded server manifest [thread 8]
15:32:07:366	[15:32:07.145596] info: [UIProject]: Loading design-time assemblies [thread 8]
15:32:07:366	[15:32:07.182551] info: [UIProject]: Loading design-time assembly dependencies [thread 8]
15:32:07:615	[15:32:07.452138] fail: [UIProject]: System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel.Syndication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
15:32:07:615	                        File name: 'System.ServiceModel.Syndication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
15:32:07:615	                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
15:32:07:615	                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
15:32:07:615	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)
15:32:07:615	
15:32:07:615	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:07:615	[15:32:07.469526] fail: [UIProject]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Schema, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
15:32:07:615	                        File name: 'System.Runtime.Serialization.Schema, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
15:32:07:615	                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
15:32:07:615	                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
15:32:07:615	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)
15:32:07:615	
15:32:07:615	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:07:709	[15:32:07.536320] fail: [UIProject]: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Ports, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
15:32:07:709	                        File name: 'System.IO.Ports, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
15:32:07:709	                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
15:32:07:709	                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
15:32:07:709	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)
15:32:07:709	
15:32:07:709	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:07:709	[15:32:07.544327] fail: [UIProject]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.OleDb, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
15:32:07:709	                        File name: 'System.Data.OleDb, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
15:32:07:709	                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
15:32:07:709	                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
15:32:07:709	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)
15:32:07:709	
15:32:07:709	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:07:709	[15:32:07.545323] fail: [UIProject]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Odbc, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
15:32:07:709	                        File name: 'System.Data.Odbc, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
15:32:07:709	                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
15:32:07:709	                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
15:32:07:709	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)
15:32:07:709	
15:32:07:709	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:07:709	[15:32:07.640188] fail: [UIProject]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=19.16.3.4, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.
15:32:07:709	                        File name: 'Microsoft.AnalysisServices.AdomdClient, Version=19.16.3.4, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
15:32:07:709	                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
15:32:07:709	                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
15:32:07:709	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)
15:32:07:709	
15:32:07:709	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:07:816	[15:32:07.770381] info: [UIProject]: Building MEF composition
15:32:08:253	[15:32:08.157347] info: [UIProject]: Disposing DesignToolsServer [thread 8]
15:32:08:253	[15:32:08.165324] fail: [UIProject]: Failed to launch design tools server process process
15:32:08:253	                        System.ArgumentException: An item with the same key has already been added. Key: vsUI/IsVsInUIState
15:32:08:253	                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
15:32:08:253	                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Protocol.ProtocolDefinition.AddEndpoints(IEnumerable`1 endpoints)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Protocol.ProtocolDefinition.Create(CompositionHost compositionHost)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Server.ServerProtocolContext.Create(ITypeIdentityResolutionService typeIdentityResolution, ILiveObjectService liveObjectService, DesignToolsServer designToolsServer, IEnumerable`1 designTimeAssemblies, IEnumerable`1 exportDescriptorProviders, ILoggerFactory loggerFactory)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.StartUpAsync(CancellationToken cancellationToken)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.StartListeningAsync(Stream stream, TraceListener traceListener)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()
15:32:08:253	
15:32:08:253	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:08:253	[15:32:08.176269] fail: Microsoft.DotNet.DesignTools.Client.ServerException: Failed to launch the design tools server process.
15:32:08:253	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:32:08:253	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:32:08:253	                           at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
15:32:08:253	                        --- End of stack trace from previous location where exception was thrown ---
15:32:08:253	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:32:08:253	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<LaunchAsync>d__28.MoveNext()
15:32:08:253	                        --- End of stack trace from previous location where exception was thrown ---
15:32:08:253	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:32:08:253	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
15:32:08:253	                        --- End of stack trace from previous location where exception was thrown ---
15:32:08:253	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:32:08:253	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:32:08:253	                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()
15:32:08:253	
15:32:08:253	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
15:32:08:565	[15:32:08.498640] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by merriemcgaw** [comment] 2023-07-27 00:12
Hi @MissyGH - are you able to reproduce this with a new project in your configuration or only an existing one? Are you referencing the files that are showing up as errors? Or, do you think a component you are referencing has a dependency that has somehow changed? I'm not able to reproduce this with a vanilla new project or with an existing one, but I don't know what nuget packages you might be referencing.

@Olina-Zhang can you confirm whether we reproduce this on our end?

**Comment by elachlan** [comment] 2023-07-27 00:16
It looks like its failing to resolve nuget dependencies.

- System.ServiceModel.Syndication
- System.Runtime.Serialization.Schema
- System.IO.Ports
- System.Data.Odbc
- Microsoft.AnalysisServices.AdomdClient

**Comment by Olina-Zhang** [comment] 2023-07-27 08:10
> @Olina-Zhang can you confirm whether we reproduce this on our end?

@merriemcgaw  I tried to install TelerikUIForWinForms with Visual Studio 2022 17.6.5, when creating a TelerikWinforms application or add Telerik any template Form in a vanilla application, designer can be loaded, but there has the same failure log in Output window. Previous Visual Studio 2022 17.6.3 has same behavior.
```
[01:05:07.073173] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceProcess.ServiceController, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                        File name: 'System.ServiceProcess.ServiceController, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.074173] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel.Syndication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
                        File name: 'System.ServiceModel.Syndication, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.080173] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Schema, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                        File name: 'System.Runtime.Serialization.Schema, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.110723] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Ports, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
                        File name: 'System.IO.Ports, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.114718] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.OleDb, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
                        File name: 'System.Data.OleDb, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.115717] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Odbc, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
                        File name: 'System.Data.Odbc, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.115717] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                        File name: 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[01:05:07.141283] fail: [WinFormsApp9]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=19.16.3.4, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.
                        File name: 'Microsoft.AnalysisServices.AdomdClient, Version=19.16.3.4, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
                           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
                           at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.LoadReferencedAssemblies(AssemblyName[] referencedAssemblyNames, HashSet`1 serverDependenciesNames, CancellationToken cancellationToken)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.

```

**Comment by merriemcgaw** [comment] 2023-08-02 20:52
@MissyGH thanks for the report, and I'm sure Telerik appreciates it as well. There's not anything we can do until Telerik investigates on their end, so I will close this issue. Don't hesitate to reach out if something changes. You can also feel free to direct them to this bug report.

**Closed by merriemcgaw** 2023-08-02 20:52 UTC
Labels: untriaged

**Comment by FixBo** [comment] 2023-08-18 14:08
> It looks like its failing to resolve nuget dependencies.
> 
> * System.ServiceModel.Syndication
> * System.Runtime.Serialization.Schema
> * System.IO.Ports
> * System.Data.Odbc

This errors come from stub forward only libraries like System.Data. Which do not have a direct link from anywhere in project.
![image](https://github.com/dotnet/winforms/assets/18525370/ee0f7ad7-0ba4-463f-a084-a537d2b3ba81)
