### ISSUE TITLE
Publish winforms application miss .ICO files in .Net Core 3.0

### ISSUE THREAD

**Issue by zangxx66** [dotnet/winforms#266] opened 2018-12-23 17:40 UTC
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: No

**Problem description:** I set a icon,but it dont work atfer publish,expction is cant found icon file.

**Actual behavior:** exceptions

**Expected behavior:** can't find file "xxx.ico"

**Minimal repro:** Publish action not include reference file,and run exe file must cmd,this isnot reasonable

**Comment by merriemcgaw** [comment] 2019-01-04 03:40
Is the issue that the dotnet publish command is not including the ico file you set as the icon for the app or is the issue that it's throwing an exception rather than an error message? This is unclear to me.  Is your icon file referenced to be included in your project file?

**Comment by zangxx66** [comment] 2019-01-04 03:48
> Is the issue that the dotnet publish command is not including the ico file you set as the icon for the app or is the issue that it's throwing an exception rather than an error message? This is unclear to me. Is your icon file referenced to be included in your project file?

I am building with vscode.Icon file be included in my project directory and I have added an icon file to my program.Run program have a miss icon file exception after publish command.../bin/netcoreapp3.0/publish is not including icon file

**Comment by merriemcgaw** [comment] 2019-01-04 19:46
Can you please attach a sample repro application so we can further diagnose the issue?

**Comment by wjk** [comment] 2019-01-04 21:31
Is this a case of https://github.com/Microsoft/msbuild/issues/2221? If you are including the icon in a resx file, then `dotnet publish` will not compile the icon properly. You will need to use full-Framework MSBuild for this to work presently.

**Comment by Symbai** [comment] 2019-01-05 19:33
I have experienced the same problem with WPF on .NET Core 3.0 too so it isn't just winforms related: https://github.com/dotnet/wpf/issues/209

**Comment by CatGirlsAreLife** [comment] 2019-02-13 02:49
Hmm interesting it seems when I try to load a resx file with only strings or a blank one that it fails to open up the resx editor when targeting .net core 3.0 and the full frameworks on vs2019.

Also seems that since I updated from preview 1 to preview 2 on net core 3 that vs2015 fails to load my projects too.

**Comment by zsd4yr** [comment] 2019-02-15 19:20
It looks like there are two issues here in the comments:
* resx work 
* inclusion of icon files

@rainersigwald What do you think about the dotnet publish issue here related to icon files? Can you direct us to who owns the dotnet publish command?

**Comment by CatGirlsAreLife** [comment] 2019-02-17 22:57
I think that is in the https://github.com/dotnet/cli repo. Maybe try filing a issue there.

**Comment by merriemcgaw** [comment] 2019-03-29 18:54
@Olina-Zhang can you confirm that setting the icon file actually works to show that icon? Then we can open an issue in CLI for the publishing concern

**Comment by rainersigwald** [comment] 2019-03-29 19:22
I think @wjk's diagnosis here is correct: if the `.ico` is a file reference in the `.resx`, `dotnet build` will mangle it into being a string. This will be fixed before .NET Core 3.0 RTM https://github.com/Microsoft/msbuild/issues/2221.

**Comment by Jessie-Zhang01** [comment] 2019-04-01 10:35
Verified this bug in .Net Core 3.0 preview 4 3.0.100.11022 build from master branch + Dev16.0 Preview 5.0 [28729.10.d16.0], according to the description of this issue, we try to reproduce as following steps, @merriemcgaw we may need to confirm with @zangxx66 again.

Repro Steps we tired: 
1. Create winforms app in .net Core or framework.
2. Copy and Paste two .ico files to project directory.
3. Add them in created app.
4. Publish the application.
5. Check if ico related files exist in Publish folder.

Test result in .net Core and framework:
![image](https://user-images.githubusercontent.com/45864649/55321621-be942a00-54ac-11e9-96c3-293376fd7ed7.png)

**Comment by zangxx66** [comment] 2019-04-03 11:29
> Verified this bug in .Net Core 3.0 preview 4 3.0.100.11022 build from master branch + Dev16.0 Preview 5.0 [28729.10.d16.0], according to the description of this issue, we try to reproduce as following steps, @merriemcgaw we may need to confirm with @zangxx66 again.
> 
> Repro Steps we tired:
> 
> 1. Create winforms app in .net Core or framework.
> 2. Copy and Paste two .ico files to project directory.
> 3. Add them in created app.
> 4. Publish the application.
> 5. Check if ico related files exist in Publish folder.
> 
> Test result in .net Core and framework:
> ![image](https://user-images.githubusercontent.com/45864649/55321621-be942a00-54ac-11e9-96c3-293376fd7ed7.png)

Debug is normal but miss ico file after run dotnet publish command with .Net Core 3.0 preview 3.
![捕获32](https://user-images.githubusercontent.com/14540861/55475484-a5bf7c00-5646-11e9-8bd3-b64a1fee2e0d.PNG)
![捕获33](https://user-images.githubusercontent.com/14540861/55475502-b112a780-5646-11e9-92ca-c8a6c52b6f32.PNG)
![捕获34](https://user-images.githubusercontent.com/14540861/55475510-b53ec500-5646-11e9-9d12-7db40adf11c0.PNG)

**Comment by Jessie-Zhang01** [comment] 2019-04-09 07:56
@zangxx66 You can try to set the "Copy to Output Directory" property for icon you used as 'Copy always' to see if your issue can be resolved.
Here is I tried, after published, we can see ico file is contained in publish folder. Please see following screenshot:
![image](https://user-images.githubusercontent.com/45864649/55782720-7d6ccd00-5adf-11e9-94c4-88477fbb85ee.png)

**Comment by zangxx66** [comment] 2019-04-09 08:07
@Jessie-Zhang01 My vs2019 cant distinguish .Net core 3.0 so much so that I use vs code build.I think this may be a problem with vs code.Can you help me?
If I build with vs I think it can be resolved.

**Comment by Jessie-Zhang01** [comment] 2019-04-09 08:58
@merriemcgaw We didn't use VS Code to test .Net Core 3.0, but this issue can't be reproduce with VS 2019 + .Net Core 3.0 preview 4 using the above way that we mentioned. Can we close this github issue now? In addition, do you have any suggestion to zangxx66?

**Comment by merriemcgaw** [comment] 2019-04-20 00:59
See @rainersigwald 's comment up on Mar 29. This is being fixed in the msbuild side of things in Microsoft/msbuild#2221. I'd suggest following that issue @zangxx66 , I'm going to close this one here as the work is in msbuild.

**Closed by merriemcgaw** 2019-04-20 00:59 UTC
Labels: bug
