### ISSUE TITLE
A warning dialog pops up when setting SelectedImageIndex property to '(none)' in TreeNode Editor

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/winforms#4131] opened 2020-10-19 02:11 UTC
* .NET Core Version: 
NET SDK 5.0.100-rtm.20515.8

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**

1. This issue also occurs when setting ImageIndex property in TreeNode Editor.
2. This issue cannot repro when targeting 3.0&3.1.
3. This is a regression issue, it cannot repro in .NET 5.0.100-rc.1.20452.10.

**Problem description:**
A warning dialog pops up when setting SelectedImageIndex property to '(none)' in TreeNode Editor. 
![TreeView](https://user-images.githubusercontent.com/54019172/96392839-e0204800-11ef-11eb-9515-147755055b8e.gif)
![SelectedINdex](https://user-images.githubusercontent.com/54019172/96392868-f29a8180-11ef-11eb-9451-026b3d6e369c.png)

**Expected behavior:**
No warning dialog pops up and SelectedImageIndex can be successfully set to '(none)'.

**Minimal repro:**

1. Create a winforms .Net Core application with a TreeView control
2. Open smart tag of TreeView, click 'Edit Nodes' to open TreeNode Editor
3. Click 'Add Root' button to add a tree node, in the right table, try to change its SelectedImageIndex property to '(none)'

**Comment by merriemcgaw** [comment] 2020-10-23 00:29
We might want to consider fixing this in servicing - it means that we can't set the value to (none). There is nothing that can be done on the designer side to work around this problem, it has to be done in the runtime. This is important enough to the designer we should do this sooner rather than later.
cc/ @RussKie - consider for servicing.

**Comment by RussKie** [comment] 2020-10-23 10:15
Copying @DustinCampbell's response from another thread:

`TreeNode.SelectedImageIndex` is supposed to be allowed to be set to `-2`. There are two special values for `TreeNode.SelectedImageIndex`:

1. `-1` means to use the TreeView's selected image index.
2. `-2` means there is no selected image index.

This is a regression that was introduced in .NET 5 with https://github.com/dotnet/winforms/commit/8490a9cff5cb7b919bd6860718bf60d81bb61316.


/cc: @hughbe

**Comment by RussKie** [comment] 2020-10-23 10:46
@DustinCampbell I've scanned through the runtime and the designer code and I can't see `-2` magic number anywhere. Could you help me find where it is coming from? I'd like to understand how we could have prevented this bug.

**Comment by DustinCampbell** [comment] 2020-10-23 15:47
Looking at `TreeNode`, `TreeView`, and `TreeNodeImageIndex` probably won't provide any hints. Reading that code, I couldn't find any places where indices are treated specially, except where `-1` is used to specify that the value from the owning `TreeView` should be used:

https://github.com/dotnet/winforms/blob/9c01d45832a0f7dcdb70bad1098e1ff6f0632b21/src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs#L2217-L2220

In the code above, if `SelectedImageIndexer.ActualIndex` has value of `-2` it just gets assigned to `TVITEM.iSelectedImage`. If that happens, I guess that Windows probably just ignores the value since it's not a valid image list index.

There's nothing in the designer code that cares about `-2` either. As a rule, the designer tries not to manipulate the runtime controls' behavior too much.

The fact that `-2` is a legal value _is_ clear in the runtime, but you need to look at the [`TreeViewImageIndexConverter`](https://github.com/dotnet/winforms/blob/68d60f683ce6a7f8f2a82f5c3636e1ceace2b01b/src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs) specified for the `TreeNode.SelectedImageIndex` property. Since, type converters are used extensively by property grid, they can be a good alternative way to see what values are legal/expected for a property.

There are several places where `-2` appears as a special value in `TreeViewImageIndexConverter`.

`TreeViewImageIndexConverter.ConvertFrom(...)`: https://github.com/dotnet/winforms/blob/68d60f683ce6a7f8f2a82f5c3636e1ceace2b01b/src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs#L31-L41

`TreeViewImageIndexConverter.ConvertTo(...)`: https://github.com/dotnet/winforms/blob/68d60f683ce6a7f8f2a82f5c3636e1ceace2b01b/src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs#L59-L70

`TreeViewImageIndexConverter.GetStandardValues(...)`: https://github.com/dotnet/winforms/blob/68d60f683ce6a7f8f2a82f5c3636e1ceace2b01b/src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs#L130-L133

and...

https://github.com/dotnet/winforms/blob/68d60f683ce6a7f8f2a82f5c3636e1ceace2b01b/src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs#L146


Note that `TreeNode.ImageIndex` has the same regression as `TreeNode.SelectedIndex` and declares the same type converter. Note that `TreeNode.StateIndex` does not have this regression, since it has a `[TypeConverter(NodeExcludedImageIndexConverter)]`.

**Closed** 2020-10-29 06:57 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress, area: designer support

**Comment by Lydia-Shi** [comment] 2020-11-05 08:50
Verified this issue with .NET 6.0.100-alpha.1.20554.7, this issue is fixed that no warning dialog pops up and SelectedImageIndex can be successfully set to '(none)' in TreeNode Editor, results as below:
![FixedTreeNode](https://user-images.githubusercontent.com/54019172/98218654-f87dba00-1f86-11eb-9388-617e8fd61a43.gif)
