### ISSUE TITLE
 CheckBoxRenderer.DrawCheckBox has always a white background

### ISSUE THREAD

**Issue by AngeloCresta** [dotnet/winforms#10680] opened 2024-01-17 12:38 UTC
### .NET version

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, in .Net7 (and prior) is working in .Net8 --> no

### Issue description

The backcolor of the checkbox is not applied using CheckBoxRenderer.DrawCheckBox(...)

In .Net7:
![image](https://github.com/dotnet/winforms/assets/12256319/082f3894-1521-46b1-9032-a9bb1d877eff)

In .Net8:
![image](https://github.com/dotnet/winforms/assets/12256319/d8b87c24-a0c9-443f-a3ed-d7d7a03835d6)

### Steps to reproduce

I've attached a sample project, but the relevant part, after adding a treeview to a form is:

` 
CheckBoxRenderer.DrawCheckBox(g, new Point(0, 1), System.Windows.Forms.VisualStyles.CheckBoxState.UncheckedNormal);
` 
[Treeview_Checkbox.zip](https://github.com/dotnet/winforms/files/13963245/Treeview_Checkbox.zip)

Angelo

**Comment by elachlan** [comment] 2024-01-17 20:55
I think this might be a duplicate of #10462

**Closed** 2024-01-22 20:04 UTC
Labels: :construction: work in progress, untriaged, :boom: regression-release

**Comment by MelonWang1** [comment] 2024-01-25 02:34
Verified this on .NET 9.0.100-preview.2.24074.16, issue was fixed. The backcolor of the checkbox can be applied via CheckBoxRenderer.DrawCheckBox(...).
![Screenshot 2024-01-25 022519](https://github.com/dotnet/winforms/assets/94418985/cc862d96-891c-4a59-b843-81258051d370)

**Comment by Philip-Wang01** [comment] 2024-02-02 07:12
Verified this issue with .NET 9 Preview 1 test pass build, it was fixed. Test result is same as above.

**Comment by Nora-Zhou01** [comment] 2024-02-08 07:16
Verified issue on .NET 8.0.200 with dlls built from Release/8.0 branch of WinForms repo, the issue was fixed, test result is as above screenshot.

**Comment by Eudora-Li01** [comment] 2024-02-26 06:10
Verified with .NET SDK 8.0.3 test pass build, this issue was fixed. Test result is same as above.
