### ISSUE TITLE
LinkLabel cut off

### ISSUE THREAD

**Issue by ahdung** [dotnet/winforms#3780] opened 2020-08-26 08:00 UTC
* .NET Version: 
3.1.301

* Have you experienced this same bug with .NET Framework?: 
Yes. .NET Framework 2.0-4.8

**Environment:**
- VS2019 16.6.3
- Windows Server 2008 R2 x64 Chinese lang

**Problem description:**

LinkLabel width not enough.
![image](https://user-images.githubusercontent.com/12094247/91275592-f6db8d00-e7b2-11ea-9614-829d32c61a5a.png)

**Expected behavior:**

like last one.

**Minimal repro:**

1. create a winform project
2. drag a `CheckBox` on `Form1`
3. add a new `Form` (auto name to `Form2`)
4. drag two `LinkLabel`s and a `Label` on `Form2`, make sure the z-order is(top to bottom): `linkLabel1`, `linkLabel2`, `label1`
5. set `linkLabel1` and `linkLabel2` font to `Arial, 10.5pt`
6. register the `Load` event for `Form2`, write codes:
    ```c#
    linkLabel2.Text = string.Empty;
    linkLabel1.Text = "<未选择>";
    linkLabel2.Text = "<未选择>";
    ```
7. modify `Main` method contents to follow codes in `program.cs` :
    ```c#
    Application.EnableVisualStyles();
    Application.SetCompatibleTextRenderingDefault(false);
    
    new Form1().ShowDialog();
    Application.Run(new Form2());
    ```
8. F5, close `Form1`, now you can see the `linkLabel1` width is not enough

**Demo.zip**
[LinkLabelWidthBugDemo.zip](https://github.com/dotnet/winforms/files/5128326/LinkLabelWidthBugDemo.zip)

**Reference:**
- [https://developercommunity.visualstudio.com/content/problem/1159811/linklabel-width-not-enough-in-particular-cases.html](https://developercommunity.visualstudio.com/content/problem/1159811/linklabel-width-not-enough-in-particular-cases.html)
- [https://stackoverflow.com/questions/63554856/linklabel-width-not-enough-in-particular-cases](https://stackoverflow.com/questions/63554856/linklabel-width-not-enough-in-particular-cases)

**Comment by Zheng-Li01** [comment] 2020-08-26 09:15
**More info**
Try to reproduce the issue using created project. get the below info.
1. The issue can't reproduce on English Lang.
2. Run the project calling the form2, can reproduce the issue; calling the form3, can't reproduce the issue, the difference is that no label controls on the Form3.
3. The issue also can't reproduce when running the Form2 directly.
4. The issue also can't reproduce after annotation the code lainlabel1.Text = string.Empty.
5. The issue also can reproduce in some fonts, some do not.

Please see below screenshot.
![GitHubIssue](https://user-images.githubusercontent.com/38325459/91285218-82f3b180-e7bf-11ea-9fd9-4c283b3db8e2.gif)
![GitHubissue](https://user-images.githubusercontent.com/38325459/91285131-648db600-e7bf-11ea-922b-d7506407cc23.png)

**Comment by weltkante** [comment] 2020-08-27 10:05
> The issue can't reproduce on English Lang.

The version and base language of the operating system are very important in reproducing these issues, as different configurations use different fallback fonts (when the selected font doesn't contain the glyph). Just switching the application or OS language doesn't always result in the same situation, since e.g. chinese installations of Windows may come with different registry settings for font fallback that aren't switched together with the language. Had to work around these issues in the past and they required me to install Chinese Windows 7 in a VM to reproduce the customer issues exactly.

Just FYI when trying to follow up on these issues.

**Comment by Tanya-Solyanik** [comment] 2020-08-27 23:22
@Zheng-Li01 - on what OS had you verified this bug?

**Comment by Zheng-Li01** [comment] 2020-08-31 05:48
@Tanya-Solyanik, verified the issue on Win10 2004(ZH-CN) environment,  the issue can reproduce.

**Comment by ahdung** [comment] 2020-10-23 03:06
any news?

**Comment by RussKie** [comment] 2020-10-23 05:39
No, no news. 
Given this is an existing long standing issue observed in .NET Framework and an existing work around this issue isn't high on the team's priority list. A pull request with a fix is welcome.

**Comment by bkoelman** [comment] 2021-06-06 21:07
I'm also seeing LinkLabel being cut off, but only when in Disabled state. I have two LinkLabels inside a GroupBox. When the GroupBox is enabled, both links render properly. When setting Enabled to false on the GroupBox, then both labels are cut off. The labels have AutoSize set to True. This all happens inside a single form that is visible and active all the time. I'm not using a custom font and the link text is static.

When I remove `Application.SetCompatibleTextRenderingDefault(false);` from my application, the problem goes away.

Discovered on Windows 8.1 EN-US using .NET 5. I've found this after migrating a legacy WinForms project to .NET Core. I don't think this issue happened on the Full .NET Framework, but I'm not entirely sure.

**Comment by Olina-Zhang** [comment] 2022-06-20 06:58
verified this issue in .Net 7.0/6.0, and .Net framework 4.8 on CHS OS. Reproduce in .Net framework 4.8 and doesn't reproduce in .Net 7.0/6.0, close it.
![image](https://user-images.githubusercontent.com/26474449/174542887-856d3d37-eebe-4f00-bdd1-589c7a71bdf6.png)
![image](https://user-images.githubusercontent.com/26474449/174542914-b2bb3d12-e6fa-422e-9192-f6d06585b76a.png)

**Closed by Olina-Zhang** 2022-06-20 06:58 UTC
Labels: up-for-grabs

**Comment by bkoelman** [comment] 2022-06-23 23:11
Tried on .NET 6 today, but still seeing the same issue:

![image](https://user-images.githubusercontent.com/10324372/175429722-faffc4dc-9750-4baf-8811-3d7e4808d7b3.png)

**Comment by RussKie** [comment] 2022-06-23 23:17
@bkoelman please raise a new issue and provide as much information as possible.

**Comment by ahdung** [comment] 2022-06-24 01:48
@bkoelman Just curious, why your button controls looks pretty? That's definitely not native button of Windows 7.

**Comment by bkoelman** [comment] 2022-06-26 10:17
> @bkoelman please raise a new issue and provide as much information as possible.

So this gets marked as up-for-grabs again? I don't really see the point...

> @bkoelman Just curious, why your button controls looks pretty? That's definitely not native button of Windows 7.

I'm using Windows 10, not 7. The following is in my Main method:
```c#
Application.SetHighDpiMode(HighDpiMode.DpiUnaware);
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);
```

**Comment by ahdung** [comment] 2022-06-27 00:43
@bkoelman But this title style is windows 7, isn't it?
![image](https://user-images.githubusercontent.com/12094247/175840600-2ba76bb9-1558-4662-9bac-1add0f92766f.png)

And native button on Windows 10 is like this, no rounded corner:
![image](https://user-images.githubusercontent.com/12094247/175840941-0a54e60b-ad0b-48a9-b948-9bff15c76a1f.png)

**Comment by bkoelman** [comment] 2022-06-29 13:17
I don't remember, it's been many years ago I wrote that application. You can find the source at https://github.com/bkoelman/DogAgilityCompetitionManagement/blob/master/src/MediatorEmulator/Program.cs and try it yourself.
