### ISSUE TITLE
Runtime crash due to localization and the way designer serializes keyboard shortcuts

### ISSUE THREAD

**Issue by filipnavara** [dotnet/winforms#2886] opened 2020-02-19 19:14 UTC
* .NET Core Version: 3.1.2

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

Steps to reproduce:
- Create a blank .NET Framework WinForms application with a Form.
- Set the Form to `Localizable = true` in the designer.
- Add context menu with single item.
- Set the `ShortcutKeys` on the item to `Control+C`.
- Observe that the application works just fine on .NET Framework 4.8.
- Switch locale at startup to German by `System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("de-DE");`
- Observe that the application still starts just fine on .NET Framework 4.8.
- Change the application to target `netcoreapp31` and it immediately crashes on startup.

The reason for the crash is that the .resx file contains the shortcut key serialized as
```
  <data name="booToolStripMenuItem.ShortcutKeys" type="System.Windows.Forms.Keys, System.Windows.Forms">
    <value>Ctrl+C</value>
  </data>
```

Notice that the serialized value starts with `Ctrl`, not `Control`. It is produced and consumed by `KeysConverter` class that is [locale dependent](https://github.com/dotnet/winforms/blob/df89eb965dd59fd15341972e3a6ce33e51a86317/src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs#L44-L66). While the value `Control` would work in any locale due to the fallback to names in the `Keys` enum the value `Ctrl` is taken from a dictionary that contains localized names. On .NET Core 3.1 in the German localization the name for `Control` key is `Strg`. Thus the value `Ctrl+C` in the resource file is invalid and causes conversion error at runtime.

Notably we migrated a large project from .NET Framework to .NET Core where we hit this issue. The .NET Framework also has similar issue in code but the localizations may differ which would explain why the problem is not hit.

Manually fixing the value in the .resx file to `Control+C` makes the application work in any locale but any further editing in the designer breaks it again.

**Expected behavior:**

No crash. The resources generated by the designer should be locale independent.

**Minimal repro:**

Here's the sample app created using the steps above. It is multi-targeting both .NET Framework and .NET Core so it can run in both variation from inside Visual Studio.

[WindowsFormsApp2.zip](https://github.com/dotnet/winforms/files/4226867/WindowsFormsApp2.zip)

**Comment by janbaltus** [comment] 2020-02-24 12:54
From comments it seems CTRL being localized as STRG is causing crash. 
Both Ctrl are localized.
If string is not ment to be localized it need to be locked by instruction.

Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationClientSideProviders\Resources\xlf\Strings.xlf
0; "KeyCtrl"
System.Windows.Forms\src\Resources\xlf\SR.xlf
0; "toStringControl"

Can you please confirm which one of above is the functional key?

**Comment by filipnavara** [comment] 2020-02-24 13:12
`toStringControl` is the problematic one.

**Comment by janbaltus** [comment] 2020-02-24 13:24
When we compare resource from .Net Framework same string ID was used and localized in the past

LocComment=(SLE)It's used by the KeyConverter to localize display of menu shortcuts,  it can be translated into whatever is printed on the keyboard for this key (eg. ALT) in the corresponding language.

So from our point of view this might be localizability issue in .NetCore. 
@RussKie can you please check?

**Comment by janbaltus** [comment] 2020-02-24 13:30
please find xls with all tostring occurrences:
[.net.xlsx](https://github.com/dotnet/winforms/files/4244762/default.net.xlsx)

**Comment by weltkante** [comment] 2020-02-24 13:46
Desktop Framework also stores ShortcutKeys localized in the resx file yet doesn't run into this issue. I don't think this is a localization problem as having localized ShortcutKey resx strings works in in Desktop Framework, its more likely that it is a tooling issue.

```xml
  <data name="booToolStripMenuItem.ShortcutKeys" type="System.Windows.Forms.Keys, System.Windows.Forms">
    <value>Ctrl+C</value>
  </data>
```

Note the `type="System.Windows.Forms.Keys, System.Windows.Forms"` which means the resx-compiler is supposed to translate this into the enum, not the runtime on the end user machine. With an enum stored in the binary resx resource instead of a string the ShortcutKeys property should be stored language-independent.

I suspect the .NET Core resx compiler ignores this instruction and stores the type as plain string, causing it to be translated at runtime, which fails depending on the users UI culture.

**Comment by filipnavara** [comment] 2020-02-24 13:54
@weltkante That is most likely correct assumption. .NET Core doesn't deserialize/reserialize resources during build.

**Comment by weltkante** [comment] 2020-02-24 14:11
Yeah can confirm the tooling is badly designed here, .NET Core uses a new resx format which prefers string serialization over binary serialization.

On the reader side they do [ConvertFromInvariantString](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Resources.Extensions/src/System/Resources/Extensions/DeserializingResourceReader.cs#L185)

But I guess on the writer side they don't roundtrip through TypeConverter to emit an invariant string, they probably just emit the resx string directly into the resource. This is probably a bug in corefx tooling, I don't know where the source of the tools is but they should do something like 
```csharp
// get the type converter for the type specified in the resx source
var tc = TypeDescriptor.GetConverter(typeof(Keys));

// roundtrip through TypeConverter once to ensure data is invariant culture
serialized_value = tc.ConvertToInvariantString(tc.ConvertFrom(resx_value));
```

**Comment by filipnavara** [comment] 2020-02-24 14:21
The whole point of the CoreFX tooling was to avoid deserialization and reserialization of the resources and loading all the assemblies with the necessary converters (https://github.com/dotnet/corefx/pull/36906). /cc @ericstj

**Comment by weltkante** [comment] 2020-02-24 14:25
Never mind, WinForms KeysConverter is also totally broken, in that it doesn't implement ConvertFromInvariantString correctly. It just ignores the culture being asked for and [initializes itself](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs#L49) with the CurrentCulture.

Sorry for the multiple posts, seems like I was digging down a rabbit hole :-) It may very well be that corefx resx writer already performs the culture-invariant transform described above and the error is on WinForms side because KeysConverter doesn't support ConvertFromString correctly when given a specific culture.

**Comment by weltkante** [comment] 2020-02-24 14:31
@filipnavara @ericstj you can't avoid running the TypeConverter on build time if you want a culture-invariant serialization format. Serializer and deserializer must be symmetric in what culture they emit and expect.

**Comment by filipnavara** [comment] 2020-02-24 14:31
Yeah, there is problem at multiple levels here and it's not obvious which level[s] need to be fixed.

**Comment by filipnavara** [comment] 2020-02-24 15:30
> But I guess on the writer side they don't roundtrip through TypeConverter to emit an invariant string, they probably just emit the resx string directly into the resource. Since the whole point of resx files is localization nobody should expect resx resources to already be in invariant culture, so this is probably a bug in corefx tooling.

How would the resource compiler know which culture to convert it from? The .resx file doesn't contain any hint about what culture it was created on. I would totally expect it to be already in the invariant form there. In this case English - my system culture - has the same strings as the invariant culture so it's hard to verify.

> Never mind, WinForms KeysConverter is also totally broken, in that it doesn't implement ConvertFromInvariantString correctly.

That looks like an obvious bug to me. For this particular case fixing that would be enough to fix the crash. It should still be verified that on German system the designer still produces invariant values in the .resx file.

**Comment by weltkante** [comment] 2020-02-24 15:48
> I would totally expect it to be already in the invariant form there.
> [...]
> It should still be verified that on German system the designer still produces invariant values in the .resx file.

Your expectations are wrong, resx files are localized (I'm on a german system and get 'Strg' instead of 'Ctrl' in my resx). Note that this behavior is the whole point of this issue, if resx files were invariant to begin with nobody would ever have run into this problem.

You can't just redefine resx files to be invariant unless you both
* update the VS designer to generate resx files invariant for .NET Core (but not for Desktop Framework due to compatibility with existing Desktop applications)
* require everyone migrating from Desktop Framework to un-localize every single resx entry

The VS designer is the reference here (and of course you also want to stay compatible with already existing resx files created in .NET Core projects), whatever culture VS uses to write into WinForms resx files is what needs to be used by the resx tooling as well. If VS designer and build tools don't agree then things never will work out.

If VS uses the current culture (which I'd guess because changing the assembly culture itself didn't have any effect on the designer) then resx files would be incompatible between build machines using different languages, which is very unfortunate, but IMHO redefining resx semantics is not an option. If anything you can extend them by adding a language attribute/tag somewhere and if its not present assume legacy semantics.

**Comment by filipnavara** [comment] 2020-02-24 15:57
> If VS uses the current culture (which I'd guess because changing the assembly culture itself didn't have any effect on the designer) then resx files would be incompatible between build machines using different languages, which is very unfortunate, but IMHO redefining resx semantics is not an option.

This is exactly the reason why I have real trouble believing that .resx can contain non-invariant strings. Note that the `KeysConverter` implementation in NetFX is broken in exactly the same way as the NetCore one (https://referencesource.microsoft.com/#system.windows.forms/winforms/managed/system/winforms/KeysConverter.cs), so even if the designer asked for conversion to invariant culture it would still get a wrong answer.

**Comment by weltkante** [comment] 2020-02-24 15:59
Yes I realized a mistake in my reasoning and edited my last post. This may all be due to the broken KeysConverter. I'll run some tests with custom TypeConverters to figure out the exact behavior of the VS designer + resx build tools.

**Comment by weltkante** [comment] 2020-02-24 18:42
Desktop Framework:
* VS designer interacts with the Property Grid in the Current Culture (OS language) but CurrentUICulture is the VS installation language - in other words the developer usually sees and edits the localized version in the designer (but for KeysConverter he will see keys localized according to his VS language because SR string resources in its implementation use CurrentUICulture not CurrentCulture)
* VS designer stores in resx with invariant culture. This breaks for KeysConverter because it keeps operating on CurrentUICulture which still is the VS installation language.
* msbuild serializes with invariant culture. KeysConverter still uses CurrentUICulture which cancels out the bug when building from within VS, but it will fail the build when run outside VS and the OS and VS language does not match (I for example have english VS on german OS and could not build the test project outside VS)
* runtime deserializes with BinaryFormatter (culture is irrelevant) so the bugs above never mattered for end users as long as your build environment had a consistent language (and if it didn't you'd get build errors instead of runtime errors)

.NET Core
* VS designer doesn't support custom controls yet so I couldn't check how CurrentCulture and CurrentUICulture are used
* msbuild does not use TypeConverter, it just takes the string from resx
* runtime deserializes with invariant culture

Asumming VS designer for .NET Core will be implemented analogous to Desktop Framework it will interact with the user in the Current Culture and serialize to resx with Invariant Culture - then everything will play out fine for a correctly implemented 3rd party TypeConverter.

That leaves the broken WinForms KeysConverter to fix. The new resx writer implementation moves a build-time localization issue (which either canceled out itself or resulted in build failures) into runtime errors, you'll have to fix KeysConverter and support serialization/deserialization with the requested culture, otherwise the new resx format will never work correctly with KeysConverter.

You also might have to consider providing a migration path, because after fixing KeysConverter the VS designer will no longer be able to read resx forms made on non-english VS installations (both made in .NET Core before the fix and those migrated from Desktop Framework will fail to open in the designer). Considering manual fixup of the resx files is possible you may get away without providing an automated resolution in the .NET Core VS designer.

**Comment by filipnavara** [comment] 2020-02-24 19:22
Thanks for the detailed analysis!

We have already worked around the problem by manually updating the resources in our application to use locale-independent versions of key resources. However, it gets broken with any edit in designer so the solution is quite error prone. We will add a unit test to verify the problem at compile time but obviously we expect the issue to be tackled upstream at some point.

**Comment by RalphLAtGitHub** [comment] 2021-04-16 16:07
@merriemcgaw: Is there still hope that the bug will be fixed? What does your timeline look like?

**Comment by filipnavara** [comment] 2021-04-16 16:11
I'd certainly hope that this gets fixed at some point. We have to force our developers to use specific locale on machines running Visual Studio that use the WinForms designer. Additionally we have a unit test that checks all the .resx files to make sure all the shortcuts could still be loaded in different locales.

**Comment by merriemcgaw** [comment] 2021-04-30 20:34
@filipnavara agreed, this certainly needs to be fixed. We'll bubble this up to take a look now since we're much further a long in the localized forms story.
@Olina-Zhang can you test this scenario for localizing keyboard shortcuts on the form? If there's still and issue, let us know here but also create a bug for the designer repo as well. Thanks so much!

**Comment by Jenna-Zheng** [comment] 2021-05-06 06:44
@merriemcgaw this issue is still reproducing and I have create a new bug [#3305](https://github.com/dotnet/winforms-designer/issues/3305) for the designer repo as well.

**Comment by RalphLAtGitHub** [comment] 2022-01-08 14:35
To whom it may concern at Microsoft: It is extremely annoying that Microsoft is unable to fix this bug after almost two years, let alone provide a timeline for solving the problem. if I did my job like that, I would be bankrupt!

**Comment by filipnavara** [comment] 2022-12-02 16:26
At the current pace we will have a 3-year anniversary of this bug report soon.

**Comment by merriemcgaw** [comment] 2022-12-02 21:11
@dmitrii-drobotov Can your team take a look at this? I would love to get this addressed soon.
FYI @Tanya-Solyanik

**Comment by dmitrii-drobotov** [comment] 2022-12-12 14:30
@merriemcgaw sure, we'll look into it.

**Comment by elachlan** [comment] 2023-01-11 04:06
Related: #8440, which suggested we remove the localization. Which would fix this issue.

**Comment by merriemcgaw** [comment] 2023-01-13 00:41
Good call. @NikitaSemenovAkvelon are you still working on this? Take a look at @elachlan's suggestion above if you need some ideas.

**Comment by NikitaSemenovAkvelon** [comment] 2023-01-13 06:33
> Good call. @NikitaSemenovAkvelon are you still working on this? Take a look at @elachlan's suggestion above if you need some ideas.

#8440 is not about the same case. #8401 already fixes this Issue by supporting provided culture in `KeysConverter`. Just waiting for review.

**Comment by merriemcgaw** [comment] 2023-04-18 00:32
Thank you for bringing this back up. I can't commit to a specific timeframe, we are working on the best solution. We are definitely open to backporting this to 6.0 given the need we have seen from the community.

FYI - @Tanya-Solyanik

**Closed** 2023-07-06 18:01 UTC
Labels: :beetle: bug, tenet-localization, :construction: work in progress, area-VSDesigner, area-Serialization-Resx

**Comment by Philip-Wang01** [comment] 2023-07-13 05:59
Verified this on latest .NET 8.0.100-preview.7.23362.29, issue was fixed. But this issue still repro's on down level targets(net3.1,5.0,6.0,7.0), already an issue tracking it(https://github.com/microsoft/winforms-designer/issues/3305).
![test80](https://github.com/dotnet/winforms/assets/86937911/33249800-8d42-4ace-a542-4b32ad9dc582)

**Comment by Tanya-Solyanik** [comment] 2023-07-13 07:24
@dmitrii-drobotov  - could you please add a custom converter, that is based on this fix, to get registered on startup in designer repo to support downlevel versions of Core.

**Comment by Tanya-Solyanik** [comment] 2023-07-13 07:24
@Philip-Wang01  - the fix was implemented only for .NET8

**Comment by Philip-Wang01** [comment] 2023-07-31 05:36
Verified with .NET SDK 8.0.100-preview.7.23376.3 test pass build, this issue was fixed with above same verification result.
