### ISSUE TITLE
TabPage.Text causes control to flicker when called frequently

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#6807] opened 2022-03-08 03:19 UTC
TabPage.Text causes control to flicker when called frequently
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tabpage.text

Test Code: C# / .net 6.0 / Visual Studio 2022
The problem also occurs in .net framework 4.8.

```
namespace TabPageFlickerTest
{
    internal static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();

            Application.Run(CreateForm());
        }

        private static long _loadCount = 0;

        private static TabPage _tabPage;
        private static Button _button;

        private static Form CreateForm()
        {
            var frm = new Form()
            {
                Size = new Size(800, 600),
                StartPosition = FormStartPosition.CenterScreen,

                Padding = new Padding(10),
            };

            var button = _button = new Button()
            {
                Size = new Size(200, 60),
                Location = new Point(20, 20),

                Text = GetTabPageText(),
            };

            var tab = new TabControl()
            {
                Dock = DockStyle.Fill,
            };

            var page = _tabPage = new TabPage()
            {
                Text = GetTabPageText(),
            };

            page.Controls.Add(button);

            tab.TabPages.Add(page);
            frm.Controls.Add(tab);

            frm.ActiveControl = button;

            frm.Load += (object sender, EventArgs e) => frm.BeginInvoke(() =>
            {
                new Thread(LoadFiles).Start();
            });

            return frm;
        }

        private static void LoadFiles()
        {
            for (int n = 0; n < 1000000; n++)
            {
                //Use the Sleep statement instead of the time it takes to load files.
                Thread.Sleep(100);

                _loadCount++;

                _tabPage.Invoke(() =>
                {
                    _tabPage.Text = GetTabPageText();
                    _button.Text = GetTabPageText();
                });
            }
        }

        private static string GetTabPageText()
        {
            return "Number of loaded files: " + _loadCount;
        }
    }
}
```

Test Result:

![001](https://user-images.githubusercontent.com/88176616/157159506-d9d5433f-db6a-4ac2-bf58-e02b7dce92d4.png)

**Comment by elachlan** [comment] 2023-12-19 23:48
`TabPage.Text` -> `UpdateParent()` -> `TabControl.UpdateTab`.
https://github.com/dotnet/winforms/blob/6c410cc50a642015fdb42bdc894e2d16a99f71d0/src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs#L1900-L1910

`SetTabPage` updates the control via `SendMessage` using `TCITEMW` to set the text and image. It then invalidates the DisplayRectangle of the control and does some layout stuff in `UpdateTabSelection`. Some optimization could happen to avoid `UpdateTabSelection` but I do not think it is the cause of the flickering as the DisplayRectangle does not include the tabs.

I'd say the first thing to test is `DoubleBuffered`.

**Comment by elachlan** [comment] 2024-02-02 06:10
@Olina-Zhang could your team please test if `DoubleBuffered` solves this issue?

**Comment by Olina-Zhang** [comment] 2024-02-04 07:00
> @Olina-Zhang could your team please test if `DoubleBuffered` solves this issue?

I cannot repro customer's issue when just using the code provided by customer, don't see any flicker about TabPage.Text.

https://github.com/dotnet/winforms/assets/26474449/8f25816d-8260-47c2-b428-675e58d48b07

**Comment by elachlan** [comment] 2024-02-04 21:04
@lonitra As the author deleted their account and we cannot reproduce the issue, I will close this.

**Closed by elachlan** 2024-02-04 21:04 UTC
Labels: help wanted, tenet-performance
