### ISSUE TITLE
.NET Core 3.0 daily build includes WinForms reference assemblies instead of runtime assemblies

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/winforms#249] opened 2018-12-17 08:13 UTC
3.0.100-preview-009839 (latest daily build)

The following assemblies are reference assemblies:

- System.Windows.Forms
- System.Windows.Forms.Design
- System.Windows.Forms.Design.Editors

An exception is thrown at runtime if you try to run a WinForms application.

**Comment by AdamYoblick** [comment] 2018-12-17 14:03
We did a release into .net core sdk on Friday, so this is mine to investigate. Will look at this first thing today. Thank you.

**Comment by zsd4yr** [comment] 2018-12-17 18:18
Alright, what I'm finding by opening with ilspy and dotpeek is that the assemblies are *not* reference assemblies but they are flagged as such...

Looking into that now

**Comment by zsd4yr** [comment] 2018-12-17 23:41
Can confirm this is fixed internally; Let's give the remainder of the day to let the changes trickle to the SDK

Thanks @0xd4d for flagging this 😄

**Comment by nguerrera** [comment] 2018-12-17 23:48
@AdamYoblick @zsd4yr The "trickling" process isn't automatic yet. If there's an official new build available to insert into the SDK, I can do that. Just let me know.

**Comment by AdamYoblick** [comment] 2018-12-17 23:58
Yeah we know :) Zach will create the PR and we'll ping you when it's ready to go. 

But since you brought it up...is there a timeline for getting dependency flow set up at least for inputs into dotnet sdk? We did this work for the DotNet-Trusted branch and it was pretty minimal for inputs. Maybe I can create the PR for this in dotnet-sdk?

**Comment by zsd4yr** [comment] 2018-12-18 02:45
> @AdamYoblick @zsd4yr The "trickling" process isn't automatic yet. If there's an official new build available to insert into the SDK, I can do that. Just let me know.

Thanks for the heads up. I just wanted to make sure eveyrone on the thread knew that this would not be _instantaneous_. Your clarification is better though 😄

**Comment by nguerrera** [comment] 2018-12-18 02:59
Cc @livarcocc. 

We are getting close to moving dotnet/core-sdk to arcade, which should make dependency uptake easier. 

I don’t have an ETA.

I don’t know what you have in mind with the PR but I would hesitate to make changes to the current build process.

**Comment by AdamYoblick** [comment] 2018-12-18 03:37
The PR would be exactly the changes to enable darc in arcade, without building with the arcade sdk. :)

We are just finishing up those changes in the repo that builds the WindowsDesktop shared UI framework, and the work is pretty minimal. I’m going to document all of it and show it to you guys. 

I think it would bring some immediate value to both coresdk, as well as consumers of coresdk, without the risk of a full arcade update. 

Thoughts? :)

**Comment by nguerrera** [comment] 2018-12-18 06:01
We already have a branch building with arcade and will merging it up to master soon. I don't think it's worth duplicating a subset of that unless it's trivial.

**Comment by AdamYoblick** [comment] 2018-12-18 14:04
The flow IN is trivial and is identical to the “real” arcade work. This is actually more important to us so our latest bits can flow into coresdk

The flow out is more custom and can probably wait.

**Comment by zsd4yr** [comment] 2018-12-18 18:30
This should now be solved. @0xd4d and others looking for a fix here, please see the [new Core SDK build](https://github.com/dotnet/core-sdk/#installers-and-binaries).

I have confirmed that this is now fixed in 3.0.100-preview-009844

**Closed** 2018-12-18 18:30 UTC
Labels: bug
