### ISSUE TITLE
ListView_OnSelectedIndexChanged_Invoke is failing intermittently

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#8156] opened 2022-11-10 02:57 UTC
### Test

System.Windows.Forms.Tests.ListViewTests.ListView_OnSelectedIndexChanged_Invoke(view: LargeIcon, showGroups: True, focused: True, selected: True, expectedCallCount: 2)

### Issue description

Failing multiple times over the past few weeks on the CI

```
Error message
Assert.Equal() Failure\r\nExpected: 2\r\nActual:   1


Stack trace
   at System.Windows.Forms.Tests.ListViewTests.ListView_OnSelectedIndexChanged_Invoke(View view, Boolean showGroups, Boolean focused, Boolean selected, Int32 expectedCallCount) in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs:line 4346
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by RussKie** [comment] 2022-11-10 23:15
We shouldn't be creating these issues manually, instead please use [Runfo app](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3A76) because it would track failures across all builds.

**Comment by dkazennov** [comment] 2023-01-04 17:27
@merriemcgaw 
I was unable to reproduce this issue locally. 
According to [Runfo app](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E100+definition%3A76+name%3AListView_OnSelectedIndexChanged_Invoke) this test is not very regular. It occurred few irregular times during last month (but it looks like there is no connection between PRs where it has been occurred).
So on the meeting we concluded that this Issue is not regular and is not in the priority. Should we close it or just leave it alone right now?

**Comment by merriemcgaw** [comment] 2023-01-13 01:01
I wouldn't prioritize it, as we discussed in the meeting. But we talked about a possible easy solution and if it works we should keep this open long enough to track whether it reproduces in a month or so.

**Comment by Tanya-Solyanik** [comment] 2023-07-18 00:26
I don't see this test in https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E100+definition%3A76

**Closed by Tanya-Solyanik** 2023-07-18 00:26 UTC
Labels: test-bug
