### ISSUE TITLE
strange appearance in text when Cell value start with number with text combination when Right-to-left enabled in DataGridView

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#4381] opened 2020-12-17 08:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/strange-appearance-in-text-when-Cell-val/1289513)._

---
<p>Hi Team,<br><br>I have created a simple DataGrid sample contain cell values that start with numbers and text. in this case, applying the RightToLeft for DataGridView. its show strange appearance for Number start with text in cell value.<br> <br>RTL applying in DataGridView code snippet for your reference,</p><pre>dataGridView1.RightToLeft = RightToLeft.Yes;
dataGridView1.DataSource = new ViewModel(). Orders; </pre><p></p><p>Replication procedure to reproduce the reported issue,<br><br>Step1: particular cell value set as Number start with text in DataGridViewDataSource. for example please refer to the below text,<br>Cell text like:<strong>&quot;</strong><strong>4 number and other text&quot;</strong><br><strong></strong><br>Step2: Run the Sample<br><br>Step3: The number starts with text cell value is a strange appearance. Please refer to the below screenshot for your reference,</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/166561-strangeappearancenumber.png"> Image:166561-strangeappearancenumber.png</a></p><p>The cell value starts with number and text when enabling RTL mode in DataGridView should properly show as<strong> </strong><b>&quot;4 number and other text&quot;<br><br>Sample Link: </b><a href="https://developercommunity.visualstudio.com/storage/attachments/166562-sample.zip">sample.zip</a></p><p>Can you please check and update the details as soon as possible?</p> <p>Regards,<br>Vijayarasan</p><p></p>

---
#### Feedback Bot on 12/17/2020, 02:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by John-Qiao** [comment] 2020-12-17 08:24
* .NET Core Version: 
.NET 6.0.100-alpha.1.20616.3

* Have you experienced this same bug with .NET Framework?: 
Yes

**More Info:**

1. This issue occurs in .NET Framework too, and it's not a regression issue.
2. If the number(4) is not the first word in text cell, this issue does not occur.

**Problem description:**

The string in textbox cell shows "number and other text 4", it's incorrect. 
![Actual](https://user-images.githubusercontent.com/45864985/102461656-a8187280-4083-11eb-885f-d9e186fb16ff.png)

**Expected behavior:**

The string in textbox cell should shows "4 number and other text".

**Minimal repro:**

1. Launch the attached project [WinFormsApp12.zip](https://github.com/dotnet/winforms/files/5707918/WinFormsApp12.zip) in VS and run it.
2. Check the string in the first cell of CustomerName column.

**Comment by weltkante** [comment] 2020-12-17 23:12
> The string in textbox cell shows "number and other text 4", it's incorrect.

Why do you think this is incorrect? All text rendering engines I've looked at behave this way, I believe this is how Unicode treats RTL text mixed with numbers and I'm sure they have very good reasons to order things this way. Its nothing specific to DataGridView either, Labels and TextBox in WinForms show it this way as well. I also tested WPF and various browsers, they all render the right to left text mixed with numbers this way.

"right to left" is a language thing, if you want right-align your cell content you need to look for a different solution.

**Comment by RussKie** [comment] 2020-12-18 01:11
Thank you @weltkante. Closing by design.

**Closed by RussKie** 2020-12-18 01:11 UTC
