### ISSUE TITLE
String Collection Editor dialog is incorrect for PropertiesToLoad property in DirectorySearcher control

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#3049] opened 2020-04-08 10:33 UTC
**.NET Core Version:**

5.0.100-preview.4.20202.8

**Have you experienced this same bug with .NET Framework?:**

No

**Problem description:**

When edit the PropertiesToLoad property for a DirectorySearcher control in PropertyGrid, the incorrect String Collection Editor dialog be opened.
![SCE1](https://user-images.githubusercontent.com/45864985/79202365-18735200-7e6c-11ea-9f9a-9152d47297ab.png)

**More info:**

This issue occurs in .NET Core 3.1 too.

**Expected behavior:**

The correct String Collection Editor dialog should be opened.
![Framework](https://user-images.githubusercontent.com/45864985/78774362-26862600-79c7-11ea-9ba8-71365e7d51b6.png)

**Minimal repro:**

1. Launch the attached project in VS and run it.
2. Click the … edit button for PropertiesToLoad property in PropertyGrid.
[WindowsFormsApp4.zip](https://github.com/dotnet/winforms/files/4449907/WindowsFormsApp4.zip)

**Comment by RussKie** [comment] 2020-04-14 06:45
This is a peculiar line in the project file:
```xml
<TargetFramework>net5.0</TargetFramework>
```
Where did it come from?

It feels related to the new TFM work (e.g. https://github.com/dotnet/designs/pull/109) but I'm not aware of any changes to our repo or WindowsDesktop that relate to that...


The app is working correctly for me if I change it to 
```xml
<TargetFramework>netcoreapp3.1;netcoreapp5.0</TargetFramework>
```

**Comment by John-Qiao** [comment] 2020-04-14 07:39
@RussKie yes, you're right. The target framework info in project file should be:

`<TargetFramework>netcoreapp3.1</TargetFramework>`
or 
`<TargetFramework>netcoreapp5.0</TargetFramework>`

But this issue still can reproduce in .NET Core 3.1 and .NET Core 5.0, I re-uploaded two test apps, please check below:
[Core3.1-TestApp.zip](https://github.com/dotnet/winforms/files/4473771/Core3.1-TestApp.zip)
[Core5.0-TestApp.zip](https://github.com/dotnet/winforms/files/4473772/Core5.0-TestApp.zip)

**Comment by RussKie** [comment] 2020-04-14 08:03
This looks similar to https://github.com/dotnet/winforms/issues/1210, which was fixed in https://github.com/dotnet/winforms/pull/1552.

The issue is originated by .NET Runtime who own System.DirectoryServices.dll.
In .NET Framework this property was decorated with the correct UITypeEditor:
https://referencesource.microsoft.com/#System.DirectoryServices/System/DirectoryServices/DirectorySearcher.cs,71128014b756ae64
In .NET this decoration was removed:
https://github.com/dotnet/runtime/blob/caa2ed96988d89a080dc63edb7c7868daca1cabc/src/libraries/System.DirectoryServices/src/System/DirectoryServices/DirectorySearcher.cs#L230-L235

I can see two distinct parts to the problem:

1. a missing mapping for [`System.Collections.Specialized.StringCollection`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.stringcollection?view=netcore-3.1).
We have mapped the following editors for string collection types:
https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs#L33-L37
`System.Collections.Specialized.StringCollection` inherits from `IList`, which is mapped to 
https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs#L28
So technically the code is working as expected. To address the error we need to add the missing mapping.

2. a recurring "Constructor on type 'System.String' not found" error thrown on line:124:
https://github.com/dotnet/winforms/blob/46cd3ca36be6fe6107ea38edece3639be75fd045/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs#L105-L125
Technically this error doesn't belong to us, but we should be able to fix it by explicit checks for `typeof(string)`.

@merriemcgaw what are our appetites for servicing this in 3.1? The second one is likely a blocker.

**Comment by merriemcgaw** [comment] 2020-04-16 23:57
The second issue is the top priority to fix, but the first one is good to have as well.

**Comment by Tanya-Solyanik** [comment] 2020-04-22 19:27
@merriemcgaw , the second part of this issue is not a regression from the .NET framework. Does it really meet the servicing bar?

1, create a .NET Framework app
2. add user control
3. add a string collection property to the user control
        public StringCollection Strings { get; set; }
4. build
5. add the user control to the form
6. open property browser for this user control
7. browse to the Strings property and open the editor
Result: error box

![image](https://user-images.githubusercontent.com/15823268/80024486-06a93480-8494-11ea-937d-1d39d175833b.png)

Why is it important to enable collection editor for specialized collections in .NET Core?

**Comment by weltkante** [comment] 2020-04-22 20:12
> Why is it important to enable collection editor for specialized collections in .NET Core?

Because it is a regression that the dotnet runtime [removed](https://referencesource.microsoft.com/#System.DirectoryServices/System/DirectoryServices/DirectorySearcher.cs,71128014b756ae64) their attributes which were present [on Desktop](https://github.com/dotnet/runtime/blob/caa2ed96988d89a080dc63edb7c7868daca1cabc/src/libraries/System.DirectoryServices/src/System/DirectoryServices/DirectorySearcher.cs#L230-L235).

WinForms has to provide the attributes because it owns the editor, but it can only do that easily by adding it for the whole type. Its technically possible to add attributes on properties through TypeDescriptors but its a lot more work.

**Comment by Tanya-Solyanik** [comment] 2020-04-22 20:42
Adding intrinsic attribute to StringCollection type(PR #3120 ) is the right fix.

Enabling scenario like this(PR #3111):
```
        [Editor(typeof(CollectionEditor), typeof(UITypeEditor))]
        public StringCollection Strings { get; set; }
```
Has the following problems:
1. It had not worked in .NET framework, we are not enabling porting apps by this fix
2. We are not encouraging the best practices. Collection Editor provides poor experience for editing strings. Add button adds an empty string which has to be edited in the property grid, this adds multiple steps compare to the StringCollectionEditor where the user can add new items by pressing enter in the end of the previous one.

**Comment by RussKie** [comment] 2020-04-22 22:52
> 2\. We are not encouraging the best practices. Collection Editor provides poor experience for editing strings. Add button adds an empty string which has to be edited in the property grid, this adds multiple steps compare to the StringCollectionEditor where the user can add new items by pressing enter in the end of the previous one.

Agree here, but this is about unblocking customers who otherwise will be blocked.

**Comment by Tanya-Solyanik** [comment] 2020-04-23 00:02
Why are customers blocked if we added intrinsic editor on this type? This is not a port from the .NET framework scenario because Collection editor had never worked with Specialized string collections.

**Comment by merriemcgaw** [comment] 2020-04-23 00:46
I think the awful generic collection editor experience is better than the current error message and no experience. Is there any chance that this would break existing apps that have been ported or impact our designer work in any way? If not, I don't have a problem taking a fix.

**Comment by Tanya-Solyanik** [comment] 2020-04-23 00:59
>I think the awful generic collection editor experience is better than the current error message and no experience.

There is no current experience because it had never worked in .NET framework. Our Core out of box experience will show the correct editor. The user has to write code in order to associate the wrong editor with the StringCollection. The error box experience is the correct experience because it indicates that the developer uses incorrect editor. The fix is hiding this error.

**Closed** 2020-04-27 05:14 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress

**Comment by John-Qiao** [comment] 2020-05-20 03:15
Verified the issue in .NET Core 5.0.100-preview.5.20269.19, this issue has been fixed that the String Collection Editor dialog be opened now.
![3049](https://user-images.githubusercontent.com/45864985/82401015-3e9f9980-9a8b-11ea-8422-ee907287f033.png)
