### ISSUE TITLE
An exception occurred when using Class library project in Winforms Core project

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#2935] opened 2020-03-03 11:21 UTC
* .NET Core Version: .Net Core 3.1.200-preview-015008 from 3.1 release branch

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**
This issue cannot reproduce when reopen the solution.

**Minimal repro:**

1. Create a Winforms Core application. 
2. Drag and drop a label to the form designer. 
3. Create a new Class Library(.Net Core) project under the solution.
4. Open Class1.cs in ClassLibrary1 and design a function in Class1.cs as below:
```
public static bool ReferenceMe()
{
	return true;
}	
```
5. Build the solution. Right click References under Core application then click Add Reference… Select Projects under Solution and check ClassLibrary1.
6. Select Form1 of Core project and double click the form to generate a load event and design as below:
```
private void Form1_Load(object sender, EventArgs e)
{
	if (ClassLibrary1.Class1.ReferenceMe())
	{
		this.label1.Text += "\n"+"ClassLibrary is referenced";
	}
}
```
7. Build and run the app.
[WindowsFormsApp8.zip](https://github.com/dotnet/winforms/files/4280955/WindowsFormsApp8.zip)

**Expected behavior:**
The application build and run successfully.

**Actual behavior:**
An exception occurred when using Class library project in Winforms Core project.
![image](https://user-images.githubusercontent.com/45864649/75770418-b9fb7580-5cfc-11ea-9383-5fda0682025d.png)
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'ClassLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=WindowsFormsApp12
  StackTrace:
   at WindowsFormsApp12.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\v-ruizha\source\repos\WindowsFormsApp12\WindowsFormsApp12\Form1.cs:line 29
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by weltkante** [comment] 2020-03-03 11:38
Probably not a WinForms bug, looks like the VS project system didn't copy the referenced class library into the output folder?

**Comment by RussKie** [comment] 2020-03-03 22:34
I am unable to repro the issue. All works as expected:

```powershell
PS> dotnet restore
PS> dotnet build
PS> dotnet run --project .\WindowsFormsApp8\WindowsFormsApp8.csproj
```

**Comment by Jessie-Zhang01** [comment] 2020-03-04 01:55
@RussKie This issue cannot reproduce when reopen the solution, it's only reproduce to new project.

**Comment by RussKie** [comment] 2020-03-04 02:15
The issue isn't specific to Windows Forms. 

@merriemcgaw I'm not sure where this belongs. Roslyn or CPS perhaps?

**Comment by merriemcgaw** [comment] 2020-03-04 02:21
@jmarolf, which one do you suggest? This seems like a pretty big regression.

**Comment by RussKie** [comment] 2020-03-04 02:36
@Jessie-Zhang01 I have created a new Windows Forms app and a new Windows Forms lib, referenced by the app. All is working.

```powershell
pushd C:\Development\temp
md test2935
cd .\test2935\
dotnet new winforms -n app
dotnet new winformslib -n lib
dotnet new sln
dotnet sln add .\app\app.csproj
dotnet sln add .\lib\lib.csproj
dotnet add .\app\app.csproj reference .\lib\lib.csproj
[string](Get-Content .\app\Form1.cs -raw).Replace("InitializeComponent();", "InitializeComponent();`r`n`t`t`tnew lib.Class1();") | Out-File .\app\Form1.cs
dotnet run -p .\app\app.csproj
```

**Comment by merriemcgaw** [comment] 2020-03-06 00:21
Duplicate of https://github.com/dotnet/project-system/pull/5941

**Closed by merriemcgaw** 2020-03-06 00:21 UTC
Labels: won't fix: external

**Comment by Jessie-Zhang01** [comment] 2020-03-06 01:49
Verified this issue on the latest VS version, this issue is fixed.
