### ISSUE TITLE
DPI scaling is broken if font of the form set in designer

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#3202] opened 2020-05-04 09:40 UTC
* .NET Core Version: **3.1.3**

* Have you experienced this same bug with .NET Framework?: **Yes**

**Problem description:**

DPI scaling (`AutoScaleMode.Font`) is broken if font of the form set in designer. Or you can read it as: DPI scaling is broken if font of the form set **after** DPI scaling logic code, even in `SuspendLayout` and before very first `PerformLayout`.
![Snipaste_2020-05-04_11-46-25](https://user-images.githubusercontent.com/17767561/80950205-1878c900-8dfe-11ea-948c-7e14b227bd49.png)
If you put yellow code in front of pink, or in constructor **before** `InitializeComponent();`  - all will be ok.

**The bug appear only if this font is different from current system font.**
Win10 pro 1809/1909.
![Snipaste_2020-05-04_11-35-08](https://user-images.githubusercontent.com/17767561/80950458-92a94d80-8dfe-11ea-8a9a-27fdd324e516.png)

Related old [stackoverflow post](https://stackoverflow.com/a/33600787/6075536).
My personal opinion is that this is not designer problem, this is the problem of DPI scaling logic that depends on instructions order even in `SuspendLayout`...

**Expected behavior:**
Form must be scaled correctly.

**Minimal repro:**
This test project was created in VS 16.6 preview 5 with using of new core designer: [WindowsFormsAppDesignerDPI.zip](https://github.com/dotnet/winforms/files/4573692/WindowsFormsAppDesignerDPI.zip)

**Comment by merriemcgaw** [comment] 2020-05-08 00:19
We want to tackle this when we address DPI scaling holistically. Will bring it up in a designer meeting to see what we might be able to do there. Since this is not a regression and there are workaround we probably won't get DPI across the board working, I'm moving to the future bucket. But I want to continue the design discussion about how we might address this.

**Comment by kirsan31** [comment] 2020-05-08 08:05
@merriemcgaw thank you. Сan you share estimated plan when / in which version will be DPI scaling overhaul?

**Comment by merriemcgaw** [comment] 2020-05-09 00:14
We're working on our longer term roadmap in the coming weeks. I'm starting to see more and more requests for a DPI overhaul from multiple channels, so I'm certain it will be one of the next big things once we get the designer work completed.

**Comment by kirsan31** [comment] 2021-08-09 20:25
@dreddy-work 
[Here](https://github.com/dotnet/winforms/issues/5205#issuecomment-895468492) you mentioned that:

> this is designer issue and is slated for VS 2022 release and will be tracked out side of .NET release.

If so, I think it's must be documented somewhere that correct DPI scaling logic depend on order of these Form's properties setters:
```
AutoScaleDimensions
AutoSizeMode
Font
```

**Comment by Olina-Zhang** [comment] 2021-11-24 06:28
@dreddy-work  verified this issue in the latest .Net 7.0 SDK build using above attached test app, it doesn't reproduce. Please see following testing results on different DPI setting:
125%DPI:
![image](https://user-images.githubusercontent.com/26474449/143186035-6b990c32-70f2-4f5a-badc-b67f4ed29729.png)
200%DPI:
![image](https://user-images.githubusercontent.com/26474449/143186105-a988c2c9-1b05-42de-9f20-3b107ae76383.png)
300%DPI:
![image](https://user-images.githubusercontent.com/26474449/143186180-929691a0-0927-40cf-9442-ddf89506ea36.png)

**Comment by kirsan31** [comment] 2021-11-24 14:27
@dreddy-work 
How could this be fixed?
Due to [this](https://github.com/dotnet/winforms/issues/5205#issuecomment-895468492) the problem is on designer side (what's strange). And VS2022 designer still put font **after** DPI logic...
Also we have #6151 opened and I am not see any PR related to this...

**Comment by dreddy-work** [comment] 2021-11-24 18:16
@Olina-Zhang , can you confirm that the Font assignment is in right place (i.e., after AutoScaleMode)?

**Comment by Olina-Zhang** [comment] 2021-11-25 03:01
Here is the result of 300% DPI: font setting of the form is after DPI scaling logic code in designer.cs file
![image](https://user-images.githubusercontent.com/26474449/143371922-3d759626-754c-4a99-b232-2efda42f4439.png)

**Comment by RussKie** [comment] 2021-11-25 03:45
@kirsan31 do you think you could test your scenarios against the latest .NET 7 and confirm the fix? Thanks

**Comment by kirsan31** [comment] 2021-11-25 07:02
@RussKie @dreddy-work 
Just checked it with latest .Net7 sdk and it's defiantly fixed! Time to port this fix to .Net6 (#6151) :)

---------------------------


P.s. after installing .Net7 and enabling this in VS2022:
![image](https://user-images.githubusercontent.com/17767561/143394002-dbb03e05-4673-4ff3-b24f-76e3db7e35b2.png)

`net6.0-windows` targets will fail to build with dozen's of import errors:
![image](https://user-images.githubusercontent.com/17767561/143394579-f2014fdd-190d-4b36-abf1-1fd6bb960ed3.png)
![image](https://user-images.githubusercontent.com/17767561/143394586-69646ded-429c-478b-a4fb-253128f0c7af.png)

These targets, still builds fine: `net7.0-windows;net5.0-windows;netcoreapp3.1;net472`...

**Comment by RussKie** [comment] 2021-11-25 09:36
> P.s. after installing .Net7 sdk and enabling this in VS2022: ![image](https://user-images.githubusercontent.com/17767561/143394002-dbb03e05-4673-4ff3-b24f-76e3db7e35b2.png)
> 
> `net6.0-windows` targets will fail to build with dozen's of import errors:

Please raise an issue in https://github.com/dotnet/sdk.

**Closed** 2021-11-25 09:37 UTC
Labels: design-discussion, area: HDPI SA, area: VS designer

**Comment by Olina-Zhang** [comment] 2021-11-26 07:10
@RussKie @kirsan31  for targeting 7.0 issue, I filed the one: https://github.com/dotnet/wpf/issues/5648 in sdk repo originally, and was moved to WPF repo now.

**Comment by kirsan31** [comment] 2021-11-26 07:21
@Olina-Zhang My errors was about only 6.0 targeting and I've post my comment in [similar issue](https://github.com/dotnet/sdk/issues/22752).
