### ISSUE TITLE
MdiContainer Form throw error when multipul call Dispose() method.

### ISSUE THREAD

**Issue by Maspapa** [dotnet/winforms#9534] opened 2023-07-21 03:51 UTC
### .NET version

.NET 8.0.100-rc.1.23369.12

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes
This issue only be occured on .net8

### Issue description

In a video below:

- Set the form's IsMdiContainer property to True.
- Add a new form, and set it's MdiParent to form.
- Show the two forms.
- Call form's Dispose() two times.
![MdiDisposeTwice](https://github.com/dotnet/winforms/assets/46096500/e39e2e80-3267-4390-9f1b-2005703818a2)

![image](https://github.com/dotnet/winforms/assets/46096500/2a2974c1-31a6-446b-920a-3adf56c0e796)

### Steps to reproduce

Build and run 
[MdiDisposeTwice.zip](https://github.com/dotnet/winforms/files/12116091/MdiDisposeTwice.zip)

**Comment by elachlan** [comment] 2023-07-21 11:56
Duplicate of #8990

**Comment by dreddy-work** [comment] 2023-07-21 21:51
closing as duplicate.

**Closed by dreddy-work** 2023-07-21 21:51 UTC
Labels: untriaged
