### ISSUE TITLE
`ListViewGroup` shows empty subtitles

### ISSUE THREAD

**Issue by Craftplacer** [dotnet/winforms#5169] opened 2021-06-29 15:48 UTC
* .NET Core Version: 
5.0.203

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
A ListViewGroup header shows space for a subtitle which isn't set.

**Expected behavior:**
A single line ListViewGroup header to be displayed when `Subtitle` (introduced in .NET Core) is set to `null` (or a whitespace, depending what is more convenient/possible inside the designer).

**Minimal repro:**
1. Create a `ListView`
2. Add a new group with `Header` set
3. Add a new item with the group assigned to it
4. ~~Set `View` to `Details` (and add a column so the items are visible)~~ (not required)

| .NET Core | .NET Framework |
| - | - |
| ![image](https://user-images.githubusercontent.com/22963120/123828060-71a89380-d901-11eb-9dd2-faeaa278bca4.png) | ![image](https://user-images.githubusercontent.com/22963120/123828553-e4b20a00-d901-11eb-896b-57a082d7ae68.png) |

**Comment by RussKie** [comment] 2021-06-29 21:19
Duplicate of #5087

**Closed by RussKie** 2021-06-29 21:19 UTC
