### ISSUE TITLE
Propertygrid displays all values in top-left corner of component

### ISSUE THREAD

**Issue by rmsmelik** [dotnet/winforms#4673] opened 2021-03-11 12:28 UTC
* .NET Core Version: 5.0 (Microsoft.WindowsDesktop.App 5.0.4)

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

In the 5.0.4 runtime release of March 9 2021, a display issue has been introduced for the WinForms PropertyGrid component that was not present in the previous 5.0.3 release. It seems that all values the property grid should display are placed in the top-left corner of the component, instead of in their cell next to their property name label.

![PropertyGridValueDisplayIssue](https://user-images.githubusercontent.com/2046078/110787279-71f72300-826d-11eb-93cf-d43775a938a5.png)

**Expected behavior:**
Values are displayed in their corresponding cell.

**Minimal repro:**
The issue can be reproduced by adding a PropertyGrid component to a Form and setting the SelectedObject to any object. Attached is a minimal example. Make sure to have Microsoft.WindowsDesktop.App 5.0.4 installed when running it.

[PropertyGridTextLocationIssue.zip](https://github.com/dotnet/winforms/files/6122935/PropertyGridTextLocationIssue.zip)

**Comment by kirsan31** [comment] 2021-03-11 17:11
https://github.com/dotnet/winforms/issues/4593
<sup>P.s. I think this is only beginning...</sup>

**Comment by RussKie** [comment] 2021-03-12 01:04
Duplicate of https://github.com/dotnet/winforms/issues/4593

**Closed by RussKie** 2021-03-12 01:04 UTC

**Comment by RussKie** [comment] 2021-03-12 01:05
This is a regression in 5.0.4, it is fixed in 5.0.5
