### ISSUE TITLE
Cannot change the BackColor of ToolStrip control

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#3975] opened 2020-09-22 09:19 UTC
* .NET Core Version: 
.NET 5.0.100-rc.2.20471.13

* Have you experienced this same bug with .NET Framework?: 
No

**More Info:**

1. This is a regression issue, it does not occur in .NET SDK 5.0.100-Preview.8.20417.9, it start from .NET 5.0 RC1.
2. This issue also can reproduce in the Properties window(design mode). 

**Problem description:**

Cannot change the BackColor of ToolStrip control
![core](https://user-images.githubusercontent.com/45864985/93864590-b4e13080-fcf7-11ea-89c0-64f3c91ef716.png)

**Expected behavior:**

The BackColor of ToolStrip control can be changed correctly. 
![framework](https://user-images.githubusercontent.com/45864985/93864605-bad71180-fcf7-11ea-9094-46caaa29e81d.png)

**Minimal repro:**
[Testapp.zip](https://github.com/dotnet/winforms/files/5260320/Testapp.zip)
1. Launch the attached project in VS and run it.
2. Try to change the BackColor property in PropertyGrid and check the result.

**Comment by JeremyKuhne** [comment] 2020-09-22 19:36
Appears to have been introduced here: https://github.com/dotnet/winforms/commit/6200def6834ec7772567b2e814c41d4d11c108ed#diff-1db24b8cc62d33e03991e772250a1aa6

**Comment by JeremyKuhne** [comment] 2020-09-22 21:46
> Appears to have been introduced here: 6200def

Or maybe not- narrowing

**Comment by JeremyKuhne** [comment] 2020-09-22 22:04
It appears to be this one: https://github.com/dotnet/winforms/commit/a6a308fa452770caafca55ee4d8ac54d1ee1015d

It does draw the right color for the background then ends up painting over it. Not immediately clear what is causing this.

**Comment by merriemcgaw** [comment] 2020-09-22 23:47
@John-Qiao  How is this behaving in HC mode? Does the ToolStrip turn the appropriate colors?

**Comment by JeremyKuhne** [comment] 2020-09-23 04:50
I found the cause and fixed it. I will have a PR up tomorrow. The problem affects anything that relies on clipping or transforms to do rendering...

**Comment by John-Qiao** [comment] 2020-09-23 09:54
@merriemcgaw @JeremyKuhne we did a full controls testing with the private dlls for PR [3956](https://github.com/dotnet/winforms/pull/3956), yes, the **BackColor** property of ToolStrip control cannot be changed in both Non-HC mode and HC mode, and the **ForColor** property of ToolStripStatusLabel/Label/LinkLabel/TextBox/ToolStrip controls does not display based on it was set in app(with and without private both repro this issue). 

Zheng Li will send a detailed testing result email to you.

**Comment by JeremyKuhne** [comment] 2020-09-24 18:17
Fixed in RC2 with #3993

**Closed by JeremyKuhne** 2020-09-24 18:17 UTC
Labels: :boom: regression, Priority 1 :exclamation:

**Comment by John-Qiao** [comment] 2020-09-27 09:19
Verified the issue in Dev16 16.9.0 Preview 1.0 [30525.185.main] + .NET 5.0.100-rc.2.20476.4 from RC2 branch , this issue has been fixed that the BackColor can be changed for ToolStrip control successfully. 
![TestResult](https://user-images.githubusercontent.com/45864985/94361265-9313ef00-00e5-11eb-91a3-e00c57a13a0e.png)
