### ISSUE TITLE
UITypeEditor does not type-forward from System.Drawing

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#2413] opened 2019-11-21 23:06 UTC
* .NET Core Version: 5.0 master
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
For some reason UITypeEditor does not automatically type-forward from System.Drawing.Design to System.Windows.Forms.Design even though it is a public type. I was under the impression that public types get their type forwards automatically generated and manual entries only are required for internal types referenced by name.

This breaks [ControlBindingsCollection](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/ControlBindingsCollection.cs#L15) which has an EditorAttribute referencing UITypeEditor itself. Technically this attribute is pretty much a no-op, its only effect is that a non-null editor is returned from TypeDescriptor.GetEditor but the editor itself has all methods no-op.

Either case I think the type forward for UITypeEditor should be put in place anyways, not just for attributes referencing by string but for general compatibility, since its a public type.

**Actual behavior:**
UITypeEditor does not type forward even though its a public type

**Expected behavior:**
UITypeEditor should type forward from System.Drawing.Design facade to System.Windows.Forms.Design. The type forward should be generated automatically and not have to be manually inserted in the project.

**Minimal repro:**
Fails test in PR #2230 when removing skip entry

**Comment by weltkante** [comment] 2019-11-22 11:02
I think UITypeEditor comes from System.Drawing, not from System.Drawing.Design, that would explain why the type forward is not generated.

I think this needs to be coordinated with CoreFX, as they own System.Drawing now? Or does WinForms have a facade for System.Drawing.dll which takes priority over CoreFX? I remember the situation to be a bit complex.

Otherwise we can just remove the attribute from ControlBindingsCollection (or update the attribute to point at the new location of UITypeEditor), this editor is really a no-op and should have never been put into the attribute in the first place.

**Comment by RussKie** [comment] 2020-01-31 05:33
I think the underlying issue that you have already discovered is that the `ControlBindingsCollection` decoration is incorrect:
https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/System/Windows/Forms/ControlBindingsCollection.cs#L16-L19

It should be:
```diff
     [DefaultEvent(nameof(CollectionChanged))]
-    [Editor("System.Drawing.Design.UITypeEditor, " + AssemblyRef.SystemDrawing, typeof(UITypeEditor))]
+    [Editor("System.Drawing.Design.UITypeEditor, " + AssemblyRef.SystemDesign, typeof(UITypeEditor))]
     [TypeConverter("System.Windows.Forms.Design.ControlBindingsConverter, " + AssemblyRef.SystemDesign)]
     public class ControlBindingsCollection : BindingsCollection
```

**Comment by RussKie** [comment] 2020-01-31 05:45
I think the underlying issue that you have already discovered is that the `ControlBindingsCollection` decoration is incorrect:
https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/System/Windows/Forms/ControlBindingsCollection.cs#L16-L19


In .NET Framework `UITypeEditor` was declared in System.Drawing.dll. However in .NET Core it was moved to System.Windows.Forms.dll, so the original decoration is incorrect.
@Tanya-Solyanik @dreddy-work @DustinCampbell should it be this?
```diff
     [DefaultEvent(nameof(CollectionChanged))]
-    [Editor("System.Drawing.Design.UITypeEditor, " + AssemblyRef.SystemDrawing, typeof(UITypeEditor))]
+    [Editor(typeof(UITypeEditor), typeof(UITypeEditor))]
     [TypeConverter("System.Windows.Forms.Design.ControlBindingsConverter, " + AssemblyRef.SystemDesign)]
     public class ControlBindingsCollection : BindingsCollection
```

Or can we just remove this line altogether?

**Comment by dreddy-work** [comment] 2020-02-11 01:23
@RussKie , We were generating facads for all public classes/methods that were moved around.  In this case, I see system.windows.forms is added as reference for System.Drawing assembly. Was it not generating facad there?

**Comment by Tanya-Solyanik** [comment] 2020-02-11 01:41
>Or can we just remove this line altogether?

Designer relies on this hard-coded text so far.

**Comment by weltkante** [comment] 2020-02-11 08:00
@dreddy-work I think this redirect was either missing or broken, as tests showed this type didn't resolve correctly. Fix could be either adding a redirect, correcting the attribute, or removing it alltogether

@Tanya-Solyanik it does? the editor which is specified here is a no-op because it doesn't implement a subclass (none of the methods on the base class do anything), so unless the designer makes a difference between a null editor and an editor which does nothing, it shouldn't matter

**Comment by dreddy-work** [comment] 2020-02-11 23:56
@weltkante , I see type forward in "System.Drawing.dll" .  Were the tests failing on the latest runtime?  I know we removed editors binary completely and merged it with winforms and design assemblies sometime back.  But i see type forwards are working as expected here.  Can you poin to the exact test that is failing ? so that we can root cause the issue before making final action?

![image](https://user-images.githubusercontent.com/36968667/74290325-604bf080-4ce6-11ea-8ff7-97d1ffd77f1e.png)

**Comment by weltkante** [comment] 2020-02-12 08:09
Last line in issue description refers to [this skip entry](https://github.com/dotnet/winforms/blob/fde3805ea206227ad01266c7d25ce0ed2df4996f/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs#L23) - if you remove it and the test no longer fails then it was solved by some other PR since the tests had been checked in

**Comment by weltkante** [comment] 2020-02-12 08:18
Your redirects are from System.Drawing 5.0 but the string references look for [4.0](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/AssemblyRef.cs#L9) so I'm pretty sure all these references will be failing.

@RussKie why was System.Drawing.dll leveled to 5.0 when the Desktop references it should be redirecting are looking for 4.0 ?

**Comment by RussKie** [comment] 2020-04-17 04:55
@ericstj do you think you could give us a guidance here?

**Comment by ericstj** [comment] 2020-04-17 14:23
For desktop compat shims don’t change the assembly version.  Don’t remove types, maintain APICompat with previous release.  APICompat should catch problems where you remove type forwards.

.NETCore does allow newer assembly versions to automatically satisfy older references, but there is no good reason to version the compat shims since they have no types.

**Comment by weltkante** [comment] 2020-04-17 15:46
Thanks, I only tested this inside WinForms repo, so I didn't notice it does work outside this repo.

> .NETCore does allow newer assembly versions to automatically satisfy older references

In the WinForms repository (which is hardcoded to use `5.0.0-alpha1.19514.1`) this doesn't work. I checked both unit tests and the `WinformsControlsTest` standalone application, both fail to resolve the redirect.

Creating an independent application with `5.0.0-preview.2.20160.6` works however.

Is this a .NET Core version issue (needing an update in the repo) or is there some switch that the WinForms repo uses, turning off this roll-forward feature?

> For desktop compat shims don’t change the assembly version.

There are type forwards in non-shim assemblies so the version forwarding definitely needs to work.

**Comment by weltkante** [comment] 2020-04-17 15:53
Disregard the version quoted above, I was on a PR branch, testing on master uses `5.0.0-preview.4.20216.4` and still doesn't work. Must be some global switch in the WinForms repo which prevents rolling forward on type redirects?

**Comment by ericstj** [comment] 2020-04-17 19:49
> I'm testing Type.GetType("System.Drawing.Design.UITypeEditor, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", false) and it returns null when called within the WinForms repo but resolves properly in a standalone project.

You should probably see what version of System.Drawing is being loaded.   I bet you're loading the one from the base shared framework rather than the one you're building in the winforms repo.  This is probably happening because your test isn't running against a WindowsDesktop shared framework and hasn't referenced the System.Drawing assembly you build in the winforms repo.  Does your test actually reference winforms's System.Drawing

**Comment by weltkante** [comment] 2020-04-17 22:19
Yup, thats it, it picks up the wrong System.Drawing.dll - and you're also right that the reference is missing.

Just adding the reference like done for the other facades isn't enough though, it gets a System.Drawing.dll with the right redirects copied into the output folder but it has version 42.42.42.42 - while the shared framework has 4.0.0.0 so I assume the loader finds an exact match and never tries the System.Drawing.dll from the output folder.

So it will obviously be necessary to revert the 5.0 version on System.Drawing (WinForms should use the same version as the shared framework it is replacing), but I have no idea how to get unit tests working when local builds use a 42.42.42.42 placeholder version. I'll leave that for someone to figure out who understands the WinForms build infrastructure.

**Comment by ericstj** [comment] 2020-04-17 22:22
> but it has version 42.42.42.42 - while the shared framework has 4.0.0.0 and gets loaded anyways, I assume because the loader finds an exact match and never tries the System.Drawing.dll from the output folder?

No, that shouldn't happen.  The host should decide one version to use.  Can you share the deps file for the test?

**Comment by weltkante** [comment] 2020-04-18 06:46
Sure, it says `"System.Drawing": "5.0.0-dev"` (which is what I'd expect when referencing the facade) but thats only present in the AssemblyInformationalVersion not in the real assembly version of System.Drawing.dll copied into the output folder. At runtime it loads the shared framework one in 4.0.0.0 either way.

[WinformsControlsTest.deps.txt](https://github.com/dotnet/winforms/files/4496178/WinformsControlsTest.deps.txt)

**Comment by ericstj** [comment] 2020-04-20 13:44
Deps file doesn’t list version info:
‘’’
        "runtime": {
          "System.Drawing.dll": {}
        }
‘’’

Normally file and assembly version info should be included to allow the host to choose which version should win.  Your build process isn’t including that.

**Comment by weltkante** [comment] 2020-04-20 13:58
@RussKie for the record, I've been adding `<ProjectReference Include="..\..\..\..\System.Drawing\src\System.Drawing.Facade.csproj" />` to the relevant test projects `WinformsControlsTest` and `System.Windows.Forms.Tests`. They were already referencing other facades and I just added the missing one.

Regarding how to fix the build process to include the required data you'll have to redirect the issue to someone who is familiar with it. I don't think it has high priority though.

**Comment by ericstj** [comment] 2020-04-20 15:32
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
@wli3 @dsplaisted

**Comment by ericstj** [comment] 2020-04-20 15:34
Might be this https://github.com/dotnet/sdk/issues/3254

**Comment by weltkante** [comment] 2020-04-20 15:54
yup, looks like WPF has the exact same problem with WindowsBase, which is also in the shared framework like System.Drawing

**Comment by weltkante** [comment] 2020-04-20 17:15
[Looks like](https://github.com/dotnet/sdk/issues/3254#issuecomment-616654069) you can work around by adding both a `ProjectReference` a direct `Reference` to the assembly file. I'll try to figure out what the right msbuild variables are and make a PR.

**Comment by weltkante** [comment] 2020-04-20 18:14
The PR does not include reverting the 5.0 versions back to 4.0, unit tests are running without doing that (mostly because I don't know how to override the version for a project, it seems to be set globally). If desired the versioning issue for facades can be moved to a separate issue so someone else can look at it who knows more about the WinForms build infrastructure.

I still think it should be done since currently the console SDK has a System.Drawing 4.0 and winforms SDK has a System.Drawing 5.0, it would be better if different parts of the SDK agree about which version to use for facades.

**Closed** 2020-04-21 08:00 UTC
Labels: :beetle: bug, :construction: work in progress, area: designer support
