### ISSUE TITLE
When form icon is used, form.resx throws an error

### ISSUE THREAD

**Issue by tanek100** [dotnet/winforms#4661] opened 2021-03-08 15:32 UTC
* .NET Core Version: 
.NET 5.0.2 SDK

* Have you experienced this same bug with .NET Framework?: 
 No
**Problem description:**
If new form is created and Icon is set in properties, then the form resx throws an error: Object reference not set to an instance of an object. Ico files was used.

![image](https://user-images.githubusercontent.com/3244218/110341906-85b74500-8033-11eb-970f-20decd7b1469.png)

**Expected behavior:**
resx file should be usable in visual studio after setting icon to form.

**Minimal repro:**
1. Add new windows form to project (.NET SDK 5.0.2, Visual studio Version 16.9.0).
![image](https://user-images.githubusercontent.com/3244218/110342473-1aba3e00-8034-11eb-8a5f-2c05880bbda0.png)
2.  and add icon to form.
![image](https://user-images.githubusercontent.com/3244218/110342523-2d347780-8034-11eb-9355-08a5bf7b96c7.png)

**Comment by kirsan31** [comment] 2021-03-08 18:53
I can confirm this on 16.8.4 too.
![image](https://user-images.githubusercontent.com/17767561/110367182-65e64800-8058-11eb-899c-30c7e821e447.png)

I am 99% sure that next step they will want from you is report it [here](https://developercommunity2.visualstudio.com/home) directly from your V.S.

**Comment by RussKie** [comment] 2021-03-09 05:54
@merriemcgaw  @Olina-Zhang do you know if this is tracked in the designer repo?

**Comment by Olina-Zhang** [comment] 2021-03-09 06:01
@RussKie，this is the designer repo issue: https://github.com/dotnet/winforms-designer/issues/1248, which had been fixed in VS: 16.10 Preivew1.

**Comment by RussKie** [comment] 2021-03-09 08:54
Thank you @Olina-Zhang 

@tanek100 closing since it's been fixed. Please let us know if you still have issues in VS 16.10P1 or later.

**Closed by RussKie** 2021-03-09 08:54 UTC
Labels: area: VS designer
