### ISSUE TITLE
NET8: BinaryFormatter not supported when .resx contains "application/x-microsoft.net.object.binary.base64"

### ISSUE THREAD

**Issue by panxn** [dotnet/winforms#9701] opened 2023-07-14 07:53 UTC
### Description
I'm using .NET8, our `.resx` files contains `<data name="imageList1.ImageStream" mimetype="application/x-microsoft.net.object.binary.base64">`

They can be successfully built but throw exception at runtime.
> BinaryFormatter serialization and deserialization are disabled within this application.

I know BinaryFormatter is going to be deprecated, and I can re-enable it by `EnableUnsafeBinaryFormatterSerialization=true`, but it's just a temporary solution.

Will dotnet team enhance the build tool to support these .resx files? or we developers should update .resx files? and what is the recommended way?

BTW, is there some help document for developers to adapt to the obsolescence of BinaryFormatter? For example, how to read existing files saved by BinaryFormatter, how to deal with `application/x-microsoft.net.object.binary.base64` in `.resx`. I believe it will be very helpful.

### Reproduction Steps

No

### Expected behavior

If `mimetype="application/x-microsoft.net.object.binary.base64"` can be built, it should not throw.

### Actual behavior

It throws exception.

**Comment by panxn** [comment] 2023-08-10 04:51
@JeremyKuhne thank you!

As for this question:

> WinForms and WPF projects should have the enabled by default for .NET 8. If this isn't happening for your project we can investigate with @GrabYourPitchforks.`BinaryFormatter`

I think it's because the main frame of our product is MFC, the entry assembly of .NET is a c++/cli module, winform&wpf are used in other C# modules.

I tried in .NET8, the runtimeconfig.json for the c++/cli module sets `EnableUnsafeBinaryFormatterSerialization` to false even though it has `<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />` in vcxproj. However, it's not a problem for us, we can set `EnableUnsafeBinaryFormatterSerialization` to true in vcxproj.

**Comment by paul1956** [comment] 2023-08-10 06:57
@JeremyKuhne,
I get 99 Binary Formatter Warnings when I open my project if I try to use .Net 8. Even with .Net 7 and no errors there are still issues with latest release and prerelease with Designer does not allow any changes without corrupting the .Designer file and crashing. One specific type causing the issue is KeyValuePair(of String, KnownColor) gets converted to KeyValuePair. But there may be others. All of this has been reported with feedback tool and a project that shows the issues is on GitHub ( could do a smaller one if required).

How am I supposed to replace BinaryConverter when I don't use it the designer does. Will there be a 1-time upgrade to convert existing Designer File to not use BinaryFormatter but something else?

If I want to try .Net8 where is the procedure to correctly do it with WinForms. If EnableUnsafeBinaryFormatterSerialization  is required for WinForms why is that not automatically set.

**Comment by MelonWang1** [comment] 2023-10-25 07:32
The original issue was [9174](https://github.com/dotnet/winforms/issues/9174).

Repro steps:
1. Create winform .NET 8.0 Core project
2. Change the TargetFramework from net8.0-windows to net9.0-windows in the csproj file
3. Add an ImageList control to form designer
4. Open smarttag and add some images
5. Build and run

Actual result:
Exception pops up when executing ImageList.ImageCollection.SetKeyName(Int32 index, String name)
![imagelist](https://github.com/dotnet/winforms/assets/94418985/d452ec90-abc4-4dcd-8ae3-0a7735d77800)

Call Stack:
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.ImageList.ImageCollection.SetKeyName(Int32 index, String name)
   at WinFormsApp119.Form1.InitializeComponent() in C:\Users\xxxg\source\repos\WinFormsApp119\WinFormsApp119\Form1.Designer.cs:line 40
   at WinFormsApp119.Form1..ctor() in C:\Users\v-melonwang\source\repos\WinFormsApp119\WinFormsApp119\Form1.cs:line 7
   at WinFormsApp119.Program.Main() in C:\Users\xxx\source\repos\WinFormsApp119\WinFormsApp119\Program.cs:line 14

**Comment by Amy-Li03** [comment] 2023-11-09 07:27
Failed to load 'Explorer Form' template forms designer on a winforms .NET VB project when targeting .NET 9.0. 
It has also appeared on a targeting .NET 8.0 projects before. https://github.com/microsoft/winforms-designer/issues/5233
![image](https://github.com/dotnet/winforms/assets/62929087/aab36dc5-cd92-4868-872b-1fd9647a17fb)

**Comment by AngeloCresta** [comment] 2023-12-01 15:05
[MelonWang1](https://github.com/MelonWang1) - [Amy-Li03](https://github.com/Amy-Li03) have you already tried to add:
`
	<PropertyGroup>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
		<NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
		<GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
	</PropertyGroup>
`

to the .net9 project file?
Just to test other behavior of the project avoiding the "well known" issue on binary formatter ...

**Comment by MelonWang1** [comment] 2023-12-04 07:40
@AngeloCresta  Verified this in .NET 9.0.100-alpha.1.23580.4, issues https://github.com/dotnet/winforms/issues/9174. and https://github.com/microsoft/winforms-designer/issues/5233 were fixed when add above codes in .csproj file. 

https://github.com/dotnet/winforms/assets/94418985/d4a280dd-4d41-4bce-bfef-fdf3a177a639

**Comment by damien-c-d** [comment] 2024-05-15 05:11
I'm getting a warning for this in .NET 8. Has there been any progress so far? Or is it just going to break when we upgrade to .NET 9? It's disappointing something still hasn't been done about it but I just hope there's a solution by the first RC for .NET 9.

**Comment by Liv-Goh** [comment] 2024-06-28 08:27
Verified this in .NET 9.0.100-preview.6.24325.8, the binary formatter issue on image list unable to fix by adding codes above to the .csproj file.

<img width="397" alt="image" src="https://github.com/dotnet/winforms/assets/169347065/4719b581-7f99-4596-ada8-276f6f9b55f4">

**Comment by AngeloCresta** [comment] 2024-06-28 12:20
Yes, in version .NET 9.0.100-preview.7.24323.5 the image file is not serialized and added to the .resx file (you can check) and the designer part is "missing" the image strem source:
`imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));`

I think it's by design ... and they're not ready to replace the BinaryFormatter in winforms in builtin components like ImageList (not working)
Angelo

**Comment by noname-1234-ai** [comment] 2024-07-11 07:58
mimetype: application/x-microsoft.net.object.binary.base64
value   : The object must be serialized with 
        : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
        : and then encoded with base64 encoding.

mimetype: application/x-microsoft.net.object.soap.base64
value   : The object must be serialized with 
        : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
        : and then encoded with base64 encoding.

mimetype: application/x-microsoft.net.object.bytearray.base64
value   : The object must be serialized into a byte array 
        : using a System.ComponentModel.TypeConverter
        : and then encoded with base64 encoding.

**Comment by canislupus-llc** [comment] 2024-07-15 21:09
I was able to work around this issue by removing the ImageList from the form designer altogether, and instead initializing it at run time from images that I saved as project resources. So, when initializing the form, just build the image list from resources, assign the image list to the control (in my case, a TreeView).

This works fine and the warning disappears.

**Comment by JeremyKuhne** [comment] 2024-07-24 22:51
We've enabled embedded binary format resources in the .NET Runtime repo. @Tanya-Solyanik and @Shyam-Gupta are investigating workflow scenarios in the designer around generating the embedded resources.

**Comment by Philip-Wang01** [comment] 2024-08-29 09:09
Verified this with the latest internal VS: 17.12.0 Preview 2.0 + .NET SDK 9.0.100-rc.2.24428.6 build, it was fixed. BinaryFormatter support when .resx contains "application/x-microsoft.net.object.binary.base64"

https://github.com/user-attachments/assets/9676348e-6b5d-4d60-837d-f6f49766a900

**Comment by Tanya-Solyanik** [comment] 2024-09-04 02:13
Suggestion to triage - close this issue.

**Comment by merriemcgaw** [comment] 2024-09-04 22:37
@Tanya-Solyanik  I think I will 😁

**Closed by merriemcgaw** 2024-09-04 22:37 UTC
Labels: area-VSDesigner, area-Serialization-Resx, tracking, area-Serialization-BinaryFormatter-FeatureWork

**Comment by damien-c-d** [comment] 2024-09-05 05:26
I assume this being closed means that when we upgrade to .NET 9 any form/control using an ImageList will not cause anything to break?

**Comment by Tanya-Solyanik** [comment] 2024-09-05 19:00
> I assume this being closed means that when we upgrade to .NET 9 any form/control using an ImageList will not cause anything to break?

If you have VS version that is being released now - 17.12 preview2 or newer
