### ISSUE TITLE
What's the matter with PropertyGrid in NET5.0 

### ISSUE THREAD

**Issue by alexluozf** [dotnet/winforms#4699] opened 2021-03-18 13:48 UTC
* .NET Core Version: 
windowsdesktop-runtime-5.0.4-win-x64

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

Only the focus property value display.
![PropertyGrid Issue](https://user-images.githubusercontent.com/62095636/111636587-989bf780-8833-11eb-9f35-239c1443d879.png)

**Expected behavior:**

**Minimal repro:**

**Comment by kirsan31** [comment] 2021-03-18 15:29
https://github.com/dotnet/winforms/issues/4593

**Comment by RussKie** [comment] 2021-03-18 22:42
Duplicate of #4593

**Closed by RussKie** 2021-03-18 22:42 UTC
