### ISSUE TITLE
Split Container - Object name: 'Disposed 'Cursor' can no longer be used.'.

### ISSUE THREAD

**Issue by AngeloCresta** [dotnet/winforms#6795] opened 2022-03-04 12:53 UTC
* .NET Core Version: 
C:\Users\Angelo>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22567
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

* Visual Studio Version: 
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.1.0

* Have you experienced this same bug with .NET Framework?: 
No 

**Problem description:**
At design time, when overing with the mouse the split container I receive:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Disposed 'Cursor' can no longer be used.'.
   at System.Windows.Forms.Cursor.get_Handle()
   at Interop.User32.SetCursor(IHandle hCursor)
   at System.Windows.Forms.Control.WmSetCursor(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.DotNet.DesignTools.Designers.Behaviors.BehaviorService.AdornerWindow.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

![image](https://user-images.githubusercontent.com/12256319/156766559-1e74f5ff-abad-46f0-8932-88f8f3529c56.png)

at runtime:

![image](https://user-images.githubusercontent.com/12256319/156766629-986374f0-b0ab-450b-ad16-3f15fc735fc7.png)

**Expected behavior:**
No error

**Minimal repro:**

[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/8185974/WinFormsApp1.zip)

**Comment by rickbrew** [comment] 2022-03-04 17:40
I think this is the same issue as here: https://github.com/dotnet/winforms/issues/6798

**Comment by AngeloCresta** [comment] 2022-03-04 17:51
we're both on the same windows dev build 22567...

**Comment by rickbrew** [comment] 2022-03-04 17:56
Yeah it seems to be a new bug in Win11 that is causing a WinForms bug to happen more often.

You should be able to workaround this in the meantime by first copying your `Stream` into a `MemoryStream` and then passing the `MemoryStream` to the `Cursor(Stream)` constructor. `MemoryStream` never returns a partial result from `Read()`.

**Comment by AngeloCresta** [comment] 2022-03-04 19:11
I've fixed on my side, sublassing all child controls of my custom form, instantiating on activation a mouse filter (tranparent click near the border) that inherits a nativewindow. There, overriding WndProc, I set an ugly try-catch... Waiting for the fix...

**Comment by RussKie** [comment] 2022-03-07 03:09
This is a Windows-level bug, see https://github.com/dotnet/winforms/issues/6798#issuecomment-1059994865.

**Comment by RussKie** [comment] 2022-03-07 03:09
Duplicate of #6798

**Closed by RussKie** 2022-03-07 03:09 UTC
