### ISSUE TITLE
Font style does not work in Application.SetDefaultFont() when the text scale value is bigger than 100% in OS

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#4978] opened 2021-05-26 09:56 UTC
* .NET Core Version: 

   .NET SDK 6.0.100-preview.5.21275.4

* Have you experienced this same bug with .NET Framework?: 

   No 

**More Info:**

This issue occurs in other System.Drawing.FontStyle enum values too, like Bold, Strikeout and Underline...

**Problem description:**

The font style is not _Italic_ for controls in form.
![Actual](https://user-images.githubusercontent.com/45864985/119639755-7ed9ea80-be4a-11eb-83aa-c3e50ac8bb23.png)
![ReproSteps](https://user-images.githubusercontent.com/45864985/119639797-87cabc00-be4a-11eb-94bb-d742976521d4.gif)

**Expected behavior:**

The font style should be _Italic_ in form, like it works when text scale is 100%.
![Expected](https://user-images.githubusercontent.com/45864985/119639685-6d90de00-be4a-11eb-8a7e-e27efd1195ef.png)

**Minimal repro:**

1. Open the attached [TestApp.zip](https://github.com/dotnet/winforms/files/6545730/TestApp.zip) project in VS, run it and check the font style of buttons. -- Font style is _Italic_ in this time.
2. Stop the project, and open the **Display** setting in OS, then change the text scale(**Make text bigger**) to 150% and click **Apply** option.
3. Run project again and observe the font style in controls.

**Comment by Olina-Zhang** [comment] 2021-05-26 11:05
This issue was found after the PR: https://github.com/dotnet/winforms/pull/4911 merged.

**Comment by kirsan31** [comment] 2021-05-26 15:48
The problem is here:
https://github.com/dotnet/winforms/blob/f577471f0d2d338721676cd78b007ae696795de4/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs#L1243
We need to set `FontStyle` too:
```cs
s_defaultFontScaled = new Font(s_defaultFont.FontFamily, s_defaultFont.Size * textScaleValue, s_defaultFont.Style);
```

**Comment by RussKie** [comment] 2021-05-26 22:54
🤦‍♂️

**Closed** 2021-06-03 00:50 UTC
Labels: :construction: work in progress, up-for-grabs

**Comment by RussKie** [comment] 2021-06-16 06:28
@kirsan31 would you be open for a chat? If so, could you please reach out to me at igor.velikorossov at microsoft dot com?

**Comment by kirsan31** [comment] 2021-06-16 06:32
@RussKie 

> would you be open for a chat? If so, could you please reach out to me at igor.velikorossov at microsoft dot com?

Hm, I don't quite understand what do you mean. I think this was closed by you in #5030.

**Comment by RussKie** [comment] 2021-06-16 07:33
Хотел бы пообщаться, если удобно напиши на емайл.

**Comment by kirsan31** [comment] 2021-06-16 08:09
@RussKie 
> would you be open for a chat? If so, could you please reach out to me at igor.velikorossov at microsoft dot com?

I emailed to you from golikova at gmail dot com, In case of spam filters.

**Comment by John-Qiao** [comment] 2021-06-17 06:50
Verified with .NET 6.0.100-preview.6.21315.23 + private binaries build from main branch in dotnet/winforms repo, this issue has been fixed that font style works when the text scale value is bigger than 100% in OS.
![TestResult](https://user-images.githubusercontent.com/45864985/122346238-517cea00-cf7b-11eb-8e62-8f2dfe6d4e23.png)

**Comment by John-Qiao** [comment] 2021-06-21 02:00
Verified with .NET 6.0.100-preview.7.21320.2 from main branch, this issue has been fixed that font style works as above when the text scale value is bigger than 100% in OS.

**Comment by John-Qiao** [comment] 2021-06-23 09:12
Verified the issue with .NET 6.0 6.0.100-preview.6.21323.1, it is fixed as above result too.
