### ISSUE TITLE
Setting GenerateMember to false is not removing class member

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#8505] opened 2023-01-14 17:25 UTC
### Environment

Microsoft Visual Studio Community 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
Version 4.8.09032

### .NET version

.Net7, .Net6. Others not tested.

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes in old .NET framework designer.

### Issue description

`GenerateMember = false` must remove corresponding class member from `*.Designer.cs`. Actual behavior:

![image](https://user-images.githubusercontent.com/17767561/212486575-cff39aa2-d3e7-4726-a71d-5f24000f856e.png)

### Steps to reproduce

Any winforms project. Open designer, select any existing control on the form, set `GenerateMember` to `false`.
Project to quick test:
[GenerateMemberTest.zip](https://github.com/dotnet/winforms/files/10418373/GenerateMemberTest.zip)

**Comment by merriemcgaw** [comment] 2023-01-18 18:55
We are tracking this in our internal designer repo. Thanks for reporting it @kirsan31!

**Comment by Tanya-Solyanik** [comment] 2024-10-25 23:43
Closing as a duplicate of an internal issue, will update this one when we make progress on the internal issue.

**Closed** 2024-10-25 23:43 UTC
Labels: area-VSDesigner, tracking
