### ISSUE TITLE
Position of minimized MDI child changes when maximized and minimized twice

### ISSUE THREAD

**Issue by MohanramAnbukkarasu** [dotnet/winforms#570] opened 2019-03-12 04:17 UTC
**Problem description:**
In an MDI environment, when we maximize and minimize an MDI child repeatedly for a couple of times, the child form hidden below

**Actual behavior:** 
When we continuously maximize and minimize an MDI child, the vertical position of the child form changed as shown in the following image. 

![image](https://user-images.githubusercontent.com/44049406/54174195-4937c980-44ab-11e9-9b99-65e8c9d87fb6.png)

**Expected behavior:**
The position of the MDI child should not be changed. 

**Minimal repro:**
Please find the sample application and the video to reproduce this from the following link.

[Sample and video illustration](https://developercommunity.visualstudio.com/storage/attachments/57799-sample.zip)

**Comment by MohanramAnbukkarasu** [comment] 2019-04-02 05:47
@merriemcgaw I don't know exactly. I think the issue is in the form.

**Comment by MohanramAnbukkarasu** [comment] 2019-04-02 09:28
Is there any update in this? Please provide the solution at the earliest.

**Comment by merriemcgaw** [comment] 2019-04-03 20:54
Please confirm whether this issue also exists in .NET Framework 4.7.2 to determine if this is a regression from .NET Framework. We're prioritizing issues that will bring .NET Core to parity with .NET Framework. General improvements and new features will be considered for .NET Core 3.0.

**Comment by MohanramAnbukkarasu** [comment] 2019-06-25 09:25
The same issue exists also in .Net Framework 4.7.2

**Comment by kirsan31** [comment] 2021-03-07 06:38
The link in the 1 post is dead, and with simple mdi app I can't repro this. We defiantly need more repro steps here.

**Comment by elachlan** [comment] 2022-12-12 07:53
I also cannot reproduce this using the WinformsControlsTest MDI Parent Form. I suggest closing this issue.

**Comment by merriemcgaw** [comment] 2022-12-12 23:15
Consider it done! 😄

**Closed by merriemcgaw** 2022-12-12 23:15 UTC
Labels: :beetle: bug, help wanted, area: MDI
