### ISSUE TITLE
Unable to select controls inside the TabControl

### ISSUE THREAD

**Issue by therawk** [dotnet/winforms#3303] opened 2020-05-19 07:45 UTC
* .NET Core Version: 
3.1.300-preview-015135

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
I added a TabControl and added other components like TextBox and Label and now want to drag the TextBox around. It doesn't work since the Designer seems to ignore my selection of a specific element. 

**Expected behavior:**
It is possible to add UI Controls to the TabControl and can select and drag around the controls inside the TabControl

**Minimal repro:**
1. Add a TabControl
2. Resize it so it covers the whole Form
3. Add a TextBox to the TabControl
4. Click outside the Form
5. Try to click on the TextBox

**Comment by Zheng-Li01** [comment] 2020-05-20 01:38
@RussKie, there have exist issue [1589](https://github.com/dotnet/winforms-designer/issues/1589) in dotnet/winforms-designer repo to track it.

**Comment by Avaruz** [comment] 2021-05-06 19:22
Same issue in Visual Studio 16.9.4 and .Net 5.0.202!!!

**Comment by merriemcgaw** [comment] 2021-05-10 23:05
@Avaruz and team - we're expecting to have a fix for this in an upcoming 16.10 this spring. We did some changes on the internal engine of the designer and this was picked up as part of those changes. I'll reply back when I can tell you which Preview for certain.

**Comment by Olina-Zhang** [comment] 2021-05-11 02:52
@Avaruz we verified this issue in the same test environment: Visual Studio 16.9.4 and .Net 5.0.202, it cannot reproduce, see following screenshot and gif:
![image](https://user-images.githubusercontent.com/26474449/117750866-bb042d00-b246-11eb-94cb-502a3be961e1.png)
![TestResult-3303](https://user-images.githubusercontent.com/26474449/117750408-ef2b1e00-b245-11eb-80bc-5b0d9cfa6a90.gif)
If you still have this issue, you can install the latest VS preview version from here: https://visualstudio.microsoft.com/vs/preview/  or waiting for a upcoming fixed release VS: spring or summer version to upgrade.

**Comment by Avaruz** [comment] 2021-05-11 13:24
> @Avaruz we verified this issue in the same test environment: Visual Studio 16.9.4 and .Net 5.0.202, it cannot reproduce, see following screenshot and gif:
> ![image](https://user-images.githubusercontent.com/26474449/117750866-bb042d00-b246-11eb-94cb-502a3be961e1.png)
> ![TestResult-3303](https://user-images.githubusercontent.com/26474449/117750408-ef2b1e00-b245-11eb-80bc-5b0d9cfa6a90.gif)
> If you still have this issue, you can install the latest VS preview version from here: https://visualstudio.microsoft.com/vs/preview/ or waiting for a upcoming fixed release VS: spring or summer version to upgrade.

Here is the same issue in other machine recently installed:

![Animation](https://user-images.githubusercontent.com/690375/117822423-8db18200-b23a-11eb-8612-1d5a1e61d86e.gif)

**Comment by RussKie** [comment] 2022-02-21 03:15
@therawk is this still an issue in the latest VS 2022?

**Closed** 2022-03-14 07:01 UTC
Labels: :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity, area: VS designer
