### ISSUE TITLE
ComboBox with DropDownList style does not reflect the configured BackColor and ForeColor

### ISSUE THREAD

**Issue by Liv-Goh** [dotnet/winforms#11900] opened 2024-08-16 10:14 UTC
### .NET version

.NET 9.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, still repro in .NET 4.8.1, it is not a regression issue

### Issue description

When change the BackColor and ForeColor of the DropDownList style combobox, the color only reflect on the dropdown items of the comboBox. The color of the comboBox does not follow the color configuration and remain the default color.

**Current Behavior (DropDownList)**
![comboBoxDropDownListCurrent](https://github.com/user-attachments/assets/a14e4130-6cbc-43f7-9f57-40a24b51f56f)

**Expected Behavior (DropDown)**
![comboBoxDropDownListExpected](https://github.com/user-attachments/assets/84f10bfd-f452-4df3-b5fe-2837b4026940)

### Steps to reproduce

1. Create a WinForms Project
2. Add a comboBox to the form
3. Add sample item to the comboBox
4. Set the DropDownStyle property to DropDownList
5. Set the BackColor and ForeColor properties to any random color
6. Build and run the project

**Comment by KlausLoeffelmann** [comment] 2024-08-17 19:53
This is by design of the underlying Win32 APIs.
I am closing this by design, if anybody feels differently, feel free to reopen.

**Closed by KlausLoeffelmann** 2024-08-17 19:53 UTC
Labels: untriaged

**Comment by Radaos** [comment] 2024-08-19 16:01
By convention, a greyed out control indicates that it is inactive. It seems like the design of the API should be reconsidered since it is breaking this convention. 
By changing ComboBox.FlatStyle = FlatStyle.Flat, BackColor is then displayed as set, so the API is not even consistent.
