### ISSUE TITLE
[.NET 8]ErrorProvider picks the wrong size from multi-resolution icons

### ISSUE THREAD

**Issue by koszeggy** [dotnet/winforms#10735] opened 2024-01-24 13:17 UTC
### .NET version

.NET 8.0.100

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

All .NET Framework versions, and also .NET Core / .NET up to .NET 7

### Issue description

If you assign a multi-resolution icon to `ErrorProvider`, then before .NET 8 a smaller size was taken than in .NET 8.

Illustration:

| Description | Image |
|-|-|
| .NET 7, 100% | ![image](https://github.com/dotnet/winforms/assets/27336165/0f68f424-d0f5-4105-aa6f-03d92e93ebc3)|
| .NET 7, 150% | ![image](https://github.com/dotnet/winforms/assets/27336165/4aadc67b-f54e-43a0-ba5a-3159f255a44b)|
| .NET 8, 100% | ![image](https://github.com/dotnet/winforms/assets/27336165/003a764d-a001-464b-ac8d-321f7659e917) |

### Steps to reproduce

See the attached [ErrorProviderIssue.zip](https://github.com/dotnet/winforms/files/14038709/ErrorProviderIssue.zip).

The screenshots above use [this](https://docs.kgysoft.net/drawing/html/P_KGySoft_Drawing_Icons_SystemError.htm) error icon, which returns dynamic sizes based on the current DPI.

When using fix-sized icons (like [this one](https://docs.kgysoft.net/drawing/html/P_KGySoft_Drawing_Icons_Error.htm)), the old behavior is also not perfect as it always takes the smallest icon. But taking the 32x32 one on 100% DPI (as it happens now in .NET 8) is definitely not a better solution.

A workaround that works both for .NET 7- and .NET 8+ is included in the attached example. It [extracts](https://docs.kgysoft.net/drawing/html/M_KGySoft_Drawing_IconExtensions_ExtractNearestIcon.htm) the proper icon size based on the current DPI. If the change is because the old behavior wasn't quite desired something like this could be a possible solution.

**Comment by elachlan** [comment] 2024-01-24 21:11
@koszeggy do you get the issue when using the default icon? (if we narrow the reproduction it makes testing easier)

**Comment by koszeggy** [comment] 2024-01-25 10:38
> @koszeggy do you get the issue when using the default icon? (if we narrow the reproduction it makes testing easier)

@elachlan: No, as the default icon always has a single image, which is correctly initialized to the current DPI, i.e. on 100% DPI it has a single 16x16 image, on 150% a 24x24 one, etc.

The issue is that when an icon contains multiple images, eg. a 16x16 one **and** a 32x32 one, then in .NET 8, at 100% DPI the 16x16 image should be picked (just like how the default icon is initialized to be a 16x16 image in this case) instead of the mistakenly chosen 32x32 image.

See the multi-res icons I linked in my report. The attached project uses them as well so the reproduction and testing must be pretty straightforward. I can also offer my [debugger visualizers](https://marketplace.visualstudio.com/items?itemName=KGySoft.drawing-debugger-visualizers-x64) to make testing easier; it can show all of the images of an `Icon` instance.

**Comment by elachlan** [comment] 2024-01-25 10:53
An ICO file can have multiple sizes. But Icon doesn't allow for this. So winforms will load the icon image and then scale it based on DPI.

This might take some investigation to get right. Since users might expect the size of the icon to be used, so we can't rescale it.

The team will know more, or someone can read up the docs on error provider and see what it says for the icon.

**Comment by koszeggy** [comment] 2024-01-25 11:23
> But Icon doesn't allow for this. So winforms will load the icon image and then scale it based on DPI.

Actually it is handled pretty well normally. Eg. `Graphics.DrawIcon` always picks the most appropriate image of a combined icon. Or, the `Form.Icon` may display the different image sizes at the same time in the taskbar and on the top-left corner of the form (though this is mainly handled natively by the OS).

Or, when loaded as (or [converted](https://docs.kgysoft.net/drawing/html/M_KGySoft_Drawing_IconExtensions_ToMultiResBitmap.htm) to) a `Bitmap` and is assigned to a `PictureBox.Image`, for example, then a repaint always picks the best fitting image.

Anyhow, even a `System.Drawing.Icon` instance can easily contain multiple images. In fact, [`SystemIcons.Shield`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.systemicons.shield) returns an `Icon` instance containing 9 images. Feel free to try the attached repro in .NET 7 and in .NET 8 assigning `SystemIcons.Shield` to the error provider.

**Comment by JeremyKuhne** [comment] 2024-01-29 23:59
May be fallout from https://github.com/dotnet/winforms/commit/90242d4409f2fb5533f5291631d49fb8cc026a35?

**Comment by elachlan** [comment] 2024-01-30 21:18
There was a change in the `IconRegion` constructor in #8486 that removed the 16x16 icon size. That might be the cause. I suspect this was done so that the icon wasn't loaded as 16x16 at different DPIs. I guess we would use ScaleHelper to get the right size?
![image](https://github.com/dotnet/winforms/assets/2433737/c8fd9547-bbcf-4253-91ef-c1ebe26e493e)

Maybe something like
```csharp
public IconRegion(Icon icon)
{
    _icon = new Icon(icon, ScaleHelper.LogicalSmallSystemIconSize);
}
```

**Comment by Tanya-Solyanik** [comment] 2024-02-01 21:19
@LeafShi1 @Epica3055 @SimonZhao888 @ricardobossan  - could you please verify what change (https://github.com/dotnet/winforms/commit/90242d4409f2fb5533f5291631d49fb8cc026a35 or https://github.com/dotnet/winforms/pull/8486)regressed this scenario?

**Comment by ricardobossan** [comment] 2024-02-03 02:37
> @LeafShi1 @Epica3055 @SimonZhao888 @ricardobossan - could you please verify what change ([90242d4](https://github.com/dotnet/winforms/commit/90242d4409f2fb5533f5291631d49fb8cc026a35) or #8486 this scenario?

@Tanya-Solyanik I investigated the reported scenario to determine if it is related to commit [90242d4][c90242d4] or PR [8486][pr8486], which was merged by that commit. Here are my findings:

### Test Procedure:

#### Setting the environment

- Utilized the provided [test project][test-proj] by @koszeggy and installed the [suggested VS extension][vs-extension].
- Modified the `ErrorProviderIssue.csproj` to include local runtime repo project references, like this:

    ```xml
    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net8.0-windows</TargetFrameworks>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="KGySoft.CoreLibraries" Version="8.1.0" />
        <PackageReference Include="KGySoft.Drawing" Version="8.0.0" />
      </ItemGroup>

      <ItemGroup>
        <ProjectReference Include="C:\Users\v-rbossan\source\repos\winforms\src\System.Drawing.Common\src\System.Drawing.Common.csproj" />
        <ProjectReference Include="C:\Users\v-rbossan\source\repos\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj" />
      </ItemGroup>

    </Project>
    ```

#### Test on runtime repo commit before 90242d4

1. Checked out to the commit **before** [90242d4][c90242d4].
2. Ran the test project repo:
   ```bash
   dotnet restore
   dotnet build
   dotnet run --framework net8.0-windows
   ```
3. Observed the application launching with too large icons, indicating the problem pre-existed commit [90242d4][c90242d4], which merged PR [8486][pr8486]:

    ![Application Launch with Large Icons](https://github.com/dotnet/winforms/assets/30190295/aaa53d97-4c1f-4667-8b1e-69f57b55615b)

#### Additional Steps

- Attempted to run `gh pr checkout 8486` but encountered an error due to the remote branch no longer existing.

### Findings

- The issue persists in the commit before [90242d4][c90242d4], suggesting it is unrelated to this specific commit or PR [8486][pr8486].

### Conclusion:

Based on the tests conducted, it appears that the reported scenario is not related to the changes introduced in commit [90242d4][c90242d4] or PR [8486][pr8486]. Further investigation may be needed to pinpoint the root cause of this issue.

[pr8486]: https://github.com/dotnet/winforms/pull/8486
[c90242d4]: https://github.com/dotnet/winforms/commit/90242d4409f2fb5533f5291631d49fb8cc026a35
[test-proj]: https://github.com/dotnet/winforms/files/14038709/ErrorProviderIssue.zip
[vs-extension]: https://marketplace.visualstudio.com/items?itemName=KGySoft.drawing-debugger-visualizers-x64

**Comment by Tanya-Solyanik** [comment] 2024-02-03 22:05
@ricardobossan - does this repro on NET9? Please start by adding a test case to WInfomsControlsTest interactive test, if it's not already available. If this does repro on NET9, please start working on it, Leaf had fixed a similar issue recently in the ThreadExceptionDialog.

**Comment by ricardobossan** [comment] 2024-02-06 23:30
Yes. I added a test case to WinformsControlTest and it does repro on NET9. I'm now working on solving it.
![image](https://github.com/dotnet/winforms/assets/30190295/2af121f2-9277-4008-80af-aa6551908b23)

**Comment by Tanya-Solyanik** [comment] 2024-02-07 01:14
Feel free to create a PR with test only. 
Suggestion: for the second text box, mention that ErrorProvider uses a system icon. For exammple:
<img width="395" alt="image" src="https://github.com/dotnet/winforms/assets/15823268/30fb8610-27b0-49a6-a5a3-2c0ab16be912">

**Comment by koszeggy** [comment] 2024-02-07 10:08
Please note though that `SystemIcons.Error` contains only a single 32x32 bitmap, so @ricardobossan's last [screenshot](https://private-user-images.githubusercontent.com/30190295/302806076-2af121f2-9277-4008-80af-aa6551908b23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDAwMzQsIm5iZiI6MTcwNzI5OTczNCwicGF0aCI6Ii8zMDE5MDI5NS8zMDI4MDYwNzYtMmFmMTIxZjItOTI3Ny00MDA4LTgwYWYtYWE2NTUxOTA4YjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA5NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOTE0ZDg3YzMxNzFlNDg1MjAyNDY3NTUyY2RlZjU4YmZiZmJmMTU0ZTNlNDEzMjZlOGEzNTNmZTg3NmNiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XzUIdmpjeGmQyatIphPOUEuM1WhG_q3rDceO1FsiO8g) is actually the expected behavior. You need to use a multi-resolution icon to reproduce the issue. If you don't want to use the 3rd party libraries from the repro project I recommend using the `SystemIcons.Shield` icon instead, which contains 3 different sizes in 3 pixel formats (9 bitmaps altogether). The aforementioned [debugger visualizers](https://marketplace.visualstudio.com/items?itemName=KGySoft.drawing-debugger-visualizers-x64) may help to check the `Icon` instances along with all their bitmaps.

**Closed** 2024-02-09 18:26 UTC
Labels: :construction: work in progress, area-Anchor/Scaling, area-HDPI, area-System.Drawing, :boom: regression-release, area-ErrorProvider

**Comment by Nora-Zhou01** [comment] 2024-02-18 06:47
Tested this issue in the latest .Net 9.0 SDK build: 9.0.100-preview.2.24116.21, it was fixed that ErrorProvider on 100% DPI,150% DPI is correctly sized in multi-resolution icons.
![10735](https://github.com/dotnet/winforms/assets/104609169/61d72440-28c9-4b64-84d3-5bcfc4574b24)

**Comment by MandiMan** [comment] 2024-03-04 08:51
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.
