### ISSUE TITLE
Wrong display of selected folder in FolderBrowserDialog with WPF in vb.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#8490] opened 2023-01-11 16:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Wrong-display-of-selected-folder-in-Fold/10176303)._

---
Hello,

With version 17.6.3 of visual studio with .Net 6 in WPF in VB language, I use the FolderBrowserDialog dialog box.  
I initialize the SelectedPath property with the value: “P:\\Gestion\_REDWOOD”.  
When displaying the dialog box, I notice that the name of the folder displayed in the textbox is truncated.  
The displayed and selected text is “estion\_REDWOOD”.  
If I move the cursor to the beginning of the text or if I press the “Home” key, I can see all the text

Here is my code :

```  
Private Sub btnDialogueDestination_Click(sender As Object, e As RoutedEventArgs) Handles btnDialogueDestination.Click

	'Sélection du dossier de destination

	Dim openFolderDialog As New Forms.FolderBrowserDialog()
	openFolderDialog.SelectedPath = txtDestination.Text
	openFolderDialog.Description = "Dossier de destination sur le cloud"
	If openFolderDialog.ShowDialog = Forms.DialogResult.OK Then
		txtDestination.Text = openFolderDialog.SelectedPath
	End If

End Sub
  
```

Here is a screenshot :

![FolderBrowserDialog.gif](https://aka.ms/dc/image?name=B9f6c3798e8774842a4354c18d2d7e0e4638017578647322735_FolderBrowserDialog.gif&tid=9f6c3798e8774842a4354c18d2d7e0e4638017578647322735)

The problem is also present with the “OpenFileDialog” dialog box.  
The file name is also truncated.

If the number of characters in the file name is less than the code example above, the file name display is correct. From a certain length of text, the text shifts to the left to be displayed. It is then truncated.

Correct display, smaller text.  
![openFileDialog1.png](https://aka.ms/dc/image?name=B040d3dd7a065447d9794f8a84322d2ea638017741879118098_openFileDialog1.png&tid=040d3dd7a065447d9794f8a84322d2ea638017741879118098)

---
#### jacky.perpete on 10/19/2022, 00:42 PM: 

(private comment, text removed)
#### Feedback Bot on 10/19/2022, 01:24 PM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 10/20/2022, 09:11 AM: 

(private comment, text removed)
#### jacky.perpete on 10/20/2022, 07:16 PM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 10/21/2022, 08:13 AM: 

(private comment, text removed)
#### jacky.perpete on 10/23/2022, 04:43 PM: 

(private comment, text removed)
#### Peng Ge [MSFT] on 10/24/2022, 03:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by elachlan** [comment] 2023-01-12 06:48
This is a duplicate of #7968

CC: @merriemcgaw

**Comment by merriemcgaw** [comment] 2023-01-12 17:58
Yep, agreed @elachlan. I am going to close this as a duplicate and I recommend that the feedback ticket be closed as "low priority" since no one is blocked and the data is there.

**Closed by merriemcgaw** 2023-01-12 17:58 UTC
