### ISSUE TITLE
VS crashes by resizing DataGridview scrollbars in inheritance when making them permanently visible

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#4284] opened 2020-11-26 02:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-crashes-by-resizing-DataGridview-scro/1263854?preview=true)._

---
[severity:It's more difficult to complete my work]
Hello,
as described and confirmed by an other community member (Timon Yang) VS 2019 crashes when you try to make the vertical and horizontal scrollbar permanently visible independant from the rows and column count. 

**Report by Timon Yang:**
If I make any changes to it and then run the project, Visual Studio will definitely crash, but after opening Visual Studio again, it won’t crash anymore.

It is always impossible to operate it in the designer, whether it is moving or deleting, but as long as the relevant code of the horizontal scroll bar is commented, it can be operated normally.
This is not a solution to this problem, but a solution for the current situation where this control cannot be operated in the designer.

**Link and Code:**
[https://social.msdn.microsoft.com/Forums/windows/en-US/f91fe749-72d6-4ccc-a41c-0208faddac61/show-always-horizontal-and-vertical-scrollbar-in-a-datagridview?forum=csharpgeneral&prof=required]()

```
 class MyDatagridview : DataGridView
    {
        public MyDatagridview()
        {
            VerticalScrollBar.Visible = true;
            HorizontalScrollBar.Visible = true;

            HorizontalScrollBar.VisibleChanged += HorizontalScrollBar_VisibleChanged;
            VerticalScrollBar.VisibleChanged += VerticalScrollBar_VisibleChanged;

        }

        private void VerticalScrollBar_VisibleChanged(object sender, EventArgs e)
        {
            if (!VerticalScrollBar.Visible)
            {
                int width = VerticalScrollBar.Width;
                VerticalScrollBar.Location = new Point(ClientRectangle.Width - width - 1, 1);
                VerticalScrollBar.Size = new Size(width, ClientRectangle.Height-2);
                VerticalScrollBar.Show();
            }
        }

        private void HorizontalScrollBar_VisibleChanged(object sender, EventArgs e)
        {
            if (!HorizontalScrollBar.Visible)
            {
                int height = HorizontalScrollBar.Height;
                HorizontalScrollBar.Location = new Point(1, ClientRectangle.Height - height );
                HorizontalScrollBar.Size = new Size(ClientRectangle.Width - 2-17,height);
                HorizontalScrollBar.Show();
            }
        }
    }
```

---
#### Feedback Bot on 11/23/2020, 11:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Zheng Li [MSFT] on 11/24/2020, 05:20 PM: 

<p>Dear customer, thanks for your feedback.</p>
<p>The issue can reproduce on side based on your description, want to confirm with you, did you have the same experience than before?</p>
<p>In addition, the Visual Studio crashed when re-size the DGV or try to delete/Cut it, if these matched your points? and the  issue also can reproduce on .NET Core project.<br>
<img src="https://aka.ms/dc/image?name=B870741ade6d24d0fa413786f5c2d7929637418077160801744_FeedBackRepro1.gif&amp;tid=870741ade6d24d0fa413786f5c2d7929637418077160801744" alt="FeedBackRepro1.gif"><br>
<img src="https://aka.ms/dc/image?name=B78fffb2bdd59470b949951bb290d0fcd637418077340278881_FeedBackRepro2.gif&amp;tid=78fffb2bdd59470b949951bb290d0fcd637418077340278881" alt="FeedBackRepro2.gif"></p>
<p><img src="https://aka.ms/dc/image?name=B283e85fb87eb48c7a9a0a3c09b23aacc637418077458786075_FeedBackRepro3.gif&amp;tid=283e85fb87eb48c7a9a0a3c09b23aacc637418077458786075" alt="FeedBackRepro3.gif"></p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Ba3984f57450e4ccea36a7461685f99cb637418077646832590_FeedBack1.zip&amp;tid=a3984f57450e4ccea36a7461685f99cb637418077646832590">FeedBack1.zip</a></p>
<p>Thanks<br>
Zheng</p>

---
### Original Solutions
(no solutions)

**Comment by Zheng-Li01** [comment] 2020-11-26 02:36
The issue also can reproduce between .NET Framework and .NET Core projects, and have a workaround provided by @KlausLoeffelmann that is working well. please see below details.

 **Repro Steps:**
1. Opened the attached project.
[FeedBack1249245.zip](https://github.com/dotnet/winforms/files/5600117/FeedBack1249245.zip)
2. Drag & drop the MyDataGridview control to Form1.cs[Design].
3. Try to cut or delete or running the project after re-sized the MyDataGridview contorl.

**Actually results:**
VS crashed.
![FB1249245Before](https://user-images.githubusercontent.com/38325459/100301356-f2ea2180-2fd2-11eb-91f7-97c29022b264.gif)

**Expected results**
VS working well.
![FB1249245After](https://user-images.githubusercontent.com/38325459/100301364-f8e00280-2fd2-11eb-80a7-d60a0133d1c3.gif)

**Workaround**
![Workaround](https://user-images.githubusercontent.com/38325459/100301329-ebc31380-2fd2-11eb-9c33-76bda9d7727c.PNG)

**Comment by merriemcgaw** [comment] 2024-10-23 20:10
Closing since we have a workaround and this applies to both designers

**Closed by merriemcgaw** 2024-10-23 20:10 UTC
Labels: area-VSDesigner
