### ISSUE TITLE
PerMonitorV2 DPI scaling not firing ScaleControl method for deeply nested layouts

### ISSUE THREAD

**Issue by filipnavara** [dotnet/winforms#6152] opened 2021-11-10 10:59 UTC
* .NET Core Version: 6.0 RTM

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

Deeply nested controls don't get `ScaleControl` called when moving to secondary monitor (150% DPI -> 100% DPI) in PerMonitorV2 mode.

**Expected behavior:**

`ScaleControl` is always called for deeply nested controls when DPI changes.

**Minimal repro:**

To be done.

It looks like the following code may be to blame:
https://github.com/dotnet/winforms/blob/83b3228c2fa5bbde44cb1e8e1b36eb6f328f1289/src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs#L688-L697

When reaching one of the deeply nested container controls it looks up the parent and gets the scale factor from it. However, the parent itself at this point has `AutoScaleMode.Inherit` and hence the values are not set and the reported scaling is `(1.0F, 1.0F)`.  That leads to the following code skipping the scaling:

https://github.com/dotnet/winforms/blob/83b3228c2fa5bbde44cb1e8e1b36eb6f328f1289/src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs#L990-L1000

Values in debugger:

![image](https://user-images.githubusercontent.com/1764393/141101092-468dba86-394c-4420-99ea-c5d205977ad1.png)

**Comment by filipnavara** [comment] 2021-11-10 14:24
Test app:
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/7513384/WinFormsApp1.zip)

On net5.0 TFM moving it to different screen (with different DPI setting) changes color:

https://user-images.githubusercontent.com/1764393/141130587-0c8d5f8a-1b96-4616-a10b-22d70624e462.mp4


On net6.0 TFM it stays gray because ScaleControl is not called:

https://user-images.githubusercontent.com/1764393/141130609-0e164133-2380-40aa-b4ff-43658f067211.mp4

**Comment by kirsan31** [comment] 2021-11-10 15:03
https://github.com/dotnet/winforms/pull/6130? Seems need to be servicing...

**Comment by merriemcgaw** [comment] 2021-11-10 17:38
@dreddy-work  can you take a look?

**Comment by dreddy-work** [comment] 2021-11-10 18:15
#6130 should help it here. Regarding service, given this is PerMonitorV2 mode, we may not be able to service but get it fixed in 7.0

**Closed** 2021-11-10 18:17 UTC
Labels: :beetle: bug, :boom: regression, area: HDPI, :construction: work in progress

**Comment by filipnavara** [comment] 2021-11-10 18:22
We absolutely need this serviced as it's a regressions from .NET 5 that is blocking upgrade to .NET 6 for us.

**Comment by dreddy-work** [comment] 2021-11-10 18:26
> We absolutely need this serviced as it's a regressions from .NET 5 that is blocking upgrade to .NET 6 for us.

Your app is already in PermonitorV2 mode? Is it possible for you to share your app?

**Comment by filipnavara** [comment] 2021-11-10 18:28
It was PerMonitorV2 for a while on supported Windows versions. Unfortunately I cannot share the source code but it can be downloaded from https://www.emclient.com. I will ne happy to share any small bits of the source code if necessary to isolate any issues but I cannot share it as a whole.

**Comment by dreddy-work** [comment] 2021-11-10 18:30
> It was PerMonitorV2 for a while on supported Windows versions. Unfortunately I cannot share the source code but it can be downloaded from https://www.emclient.com. I will be happy to share any small bits of the source code if necessary to isolate any issues but I cannot share it as a whole.

That is fine. I will request if i need any further. It helps in our validations to cross verify customer apps. Will update this thread on  servicing decision.

**Comment by RussKie** [comment] 2021-11-10 22:04
> We absolutely need this serviced as it's a regressions from .NET 5 that is blocking upgrade to .NET 6 for us.

@dreddy-work it would be good to do a root cause analysis and find what changes caused this regression.

**Comment by filipnavara** [comment] 2021-11-10 22:35
The incorrect code was first introduced in https://github.com/dotnet/winforms/pull/5032. Note that there's a similar `IsScaledByParent` method introduced in the same commit which is likely correct (but should be checked anyway by someone who understands it better).

**Comment by RussKie** [comment] 2021-11-10 22:48
Thank you @filipnavara, this is really helpful.

**Comment by dreddy-work** [comment] 2021-11-10 23:11
> Note that there's a similar `IsScaledByParent` method introduced in the same commit which is likely correct

That method was checking if parent hierarchy has a Container that could lead to scaling children. Given that it was not  looking for which parent Container, that should be good.

**Comment by Ashley-Li** [comment] 2021-11-17 09:25
Verified this issue on .NET 7.0.0-alpha.1.21566.13 build, issue was fixed. When moving to secondary monitor (150% DPI -> 100% DPI) in PerMonitorV2 mode, changes color. Please see below video:[test_resut.zip](https://github.com/dotnet/winforms/files/7553376/test_resut.zip)

**Comment by Philip-Wang01** [comment] 2021-11-25 08:08
Verified this issue in .Net 6.0.101-servicing.21568.17 build, it is fixed with the same above result on .Net 7.0.
