### ISSUE TITLE
The ListView's GroupCollapsedStateChanged events no longer fire even if the CollapsedState is actually changed 

### ISSUE THREAD

**Issue by VinoWang01** [dotnet/winforms#6699] opened 2022-02-16 08:31 UTC
.NET Core Version: 

- .NET Core SDK: 7.0.100-PREVIEW.2.22115.2

Have you experienced this same bug with .NET Framework?: 

- No. `ListViewGroup.CollapsedState` was implemented in .NET Core 5.0 (https://github.com/dotnet/winforms/pull/3155) and from (https://github.com/dotnet/winforms/issues/5960)

**Problem description:**
The `expand/collapse` state is changed correctly, but the `GroupCollapsedStateChanged` events no longer fire.
![NoFireEvent_Keyboard](https://user-images.githubusercontent.com/90816462/154224888-d0ac9441-0513-4d88-b553-00ea5bee94b6.gif)

**Expected behavior:**
The `expand/collapse` state should be changed correctly and the `GroupCollapsedStateChanged` events should be fired.
![NoFireEvent_Mouse](https://user-images.githubusercontent.com/90816462/154224933-cb42374a-7b82-4d11-b489-b6d8f01ab083.gif)

**Minimal repro:**

1. Run the Test app. [ListViewGroupState.zip](https://github.com/dotnet/winforms/files/8078074/ListViewGroupState.zip)
2. Collapse the second ListViewGoup -- 'Expanded ListViewGroup'. 
3. Focus on the third `ListViewGroup group header` using keyboard -- 'Collapsed ListViewGroup'. 
4. Press left and right key arrows to see the behavior. 

**More Info:**
This issue can't reproduce when the second ListViewGoup -- 'Expanded ListViewGroup' is keeping Expanded.

**Comment by merriemcgaw** [comment] 2022-02-17 23:34
@jbhensley , I see you've been playing in this space lately. Do you mind taking a look at this issue as well?

**Comment by NikitaSemenovAkvelon** [comment] 2022-07-29 11:38
It seems correct, the event was raised on collapsing/expanding. And it works both ways via a mouse or a keyboard.
![4Qc0AUcrMn](https://user-images.githubusercontent.com/109065597/181750222-5a23074e-a2e1-4e88-8d63-c21beb919550.gif)
So, @merriemcgaw could we close the issue as non-reproduced?

Also, I've noticed strange behavior with focus after collapsing/expanding. It always moves to the first element of ListView. Is it a bug?

**Comment by merriemcgaw** [comment] 2022-07-29 20:05
Yep, this looks like something we may have fixed with earlier work. Since we can't reproduce I'll be happy to close it 😺

**Closed by merriemcgaw** 2022-07-29 20:05 UTC
Labels: up-for-grabs, area: listview
