### ISSUE TITLE
Short freeze when clicking on ListViewGroup header

### ISSUE THREAD

**Issue by udaken** [dotnet/winforms#6119] opened 2021-11-04 04:18 UTC
* .NET Core Version:
6.0.100-rc.2.21505.57

* Have you experienced this same bug with .NET Framework?:
No

**Problem description:**
When I click on the last group of a ListView that has many (I used 1000 groups) ListViewGroups, the app freezes for a short time.

In my environment, .NET Framework 4.8, it does not freeze when I click on it.
.NET 6 will freeze.

![1000](https://user-images.githubusercontent.com/7896698/140262006-b73540be-ca47-4f3e-adf1-bc3c25c99b56.gif)

**Expected behavior:**
I expect it to run as fast as .NET Framework.

**Minimal repro:**
[NetCoreWindowsFormsApp2_1000.zip](https://github.com/dotnet/winforms/files/7472496/NetCoreWindowsFormsApp2_1000.zip)

**Comment by RussKie** [comment] 2021-11-04 05:02
I am afraid I do no observe any significant discrepancy in selection times as far as this non-scientific method goes, all selections appear to be happening in comparable time:
https://user-images.githubusercontent.com/4403806/140260275-9791436b-77a5-4521-ba9a-758cdc40a940.mp4

For us to investigate further we'll need a repro with measurements and results that clearly indicate a regression.

**Comment by udaken** [comment] 2021-11-04 05:20
@RussKie 
Thank you for making an important point.

To manifest this problem, using more groups can be effective.
Using 1000 groups will cause the application to stop responding.
![1000](https://user-images.githubusercontent.com/7896698/140262006-b73540be-ca47-4f3e-adf1-bc3c25c99b56.gif)

**Comment by udaken** [comment] 2021-11-04 05:26
I have updated the Issue and Minimal repo.

**Comment by Nora-Zhou01** [comment] 2022-06-27 08:59
Verified with 17.3.0 Preview 3.0 [32626.21.main] from main branch,  it doesn't repro. So close this issue now.  See below screenshot.
![0627](https://user-images.githubusercontent.com/104609169/175901193-176e1beb-804e-4dc1-82d2-b05267e4f7b9.gif)

**Comment by elachlan** [comment] 2023-01-11 03:12
I have been unable to reproduce it using the following code. @udaken am I missing anything?
```csharp
using Form form = new();
using ListView listView = new()
{
    Dock= DockStyle.Fill,
    HideSelection = false,
    UseCompatibleStateImageBehavior = false,
    View = View.Details
};
using ColumnHeader columnHeader = new()
{
    Width = 600
};
listView.Columns.Add(columnHeader);
form.Controls.Add(listView);
for (var g = 0; g < 1000; g++)
{
    var group = new ListViewGroup($"group{g}");
    listView.Groups.Add(group);
    for (var i = 0; i < 5; i++)
    {
        var item = new ListViewItem($"item{i}", group);
        listView.Items.Add(item);
    }
}

form.ShowDialog();
```

**Comment by elachlan** [comment] 2023-01-17 05:47
@Olina-Zhang I tried to reproduce this issue using the latest, could your team have a look again? Is my test above missing something?

**Comment by Olina-Zhang** [comment] 2023-01-17 08:33
@elachlan this issue can reproduce in .Net 6.0, and cannot reproduce in .Net 7.0 and 8.0. So whether we can close this issue?
.Net 6.0:
![6 0](https://user-images.githubusercontent.com/26474449/212847801-560b1bc6-1386-40ec-baf2-7a1fa91ed429.gif)

.Net 7.0:
![7 0](https://user-images.githubusercontent.com/26474449/212847817-cd3055ea-46f5-4ed3-85de-4ba2f50c0574.gif)

.Net 8.0:
![8 0](https://user-images.githubusercontent.com/26474449/212847843-a1e4c505-1808-4f3c-84f2-d94c72e31aac.gif)

**Comment by elachlan** [comment] 2023-01-17 08:36
@merriemcgaw this issue is apparently fixed. I don't know what fixed it, so a back port for .NET 6 might be hard.

**Comment by merriemcgaw** [comment] 2023-01-17 18:27
Let's close it then 😄. We can always reopen if needed.

**Closed by merriemcgaw** 2023-01-17 18:27 UTC
Labels: enhancement, tenet-performance
