### ISSUE TITLE
Executes the given Action on the thread that owns this Control's underlying window handle. 

### ISSUE THREAD

**Issue by maikebing** [dotnet/winforms#1347] opened 2019-07-12 01:25 UTC
The following code I think is more complicated and old.
Code sample:
```
this.Invoke((MethodInvoker)delegate
{
         // some code 
});
```
I want to  add a method   Invoke( Action action)
Code sample:
`  this.Invoke(() =>  MessageBox.Show(ex.Message));
`
This code looks more modern and conforms to the new syntax.

**Comment by JeremyKuhne** [comment] 2020-08-11 00:41
Looks like we're asking for overloads:

``` C#
public void Invoke(Action action);
```

The question here is how we deal with the underlying object handling. Is it possible here to do Action<T>, Func<T>, etc?

**Comment by weltkante** [comment] 2020-08-11 08:56
Most people I've worked with just add an `internal static void Invoke(this Control control, Action action);` extension method, so this is mostly just "nice to have" but not blocking anything.

I don't think there is any "etc", only `Action` and `Func<T>` should be required. The overloads are needed for when you want to call the method with a closure, the compiler needs a hint from the method signature to figure out the right delegate. When you have a closure you usually wouldn't pass any arguments, you'd just access them directly.

Callers which are aware of allocations probably won't use closures anyways and allocate the delegate separately, so they are already explicitly typed and using the existing overload, they don't need additional ones.

**Comment by RussKie** [comment] 2021-03-01 04:17
Duplicate of #4608

**Closed by RussKie** 2021-03-01 04:17 UTC
Labels: api-suggestion, design-discussion

**Comment by KathleenDollard** [comment] 2021-03-29 14:54
Sorry for the delay. I am OK with this change. I do think we should get it into the breaking change list with an explanation of the limited times someone will encounter it.
