### ISSUE TITLE
An exception was throwing when switching the dates of MonthCalendar control on .NET 6.0 windows arm64 SDK

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#4629] opened 2021-03-02 09:30 UTC
* .NET Core Version: 
.NET SDK 6.0.100-preview.3.21123.4

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**
1. This issue **cannot** reproduce on .NET 6.0 Windows x64 SDK build
2. This issue can reproduce from .NET 6.0 Preview 1 to Preview 3 windows arm64 SDK latest build
2. This issue cannot reproduce on DateTimePicker control

**Minimal repro:**
[TestApp.zip](https://github.com/dotnet/winforms/files/6067569/TestApp.zip)

1. Install .NET 6.0 windows arm64 SDK latest build from: https://github.com/dotnet/installer on ARM 64-bit OS machine
2. Create a Winforms Core application with a MonthCalendar control
3. Build and run this project, then switch dates of MonthCalendar

**Actual behavior:**
An exception was throwing when switching dates of MonthCalendar.
![Core](https://user-images.githubusercontent.com/62929087/109626225-3e384100-7b7b-11eb-9d68-6e7dcf26a6f5.gif)

**Expected behavior:**
The dates switched successfully.

**Call Stack:**
************** Exception Text **************
System.ArgumentOutOfRangeException: Hour, Minute, and Second parameters describe an un-representable DateTime.
   at System.Windows.Forms.DateTimePicker.SysTimeToDateTime(SYSTEMTIME s)
   at System.Windows.Forms.MonthCalendar.GetMonthRange(GMR flag)
   at System.Windows.Forms.MonthCalendar.BoldDates(DateBoldEventArgs e)
   at System.Windows.Forms.MonthCalendar.WmDateBold(Message& m)
   at System.Windows.Forms.MonthCalendar.WmReflectCommand(Message& m)
   at System.Windows.Forms.MonthCalendar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by RussKie** [comment] 2021-03-02 09:39
@Amy-Li03 can you please try an MFC app to establish where the problem is - in the underlying Win32 control or Windows Forms' wrapper? Thanks

**Comment by weltkante** [comment] 2021-03-02 13:51
If this works in MFC you may want to double check that the stackalloced structs get properly zero initialitzed, since [GetMonthRange](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L1293) passes on the datetime unchanged to [SysTimeToDateTime](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs#L1660) and the [docs](https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-monthcal_getmonthrange) say

> The time members of these structures will not be modified.

I believe stackalloc is specced to zero initialize so the code _should_ be correct, but worth checking anyways to make sure this is working as intended. Garbage in the time fields certainly would explain the exception.

**Comment by Amy-Li03** [comment] 2021-03-03 05:35
@RussKie Create a MFC project with a monthCanlendar control on win10 machine, build this project, then run it on win arm64 machine, there is no exception was throwing when switching dates of MonthCalendar.

![MFC](https://user-images.githubusercontent.com/62929087/109753636-97f14780-7c1d-11eb-9707-8d6eca74eb38.gif)

**Comment by weltkante** [comment] 2021-03-03 12:40
> there is no exception was throwing when switching dates of MonthCalendar.

The exception does not come from switching dates, it comes from WinForms intercepting the date switch and running custom code. The code looks correct but on ARM something behaves incorrectly. To determine if its the native control that behaves incorrectly you may need to recreate the interop call WinForms does and see if it works when done in a native MFC application.

I had some links above, basically the native GetMonthRange call returns something the managed code does not understand. Its the question where the bug is, could be the native control (returning garbage), the dotnet runtime (not properly zeroing out stackalloced arrays) or WinForms (doing interop wrong in a way I could not identify).

**Comment by Tanya-Solyanik** [comment] 2022-01-12 18:15
@Amy-Li03 - Could you please try to repro this regression on .NET Framework on ARM64. I see that you commented that it does not repro on .NET Framework, but it's not clear if on ARM or AMD.

**Comment by Amy-Li03** [comment] 2022-01-13 06:41
@Tanya-Solyanik yes, ` .NET 6.0 Windows x64 SDK` is not ARM SDK.

This issue is not reproducing on .NET Framework on ARM64.

**Comment by Ashley-Li** [comment] 2022-02-09 10:08
Verified this issue with .NET 7.0.100-preview.1.22108.1(arm64) form Release/7.0.1xx-preview1 branch and .NET 6.0.300-preview.22108.7 form Release/6.0.3XX branch , it is not repro that build this project, then run it on win arm64 machine, there is no exception was throwing when switching dates of MonthCalendar. So close it.
![4629_verify](https://user-images.githubusercontent.com/56664234/153176046-6842065b-d059-418c-bcbf-6d92670fa47d.gif)

**Closed by Ashley-Li** 2022-02-09 10:08 UTC
Labels: :beetle: bug, area: arch-arm64, area: comctl/shell
