### ISSUE TITLE
A display problem when use Gdiplus

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#8344] opened 2022-12-07 08:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/A-display-proplem-when-use-Gdiplus/10220512)._

---
![form1.png](https://aka.ms/dc/image?name=Bddea386e036f4bc08adc9ae9722ef792638056713659906243_form1.png&tid=ddea386e036f4bc08adc9ae9722ef792638056713659906243)

A simple C# project (6 files)
[Form1.cs](https://aka.ms/dc/file?name=Be908c55247e244edaef1b2c0806885b3638056716931924672_Form1.cs&tid=e908c55247e244edaef1b2c0806885b3638056716931924672)
[Form1.Designer.cs](https://aka.ms/dc/file?name=B547bdb9bb216427193ebafc624104e18638056717117862986_Form1.Designer.cs&tid=547bdb9bb216427193ebafc624104e18638056717117862986)
[Form1.resx](https://aka.ms/dc/file?name=B7ebe38ef29ea4d798bb1c78163d46eab638056717227058430_Form1.resx&tid=7ebe38ef29ea4d798bb1c78163d46eab638056717227058430)
[Program.cs](https://aka.ms/dc/file?name=B71a3e80a28c44e28834c77603a0fca7c638056717360528177_Program.cs&tid=71a3e80a28c44e28834c77603a0fca7c638056717360528177)
[WinFormsApp1.csproj](https://aka.ms/dc/file?name=B0c86b5af9096436ebf2beb978021d1a2638056717496266632_WinFormsApp1.csproj&tid=0c86b5af9096436ebf2beb978021d1a2638056717496266632)
[WinFormsApp1.sln](https://aka.ms/dc/file?name=B8e8897fd16534774bdb402d599c4164f638056717816317595_WinFormsApp1.sln&tid=8e8897fd16534774bdb402d599c4164f638056717816317595)

**Comment by Cassie-Li01** [comment] 2022-12-07 08:29
.NET Core build: .NET 8.0.100-alpha.1.22606.4

Repro Steps:
1. Build and run attached project.
[Testapp.zip](https://github.com/dotnet/winforms/files/10174046/Testapp.zip)

Current Behavior:
There is a problem with the display
![image](https://user-images.githubusercontent.com/96758262/206126273-c1ec0ed7-f2dc-4718-948e-b4ee2eca6216.png)

On below solution, the displayed problem is more obvious:
![image](https://user-images.githubusercontent.com/96758262/206126540-093a07a0-ed5d-4625-8a55-22718dfc5a12.png)

More info:
1. This issue also repro on .NET Framework.
2. This is not a regression issue. Also repro on .NET Core 6.0, 7.0.

**Comment by merriemcgaw** [comment] 2022-12-08 00:58
@Cassie-Li01 because there is little chance of Windows will make any changes here - and this is in Windows not us. We don't do any special calculations on our end. The feedback ticket should be closed as Low Priority, but if this is blocking the user, they will need to file a feedback ticket.

**Closed by merriemcgaw** 2022-12-08 00:58 UTC
Labels: untriaged
