### ISSUE TITLE
Combobox does not fire SelectedIndexChanged event

### ISSUE THREAD

**Issue by MatthewBeardmore** [dotnet/winforms#1620] opened 2019-08-13 21:08 UTC
* .NET Core Version: 3.0 Preview8
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
When using a ComboBox with a SelectedIndexChanged event, the event will not fire if you set the SelectedIndex in the Constructor.

**Actual behavior:**
The SelectedIndexChanged event *only* fires when the "SelectedIndex = 0;" line is run and does not fire when changed by the end-user.

**Expected behavior:**
The SelectedIndexChanged event fires both from the code and from the end-user changing the box in the UI.

**Minimal repro:**
[ComboBoxIssue.zip](https://github.com/dotnet/winforms/files/3498883/ComboBoxIssue.zip)

**Comment by kirsan31** [comment] 2019-08-13 21:36
#1311?

**Comment by RussKie** [comment] 2019-08-14 11:49
Duplicate of #1311

**Closed by RussKie** 2019-08-14 11:49 UTC
