### ISSUE TITLE
In self-contained app Application.ExecutablePath returns dll

### ISSUE THREAD

**Issue by shutdown256** [dotnet/winforms#1143] opened 2019-06-18 10:21 UTC
I'm not sure if this is bug or by design but in a self-contained app `Application.ExecutablePath` return path to dll and there is no apparent way to easily get path to the executable. What is recommended way to solve this problem?

**Comment by Symbai** [comment] 2019-06-21 12:32
I've noticed this too. I believe the executable, considering its tiny size, is just a wrapper hosting your application which is basically still the DLL. So the path of the executable of your application is the path to your dll. To me it looks like an expected behavior which is by-design.

By the way it also links to your DLL when not self contained.

**Comment by weltkante** [comment] 2019-06-24 10:20
I don't think its by design, but rather a side effect of .NET Core handling things differently. [Application.ExecutablePath](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Application.cs,0765d7c8c8bf6a14) already has code to figure out the native entry point but in Desktop Framework the entry point is always in an exe because the native code to load the framework is in the OS. With .NET Core they need to have a loader separate from the OS so its much more common that the entry point is in a DLL.

I think this should be fixed, this property is commonly used when you want to restart the application, otherwise there should be an alternate API for this common use case so you don't have to fall back to unmanaged code.

@shutdown256 you can implement this yourself by invoking the unmanaged [GetModuleFileName](https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-getmodulefilenamew) API.

**Comment by Symbai** [comment] 2019-06-24 10:50
You don't have to fall back to unmanaged code. You simply use Path.ChangeExtension on the return of Application.ExecutablePath. I would consider it as a breaking change similar to the behavior of Process.Start where on .NET Framework it automatically uses shellexecute while on core it does not. Which means if you do Process.Start("explorer.exe") it works in .NET framework but not in .NET Core, which also was confirmed as "by design".

**Comment by weltkante** [comment] 2019-06-24 11:06
Well, the decision with Process.Start was that they wanted it to behave the same on all platforms, but only Windows has the ShellExecute support, so whatever choice they took it was going to be broken from the start.

The case here is different, the implementation already has code to look for the "right" return value (return the native exe) but it isn't triggered because what was previoulsy an edge case is now the common case (most people didn't write a native host, now you get one auto-generated).

The WinForms team can of course still close the issue as 'by design' but I think its possible to fix this now, in particular since 3.0 hasn't been released yet.

**Comment by Symbai** [comment] 2019-06-24 18:28
This "fix" would need to be a windows - only thing then. So it would behave differently on different OS, which you said, was the goal why shellexecute was changed, although it's a huge breaking change as it's literally never set manually to true in most source codes I've seen.

That was my thought of why this behavior could be a "by design" decision. I'm not saying that a fix doesn't make sense, rather than I believe it's not a bug but just a thing like shellexecute where, when you came from framework development you now need to deal with.

**Comment by weltkante** [comment] 2019-06-25 08:00
@Symbai The code for `Application.ExecutableImage` in WinForms is already Windows only anyways, and the `Application` class won't be going cross-platform anytime soon either because it is based on the Windows message loop. For cross-platform there is `Assembly.GetEntryAssembly` and I don't suggest to change that.

**Comment by merriemcgaw** [comment] 2019-10-17 00:43
This issue is a dup of dotnet/core-setup#7491

**Comment by weltkante** [comment] 2019-10-17 07:23
@merriemcgaw are you sure? we are talking about WinForms API here, unless .NET Core changes the entire approach and no longer uses a stub exe, WinForms needs to adapt to the way .NET Core handles things.

Right now the implementation in WinForms is broken because it looks at the stub and doesn't recognize it as a managed application.

**Comment by RussKie** [comment] 2020-02-04 02:45
I don't get an impression this is an issue for the Core Runtime to fix it, and it is up to us to deal with it.

**Closed** 2020-02-10 05:17 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress
