### ISSUE TITLE
VisualStyleRenderer.IsElementDefined loops forever, doesn't in netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2128] opened 2019-10-18 13:54 UTC
```cs
public static IEnumerable<object[]> IsElementDefined_TestData()
{
    yield return new object[] { VisualStyleElement.Button.PushButton.Hot, true };
    yield return new object[] { VisualStyleElement.Button.PushButton.Normal, true };
    yield return new object[] { VisualStyleElement.Button.RadioButton.CheckedHot, true };
    yield return new object[] { VisualStyleElement.Button.RadioButton.CheckedNormal, true };
    yield return new object[] { VisualStyleElement.ComboBox.DropDownButton.Hot, true };
    yield return new object[] { VisualStyleElement.ComboBox.DropDownButton.Normal, true };

    yield return new object[] { VisualStyleElement.CreateElement(string.Empty, 0, 0), false };
    yield return new object[] { VisualStyleElement.CreateElement("NoSuchName", 0, 0), false };
}

[Theory]
[MemberData(nameof(IsElementDefined_TestData))]
public void VisualStyleRenderer_IsElementDefined_Invoke_ReturnsExpected(VisualStyleElement element, bool expected)
{
    Assert.Equal(expected, VisualStyleRenderer.IsElementDefined(element));
}

[Fact]
public void VisualStyleRenderer_IsElementDefined_NullElement_ThrowsArgumentNullException()
{
    Assert.Throws<ArgumentNullException>("element", () => VisualStyleRenderer.IsElementDefined(null));
}

[Fact]
public void VisualStyleRenderer_IsElementDefined_NullElementClassName_ThrowsArgumentNullException()
{
    VisualStyleElement element = VisualStyleElement.CreateElement(null, 0, 0);
    Assert.Throws<ArgumentNullException>("className", () => VisualStyleRenderer.IsElementDefined(element));
}
```

**Comment by zsd4yr** [comment] 2019-10-18 20:06
Can you narrow down if a single one of these tests loops forever?

**Comment by hughbe** [comment] 2019-10-21 08:14
Seems like

```cs
VisualStyleRenderer.IsElementDefined(VisualStyleElement.Button.PushButton.Hot, true);
```

**Comment by zsd4yr** [comment] 2019-10-21 18:37
@hughbe I commented on your PR here. I think if you try this in an application, it will not reproduce. 

I think the issue is with the tests. The test projects each need to reference the facades. I think types are not resolving.

**Closed** 2019-10-23 00:38 UTC
Labels: :construction: work in progress
