### ISSUE TITLE
Need to be able to remove empty events in Windows Form

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#6550] opened 2022-01-26 03:06 UTC
**Is your feature request related to a problem? Please describe.**
Events can be left empty in the code during visual design. A visual design session may cause many empty unwanted event handler code to be created while experimenting with controls, etc. The code will end-up containing empty event handlers. A programmer can’t just delete such code from the code without getting horrible error message because the event handler coded is in 2 files. The only safe way is to go to the visual designer and remove them one by one manually. This process is so tedious and DANGEROUSE.

This behavior is as old as VS. It happens in Windows Forms at least.

**Describe the solution you'd like and alternatives you've considered**
Note that this is a C#-only issue. In VB, the Handles clause makes it easy to delete event handlers without causing an error with the InitializeComponent method.

A Roslyn Analyzer is a good suggestion to improve the experience here. I should mention that it's not necessarily a cheap analyzer to run, since it would have to be careful to only suggest removing an empty event handler if the only reference to is in InitializeComponent, but such an analyzer wouldn't be hard to write.

**Comment by AraHaan** [comment] 2022-02-02 10:26
> **Is your feature request related to a problem? Please describe.** Events can be left empty in the code during visual design. A visual design session may cause many empty unwanted event handler code to be created while experimenting with controls, etc. The code will end-up containing empty event handlers. A programmer can’t just delete such code from the code without getting horrible error message because the event handler coded is in 2 files. The only safe way is to go to the visual designer and remove them one by one manually. This process is so tedious and DANGEROUSE.
> 
> This behavior is as old as VS. It happens in Windows Forms at least.
> 
> **Describe the solution you'd like and alternatives you've considered** Note that this is a C#-only issue. In VB, the Handles clause makes it easy to delete event handlers without causing an error with the InitializeComponent method.
> 
> A Roslyn Analyzer is a good suggestion to improve the experience here. I should mention that it's not necessarily a cheap analyzer to run, since it would have to be careful to only suggest removing an empty event handler if the only reference to is in InitializeComponent, but such an analyzer wouldn't be hard to write.

But then there is another issue: All events would be marked as empty unless you have it flag only events with empty code bodies as well too.

**Comment by KalleOlaviNiemitalo** [comment] 2022-03-02 16:58
If there is no handler for the [DataGridView.DataError](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridview.dataerror?view=windowsdesktop-6.0) event, then DataGridView displays a message box by default. If there are event handlers, then DataGridView just calls them. For this event, an empty event handler is not equivalent to having no event handler, and should not be automatically removed by a code fixer. A diagnostic would be OK though, as the behavior is somewhat surprising and deserves at least a comment in the event handler.

**Comment by kirsan31** [comment] 2022-04-18 10:14
Before implementing this, https://github.com/dotnet/winforms/issues/7042 defiantly must be fixed.

**Comment by Olina-Zhang** [comment] 2022-05-07 06:41
Verified this issue in Visual Studio 2022 internal build, it was fixed: when event is not referenced, the event code is still keeping there. Please use incoming Visual Studio 2022 preview version for this improvement.

**Comment by kirsan31** [comment] 2022-05-07 06:49
@Olina-Zhang you closed this by mistake?

**Comment by Olina-Zhang** [comment] 2022-05-07 07:16
I am not clear if I understand correctly, @RussKie mentioned another issue: [7042](https://github.com/dotnet/winforms/issues/7042), want us to verify them together. Please correct me if issue has more feature request.

**Comment by kirsan31** [comment] 2022-05-07 07:25
Hmm, this is your issue, isn't  it? 
**Need to be able to remove empty events in Windows Form**
Why it was closed? 🤔

**Comment by Olina-Zhang** [comment] 2022-05-07 07:34
This is from external suggestion feedback ticket, not mine. I understand the fix is the event code is keeping there when it is not referenced, not deleted now. Let our engineer team give more details for this bug, @RussKie, @merriemcgaw.

**Comment by kirsan31** [comment] 2022-05-07 07:40
I think the misunderstanding here arose because of my [comment](https://github.com/dotnet/winforms/issues/7042#:~:text=Some%20how%20related%20to%20%236550.) in description of #7042:

> Some how related to #6550.

But by relation, I meant only [this](https://github.com/dotnet/winforms/issues/6550#issuecomment-1101288184):

> Before implementing this, https://github.com/dotnet/winforms/issues/7042 defiantly must be fixed.

**Comment by AraHaan** [comment] 2022-05-07 15:50
Speaking about events: Inlined events using delegate syntax's get removed by the designer whenever you change even a slight thing (and it does not care if it has code in it or not).

**Comment by RussKie** [comment] 2022-05-09 00:44
@kirsan31 the issue was closed because it was fixed in the designer repo. I asked @Olina-Zhang to close it after the fix was confirmed.
The fix is expected to be available in 17.3p2.

**Closed by RussKie** 2022-05-09 00:44 UTC
Labels: area: VS designer
