### ISSUE TITLE
Winforms IAccessible broken in .NET 5 RC 1

### ISSUE THREAD

**Issue by qmgindi** [dotnet/winforms#4110] opened 2020-09-19 14:56 UTC
AccessibleObjectFromPoint always returns error "invalid parameter".
AccessibleChildren returns VARIANTs with invalid vt = VT_UI4 (must be VT_I4).

With .NET 5 preview 7 AccessibleObjectFromPoint works, but AccessibleChildren does not work correctly with many controls.

Tested on latest Windows 10 64-bit.

Probably related: UI Automation cannot get children of some controls.

**Comment by RussKie** [comment] 2020-10-14 23:04
Duplicate of #4100

**Closed by RussKie** 2020-10-14 23:04 UTC
