### ISSUE TITLE
VS.IDE deletes components, which cannot be created during the loading of the form

### ISSUE THREAD

**Issue by Atma9** [dotnet/winforms#4803] opened 2021-04-16 18:15 UTC
Dear All,

While upgrading to Winforms .NET Core 5.0, we have encountered several situations, where the component, or the control could not be created by the Winforms designer UI (null pointer exception in the constructor). If we disregard the reason, why the error happens, the default behavior of the Winforms UI Designer is to silently delete the component from the source code. The components can be quite elaborate with hundreds of settings. 

It is of course possible, to "undo" the changes, but the trouble is: How do you know that something was deleted?
There is no error message displayed. Only few days later you can discover that that the "Forms" are "leaking" controls and components. 

* .NET Core Version: 
This affects .NET 5.0 Winforms and newer. 

* Have you experienced this same bug with .NET Framework?: 
No. 

**Expected behavior:**
Display an error message, if a component is to be deleted. Do not silently delete the component. 

**Minimal repro:**
Throw an exception in any component constructor and notice that the VS.IDE Winform Designer removed all trace of that component from the source code without any error message or warning. 

Another aspect of this problem, is why the controls throw an exception in the constructor:
Sometimes the assembly which holds the components cannot be loaded by the VS.IDE. There is so much dynamic loading of assemblies in to the Winforms UI Designer, that it is possible to notice why this sometimes fails (every few minutes). The error messages range from: 

a.) The assembly is "used by another process". This process can be some subsystem of the VS.IDE itself or of Windows. Even though we have AntiVirus disabled for our project directories, we still sometimes get a message, that the file read/write was blocked because another process was locking the file. It is also not the Search Indexing. We simply could not figure out what that process could have been.  The conclusion was, some bug with Windows OS.

b.) Interdependent assemblies. Are there some time-outs in place when loading the assemblies and if the load chain is very long (due to frequent dynamic loading of multiple dependent assemblies), the UI appears to occasionally time out? We need to open Forms in quite specific order not to cause this time-out to trigger, because if it does, the assembly loading will fail and components will be deleted without any warning messages. 

c.) Static type initializers. I am not convinced that constructors of static classes are fully functional. Sometimes Frame loading fails, as if the constructors of static classes did not execute quickly enough, after one of the members of the static class was accessed. 

The practical reality of the current state of Winforms 5.0 .NET Core VS.IDE experience is "unusable" for development due to nearly random failure to open forms without loosing components and not giving any error messages, when it happens. 

Kind Regards!
Atmapuri

**Comment by kirsan31** [comment] 2021-04-16 19:29
[Here](https://github.com/dotnet/winforms/issues/4122#issuecomment-725798527) is **old** @merriemcgaw answer about similar issue.

**Comment by Atma9** [comment] 2021-04-17 07:11
Thanks for the link. The issues are not "as bad" as in that post, but I would like to add:

1.) Toolbox sometimes shows components, which are currently inserted in to the open form. Sometimes it does not show them. More often not showing. Why they get to present sometimes and sometimes not, I cant tell.
2.) Toolbox does not load ToolboxBitmap(s). On the form itself, the bitmap icons are shown for some assemblies and not for others. 
3.) The file locking issues are "so bad", that occasionally there is an error: "Unable to load the form, because it was not possible to  load the source code file." The .cs file window remains empty when double clicking the file in the solution explorer. Possibly related to InteliSense service? To resolve the problem,  VS.IDE needs a restart.

All this is with the latest version of VS.IDE on the date of posting this messages (16.9.4). 
The whole thing looks like a giant web of intertwined "file locking" and "VS.IDE timeout" issues happening at random times, causing silent removal of components from the form, silent removal of components from the Toolbox and at least showing an error message, when a .cs file can't be opened. Interestingly, the .cs files always open, if they have no forms. This error only shows up sometimes, if they do have a Form. 

The project solution has about 1M lines of C# code and combined size of related un-managed dlls of about 200MB. 

Still works fine with .NET Framework. 

Kind Regards!
Atmapuri

**Comment by RussKie** [comment] 2021-04-21 23:44
Unfortunately it is a known gap, and we're still working on getting the .NET designer to parity with the .NET Framework designer. We've done quite a few changes in the latest designer. Can you please try VS 16.10 Preview2 (or better yet 16.10 preview3 which will be out in a matter of weeks).

The best way to report issues with with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.
Once you've raise the VS Feedback you're welcome to post the link here for us to track.

**Comment by Atma9** [comment] 2021-04-22 08:02
Dear RussKie,

>an you please try VS 16.10 Preview2

Yes, have tried before and have not noticed anything special to be different. 

>The best way to report issues with with VS and VS Designer should be sent via VS Feedback channel

How do you report an issue, if there is no error reported? The component leakage from the forms is silent and depends IDE time-out and various file-locking issues, which are transient.

Thanks!
Atmapuri

**Comment by RussKie** [comment] 2021-04-22 08:16
Please refer to this article: https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio

**Comment by Atma9** [comment] 2021-04-22 08:39
Considering that a reproducible issue does not exist, is there any sense in submitting such report?

Thanks!
Atmapuri

**Comment by RussKie** [comment] 2022-02-21 04:00
I acknowledge that the issue is known to the team, and it is on our backlog. I am afraid there is nothing else I can add to this.
Closing due to age.

**Closed by RussKie** 2022-02-21 04:00 UTC
Labels: area: VS designer
