### ISSUE TITLE
WinForms Controls Rendering Issue with Dynamic System Scale Changes at Runtime

### ISSUE THREAD

**Issue by ManiAkash9** [dotnet/winforms#12378] opened 2024-10-23 13:10 UTC
### .NET version

.NET CORE 80
.NET Framework 4.8

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Did not checked

### Issue description

In a WinForms application, controls such as buttons and checkboxes do not render correctly when the system scale is adjusted at runtime. This issue occurs intermittently and is challenging to reproduce consistently.

**Video reference is attached**

https://github.com/user-attachments/assets/217bd820-d9fc-4218-b974-7cdb5299b426

### Steps to reproduce

System Resolution: 1366x768
Scale: 100%

- Add a button to the form designer in a WinForms application.
- Run the application.
- While the application is running in the background, change the system scale to 125%.
- Observe that the button is not rendered correctly after the scale change.

**Comment by JeremyKuhne** [comment] 2024-10-23 16:29
@Olina-Zhang can you reproduce this behavior?

**Comment by Philip-Wang01** [comment] 2024-10-24 07:26
@JeremyKuhne We just reproduced the issue twice in multiple attempts. This issue has a very low reproduction rate and is difficult to reproduce consistently.
![Image](https://github.com/user-attachments/assets/4a3951c2-5e94-41a8-b0d3-ad1ee0255782)

**Comment by merriemcgaw** [comment] 2024-10-25 21:47
@Philip-Wang01 have you tested on multiple OS versions by any chance? I wonder if there is some change in rendering code that makes this happen. Are the test apps PMv2?

**Comment by Philip-Wang01** [comment] 2024-10-30 03:24
@merriemcgaw After testing, the issue has a slightly higher probability of reproducing on Win11, the issue has not been reproduced on win10 clients, and has been reproduced once on Windows Server 2019. This is a single screen issue without any HDPI mode set up.

**Comment by merriemcgaw** [comment] 2024-10-31 18:32
@Philip-Wang01  - is the application a PMV2 application?

**Comment by Philip-Wang01** [comment] 2024-11-01 01:08
@merriemcgaw the application is not a PMV2 application and does not have any HDPI mode set, the default should be SystemAware.

**Comment by merriemcgaw** [comment] 2024-11-12 21:21
Since this is System Aware, we don't many any promises  about dynamic rendering. It also seems hard to reproduce and is likely Windows related, rather than something we are able to address. Without more information, I am going to close this issue.

**Comment by ManiAkash9** [comment] 2024-11-13 11:43
Could this issue be reopened? While I understand the System Aware limitations, I believe there are cases where this issue significantly impacts functionality. I’m happy to provide additional details, and I have attached a sample that can be used to replicate the issue. This may not be isolated to Windows alone. Thank you for reconsidering.

Sample : [WinFormsApp1.zip](https://github.com/user-attachments/files/17731826/WinFormsApp1.zip)

**Comment by ManiAkash9** [comment] 2024-11-22 05:48
@merriemcgaw  - Could this issue be reopened?

**Comment by ManiAkash9** [comment] 2024-11-28 05:51
Hi team,

Could this issue be reopened?

**Comment by ManiAkash9** [comment] 2024-12-06 03:41
@merriemcgaw - Could this issue be reopened?

**Comment by merriemcgaw** [comment] 2024-12-11 00:40
Hi @ManiAkash9 - if the application is set up as SystemAware we do not get the system notifications that scaling has changed. There isn't anything WinForms can do if we don't reliably get notifications from Windows that things have changed. In fact, it's quite possible that that this issue resides in the GDI layer of Windows because that is the layer where Windows renders SystemAware applications when the scaling  changes on the fly. 

So, I ap

**Closed** 2024-12-11 00:41 UTC
Labels: area-HDPI
