### ISSUE TITLE
WinForms designer failed to start, if project reference on readonly file

### ISSUE THREAD

**Issue by svg2003** [dotnet/winforms#12453] opened 2024-11-09 06:42 UTC
### Environment

MSVS Version 17.10.6

### .NET version

.net8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

no

### Issue description

If project is reference on another DLL with readonly attribute, designer failed to start.
It throws an exception, trying to copy (overwrite) readonly file in a cache.

_[22:34:30.490778] info: [MySuperProject]: Copying project reference: 'G:\test\_import\MyReferencedDll.dll'.
[22:34:30.512777] fail: System.UnauthorizedAccessException: Access to the path 'C:\Users\XXX\AppData\Local\Microsoft\VisualStudio\17.0_d57e068e\WinFormsDesigner\jrryl1cy.2b0\UserAppData\MyReferencedDll.dll'' is denied.
                           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                           at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
                           at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
                           at System.Threading.Tasks.Task.Execute()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<CacheFileAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.<CopyProjectReferenceToUserAppDataFolderAsync>d__19.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.NetCoreServerLayout.<CopyProjectOutputToShadowCacheHelperAsync>d__5.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.NetCoreServerLayout.<CopyProjectOutputToShadowCacheAsync>d__4.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.<CreateAsync>d__10.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<CreateAsync>d__21.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__9.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting._

### Steps to reproduce

Just reference on readonly DLL, and try to build/open in designer several times

### Diagnostics

```text

```

**Comment by Tanya-Solyanik** [comment] 2024-11-12 20:00
@Olina-Zhang  - could you please copy this bug to the designer repo?

**Comment by Olina-Zhang** [comment] 2024-11-13 02:25
@svg2003 I cannot reproduce this issue, when making library to ReadOnly, then referencing it to Winforms application, designer loads well after build solution and re-open it. It displays as blow. Can you please confirm for me if this is a similar operation or help with a repro project? Thanks!
![Image](https://github.com/user-attachments/assets/7eca98d4-e86f-4da7-81bc-d0fcfa9b78d0)

**Comment by svg2003** [comment] 2024-11-13 03:58
> [@svg2003](https://github.com/svg2003) I cannot reproduce this issue, when making library to ReadOnly, then referencing it to Winforms application, designer loads well after build solution and re-open it. It displays as blow. Can you please confirm for me if this is a similar operation or help with a repro project? Thanks! ![Image](https://github.com/user-attachments/assets/7eca98d4-e86f-4da7-81bc-d0fcfa9b78d0)

It is net8 target, right? Did you try to change your form after that? 
Per my understanding, at first attempt, designer just create cache folder and copy everything there. 
But, when you change you form, designer would try to copy all references again and this time it won't be able to overwrite old dll (due it it's readonly)

**Comment by svg2003** [comment] 2024-11-13 04:27
I did couple more tests, and seems it's due to multitarget. It first copies DLL from net472 target, and after cannot replace DLL with the same name from net8 target:


[20:23:18.467055] info: Shadow cache base directory: C:\Users\XXX\AppData\Local\Microsoft\VisualStudio\17.0_d57e068e\WinFormsDesigner
[20:23:18.469058] info: [WinFormsApp3]: Preparing shadow cache folder.
[20:23:18.469058] info: [WinFormsApp3]: NetCoreServerLayout - Platform: AnyCPU, Normalized PlatformName: x64
[20:23:18.469058] info: [WinFormsApp3]: Copying design tools server common files from: 'c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\Common'.
[20:23:18.549056] info: [WinFormsApp3]: Copying design tool server platform-specific files from: 'c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\x64'.
[20:23:18.560055] info: [WinFormsApp3]: Copying project output file: 'C:\!!!Projects\Test\winforms-readonlyRef\WinFormsApp3\bin\Debug\net8.0-windows\WinFormsApp3.dll'.
[20:23:18.562055] info: [WinFormsApp3]: Copying project reference: 'C:\!!!Projects\Test\winforms-readonlyRef\ClassLibrary3\toRef\net472\ClassLibrary3.dll'.
[20:23:18.563055] info: [WinFormsApp3]: Copying 'C:\!!!Projects\Test\winforms-readonlyRef\WinFormsApp3\obj\Debug\net8.0-windows\WinFormsApp3.designer.deps.json' to 'DesignToolsServer.deps.json'
[20:23:18.565056] info: [WinFormsApp3]: Copying 'C:\!!!Projects\Test\winforms-readonlyRef\WinFormsApp3\obj\Debug\net8.0-windows\WinFormsApp3.designer.runtimeconfig.json' to 'DesignToolsServer.runtimeconfig.json'
[20:23:18.566058] info: [WinFormsApp3]: Copying project reference: 'C:\!!!Projects\Test\winforms-readonlyRef\ClassLibrary3\toRef\net8.0\ClassLibrary3.dll'.
[20:23:18.571058] fail: System.UnauthorizedAccessException: Access to the path 'C:\Users\XXX\AppData\Local\Microsoft\VisualStudio\17.0_d57e068e\WinFormsDesigner\z5uyqjfp.gtr\UserAppData\ClassLibrary3.dll' is denied.
                           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                           at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
                           at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
                           at System.Threading.Tasks.Task.Execute()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<CacheFileAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.<CopyProjectReferenceToUserAppDataFolderAsync>d__19.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.NetCoreServerLayout.<CopyProjectOutputToShadowCacheHelperAsync>d__5.MoveNext()

[winforms-readonlyRef.zip](https://github.com/user-attachments/files/17726105/winforms-readonlyRef.zip)

**Comment by Olina-Zhang** [comment] 2024-11-13 06:54
Thanks @svg2003, filed it in our internal designer repo: https://github.com/microsoft/winforms-designer/issues/6166 to track, closing this one.

**Closed by Olina-Zhang** 2024-11-13 06:54 UTC
Labels: area-VSDesigner
