### ISSUE TITLE
The result of Screen.FromPoint() is wrong.

### ISSUE THREAD

**Issue by changhao6** [dotnet/winforms#10663] opened 2024-01-15 09:26 UTC
### .NET version

.net8

### Did it work in .NET Framework?

Yes

### Issue description

I want to konw which screen the cursor in when mousemove in the form by using the code blow:
```C#
        private void Form1_MouseMove(object sender, MouseEventArgs e)
        {
            var screen = Screen.FromPoint(MousePosition);
            this.label1.Text = $"{screen.DeviceName}";
        }
```
It seem can't get which screen the mouse is in exactly.
![screen](https://github.com/dotnet/winforms/assets/47862827/dc5277cf-d0ee-426c-890e-ab95a434f293)
The background color purple is screen1 and black is screen2.

### Steps to reproduce

Move the form between the two screens and move the mouse.

**Comment by elachlan** [comment] 2024-01-15 11:25
@Olina-Zhang can your team please test this?

**Comment by elachlan** [comment] 2024-01-15 21:54
@changhao6 are the monitors on 100% DPI?

**Comment by changhao6** [comment] 2024-01-16 01:39
@elachlan  screen1 is 125% and screen2 is 100%.

**Comment by elachlan** [comment] 2024-01-16 01:50
@changhao6 if you change the monitors to both be 100%, does the issue still reproduce?

**Comment by changhao6** [comment] 2024-01-16 02:00
@elachlan I change the monitors to both be 100%, this issue didn't reproduce, It works fine. But I think `Screen.FromPoint()` should get the right Screen even if the scale of the two screens is different, what do you think?

**Comment by elachlan** [comment] 2024-01-16 02:04
@changhao6 thank you, that test was to narrow the issue to HDPI.

**Comment by elachlan** [comment] 2024-01-16 02:30
Winforms basically calls directly to the WINAPI function `MonitorFromPoint`:
https://github.com/dotnet/winforms/blob/fb21385ad0224ddf4c92b9a997016ceed4116f27/src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs#L246-L252

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfrompoint
https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-improvements-for-desktop-applications

Maybe try enabling this in the csproj?
`<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>`

**Comment by changhao6** [comment] 2024-01-16 03:54
@elachlan Thanks for your solution. Does that means that we can't get correct screen without setting `ApplicationHighDpiMode`?

**Comment by elachlan** [comment] 2024-01-16 03:59
@changhao6 Try testing the different options and see? I haven't used them myself and I am unsure on what will solve your issue.

**Comment by changhao6** [comment] 2024-01-16 04:15
OK, I will try it even if I think it should get the right result without setting `ApplicationHighDpiMode`. Thank for your help!

**Comment by elachlan** [comment] 2024-01-16 04:49
@changhao6 please let us know if the `ApplicationHighDpiMode` does not work.

**Comment by changhao6** [comment] 2024-01-16 05:38
@elachlan It works if I use `Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);` . Thank you.

**Comment by elachlan** [comment] 2024-01-16 05:52
@changhao6 Excellent! I will close this issue now as it is resolved. I don't think there is a way for it to work without PMv2, because of how HDPI works in windows.

**Closed by elachlan** 2024-01-16 05:52 UTC
Labels: untriaged, area-HDPI
