### ISSUE TITLE
Winforms ListView ColumnWidthChanging event is not fired

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7663] opened 2022-08-25 03:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Winforms-ListView-ColumnWidthChanging-ev/10129947)._

---
[severity:It's more difficult to complete my work]
ListView has an event ColumnWidthChanging which should allow the expected column width change to be cancelled, however the event is never fired because the HDN.ENDTRACKW notification is received before HDN.ITEMCHANGINGW and it resets listViewState[LISTVIEWSTATE_headerControlTracking] preventing the HDN.ITEMCHANGINGW handler from raising the event.

---
#### Feedback Bot on 8/25/2022, 09:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by John-Qiao** [comment] 2022-08-25 03:58
- .NET Core Version:
 .NET SDK 7.0.100-alpha.1.22060.5

- Have you experienced this same bug with .NET Framework?:
  Yes

**Problem description:**

The ColumnWidthChanging event is not fired.

**Expected behavior:**

The ColumnWidthChanging event should be fired.

**Minimal repro:**

1. Open the attached [ColumnWidthChanging-TestApp.zip](https://github.com/dotnet/winforms/files/9421213/ColumnWidthChanging-TestApp.zip) project in VS and run it.
2. Try to changing the column width in list view control.

**Comment by merriemcgaw** [comment] 2022-08-30 23:49
@John-Qiao can you please work with @Amy-Li03 and the customer to determine the Framework impact and advise the CSS route? And perhaps for this one find out what version of .NET Framework they are targeting. 

We will consider doing something in .NET 8 because this one seems to be more impactful.

**Comment by Tanya-Solyanik** [comment] 2022-08-30 23:52
@John-Qiao  - additional question, what version of the .NET Framework does this repro on? For example, retarget the application to 3.5 to see if it repros. I wonder if this could had been caused by the old accessibility fixes in the FX

**Comment by John-Qiao** [comment] 2022-08-31 02:58
@merriemcgaw ok, we will confirm that info with customer in ticket.

@Tanya-Solyanik double-click on column header divider can fire the ColumnWidthChanging event, but drags the column header divider cannot fire ColumnWidthChanging event. This issue occurs in all .NET Framework versions(from 3.5 to 4.8.1) and .NET Core versions(from 3.1 to 7.0).

**Comment by Tanya-Solyanik** [comment] 2022-08-31 05:18
Thank you, @John-Qiao , so this is not a regression.

@merriemcgaw - I would suggest not touching this behavior, or at least quirking it. Chances are, there exists an application that relies on not having a changing event in this case.

**Comment by merriemcgaw** [comment] 2022-08-31 18:46
I would have to agree wholeheartedly. Two steps here - if @John-Qiao can you work with the customer on this feedback ticket to see if the Framework version of the bug is a blocking issue for the customer. If it is not, then close it as low priority because changing this could cause problems for other apps. I'll leave this issue open for .NET 8+ and when it is fixed we will want to ensure that we've quirked it appropriately.

**Comment by John-Qiao** [comment] 2022-09-01 01:32
@merriemcgaw customer is using .NET 6.0.8 and this bug is not blocked his project, he enabled the ColumnWidthChanged event as a workaround. As this bug is a .NET runtime issue, I have closed the initial feedback ticket as duplicated to this GH issue. Below is the reply from customer:

`I’m using .net 6.0.8. It’s just an annoyance. I’ve been able to work around it by forcing the column width in the ColumnWidthChanged handler.`

**Comment by RussKie** [comment] 2022-09-01 03:37
Closing as won't fix due to the risk profile and availability of a workaround.

**Closed by RussKie** 2022-09-01 03:37 UTC
