### ISSUE TITLE
Menus and *Strips and SplitContainer controls do not respect application font

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#5391] opened 2021-08-04 00:11 UTC
As reported in https://github.com/dotnet/winforms-designer/issues/3611

**Problem description:**

The font for these controls: ToolStrip/menuStrip/StatusStrip, MonthCalendar, SplitContainer is not rendered after setting an application font, is not same as button's
![image](https://user-images.githubusercontent.com/26474449/126601047-51e49925-e4f8-4b89-b4be-6a7df4ee8b65.png)

<details>
<summary>.NET 6.0 RC1</summary>

* Runtime
![image](https://user-images.githubusercontent.com/4403806/126939007-93cba08c-343a-4d67-9dcc-82c58da8d05a.png)
* Designer
![image](https://user-images.githubusercontent.com/4403806/126939122-ddabf7e8-da7a-4b04-80e1-3a544d0ef8f0.png)

</details>

<details>
<summary>.NET 5.0</summary>

* Runtime
![image](https://user-images.githubusercontent.com/4403806/126946460-15191dd4-24ed-4876-bac7-2bdc8d12fb13.png)

* Designer:
![image](https://user-images.githubusercontent.com/4403806/126946426-2aad4a32-5a4c-4cc6-8efe-f3d7efc7364d.png)

</details>

**Expected behavior:**

The font for these controls: ToolStrip/menuStrip/StatusStrip, MonthCalendar, SplitContainer is rendered as that application font

**Repro steps:**

1. Create a Winforms .Net application
2. Set a custom application font in .csproj file as following:
```xml
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <OutputType>WinExe</OutputType>
              <TargetFramework>net6.0-windows</TargetFramework>
              <Nullable>enable</Nullable>
              <UseWindowsForms>true</UseWindowsForms>
	          <ApplicationFont>Arial, 12pt, style=Bold, Italic</ApplicationFont>
            </PropertyGroup>
          </Project>
```
3. Add some controls: Button, ToolStrip/menuStrip/StatusStrip, MonthCalendar/SplitContainer to form designer, then to observe

A test solution is also available at https://github.com/RussKie/DesignerTestbed

**Comment by dreddy-work** [comment] 2021-08-06 00:48
Can we repro this by just setting Font on the Form and no explicit Default font?

**Comment by dreddy-work** [comment] 2021-08-06 00:50
@Olina-Zhang , Can you verify if any other winforms controls, other than what is specified here,  experiencing same issue?

**Comment by Olina-Zhang** [comment] 2021-08-06 02:00
@dreddy-work this issue still repro by just setting Font on the Form and no explicit default font, design time and run time have same result. And other Winforms controls cannot repro this issue.
![image](https://user-images.githubusercontent.com/26474449/128444426-74c1484f-fb0c-4e7b-b8b1-abdfa0047f98.png)

**Comment by merriemcgaw** [comment] 2023-02-28 19:57
Let's see if we can fix the *Strip items. I don't think the MonthCalendar is anything we can control, but the *Strips are.

**Comment by dreddy-work** [comment] 2023-07-28 17:23
adding @merriemcgaw to reassign.

**Comment by Tanya-Solyanik** [comment] 2023-07-28 18:59
@LeafShi1 @SimonZhao888 @Epica3055  - I moved this bug to your project, but this is not urgent, Please start with the *Strip controls, and once they are done, investigate the SplitContainer. Also please share results of your investigation in this issue (or a meeting) so that I have a chance to review it before you implement the fix.

**Comment by LeafShi1** [comment] 2023-07-31 01:53
> @LeafShi1 @SimonZhao888 @Epica3055 - I moved this bug to your project, but this is not urgent, Please start with the *Strip controls, and once they are done, investigate the SplitContainer. Also please share results of your investigation in this issue (or a meeting) so that I have a chance to review it before you implement the fix.

OK, we will investigate this bug.

**Comment by LeafShi1** [comment] 2023-08-31 07:57
@Tanya-Solyanik For SplitContainer, the text "panel1", "panel2" will not be displayed at runtime, if I add some other controls in it, the font of the control will follow the logic of the control itself, so it seems that we don't need to do font judgment on it.
![image](https://github.com/dotnet/winforms/assets/132890443/0b8ed5d4-ecf2-450f-98c2-bd6c4f4072cf)

**Comment by Tanya-Solyanik** [comment] 2023-09-01 22:18
Looking at the ToolStripManager - https://github.com/dotnet/winforms/blob/5bc22fac7f9bdeac69d8865db6f6d52e4700d5a1/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs#L96-L100 It seems that menus have special handling for fonts and don't inherit font from the parent, and default to a different font compared to regular controls.

**Comment by LeafShi1** [comment] 2023-09-04 10:33
> Looking at the ToolStripManager -
> 
> https://github.com/dotnet/winforms/blob/5bc22fac7f9bdeac69d8865db6f6d52e4700d5a1/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs#L96-L100
> 
> It seems that menus have special handling for fonts and don't inherit font from the parent, and default to a different font compared to regular controls.
> This might had been "by design" in the past. Personally I like that menu font matches the container font now, but I wonder what the team thinks and this is why i'm moving this issue to untriaged.
> Windows does not separate menu fonts from text fonts in the settings now.

Menu is only displayed at design time, so I don't think it has to be consistent with the font of the parent control
![image](https://github.com/dotnet/winforms/assets/132890443/097d14ac-f65b-4d06-b364-b33f20332521)

The font displayed at runtime should be consistent with the font of the parent window or parent control
![image](https://github.com/dotnet/winforms/assets/132890443/2371542d-8640-4f64-8f92-7a17dd5183c6)

**Comment by Tanya-Solyanik** [comment] 2023-09-06 00:49
I'm ok that the design time-only menu has different font.

I was saying that previously menus were supposed to have different font, and we had special font manager for that purpose. This fix is changing this design and that had not been discussed in this bug.

**Comment by LeafShi1** [comment] 2023-09-06 02:07
> I'm ok that the design time-only menu has its own font.
> 
> I was saying that previously menus were supposed to have a different font, and potentially some apps were sized to support that, we had special font manager for that purpose. This fix is changing this design and I don't see a discussion in this bug. So I want to hear what the team thinks.
> 
> @LeafShi1 - we might want to define an opt-out from this change. Please see how Devendar had done it -
> 
> https://github.com/dotnet/winforms/blob/e2bfda0f76b2ee6243bc1731f88c113d15492cc5/src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs#L9

OK， get it!

**Comment by Tanya-Solyanik** [comment] 2023-09-06 22:03
@LeafShi1  - we had re-triaged this issue in the meeting today and decided to wait until we have customer reports because this can cause layout corruption in the application if that application had relied on certain font size in menus, for example by providing images within menu items

**Comment by LeafShi1** [comment] 2023-11-15 10:10
One customer reported this issue: [FeedbackTicket 1449238 WinForms default font is not applied to tool strip (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1449238)

**Comment by merriemcgaw** [comment] 2023-11-21 19:30
Menus historically have had different default fonts than the Form/Window itself. Changing this behavior would be very breaking for existing applications, so we would prefer not to do that.
@John-Qiao - can you sync the feedback ticket up with "By Design"

**Closed by merriemcgaw** 2023-11-21 19:30 UTC
Labels: :beetle: bug, Priority:2, untriaged
