### ISSUE TITLE
Nuance's Dragon Professional fails to function with NET 8 & 9 but works with NET 7 and earlier

### ISSUE THREAD

**Issue by efm5** [dotnet/winforms#11120] opened 2024-03-24 21:05 UTC
### Description

Nuance's Dragon Professional fails to exercise Controls (menu item, button etc.) when apps are compiled with with NET 8 & 9 but works with NET 7 and earlier. When Dragon is running, it should be possible to say "click" followed by the text/label of a Control and have the handler procedure linked to that Control entered (and actions performed).

### Reproduction Steps

0) Make sure Dragon 15.x or 16.x (the most recent versions) is running and listening.
1) Create a simple Windows Form app with a button whose text is "Horse".
1a) add a Click handler to the Button with its only code:
MessageBox.Show("horse");
2)  Compile with NET 7 (for Windows 7.0)
3) Run the app and say "click horse"
4) Close the app
5) Compile with NET 8 (I also tested NET 9 - both fail)
6) Run the app and say "click horse"

### Expected behavior

A built-in Dialog should open displaying "horse" as the message (with default title, buttons and icon).

### Actual behavior

With NET 7  (and all previous going back to early Net Framework versions) the expected behavior occurs.

With both NET 8 & 9 nothing happens at all - the button is not exercised.

### Regression?

Works perfectly in NET 7 but started failing sometime in NET 8 development.

### Known Workarounds

Compile with NET 7 accepting all associated restrictions.

### Configuration

NET 7 - works
NET 8 & 9 - fails
VS 2019 (tested a few versions), 2022 (tested at least 10 versions) & 2022 Preview  (only tested Preview 2) - all act the same
OS Win10 & Win 11 tested with identical results
Tested with both "AnyCPU" and x64 - not specific works or fails in both
Not using Blaxor

### Other information

This is a major regression for developers working with the disabled community. I would be extremely happy to beta test NETs to help resolve this issue. I am a hands-free coder and have nothing but time on my hands! I am fairly experienced in NET Windows Form and Console coding and am the sole author on more than 10 major applications highly used by folks who use Dragon to operate their computers and dictate text. I would be willing to do remote desktop sessions at most any time of the day or night.

**Comment by efm5** [comment] 2024-03-24 21:27
Thanks for the transfer!

**Comment by elachlan** [comment] 2024-03-25 00:00
@efm5 can you please provide a reproduction project in the issue description? Do you have the same issue with [Accessibility Insights for Windows](https://devblogs.microsoft.com/engineering-at-microsoft/accessibility-insights-for-windows/)? You might also want to report this to Nuance and provide them with a link to this issue.

@Olina-Zhang can your team please test this?

**Comment by efm5** [comment] 2024-03-25 00:21
https://github.com/dotnet/winforms/assets/9344405/eca75f96-4157-4bfd-81b7-e0d49c4a00a0

[NET9broken.zip](https://github.com/dotnet/winforms/files/14737364/NET9broken.zip)
here is a very simple project and a very brief video which demonstrates the problem

**Comment by efm5** [comment] 2024-03-25 00:26
I do not believe that Nuance accepts bug reports; that may have changed since its recent acquisition by Microsoft. They only offer telephone support for their software.

**Comment by elachlan** [comment] 2024-03-25 00:33
Thank you so much for the video! The team will comment here soon and we will find out the next steps.

**Comment by elachlan** [comment] 2024-03-25 00:34
@merriemcgaw this is an accessibility regression issue you might be interested in.

**Comment by Olina-Zhang** [comment] 2024-03-25 07:31
There is a feedback with the same issue when using Nuance's Dragon Professional: https://developercommunity.visualstudio.com/t/NET-8-changed-breaking-Nuance%E2%80%99s-Dragon-P/10623024

Here is a clear video with sound from that feedback:

https://github.com/dotnet/winforms/assets/26474449/5216f0f8-c117-4010-be7b-180631c3be6f

**Comment by merriemcgaw** [comment] 2024-03-26 18:52
@LeafShi1 can your team take a look at this issue and see if you can root cause it?

**Comment by Tanya-Solyanik** [comment] 2024-03-26 22:28
@LeafShi1  - please investigate if Inspect can execute default action on a button under MSAA or Invoke.Invoke under UIA.

@Olina-Zhang  - could you please search for any bugs related to timeouts in Invoke pattern, I seem to remember a customer report.

**Comment by Tanya-Solyanik** [comment] 2024-03-27 01:15
@Olina-Zhang  - please experiment with voice access on windows 11 -  https://support.microsoft.com/topic/get-started-with-voice-access-bd2aa2dc-46c2-486c-93ae-3d75f7d053a4

**Comment by Olina-Zhang** [comment] 2024-03-27 02:19
> @Olina-Zhang - could you please search for any bugs related to timeouts in Invoke pattern, I seem to remember a customer report.

Is this one: https://github.com/dotnet/winforms/issues/10244?

**Comment by LeafShi1** [comment] 2024-03-27 05:44
> @LeafShi1 - please investigate if Inspect can execute default action on a button under MSAA or Invoke.Invoke under UIA.
> 
> @Olina-Zhang - could you please search for any bugs related to timeouts in Invoke pattern, I seem to remember a customer report.

Yes, Inspect can execute default action on a button under MSAA and Invoke.Invoke under UIA
![Result](https://github.com/dotnet/winforms/assets/132890443/a60c8901-0c39-4696-8d93-0f80b9df11bb)

**Comment by Olina-Zhang** [comment] 2024-03-27 08:36
> @Olina-Zhang - please experiment with voice access on windows 11 - https://support.microsoft.com/topic/get-started-with-voice-access-bd2aa2dc-46c2-486c-93ae-3d75f7d053a4

I tested winforms menuItem and button with voice access on windows 11, .Net 7 and .Net 9 behaviors are same: all can be invoked by Voice access commands, see the video as below:

https://github.com/dotnet/winforms/assets/26474449/c5992de0-573d-49fe-aceb-97e28faea211

**Comment by Tanya-Solyanik** [comment] 2024-03-27 17:03
Thank you, Olina, for finding #10244! I believe this is a duplicate of this bug. We don't have source code for Nuance's Dragon tool, but InvokePattern.Invoke method is the way to open a named UIA Element, it's reasonable to assume that the root cause of the two bug is the same. 
@LeafShi1  - please prioritize #10244 within your team.

**Closed** 2024-03-27 17:04 UTC
Labels: tenet-accessibility, :boom: regression-release
