### ISSUE TITLE
Make the owner window foreground, when the child window that the user had clicked is closed.

### ISSUE THREAD

**Issue by HubKing** [dotnet/winforms#4600] opened 2021-02-25 07:56 UTC
**Is your feature request related to a problem? Please describe.**

I have been personally annoyed by this "disappearing window" issue of my own WinForms app for years. When I close a child window, suddenly the main window gets hidden for some reason. I did not know exactly why it happened, and today, I finally found it out.

Let's say that the WinForms app has a MainWindow and a child Window. Create a new WinForms project, and add the following lines of code after `InitializeComponent();`.

		this.Size = new Size(600,300);
		var b = new Button();
		b.Text = "Open";
		b.Location = new Point(100,100);
		this.Controls.Add(b);
		b.Click += (_, _) =>
		 {
			var f = new Form();
			f.Size = new Size(600,300);
			f.Show(this);
		};

Now, run the application, and click the button. When the child window is open, click another application so that it becomes the foreground app obscuring the WinForms app. Now, click the child window to make the WinForms app foreground. We can see both the child and the main window. Now close the child window. I expect then the main window becomes the foreground window, because the WinForms app is the foreground app. However, it gets obscured by the other application. See the screen recording below.

![LiFd8mumVi](https://user-images.githubusercontent.com/10900489/109120482-5843df00-7789-11eb-81a4-f80edaf187ea.gif)

Probably the developers thought this was the correct behaviour, but to a simple user like myself, this is counter-intuitive. I thought I brought the WinForms app to the foreground by clicking the child window. Even if the child window is closed, this WinForms app should stay foreground.

**Describe the solution you'd like and alternatives you've considered**

There needs to be an option to make the owner window of the foreground child window stay foreground when the foreground child window is closed. I do not know if in some cases, the current behaviour makes more sense, but in my opinion, most of the cases, it is desirable that the main window stays foreground.

**Will this feature affect UI controls?**

No VS designer support or localisation is needed; just a behavioural change of the Form. I am not sure about accessibility, but probably no impact.

**Comment by weltkante** [comment] 2021-02-25 22:15
WinForms can hand off activation to a different window before it closes the form. If it doesn't then the Windows standard logic will kick in and (probably) activate the most recently used window. This usually makes sense, but for owned windows its indeed odd since the most recently used is not matching whats in the foreground when you close the child window.

I have no objection for WinForms to automatically pass focus to the owner before closing an owned window, even if thats not standard behavior of native windows it does seem to make sense.

If so I'd suggest following procedure to avoid flicker:
- call `OnClose` callbacks to allow user code to pass on focus first
- before returning from close handler check if activation is still on the form, if so pass it on to its owner

This should gracefully handle the case where the user already is handing off activation explicitly in the event handler or override.

**Comment by dreddy-work** [comment] 2021-03-04 02:18
I am not sure if making this proposed behavior as default is good.  for ex: While i am working on window # 1, got a popup message from a process running under window # 2. responding on this popup message will take me back to what i was working on. Falling back to previous active window seems right ( even from accessibility perspective). I agree that we should not hide the parent window ( as shown in the GIF) though.

**Comment by dreddy-work** [comment] 2022-05-05 22:51
Thank you @HubKing for filing this, this has been open and hasn't got any traction form community. If you are blocked or a fix in mind, please feel free to propose solution and we can help drive it in the coming milestone.

**Comment by Amy-Li03** [comment] 2022-06-21 02:46
Hi @HubKing verified this issue on .NET SDK 5.0, 6.0 & 7.0, we all cannot reproduce this issue, following is our repro steps, please correct us if we have done anything wrong, if you also don't reproduce it any longer, we will close this.
![NotRepro](https://user-images.githubusercontent.com/62929087/174705410-e2bc21a9-3a0c-4540-949f-473f58dde516.gif)

**Closed** 2022-07-12 07:02 UTC
Labels: up-for-grabs, api-suggestion, :mailbox_with_no_mail: waiting-author-feedback, :zzz: no-recent-activity
