### ISSUE TITLE
ControlBox (maximize, minimize, and close button)  is not visible on MainMenu when maximizing child form

### ISSUE THREAD

**Issue by nkastratovic** [dotnet/winforms#4388] opened 2020-12-17 15:17 UTC
* .NET Core Version: 
.NET 5.0.1

* Have you experienced this same bug with .NET Framework?: 
 No

**Problem description:**

I have windows desktop application where the main form is MdiParent form with IsMdiContainer = true, and MainMenuStrip = MenuStrip.
When I open the child form and maximize it, the ControlBox (maximize, minimize, and close button) on the right side of MainForm-MainMenu is not visible, only when I move cursor on this part of MainMenu it shows very thin buttons.
With .Net Code 3.1 and the same settings, my application doesn’t have this problem, ControlBox is visible in MainMenu and normal size.
Also, this works with .Net Framework 4.8.

![dotNet3 1](https://user-images.githubusercontent.com/22772163/102506385-5374f780-4083-11eb-9477-5a93760844ab.PNG)
![dotNet5 0](https://user-images.githubusercontent.com/22772163/102506400-5839ab80-4083-11eb-985b-87600d7c1d71.png)

**Comment by RussKie** [comment] 2020-12-17 22:46
Duplicate of #3029

**Comment by RussKie** [comment] 2021-01-11 05:36
After further investigations, this issue appears to be different  from #3029 (yet related). The issue is a regression introduced in https://github.com/dotnet/winforms/pull/2659 

/cc: @hughbe

**Comment by callanac** [comment] 2021-01-11 12:30
It's good to hear that this issue has been resolved in the code. @RussKie do you know when this will make into into .NET release? My team are currently building software and we can't release until we get this fix. Many thanks

**Comment by RussKie** [comment] 2021-01-11 22:02
> do you know when this will make into into .NET release?

I would expect this issue serviced, and will be presenting it to the shiproom. If it is approved for servicing, it will go out in one of the future 5.0 servicing updates. Until it is approved, I can't tell in which one.

**Closed** 2021-01-12 23:48 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress

**Comment by Jenna-Zheng** [comment] 2021-01-26 06:44
Verified this issue with sdk 5.0.103-servicing.21073.8, that the issue has been fixed, the MDI forms show sub control box correctly. see below screenshot.
![image](https://user-images.githubusercontent.com/64949616/105809891-facf3d80-5fe4-11eb-996e-eca61c56c252.png)
