### ISSUE TITLE
Button_Anchor_ResizeOnWindowSizeWiderAsync fails intermittently

### ISSUE THREAD

**Issue by fernandanavamoya** [dotnet/winforms#7383] opened 2022-07-07 01:30 UTC
### Test

System.Windows.Forms.UITests.ButtonTests.Button_Anchor_ResizeOnWindowSizeWiderAsync

### Issue description

Failed in Windows_x64 Release. History shows several failures over the past week.

```
Assert.True() Failure\r\nExpected: True\r\nActual:   False

   at System.Windows.Forms.UITests.ButtonTests.<Button_Anchor_ResizeOnWindowSizeWiderAsync>b__7_0(Form form, Button button) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs:line 178
   at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass28_0`1.<<RunFormAsync>b__0>d.MoveNext() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 242
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
   at System.Windows.Forms.UITests.ControlTestBase.RunFormAsync[T](Func`1 createDialog, Func`3 testDriverAsync) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 261
   at System.Windows.Forms.UITests.ControlTestBase.RunSingleControlTestAsync[T](Func`3 testDriverAsync, Func`1 createControl, Func`1 createForm) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 179
   at System.Windows.Forms.UITests.ButtonTests.RunTestAsync(Func`3 runTest) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs:line 395
   at System.Windows.Forms.UITests.ButtonTests.Button_Anchor_ResizeOnWindowSizeWiderAsync() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs:line 161
--- End of stack trace from previous location ---
```

**Comment by fernandanavamoya** [comment] 2022-07-07 01:36
fyi: @RussKie

**Comment by Tanya-Solyanik** [comment] 2022-07-14 07:47
duplicate of https://github.com/dotnet/winforms/issues/7297

**Closed by Tanya-Solyanik** 2022-07-14 07:47 UTC
Labels: test-bug
