### ISSUE TITLE
Textbox MaxLength > 32767 has no effect, may be documentation oversight

### ISSUE THREAD

**Issue by goroggy** [dotnet/winforms#8985] opened 2023-04-13 10:14 UTC
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 3.0
<TargetFramework>net8.0-windows</TargetFramework>
<LangVersion>preview</LangVersion>
<Platforms>x64</Platforms>

### .NET version

<TargetFramework>net8.0-windows</TargetFramework>

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I don't know

### Issue description

Setting TextBox MaxLength to e.g. 99_999, it still accepts only the first 32_727 characters.

### Steps to reproduce

Put a textbox on a windows form. Copy text longer than 32_727 characters. Paste into this textbox. Textbox will accept the first 32_727 characters. Set MaxLength to 99_999. Textbox still accepts the first 32_767 characters only.

### Diagnostics

```text
// 
            // TbInput
            // 
            TbInput.Location = new Point(7, 124);
            TbInput.MaxLength = 99999;
            TbInput.Multiline = true;
            TbInput.Name = "TbInput";
            TbInput.ScrollBars = ScrollBars.Vertical;
            TbInput.Size = new Size(846, 523);
            TbInput.TabIndex = 21;
            TbInput.TextChanged += TbInput_TextChanged;
```

**Comment by elachlan** [comment] 2023-04-14 03:19
@goroggy I cannot reproduce it using `WinformsControlsTest` and setting `multilineTextBox.MaxLength = int.MaxValue - 1;` or `multilineTextBox.MaxLength = 99999;` in the constructor.

I also tested by setting it in the designer code.

@Olina-Zhang can you team please confirm this?

Docs on limits: 
- https://learn.microsoft.com/en-us/windows/win32/controls/em-setlimittext
- https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.textboxbase.maxlength?redirectedfrom=MSDN&view=windowsdesktop-7.0#System_Windows_Forms_TextBoxBase_MaxLength
- https://stackoverflow.com/questions/8097949/disabling-the-maxlength-property-of-a-textbox-in-c-sharp

**Comment by Olina-Zhang** [comment] 2023-04-14 07:26
I also do not reproduce the problem: when setting TextBox MaxLength to 99999 or 32767, it can accept corresponding number of characters.

**Comment by JeremyKuhne** [comment] 2023-04-19 20:27
@goroggy we're having issues reproducing this, is there any clarifying steps you might be able to provide?

**Comment by goroggy** [comment] 2023-04-20 06:35
Jeremy, sorry for the hassle. My mistake. The MaxLength limit works as
expected.
Thanks for your efforts.
Görög György


Jeremy Kuhne ***@***.***> ezt írta (időpont: 2023. ápr. 19.,
Sze, 22:28):

**Comment by elachlan** [comment] 2023-04-24 00:20
@goroggy if this issue is resolved, could you please close this issue?

**Comment by goroggy** [comment] 2023-04-27 11:33
Sorry again.

**Closed** 2023-04-27 11:33 UTC
Labels: area: VS designer
