### ISSUE TITLE
.net7.0 winform slow on windows7

### ISSUE THREAD

**Issue by ahdung** [dotnet/winforms#9666] opened 2023-08-05 00:42 UTC
### .NET version

```
C:\Users\Administrator>dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

运行时环境:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspN
etCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore
.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.
WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocat
ion]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

`.net 6.0` is OK.

### Issue description

open `winform` apps slow, need wait 5+ seconds, actually `wpf` same too;
close also slow, the process need 6+ seconds to stop.

### Steps to reproduce

as `description` said.

**Comment by elachlan** [comment] 2023-08-05 21:04
.Net7 does not support windows 7 and it also has a lower bar for updates as it isn't LTS.

https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md

I suspect the team will be unlikely to investigate it because of this.

**Comment by elachlan** [comment] 2023-08-06 23:53
@Olina-Zhang does your team no longer test windows 7?

**Comment by ahdung** [comment] 2023-08-07 01:01
@elachlan Thank you, I know the support list, but I still hope it gets fixed.

**Comment by elachlan** [comment] 2023-08-07 01:29
@ahdung you will need to provide a test app. Is it just winforms project with an empty form?

**Comment by Olina-Zhang** [comment] 2023-08-07 02:33
> @Olina-Zhang does your team no longer test windows 7?

We hardly test this Win7 with visual studio 2022 now. Because we got the notification "Starting with 17.7 Preview 1 Visual Studio 2022 installation and update will be blocked on OS below Windows 10 and Server 2016. Specifically, VS2022 17.7 and above will no longer install/update on Win 7, Win 8.1, WinServer 2012r2, WinServer 2012, and WinServer 2008r2. Customers who choose to continue running on legacy OS must channel hop to 17.6 LTSC to remain on a serviceable build until Jan 2025. Customers who attempt to install or upgrade on a legacy OS will receive an error dialog telling them that they must upgrade their OS to install VS2022."

And if @ahdung provide a test app, we'd love to go to test on win7.

**Comment by ahdung** [comment] 2023-08-07 06:23
@Olina-Zhang Thank you, here you are:
[WinformSlowDemo.zip](https://github.com/dotnet/winforms/files/12272740/WinformSlowDemo.zip)

Totally a new project, no any my code here, already complied, you can comparing the `.net6.0` and `.net7.0` binaries, in `bin\`

**Comment by Olina-Zhang** [comment] 2023-08-07 09:29
Tested a winforms application with different .Net versions: 6.0, 7.0 and 8.0 on Win7, we can see that difference between .Net 6.0 and .Net 7.0/8.0. When opening and closing .Net 7.0 or 8.0 application, it has extra 2~3 seconds compared to .Net 6.0. In this situation, the CPU and Memory are higher. WPF has same result on Win7.

https://github.com/dotnet/winforms/assets/26474449/0552c687-6ec1-4b86-9e03-2777ea8a0c48


It doesn't reproduce on Win11 machine.

**Comment by JeremyKuhne** [comment] 2023-08-07 19:21
@ahdung Windows 7 is out of support. If you find performance issues in Windows 10 or Windows 11 we're happy to look into it.

**Closed by JeremyKuhne** 2023-08-07 19:21 UTC
Labels: untriaged
