### ISSUE TITLE
RichTextBox.GetCharIndexFromPosition does not return position behind last character unconditionally limits result to (Text.Length - 1)

### ISSUE THREAD

**Issue by mstv** [dotnet/winforms#9762] opened 2023-08-20 13:58 UTC
### .NET version

- .NET 6.0.21
- Microsoft Windows NT 10.0.19045.0

### Did it work in .NET Framework?

Not tested/verified

### Issue description

`RichTextBox.GetCharIndexFromPosition()` unconditionally limits the result to `Text.Length - 1`.
So it never returns the position behind the last character.

```
            var wpt = new Point(pt.X, pt.Y);
            int index = (int)User32.SendMessageW(this, (User32.WM)User32.EM.CHARFROMPOS, IntPtr.Zero, ref wpt);

            string t = Text;
            // EM_CHARFROMPOS will return an invalid number if the last character in the RichEdit
            // is a newline.
            //
            if (index >= t.Length)
            {
                index = Math.Max(t.Length - 1, 0);
            }

            return index;
```

### Steps to reproduce

Set a (single-line) `Text` without a newline at the end.
Call `RichTextBox.GetCharIndexFromPosition()` with click location at / behind the last character.

**Comment by elachlan** [comment] 2023-08-20 22:03
@Olina-Zhang could your team please test this?

**Comment by Olina-Zhang** [comment] 2023-08-21 02:47
Looks like it is a "By design" issue: This method returns the character index that is closest to the position specified in the pt parameter. **The character index is a zero-based index of text in the control, including spaces.**  Which is from the Doc: https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.richtextbox.getcharindexfromposition?view=windowsdesktop-7.0#:~:text=This%20method%20returns%20the%20character%20index%20that%20is%20closest%20to%20the%20position%20specified%20in%20the%20pt%20parameter.%20The%20character%20index%20is%20a%20zero%2Dbased%20index%20of%20text%20in%20the%20control%2C%20including%20spaces. That document website has an example to understand the character index.

**Comment by mstv** [comment] 2023-08-21 17:23
Yes, the result matches the documentation. I hope there are other usecases for which it is useful - but it is not for cursor positioning.
I see the risk if the implementation would be changed. The internal comment does not describe the complete reasoning, i.e. is misleading to me.

**Comment by JeremyKuhne** [comment] 2023-08-21 18:19
@mstv if you think you can offer some more clarity to the docs, please feel free to open a proposed edit. There is a link to do so at the top right of the page. :) Closing as this is by design.

**Closed by JeremyKuhne** 2023-08-21 18:19 UTC
Labels: untriaged
