### ISSUE TITLE
The WH_GETMESSAGE hook type is not working in .NET 7

### ISSUE THREAD

**Issue by icom85** [dotnet/winforms#8062] opened 2022-10-28 09:27 UTC
### Description

Hello!

The P/Invoked `SetWindowsHookEx` method using the [WH_GETMESSAGE](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks#wh_getmessage) hook type is not working in .NET 7. The messages that are constructed seem odd, for example in .NET 7 the WM_LBUTTONDOWN message is never created. The issue seems to be e regression as the same code and setup is working in .NET 6.

### Reproduction Steps

1. Create a simple WinForms project and target .NET 7.
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

2. In the click event of a button install the hook:
```C#
using System.Runtime.InteropServices;

namespace GetMessageHookNet7
{
    public partial class Form1 : Form
    {
        const int WM_LBUTTONDOWN = 0x201;

        private delegate int HookProc(int code, IntPtr wParam, IntPtr lParam);

        [DllImport("user32.dll")]
        private static extern IntPtr SetWindowsHookEx(HookType code, HookProc func, IntPtr hInstance, int threadID);

        [DllImport("kernel32.dll")]
        static extern int GetCurrentThreadId();

        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            this.button1.Enabled = false;
            int threadId = GetCurrentThreadId();
            SetWindowsHookEx(HookType.WH_GETMESSAGE, new HookProc(GetMessageHookProc), IntPtr.Zero, threadId);
        }

        private int GetMessageHookProc(int code, IntPtr wParam, IntPtr lParam)
        {
            if (code >= 0 && (long)wParam > 0)
            {
                Message msg = (Message)Marshal.PtrToStructure(lParam, typeof(Message));
                if (msg.Msg == WM_LBUTTONDOWN)
                {

                }
            }

            return 0;
        }

        private enum HookType
        {
            WH_MSGFILTER = -1,
            WH_JOURNALRECORD = 0,
            WH_JOURNALPLAYBACK = 1,
            WH_KEYBOARD = 2,
            WH_GETMESSAGE = 3,
            WH_CALLWNDPROC = 4,
            WH_CBT = 5,
            WH_SYSMSGFILTER = 6,
            WH_MOUSE = 7,
            WH_HARDWARE = 8,
            WH_DEBUG = 9,
            WH_SHELL = 10,
            WH_FOREGROUNDIDLE = 11,
            WH_CALLWNDPROCRET = 12,
            WH_KEYBOARD_LL = 13,
            WH_MOUSE_LL = 14
        }
    }
}
```
4. Put a breakpoint in the `GetMessageHookProc` inside the _if_ statement where we check for the `WM_LBUTTONDOWN` message.
3. Build and run the project.
4. Click the button to install the hook.
6. Click anywhere on the form.
7. Notice that you will not stop at the breakpoint.

Debugging the project, you will notice that some very strange messages be generated. I am attaching the test project for reference.
[GetMessageHookNet7.zip](https://github.com/dotnet/runtime/files/9887034/GetMessageHookNet7.zip)

The issue also does not reproduce in .NET 6. I am attaching a short gif file showing the observed behavior.
![net7-hook](https://user-images.githubusercontent.com/5156494/198553004-8b427580-a395-4942-bcdf-8709a67e036e.gif)

### Expected behavior

The breakpoint inside the GetMessageHookProc is hit.

### Actual behavior

The breakpoint inside the GetMessageHookProc is **not** hit.

### Regression?

Yes, this issue is a regression. It does not reproduce in .NET 6. 

I tested it in the latest version of VS2022 - **17.4.0 Preview 5.0** and with .NET 7 SDK: **7.0.100-rc.2.22477.23** I also tested with the first preview of .NET 7 - **7.0.100-preview.1.22110.4** and issue still reproduces.

**Comment by JeremyKuhne** [comment] 2022-10-28 18:20
Yes, this is because we changed the order of the fields in `Message`. As it originally doesn't match `MSG` it didn't seem like internal modifications would impact anyone (as it isn't technically blittable as only the first 4 fields line up, the rest will be garbage).

We can change the order back, but that would have to come in servicing at this point. Tagging @merriemcgaw.

If you want to work around this you can use this definition instead:

``` C#
[StructLayout(LayoutKind.Sequential)]
public struct MSG
{
   public IntPtr hwnd;
   public uint message;
   public IntPtr wParam;
   public IntPtr lParam;
   public uint time;
   public Point pt;

   public static implicit operator Message(MSG msg)
       => new Message { HWnd = msg.hwnd, Msg = (int)msg.message, WParam = msg.wParam, LParam = msg.lParam };

   public static implicit operator MSG(Message message)
       => new MSG { hwnd = message.HWnd, message = (WM)message.Msg, wParam = message.WParam, lParam = message.LParam };
}
```

I'd actually recommend this as it's generally risky to try and blast mismatching datatypes over each other.

**Comment by JeremyKuhne** [comment] 2022-10-28 18:31
I'd note there is also substantial risk here if we ever needed to add another field to the struct. In the future we could end up with a struct that is bigger, which could result in an Access Violation exception doing what you're doing.

**Comment by JeremyKuhne** [comment] 2022-10-28 20:01
#8063 fixes this for .NET 8.

We've made a number of internal changes to the `Message` struct to harden our code against casting mistakes. The internal layout changed in the process of doing this.

**Comment by icom85** [comment] 2022-10-30 09:24
Hi, Jeremy! Thanks for fixing this so quickly. Big thanks also for the for the workaround, I think we could use it.

**Comment by RussKie** [comment] 2022-10-31 00:08
@JeremyKuhne @dreddy-work please file a "known issue" for .NET 7 https://github.com/dotnet/core/blob/main/release-notes/7.0/known-issues.md.
I believe @rbhanda can guide you.

**Comment by RussKie** [comment] 2022-10-31 01:16
The regression was introduced in #5849.

**Comment by JeremyKuhne** [comment] 2022-10-31 17:47
@dreddy-work, @RussKie  Please do not put this in "known issues". This is an unsafe use of undocumented internals. Nobody should be doing this as we could break people worse in the future by adding additional functionality in `Message` (if we added additional fields this sort of hard blit could AV). While we were able to make an accommodation in this case, I don't want to give any inclination that this sort of thing (relying on internals) is ok or something that we can / will fix. If we find the impact is widespread then we can reconsider adding to "known issues" with the appropriate warning flags.

**Comment by RussKie** [comment] 2022-11-01 07:21
I completely disagree here. This was working, and now it doesn't. It doesn't matter how we feel about it - it is broken now. This is the definition of a "breaking change".

If the change was deliberate it **must be documented** https://learn.microsoft.com/dotnet/core/compatibility/7.0 - an appropriate "breaking change" issue must be created in https://github.com/dotnet/docs/ repo. 
If this was an accidental break - then the issue **must be documented** under "Known issues". 

We can add disclaimers there that while being fixed in an upcoming servicing release (if we decide to do so), this behaviour isn't a recommended and should be avoided.

**Comment by merriemcgaw** [comment] 2023-01-10 20:03
We're landing with @JeremyKuhne's take on the documentation.

**Comment by merriemcgaw** [comment] 2023-01-10 20:04
@icom85 - do we need to service this to .NET 7? I don't t hink we've done that yet.

**Comment by icom85** [comment] 2023-01-12 10:30
Hi @merriemcgaw, in .NET 7 we are using the workaround with the struct that has the correct properties order. If you don't service the fix to .NET 7, we can stay with the current solution. It's up to you to decide.

**Comment by merriemcgaw** [comment] 2023-01-12 17:56
Thanks @icom85! I think we'll keep things as is for .NET 7 unless there are other customers who need this fix. Until that time I shall close this issue.

**Closed by merriemcgaw** 2023-01-12 17:56 UTC
Labels: :boom: regression
