### ISSUE TITLE
ContextMenuStrip in Tray doesn't look "Native"

### ISSUE THREAD

**Issue by robertmuehsig** [dotnet/winforms#10723] opened 2024-01-23 15:58 UTC
### .NET version

6.0

### Did it work in .NET Framework?

Yes (Kind of - at least the "older" MenuItem variant)

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

We are in the process to migrate our application from ".NET Framework 4.8" to .NET 6 (and upwards). 
The "Upgrade Assistant" told us to migrate the "ContextMenu" (and similar classes) to the newer "ContextMenuStrip" system for our application tray icon.

After we migrate the code the look and feel doesn't match the system.

Before:
![image](https://github.com/dotnet/winforms/assets/756703/86001be3-de7c-4ac2-8aa9-6982805fe2bb)

After:
![image](https://github.com/dotnet/winforms/assets/756703/99acff01-65d1-40c7-9474-2862a795b14c)

I already discovered these issues, but I wasn't sure if they apply to the "tray icon" stuff as well:
- #2476
- #2543

... because drop downs in Windows 11 looks different then the items in a tray icon.

My question: Is this by design and an open bug or do I miss something? The goal would be that it should like other native tray menus.

### Steps to reproduce

Following code:

```
using System;
using System.Drawing;
using System.Windows.Forms;

public class TrayApplicationContext : ApplicationContext
{
    private NotifyIcon trayIcon;
    private ContextMenuStrip contextMenu;

    public TrayApplicationContext()
    {
        InitializeContext();
    }

    private void InitializeContext()
    {
        // Create a context menu for the tray icon
        contextMenu = new ContextMenuStrip();
        contextMenu.Items.Add("Item 1", null, OnItem1Click);
        contextMenu.Items.Add("Item 2", null, OnItem2Click);
        contextMenu.Items.Add(new ToolStripSeparator());
        contextMenu.Items.Add("Exit", null, OnExitClick);

        // Initialize the tray icon
        trayIcon = new NotifyIcon()
        {
            Icon = SystemIcons.Application,
            ContextMenuStrip = contextMenu,
            Visible = true
        };
    }

    private void OnItem1Click(object sender, EventArgs e)
    {
        MessageBox.Show("Item 1 clicked");
    }

    private void OnItem2Click(object sender, EventArgs e)
    {
        MessageBox.Show("Item 2 clicked");
    }

    private void OnExitClick(object sender, EventArgs e)
    {
        Application.Exit();
    }
}

public class Program
{
    [STAThread]
    public static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.Run(new TrayApplicationContext());
    }
}
```

Will render this:
![image](https://github.com/dotnet/winforms/assets/756703/8d24b255-ed4e-4a05-b2bf-741f752de2a9)

Instead of something like this:

![image](https://github.com/dotnet/winforms/assets/756703/8017c648-f5d7-43e5-b9c1-148882561a3e)

**Comment by merriemcgaw** [comment] 2024-01-23 19:29
@robertmuehsig thanks for filing this! The issues you noted are in fact covered by the issues already filed. I'm going to close this as a duplicate of #2543 but this issue will serve to remind us that we need to make sure to test the experience in the system tray.

**Closed by merriemcgaw** 2024-01-23 19:29 UTC
Labels: area-Theming, untriaged
