### ISSUE TITLE
List of tests with [Skip] attribute

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#6690] opened 2022-02-14 10:53 UTC
This is a global issue for tracking flaky tests for different controls, that need to be skipped.

* .NET Core Version: 7.0

**Problem description:**
Some tests fail sometimes and block successful fixes deployment:
- [x] #6597
- [ ] #6609
- [ ] #6610
- [ ] #6635
- [ ] #6654
- [ ] #6714
- [ ] #6729
- [ ] #7297 
- [ ] #7407

**Expected behavior:**
- All successful PRs pass CI build correctly

**Comment by vladimir-krestov** [comment] 2022-02-14 11:00
FYI: @dreddy-work, @RussKie

**Comment by dmitrii-drobotov** [comment] 2022-04-08 12:02
@vladimir-krestov 
* I think we can add https://github.com/dotnet/winforms/issues/6739 and https://github.com/dotnet/winforms/issues/6926 as separate items to the list in issue's description. They're mentioned in #6597 but these 2 are failing not only on arm64 as shown in their description.
* https://github.com/dotnet/winforms/issues/6730 is missing from the list.

**Comment by dreddy-work** [comment] 2023-02-09 21:03
Closing as dupe of #8607

**Closed by dreddy-work** 2023-02-09 21:03 UTC
Labels: test-bug, Epic
