### ISSUE TITLE
bug: listview column click exception

### ISSUE THREAD

**Issue by the-namelessone** [dotnet/winforms#4306] opened 2020-12-01 16:09 UTC
* .NET Core Version: 
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

[listviewbug.zip](https://github.com/dotnet/winforms/files/5623842/listviewbug.zip)

In .NET 5.0 version see above and Visual Studio 16.8.2 the attached example program crashes and gives exception when clicking a column header. Find all source code in the zip file.

The exceptions that are thrown (randomly the one or the other):

System.NullReferenceException: 'Object reference not set to an instance of an object.'

System.ExecutionEngineException

Those exceptions are .NET 5.0 exceptions and don't occur in  .NET Framework 4.8!

**Expected behavior:**

This code works without exception in .NET Framework 4.8

greetings
The c0demast3r

**Comment by Zheng-Li01** [comment] 2020-12-02 03:14
Repro the issue with the project provided by customer.([listviewbug.zip](https://github.com/dotnet/winforms/files/5626746/listviewbug.zip))
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/100823584-6d151d00-348f-11eb-93aa-b57d6a4cdf56.gif)

**Comment by Olina-Zhang** [comment] 2020-12-02 06:28
Verified this issue in .Net SDK 5.0.101-servicing.20601.5 build, this issue cannot repro. Click ListView columns, no exception now.
![ListViewSort](https://user-images.githubusercontent.com/26474449/100836671-a7d87e80-34aa-11eb-985e-07acae7da555.gif)

**Comment by RussKie** [comment] 2020-12-02 07:19
Thank you @Olina-Zhang.

Presume the issue duplicate of #4264, and fixed.

**Comment by RussKie** [comment] 2020-12-02 07:19
Duplicate of #4264

**Closed by RussKie** 2020-12-02 07:19 UTC
Labels: :boom: regression
