### ISSUE TITLE
Winform Designer generates confliting resource files on partial class

### ISSUE THREAD

**Issue by CyrilPaulus** [dotnet/winforms#11411] opened 2024-05-22 06:17 UTC
### Environment

Version 17.9.6

### .NET version

8.0.204

### Issue description

When editing a control split into a partial class, the designer generates a new resource file for each file contributing to the partial class. This makes compilation impossible, as the generated resource files conflict with each other.

### Steps to reproduce

1. Clone the repo https://github.com/CyrilPaulus/WinFormDesignerPartialResourceBug
2. Open the file Form1_partial.cs with the WinForm Designer.
3. The file Form1_partial.resx should have been generated.
4. Try to compile the project.

**Comment by LeafShi1** [comment] 2024-05-22 08:24
This issue reproduce in .Net6.0 and not reproduce in .NetFramework 4.8.1

**Comment by elachlan** [comment] 2024-05-22 10:01
@LeafShi1 you will probably need to search the designer repo and see if there is an existing issue.

**Comment by LeafShi1** [comment] 2024-05-24 09:31
> @LeafShi1 you will probably need to search the designer repo and see if there is an existing issue.

No existing issue found in designer repo

**Comment by elachlan** [comment] 2024-05-24 10:32
@LeafShi1 create a new designer issue and link it here I think.

CC: @Shyam-Gupta

**Comment by Tanya-Solyanik** [comment] 2024-05-24 17:41
This is a duplicate of https://github.com/microsoft/winforms-designer/issues/5900

**Comment by Tanya-Solyanik** [comment] 2024-10-24 17:57
This is tracked in the designer repo and visible externally as VS feedback - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2014398

**Closed by Tanya-Solyanik** 2024-10-24 17:57 UTC
Labels: :beetle: bug, tenet-compatibility, area-VSDesigner, tracking
