### ISSUE TITLE
UserControls with type parameters cannot be designed in .NET Core

### ISSUE THREAD

**Issue by janseris** [dotnet/winforms#11124] opened 2024-03-25 15:55 UTC
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.9.2

### .NET version

.NET 8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes it worked in .NET Framework

### Issue description

UserControls with type parameters cannot be designed in .NET Core

### Steps to reproduce

https://github.com/janseris/WinFormsGenericUserControlDesignerTest
And open designer for all UserControls in the NetCore projct

https://github.com/dotnet/winforms/assets/64279914/aa6d36a1-41dc-4707-bdbf-b1659608cc66

**Comment by elachlan** [comment] 2024-03-26 08:44
related to #3328 and #10368

Its on the teams backlog, but is unlikely to be done.

CC: @merriemcgaw

**Comment by janseris** [comment] 2024-03-26 09:28
@elachlan thanks for info.
btw this is not a suggestion or feature request but a bug because it works in Framework

**Comment by merriemcgaw** [comment] 2024-03-26 19:05
@janseris Thanks for reaching out about the issue. Knowing it is blocking your adoption of Core is a key piece of feedback we need in the prioritization process! @KlausLoeffelmann let's discuss this issue, and whether we can get it on a future release.

**Comment by Tanya-Solyanik** [comment] 2024-03-26 20:37
@Olina-Zhang  - Could you please test this on a recent build of the designer?

**Comment by KlausLoeffelmann** [comment] 2024-04-02 17:42
I (have to) (absolutely) agree.

**Comment by Olina-Zhang** [comment] 2024-04-03 06:12
Filed a designer issue: https://github.com/microsoft/winforms-designer/issues/5906.

**Comment by Tanya-Solyanik** [comment] 2024-10-25 23:17
A duplicate of https://github.com/microsoft/winforms-designer/issues/5906, closing, we'll update this issue when we make progress on the internal issue.

**Closed by Tanya-Solyanik** 2024-10-25 23:17 UTC
Labels: tenet-compatibility, area-VSDesigner, tracking
