### ISSUE TITLE
Need for complete (OOP) custom control template (VB)

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#8219] opened 2022-11-17 16:47 UTC
### Environment

.Net 7

### .NET version

Everything Core

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Framework

### Issue description

When I create a new custom control (in VB and I assume C#) the code created is identical to Framework and nothing is created for the OOP parts. The template should include everything necessary to the OOP designer.

### Steps to reproduce

N/A

**Comment by merriemcgaw** [comment] 2022-11-17 23:58
@paul1956 thanks for bringing this up. @KlausLoeffelmann and I are editing a blog post and new "beta" templates for exactly this purpose. Both for VB and C#. This blog post will run through some of the most common scenarios with varying degrees of complexity. We'll have samples and a detailed readme.md in a repo that will serve as our first round of detailed documentation for the new process.

I recognize we've said this before and not been able to deliver something in a timely manner, and for that I apologize. We have the beta templates tested and ready now in both languages and we've got the samples repo waiting. The main thing that's left is the final edits of the post by me and the blogs team. We're off next week, but I expect it within the month of December.

**Comment by KlausLoeffelmann** [comment] 2022-11-18 00:09
> but I expect it within the month of December.

Yeah, the templates are ready for the first go, both for VB and C#, and we have planned to open up the new Repo hosting the templates and samples in the 2nd week of December (first week is only a couple of days I think). Send me PM if you want to start testing earlier.

**Comment by paul1956** [comment] 2022-11-18 00:24
I am out of the country until January 5th with very little internet access so I can wait.

Not sure if the is separate or related. I have a custom ToolStrip control and the designer does not list it as an option but does list custom DataGridViewColumn types.

**Comment by KlausLoeffelmann** [comment] 2022-11-18 00:33
> I have a custom ToolStrip control and the designer does not list it as an option but does list custom DataGridViewColumn types.

Happy to take a look when you've returned in the new year!

**Comment by paul1956** [comment] 2022-11-18 02:09
@KlausLoeffelmann 
OK both controls are on NuGet and open source on GitHub. 

https://github.com/paul1956/ToolStripComboBoxEx
Doesn't show up in ToolBox  (I think as expected) or Designer where it should be a ToolStrip option

https://github.com/paul1956/DataGridViewDisableButtonColumnEx
Works as mostly expected (doesn't show up in ToolBox)  but does show up as a Column I can add to a DataGridView except the new Public Enabled Property does not show up in Designer.

Both controls come from examples in Microsoft Documentation for Framework 4.8.
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-wrap-a-windows-forms-control-with-toolstripcontrolhost?view=netframeworkdesktop-4.8
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/disable-buttons-in-a-button-column-in-the-datagrid?view=netframeworkdesktop-4.8

**Comment by paul1956** [comment] 2023-01-18 16:40
> > I have a custom ToolStrip control and the designer does not list it as an option but does list custom DataGridViewColumn types.
> 
> 
> 
> Happy to take a look when you've returned in the new year!

I am back in US if you have something I can start with I am working on 2 custom controls derived from ComboBox using KnownColor and custom painting both crash latest Preview Designer.

**Comment by kirsan31** [comment] 2023-01-21 11:28
@paul1956 
While @KlausLoeffelmann is busy...

Most of your questions can be answered by these:
1. Blog post: https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/
2. This repo (see issue s too): https://github.com/microsoft/winforms-designer-extensibility
3. [Chart](https://github.com/kirsan31/winforms-datavisualization) repo for more easy examples.

Keep in mind that 1. and 2. are very overcomplicated.  So watch 3. and ask questions...

**Comment by KlausLoeffelmann** [comment] 2023-01-21 16:43
> and templates are not working.

Please everyone check, if this can be reproduced anywhere else. I just checked...

https://github.com/microsoft/winforms-designer-extensibility/issues/8#issuecomment-1399285554

...and it's working fine for all of the versions for me.
So, if this issue repros anywhere else, we need to get to the root cause of this.

Thanks,

Klaus

**Comment by kirsan31** [comment] 2023-01-21 21:05
> Please everyone check, if this can be reproduced anywhere else. I just checked...

In 17.4.4 all work fine again.

**Comment by paul1956** [comment] 2023-01-23 02:26
I read the Blog, do I need to Clone Repo and create my own templates or will they be included in a Version 17.5.0 Preview

**Comment by KlausLoeffelmann** [comment] 2023-02-22 01:41
For the moment, you need to clone the repo and build the templates. That will install them, and you can use them in VS.

**Comment by KlausLoeffelmann** [comment] 2023-02-22 02:45
I am closing this for now.

**Closed by KlausLoeffelmann** 2023-02-22 02:45 UTC
Labels: area: VS designer

**Comment by paul1956** [comment] 2023-02-26 10:04
@KlausLoeffelmann I found instructions to build repo and did but don't see anything about building templates or where I find them. Where would I find that information?

**Comment by kirsan31** [comment] 2023-02-26 10:37
> @KlausLoeffelmann I found instructions to build repo and did but don't see anything about building templates or where I find them. Where would I find that information?

https://github.com/dotnet/winforms/issues/8219#issuecomment-1399233095

Punkt one.

**Comment by KlausLoeffelmann** [comment] 2023-02-27 17:20
Building installs them.

Is "Punkt" German?

**Comment by kirsan31** [comment] 2023-02-27 17:26
> Building installs them.
> 
> Is "Punkt" German?

Sorry no - corrected lol 😳

**Comment by RussKie** [comment] 2023-03-01 09:33
> 
> Is "Punkt" German?

Isn't it? 😄 🍿
