### ISSUE TITLE
Screen Resolutions issue - UI issue of responsiveness with screen resolution (125%, 150%)

### ISSUE THREAD

**Issue by shishiraltysys** [dotnet/winforms#10382] opened 2023-11-27 08:18 UTC
### .NET version

.Net 7

### Did it work in .NET Framework?

Not tested/verified

### Issue description

UI breaking, It's working fine with 100 % resolution, but not with 125%, and 150
![image](https://github.com/dotnet/winforms/assets/137883104/c39685f5-282a-4d20-9ddd-2b5fa17cb49a)
% resolution. 

### Steps to reproduce

These are UI issues:
First, we open application in 100% resolution and it's working fine, once we go and change resolution 100 to 125% UI distorted. Could you please let me know how we will support responsive UI in any size of resolution in windows forms.

**Comment by elachlan** [comment] 2023-11-27 11:24
@shishiraltysys can you provide a sample application? Also have you tried .NET 8?

**Comment by elachlan** [comment] 2023-11-27 11:27
@Olina-Zhang could your team please test this?

**Comment by merriemcgaw** [comment] 2023-11-27 19:59
@shishiraltysys What type of DPI Awareness setting are you using? We default to System Aware, and you shouldn't be having a problem there. But if you are trying Per Monitor v2 we are still working out the kinks in how we respond with the many types of layouts.

The best way we can help you is if you have a small repro app that demonstrates the problem. @Olina-Zhang can test that sample and we can find out if this is a regression in 7, fixed in 8, or simply something that has been this way all along.

**Comment by Philip-Wang01** [comment] 2023-12-08 08:25
@shishiraltysys thank you for the additional information, but your video seems to provide the wrong link, so we can only test it against the project you provided. Please feel free to correct me if I have misunderstood or missed anything.

@elachlan the customer is using `SystemAware` mode, using `PerMonitorV2` mode does not solve the problem. The custom checkbox control has problems scaling on .NET 6.0 - 8.0 but works fine on the latest .NET 9.0(9.0.100-alpha.1.23607.4).

![image](https://github.com/dotnet/winforms/assets/86937911/5012acd2-6b60-45ce-b2b8-38265bed6783)

**Comment by merriemcgaw** [comment] 2023-12-09 00:22
@Philip-Wang01 Just want to make sure I understand. Does PMv2 or SystemAware work as expected in .NET 9? @JeremyKuhne we made the anchoring fix opt-out by default for .NET 8 but I do have to wonder if that was only done in a release branch and didn't make it to 9. Thoughts?

**Comment by Philip-Wang01** [comment] 2023-12-11 02:15
@merriemcgaw Yes, it works as expected on .NET 9.0 in both `SystemAware` mode and `PerMonitorV2` mode.

**Comment by merriemcgaw** [comment] 2023-12-12 02:52
@JeremyKuhne, @lonitra, @KlausLoeffelmann This looks like the change to keep the anchoring HDPI work is only in .NET 8 GA.

**Comment by shishiraltysys** [comment] 2023-12-12 07:30
@Philip-Wang01 Thank you for your response. Yeah, I guess I put the wrong file in there, and the video connection is broken. However, I note that you are able to reproduce the issue on.net 7. As you mentioned, it only works on .Net 9, however it is not yet online. And, because we intend to upgrade from .Net 7 to.Net 8, rather than .Net 9, could you help resolve this issue in .Net 8 if possible?

**Comment by Philip-Wang01** [comment] 2023-12-12 08:27
> And, because we intend to upgrade from .Net 7 to.Net 8, rather than .Net 9, could you help resolve this issue in .Net 8 if possible?

@merriemcgaw Could you please take the time to look at this?

**Comment by merriemcgaw** [comment] 2023-12-13 02:44
@Philip-Wang01 can you check if .NET 8 works as expected when you set  ` "System.Windows.Forms.AnchorLayoutV2": true` in the runtimeconfig.json? That might solve @shishiraltysys issues for now. I can't say that this won't uncover other regressions in the sample or other code, which is why we have that as an opt-in feature in .NET 8. It appears to be on by default in .NET 9, and we may end up changing some things for .NET 10, but it's worth testing out.

**Comment by Philip-Wang01** [comment] 2023-12-13 03:20
@merriemcgaw Thank you very much for your help, .NET 8.0 works as expected.
@shishiraltysys You can try this feature on .NET 8.0, hope it helps!

https://github.com/dotnet/winforms/assets/86937911/407f6555-bd6e-4ce0-a88e-28bb89231e80

**Comment by merriemcgaw** [comment] 2023-12-14 00:47
@LeafShi1 can you make sure this PR is also in .NET 9 (to make the anchoring opt-in permanently) I think you just need to revert #9942 in .NET 9

**Comment by LeafShi1** [comment] 2023-12-14 02:09
> @LeafShi1 can you make sure this PR is also in .NET 9 (to make the anchoring opt-in permanently) I think you just need to revert #9942 in .NET 9

Will do it today.

**Comment by LeafShi1** [comment] 2023-12-14 06:09
> > @LeafShi1 can you make sure this PR is also in .NET 9 (to make the anchoring opt-in permanently) I think you just need to revert #9942 in .NET 9
> 
> Will do it today. But the #9942 only contained in .Net 8, so we just need to revert it on .Net 8. Right? In addition, this issue only reproduce in Win10 and work well in Win11.

**Comment by Tanya-Solyanik** [comment] 2023-12-15 01:07
@LeafShi1  - this is another way around actually. We want to port https://github.com/dotnet/winforms/pull/9942 to main.

**Comment by LeafShi1** [comment] 2023-12-15 01:55
> @LeafShi1 - this is another way around actually. We want to port #9942 to main.
Yes, I submitted a another PR #10484 for it, in that case the switch `System.Windows.Forms.AnchorLayoutV2` will be disabled by default, do we want to do that?

**Comment by LeafShi1** [comment] 2023-12-18 02:32
@shishiraltysys Since the layout work is still in progress, so the best workaround to the current problem is to setting `"System.Windows.Forms.AnchorLayoutV2": true ` in the runtimeconfig.json

**Closed** 2023-12-18 02:33 UTC
Labels: :construction: work in progress, area-HDPI

**Comment by Nora-Zhou01** [comment] 2023-12-21 03:03
Verified this on .NET 9.0.100-alpha.1.23620.7, issue was fixed. Set "System.Windows.Forms.AnchorLayoutV2" in runtimeconfig.json: true, and the UI works normally at 100%, 125%, and 150%.

https://github.com/dotnet/winforms/assets/104609169/ed87b0a4-db39-44c1-a0e0-23d68edee2fa
