### ISSUE TITLE
When text is saved and opened next time, center alignment fails and right alignment fails

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#7384] opened 2022-07-07 07:18 UTC
### .NET version

.NET Framework 4.5.2

### Did it work in .NET Framework?

Yes

### Issue description

```C#
// On form load event.
rtbLeftHeaderCaption.SelectionAlignment = HorizontalAlignment.Left;
rtbCenterHeaderCaption.SelectionAlignment = HorizontalAlignment.Center;
rtbRightHeaderCaption.SelectionAlignment = HorizontalAlignment.Right;
```

### Steps to reproduce

None

**Comment by merriemcgaw** [comment] 2022-07-12 23:33
Thanks for filing this issue. We could use more information about your scenario and what is being impacted.

**Comment by merriemcgaw** [comment] 2022-07-15 17:55
@kelicto I'd like to understand more about your specific scenario, and whether you're blocked (and whether this is a regression for you). This will enable me to prioritize accordingly. Though I do note that you are referring to .NET Framework, and there is a different process to getting bugs fixed there because it is part of the Windows OS we're concerned about unintended regressions. Only high priority bugs that are blocking key scenarios are considered for servicing in .NET Framework. That said, if we understand more about your scenario, I could decide how to prioritize the bug in .NET 7/8.

**Comment by kelicto** [comment] 2022-07-22 11:27
Sorry about that, this task queue is lagging behind in priority, it's not hard to reproduce, I'll provide everything I need when I'm done taking time.

**Comment by merriemcgaw** [comment] 2022-07-22 20:33
@kelicto - no worries at all. If you're able to help us with a scenario and repro, we will make an effort to see it's fixed in .NET 7. Note however that we aren't able to commit to a fix in the .NET Framework given the super high servicing bar for it.

**Comment by elachlan** [comment] 2023-11-03 23:32
closing this issue as the user account has been deleted and we required more information.

**Closed by elachlan** 2023-11-03 23:32 UTC
