### ISSUE TITLE
Intermittent fatal exception opening file dialog

### ISSUE THREAD

**Issue by blusteryDay** [dotnet/winforms#12305] opened 2024-10-08 16:55 UTC
### Description

One of our testers is seeing a very intermittent fatal exception attempting to open a file dialog to browse the file system.  The application simply terminates, bypassing our main exception handler.  Restarting the application and opening the file dialog in the same way with the same initial folder and filter is successful.  This exception has occurred 3 times in hundreds of attempts over two weeks of testing.

### Reproduction Steps

Various places in the application attempt to open a file dialog, which causes a very intermittent exception.

### Expected behavior

No exception, file dialog is shown

### Actual behavior

Unhandled exception occurs and application terminates.

Call stacks for 8.0.6 and 8.0.8

CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFD2B1C048E
Stack:
   at Windows.Win32.UI.Shell.IFileDialog.Show(Windows.Win32.Foundation.HWND)
   at System.Windows.Forms.FileDialog.TryRunDialogVista(Windows.Win32.Foundation.HWND, Boolean ByRef)
   at System.Windows.Forms.FileDialog.RunDialog(IntPtr)
   at System.Windows.Forms.CommonDialog.ShowDialog(System.Windows.Forms.IWin32Window)
   
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFA649AE46E
Stack:
   at Windows.Win32.UI.Shell.IFileDialog.Show(Windows.Win32.Foundation.HWND)
   at System.Windows.Forms.FileDialog.TryRunDialogVista(Windows.Win32.Foundation.HWND, Boolean ByRef)
   at System.Windows.Forms.FileDialog.RunDialog(IntPtr)
   at System.Windows.Forms.CommonDialog.ShowDialog(System.Windows.Forms.IWin32Window)

### Regression?

We have not seen this prior to updating to .NET 8, although it is so random that we can't confirm it does not exist prior to that.

### Configuration

Windows 10 Enterprise 22H2, build 19045.4894;
Occurred with .NET 8.0.6 and 8.0.8
Desktop is in dark mode if that's relevant.

**Comment by merriemcgaw** [comment] 2024-10-16 22:45
@Olina-Zhang could your teams try to create a test app and see if we can reproduce this in-house? If we can, let's check whether frequency changes with .NET 9 or with different versions of Windows. Thanks!

**Comment by Olina-Zhang** [comment] 2024-10-21 08:01
@merriemcgaw We tried many times on Windows 10 Enterprise 22H2, but it didn't reproduce.

**Comment by lonitra** [comment] 2024-10-25 18:39
Based off of the exception code, it looks like we are dealing with an access violation. https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-imodalwindow-show indicates that the passed in parameter can be null, so if we are passing null in this scenario, this should not be an issue. It seems like the dialog itself has somehow gotten into a corrupt state, however on a cursory look there is nothing that stands out that we are doing on our end that would cause this as our set up code for the dialog currently does not return `HRESULT` meaning exception would have been thrown from [OnBeforeVistaDialog](https://github.com/dotnet/winforms/blob/80cd75fea60a75de883cd0216427f1e49eb737ed/src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FileDialog.Vista.cs#L50) or [TryRunDialogVista](https://github.com/dotnet/winforms/blob/80cd75fea60a75de883cd0216427f1e49eb737ed/src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FileDialog.Vista.cs#L23) if an error had occurred while setting up -- not within `show()`.

**Comment by merriemcgaw** [comment] 2024-10-31 18:48
Since there's nothing on our side we can see, and there isn't a consistent repro we have to close this issue. If there are more consistent repros in the future we can reopen to investigate futher.

**Closed by merriemcgaw** 2024-10-31 18:48 UTC
Labels: untriaged
