### ISSUE TITLE
Setting the Maximum value on a Trackbar to a very large number results in excessive memory usage

### ISSUE THREAD

**Issue by NarryG** [dotnet/winforms#329] opened 2019-01-17 06:57 UTC
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**  
Setting the MaxValue on the Trackbar control to a very high number results in excessive ram usage (in the gigabytes for a very large number).  

This appears to be because on initialization of the underlying windows control, the maximum is set before the tick mark frequency, resulting in it initializing excessive amounts of tickmarks, although I do not have the build configuration to verify this theory myself at this time as if I did, I would just verify and submit this as a PR.
https://github.com/dotnet/winforms/blob/01eef03d8e0a6630076716b6cb08ed0a9def611a/src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs#L893-L894

**Actual behavior:** 
Excessive ram is used (multiple gigabytes if compiled in x64)

**Expected behavior:**
A reasonable amount of ram is used (assuming you set tickmarks to a reasonable number).

**Minimal repro:**  
Within a form
```
TrackBar tb = new TrackBar();
tb.TickFrequency = 0; //Ensure no tickmarks should be drawn
tb.Maximum = 1000000000;
this.Controls.Add(tb);
```

**Comment by KlausLoeffelmann** [comment] 2019-01-20 11:11
@Olina-Zhang, could you take a look if this is also an issue in 4.8?

**Comment by Olina-Zhang** [comment] 2019-01-21 05:33
@KlausLoeffelmann, this issue cannot repro in .Net 4.8, and repro in .Net Core 3.0. See following comparison of picture:
![compare](https://user-images.githubusercontent.com/26474449/51454713-f176b080-1cfa-11e9-8a58-7fe9d4b42787.png)

**Comment by NarryG** [comment] 2019-01-21 05:51
For reference, the version of the Framework I experienced this on was 4.7.2.  I just retargeted the program to 4.8 for testing and I am still experiencing it, so I'm not entirely sure why Olina was unable to repro it on 4.8
![image](https://user-images.githubusercontent.com/3047793/51455214-8aff8b80-1d16-11e9-930b-1ed4aad7664b.png)

**Comment by JeremyKuhne** [comment] 2020-08-10 23:58
We should be able to just flip the messages here which should be an easy fix.

**Comment by T-rvw** [comment] 2022-02-21 15:03
But still not fixed? It spent me 5 hours addressing the same issue.

**Comment by RussKie** [comment] 2022-02-21 22:01
You're welcome to send a PR fix.

**Comment by T-rvw** [comment] 2022-03-02 06:51
Yesterday, I got some time to browse the implementation and found that drawing so many TickLines caused the large memory usage. We have two ways to avoid this issue:
1. Don't draw TickLine : `this.TickStyle = TickStyle.None;`
2. Set `TickFrequency` to draw a reasonable number of TickLine.

Back to the "bug“ itself, I think it just doesn't defend wrong user input. We usually don't care about TickLine while modifying TrackBar's min value and max value. So in my opinion, `TrackBar` can limit the max number of TickLine to the pixels of bar's width in horizontal mode or bar's height in vertical mode.

**Comment by RussKie** [comment] 2022-03-03 05:40
Sounds good 👍

**Comment by conorgee** [comment] 2022-11-04 11:56
After testing the TrackBar tickFrequency to limit the max number of Ticks to the pixels of bar's width in horizontal mode or bar's height in vertical mode. I found the memory consumption stays the same the tickStyle set to none was the only fix I could find to avoid the issue.

**Comment by elachlan** [comment] 2022-11-09 21:35
Just to clarify, there was no improvement in memory usage by changing the `tickFrequency`? Do we use `TBS_AUTOTICKS`?

From `TBM_SETTICFREQ` docs:
> The trackbar must have the [TBS_AUTOTICKS](https://learn.microsoft.com/en-us/windows/win32/controls/trackbar-control-styles) style to use this message.

https://learn.microsoft.com/en-us/windows/win32/controls/tbm-setticfreq

**Comment by conorgee** [comment] 2022-11-10 22:45
Yes , TBS_AUTOTICKS is being used
 
![autoticks](https://user-images.githubusercontent.com/57994682/201217140-d4f09441-dd2b-4d3b-b9a2-4541527da8be.PNG)

I first of all have distinctly found two separate issues while experimenting. The tick frequency solves the issue of the laggy trackbar. The tickstyle set to none fixes the memory consumption issue. I created the method setTickFrequency as a fix for this issue but I eventually figured out It does not solve the memory consumption. However I figured out that the trackbar loads quicker and is more responsive. I checked if setting an arbitrary value of ticks such as 10, automatically sped up performance of the trackbar, which it did. Then I created a method for this. Firstly I created a block diagram for the algorithm. 
 
![image](https://user-images.githubusercontent.com/57994682/201221047-bb247306-9705-42c8-8aed-a9e2908c3918.png)

        `private void SetTickFrequency()
        {
            // check if the value of the max is greater then the taskbar size
            // if so then we divide the value by size and only that many ticks to be drawn on the screen

            if (TickStyle == System.Windows.Forms.TickStyle.None)
            {
                return;
            }

            int tickFrequency = _tickFrequency;
            int trackbarSize;
            uint maxValue = (uint)(_minimum + _maximum);
            if (Orientation == Orientation.Horizontal)
            {
                trackbarSize = Size.Width;
            }
            else
            {
                trackbarSize = Size.Height;
            }

            if (maxValue > trackbarSize && trackbarSize != 0)
            {
              tickFrequency = (int)(maxValue / trackbarSize);
            }

             PInvoke.SendMessage(this, (User32.WM)PInvoke.TBM_SETTICFREQ, (WPARAM)tickFrequency);
        }`

This works because to instead of loading all the ticks at runtime the trackbar is constrained to the physical parameters of the trackbar. E.g. max is 2500 but trackbar is 250 pixels we then divide the value of max by the trackbar size.  I believe the issue with memory consumption is with the windows message tickstyle. Even after using this fix it still uses excessive RAM for a large maximum value on the trackbar. I don’t believe the issue can be fixed without changing tickstyle.

![image](https://user-images.githubusercontent.com/57994682/201221475-52a3c0a2-6b64-4ea6-811d-ae48591d5a13.png)
![image](https://user-images.githubusercontent.com/57994682/201221578-29389a0d-c2b0-4428-bd1f-05169b99fe85.png)

**Comment by elachlan** [comment] 2022-11-14 01:50
@JeremyKuhne putting the Frequency before the maximum call doesn't fix the problem. The call to set the maximum value is what ends up triggering the change in memory usage.

It looks like for each integer in the range min to max its taking ~4bytes of memory.

@conorgee has a PR that was trying to fix the issue at: #8060

**Comment by elachlan** [comment] 2022-11-14 03:00
@conorgee An alternative is to maybe manually specify the tick marks using `tbm-settic`:
https://learn.microsoft.com/en-us/windows/win32/controls/tbm-settic

My testing showed that the memory usage didn't go above 35mb for any maximum value. Although it was slow when drawing a tick mark per int in really large ranges.

Another smart optimisation would be to only draw tick marks when there is a gap between them. So if the width is 350, then you would create 350/2 tick marks. thus leaving a single pixel gap between each one.

Obviously it would be nicer for the `TBS_AUTOTICKS` style to be fixed so that whatever its doing doesn't use so much memory.

```csharp
private void SetTickFrequency()
{
    // check if the value of the max is greater then the taskbar size
    // if so then we divide the value by size and only that many ticks to be drawn on the screen

    if (TickStyle == System.Windows.Forms.TickStyle.None)
    {
        return;
    }

    int tickFrequency = _tickFrequency;
    int trackbarSize = (Orientation == Orientation.Horizontal ? Size.Width : Size.Height)/2;
    //int trackbarSize = 100;
    uint maxValue = (uint)(_minimum + _maximum);

    if (maxValue > trackbarSize && trackbarSize != 0)
    {
        tickFrequency = ((int)(maxValue / trackbarSize));
    }

    PInvoke.SendMessage(this, (User32.WM)PInvoke.TBM_CLEARTICS, (WPARAM)1, (LPARAM)0);
    for (int i = tickFrequency; i < maxValue; i += tickFrequency)
    {
        PInvoke.SendMessage(this, (User32.WM)PInvoke.TBM_SETTIC,lParam: (LPARAM)i);
    }
}
```

You also have to remove the `TBS_AUTOTICKS` in `CreateParams`.

@RussKie Is this solution okay? Or would you rather have the winapi team fix their implementation?

**Comment by RussKie** [comment] 2022-11-14 04:01
Thank you @elachlan for the suggestion. I think it is pretty safe to assume that the Windows team won't be fixing any non-security related issues in Common Controls library and it's up to us to try to fix or find suitable workarounds for underlying issues. The bar is obviously high, we can't break any existing customers. The good news is that we can put the changes under a [feature flag](https://github.com/dotnet/winforms/blob/main/docs/runtime-configuration.md#design-proposal), so that developers will be able to opt-out and retain the old behaviour, if desired.

**Comment by RussKie** [comment] 2022-11-14 04:08
The suggestion is pretty interesting. Just to confirm I understand it correctly - if a number of items (i.e., `_maximum - _minimum`) is greater than `trackBar1.Width` (or `trackBar1.Height for the vertical orientation) then disable `TBS_AUTOTICKS` and render ticks manually for every second pixel. Is this correct?
The only problem I see here is that we could send ~2K messages on a 4K screen...

@JeremyKuhne do you have any thoughts?

**Comment by elachlan** [comment] 2022-11-14 04:22
I'd suggest disabling `TBS_AUTOTICKS` all together. It shouldn't create more ticks than the width/height of the control depending on orientation. 

The issue I found was that you just get a grey bar if the number of ticks > width. Which makes it functionally redundant. Because the user won't be able to see the tick marks individually. 

The other thing to note is that width/height are `typically measured in pixels`. I am unsure how size works in practice with winform controls and if it always means `1 unit = 1 pixel`.

I guess we could change the code so that this is the "Max" number of ticks. Then if the `tickFrequency` was higher, we use that value because there would be less ticks.

**Comment by conorgee** [comment] 2022-11-14 15:54
@elachlan The Trackbar doesnt seem to repaint the correct amount of ticks after I used your solution. If I set the the tickstyle to none then back to tickstyle.BottomRight they appear. Maybe we need to tell the trackbar to repaint after setting the ticks.

![image](https://user-images.githubusercontent.com/57994682/201704725-007440bb-b464-4f4f-957f-59d5e74f7205.png)
![image](https://user-images.githubusercontent.com/57994682/201705194-b8e7c1ab-6449-460a-81d9-f871749362c7.png)

**Comment by elachlan** [comment] 2022-11-14 20:48
@JeremyKuhne there is [TrackbarRenderer](https://github.com/dotnet/winforms/blob/83651704a258b6be318659f785d31d42b1b16fef/src/System.Windows.Forms/src/System/Windows/Forms/TrackBarRenderer.cs). That is where I got my idea to draw each tick, which then lead to me finding `TBM_SETTIC`

**Comment by elachlan** [comment] 2022-11-14 20:52
@conorgee, could you update your PR to use the manual method? I'll review it and let you know where the issue is. I had a similar issue and I just had to make sure `SetTickFrequency` was called after setting the min/max values. Because the min/max values are used to validate the `TBM_SETTIC` message.

**Comment by RussKie** [comment] 2022-11-14 22:59
> Maybe we need to tell the trackbar to repaint after setting the ticks.

If required, this can be done with `Invalidate()` call.

**Comment by RussKie** [comment] 2022-11-14 23:08
> I'd suggest disabling `TBS_AUTOTICKS` all together. It shouldn't create more ticks than the width/height of the control depending on orientation.

I suppose a hybrid solution could be an option. That is, if the range (max - min) is less or equal to the number of pixels the trackbar is drawn in - then use `TBS_AUTOTICKS`. Else, fallback to manual ticks calculation/rendering.
This is worth experimenting with, as @JeremyKuhne said, and depending on complexity of the result we could consider taking a fix in.



> Updating the docs is much easier and lower maintenance, and probably addresses the situation though.

The docs are located at https://learn.microsoft.com/dotnet/api/system.windows.forms.trackbar. The edit button (in the top right) will take you here: https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows.Forms/TrackBar.xml.

**Comment by RussKie** [comment] 2022-11-15 07:14
> @JeremyKuhne Jeremy Kuhne FTE there is [TrackbarRenderer](https://github.com/dotnet/winforms/blob/83651704a258b6be318659f785d31d42b1b16fef/src/System.Windows.Forms/src/System/Windows/Forms/TrackBarRenderer.cs). That is where I got my idea to draw each tick, which then lead to me finding `TBM_SETTIC`

Nice! `TrackBarRenderer` isn't used directly, but it can be used to render a custom trackbar control, we have a [sample](https://learn.microsoft.com/dotnet/api/system.windows.forms.trackbarrenderer)https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.trackbarrenderer?view=windowsdesktop-7.0 in the docs.
Which gives yet another idea to explore - if number of ticks would exceed number of available (to control) pixels, we can disable ticks and render those manually using `TrackBarRenderer` in `OnPaint`....

**Comment by conorgee** [comment] 2022-11-15 19:33
> I suppose a hybrid solution could be an option. That is, if the range (max - min) is less or equal to the number of pixels the trackbar is drawn in - then use `TBS_AUTOTICKS`. Else, fallback to manual ticks calculation/rendering. This is worth experimenting with, as @JeremyKuhne said, and depending on complexity of the result we could consider taking a fix in.
I made a commit to the pull request that implements this boolean for autoticks if range is greater then the number of pixels the trackbar is drawn in.

**Comment by conorgee** [comment] 2022-11-16 00:08
https://github.com/conorgee/winforms/blob/8425ccde09b0e1ce0a6191777769abd39b16794d/src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs#L834-L859 

@RussKie I cant figure out a way of telling tickstyle to refresh tickstyle after sutoticks boolean is set to null , 
tried using recreatehandle but that was causing issues as tickfrequency is called when recreating handle so this wasnt effective as it created an infinite loop. any ideas ?

**Comment by RussKie** [comment] 2022-11-18 05:31
I found a bug :)

![image](https://user-images.githubusercontent.com/4403806/202627884-73c89bdd-0ba9-4713-adb4-6dfb73b30b87.png)

**Closed** 2022-12-27 19:24 UTC
Labels: :beetle: bug, help wanted, :construction: work in progress

**Comment by John-Qiao** [comment] 2023-01-06 03:24
Verified this issue on .NET latest build: 8.0.100-alpha.1.23055.16, issue was fixed that ram is used as same as .NET Framework 4.8.1.

.NET 8.0
![329-1](https://user-images.githubusercontent.com/45864985/210923745-576d024d-3f40-4f19-9276-03e015457caa.png)


.NET Framework 4.8.1
![329-2](https://user-images.githubusercontent.com/45864985/210923763-6963c943-e575-4874-b883-58868aa2be25.png)

**Comment by elachlan** [comment] 2023-01-06 03:39
Memory usage should be a lot less with .NET 8

**Comment by RussKie** [comment] 2023-01-09 01:19
@John-Qiao: unfortunately, from your screenshot it's not clear how you tested the fix. The original bug was only surfacing when the set range was exceptionally large. @conorgee described various use case in which the issue was observed in https://github.com/dotnet/winforms/pull/8060#issue-1427221217.

**Comment by John-Qiao** [comment] 2023-01-09 06:26
@RussKie In my above test result, I tested the fix using the follow codes which copied from initial "Minimal repro:" in this issue.

Within a form

```
TrackBar tb = new TrackBar();
tb.TickFrequency = 0; //Ensure no tickmarks should be drawn
tb.Maximum = 1000000000;
this.Controls.Add(tb);
```

**Comment by RussKie** [comment] 2023-01-09 06:36
@John-Qiao @dreddy-work could this not work correctly because of https://github.com/dotnet/winforms/pull/8467?

**Comment by John-Qiao** [comment] 2023-01-09 06:40
@RussKie In my above test result, I tested the fix using the follow codes which copied from initial "Minimal repro:" in this issue.

Within a form
```
TrackBar tb = new TrackBar();
tb.TickFrequency = 0; //Ensure no tickmarks should be drawn
tb.Maximum = 1000000000;
this.Controls.Add(tb);
```
