### ISSUE TITLE
What does the default font size of WinForms depend on?

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#7057] opened 2022-04-20 10:58 UTC
### Environment

ALL

### .NET version

ALL .NET Framework Versions.

### Issue description

My colleagues their `form` font is 9 by default, my font is 8.25 in any case, causing the problem of unsatisfactory display effect.

What is the reason for this and how can I solve the problem of default font size setting? I think it's like some default setting switch of the OS.

![Uploading image.png…]()

### Steps to reproduce

Nothing.

### Diagnostics

```text
Nothing.
```

**Comment by kelicto** [comment] 2022-04-21 01:42
I want to change `System.Drawing.SystemFonts.DefaultFont`.

**Comment by kelicto** [comment] 2022-04-22 02:41
I did not make any interventional settings.

**Comment by dreddy-work** [comment] 2022-04-27 23:11
@kelicto , WinForms does not control the selection of DefaultFont based on OS locale. Linked runtime bug should be good to track a response on that. Meanwhile, If you like to keep your application with consistent Font, setting `Application.DefaultFont` is an alternative here.  Closing this issue as external.

**Closed by dreddy-work** 2022-04-27 23:11 UTC
Labels: area: VS designer

**Comment by kelicto** [comment] 2022-04-29 01:24
Not exactly true, the designer won't understand your intentions.

**Comment by kelicto** [comment] 2022-04-29 01:30
What is `Application.DefaultFont`? I don't find any useful code to solve my problem.  `WindowsFormsSettings.DefaultFont = new System.Drawing.Font("Arial", 12);` make sure ok on runtime, but not a designer.

**Comment by RussKie** [comment] 2022-04-29 03:23
If you're using third party libraries (such as DevExpress) please direct your queries to the authors of these libraries.

This repo contains the code for the Windows Forms SDK, and whilst the team maintaining this repo tries to provide assistance and guidance, we can't answer questions or debug applications. There are other more suited channels to seek information (such as [docs](https://docs.microsoft.com/)) and ask questions (such as [Discussions](https://github.com/dotnet/winforms/discussions), [Gitter](https://gitter.im/dotnet/corefx), [Discord](https://discord.com/channels/732297728826277939/799788915371278377), [StackOverflow](https://stackoverflow.com/), etc.).

We will look at customer issues with the Windows Forms applications, **if** those issues can be demonstrated to have been caused by the Windows Forms SDK. To that extent we have created several [issue templates](https://github.com/dotnet/winforms/issues/new/choose) which ask for necessary information for the team (and the community) to triage issues. Also, when you have an issue we'd expect you to debug it first and distill it to a small repro sample, that we then can investigate and (hopefully) fix.

Thank you for understanding.
