### ISSUE TITLE
Unnecessary duplication of filter pattern in System.Windows.Forms.FileDialog.Filter when not using wildcards

### ISSUE THREAD

**Issue by ThatCesarGon** [dotnet/winforms#10965] opened 2024-02-28 09:56 UTC
### .NET version

8.0.100

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Same issue is present in .NET 7.0

### Issue description

The [Filter](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.filter?view=windowsdesktop-8.0) property of the [System.Windows.Forms.FileDialog](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog?view=windowsdesktop-8.0&viewFallbackFrom=net-8.0) class is supposed to accept a pipe-separated string containing description/pattern pairs, e.g. "Text files (\*.txt)" / "\*.txt". Pairs are also separated by pipe characters. A typical value for Filter would be "Text files (\*.txt)|\*.txt|All files (\*.\*)|\*.\*".

At runtime, winforms uses this information to show items in the file dialog dropdown box so that the user can select a filter to apply. Using the sample filter string above, the dropdown displays as shown:

<img width="148" alt="image" src="https://github.com/dotnet/winforms/assets/131369062/3bd4e79d-092c-4eb8-8b3b-0d8980f9b06b">

As you can see, winforms shows each filter description for each line in the dropdown box.

Now, if the filter descriptions do not include the filter pattern in parenthesis, winforms adds it automatically for you. For example, if you set Filter to "Text files|\*.txt|All files|\*.\*", the dropdown displays exactly as above.

However, this fails when a filter pattern does not include wildcards (asterisks or question marks), but is made of just a file name. Consider the filter string "Databases (Database.db)|Database.db|All files (\*.\*)|\*.\*". This displays as follows:

<img width="166" alt="image" src="https://github.com/dotnet/winforms/assets/131369062/42d03752-9bf2-4d18-bf30-1370f682ad82">

As you can see, the "Database.db" filter pattern is appended to the first item despite the fact that it is already included in the description. This should not happen.

### Steps to reproduce

Create an instance of OpenFileDialog in code and then show it, as follows:

```
var dlg = new OpenFileDialog
{
    Filter = "Databases (Database.db)|Database.db|All files (*.*)|*.*"
};

dlg.ShowDialog();
```

Since the Filter string includes a pair with no wildcards in its pattern, winforms appends the pattern to the description, causing unnecessary and cumbersome duplication.

**Comment by Zheng-Li01** [comment] 2024-02-28 10:08
@ThatCesarGon , it's working well with you reproduce steps, see below reproduce GIF.

![10965](https://github.com/dotnet/winforms/assets/38325459/2a7248a1-af92-49fe-9837-ab44fbc26241)

**Comment by merriemcgaw** [comment] 2024-02-28 21:26
@ThatCesarGon can you help us understand the problem that you're seeing in your code? We're seeing what appears to be the right behavior.

**Comment by ThatCesarGon** [comment] 2024-02-29 02:04
@Zheng-Li01 @merriemcgaw Thanks for your responses. Please see below the issue as displayed on my computer:


https://github.com/dotnet/winforms/assets/131369062/b13b8413-a661-4a86-bab2-cf6a5c2d7590

**Comment by Zheng-Li01** [comment] 2024-02-29 02:25
@ThatCesarGon thanks for your response, just try it again found that the issue can reproduce **Windows 10 OS** on both  .NET and .NET Framework, cannot reproduce it on **Windows11 OS o**n both .NET and .NET Framework as below screenshot.
![image](https://github.com/dotnet/winforms/assets/38325459/79e14132-5b2f-4d13-a902-1006113db26c)


FYI: @merriemcgaw

**Comment by ThatCesarGon** [comment] 2024-02-29 21:10
Thanks, @Zheng-Li01. Is there anything else I can do about this issue?

**Comment by elachlan** [comment] 2024-03-01 01:05
@ThatCesarGon There isn't much you can do because its an external OS issue. @merriemcgaw might be able to forward it to the internal OS team, but I suspect it will not get fixed as it isn't a serious bug.

You can work around it by checking the OS version when setting the filter. That should unblock you.

**Comment by ThatCesarGon** [comment] 2024-03-01 07:02
Perfect, many thanks.

**Comment by merriemcgaw** [comment] 2024-03-05 19:49
Yay! @ThatCesarGon so glad that the workaround solved your issue. Given that hte latest versions of Windows are correct, I doubt that we'll see them make any changes in servicing Win10 for this particular issue. Since you're unblocked, I'm going to close this issue.

Special thanks to @Zheng-Li01 and his workaround 😄 !

**Closed by merriemcgaw** 2024-03-05 19:49 UTC
Labels: untriaged, external-OS-issue
