### ISSUE TITLE
Unable to add full public IntPtr parameter to a Control

### ISSUE THREAD

**Issue by Erdien** [dotnet/winforms#10246] opened 2023-11-08 02:42 UTC
### Environment

17.7.34031.279
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.7.4
and
17.5.33627.172
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.5

### .NET version

tested on .NET 7.0 and .NET 6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It is working on .NET Framework 4.7.2

### Issue description

After adding an User control, that implements a public parameter with getter and setter - you won't be able to add it to the form through Designer Editor. Instead - A dialog box appears with a message: ***The connection to the server has been lost***
![image](https://github.com/dotnet/winforms/assets/32906524/3ee1d822-daef-48e8-aa6d-b2bc9bd76a56)

You're still able to add the control through manual modification of the Form Designer File, but then - you won't be able to edit the form through Designer Editor.

### Steps to reproduce
1. On a WinForms Application - add new, or edit existing UserControl to the project.
2. Add to the UserControl's body these 2 lines of code:
```cs
IntPtr hwnd;
public IntPtr Hwnd { get => hwnd; set => hwnd = value; }
```
Keep in mind, that the parameter have to be public, and have to get both - a getter and a setter.
An example of the body of the UserControl may look as follows:
```cs
public partial class UserControl1 : UserControl
{
	private IntPtr hwnd;
	public IntPtr Hwnd { get => hwnd; set => hwnd = value; }
	public UserControl1()
	{
		InitializeComponent();
	}
}
```
3. After recompiling the project in a way, that the control appears on the Toolbox - Drag&Drop the UserControl on the Form's body.
4. Try to save the Form `Ctrl + S`. Now you reproduced the issue.

#### Alternatives
The following line of code will also generate the error:
```cs
public IntPtr HWnd { get => IntPtr.Zero; set => _ = value; }
```
But these lines of code will work properly:
```cs
private IntPtr hWnd;
public IntPtr HWndGet { get => hWnd;}
public IntPtr HWndSet { set => hWnd = value; }
```

#### Test Project
You may download attached project and check 4 cases, where every presented case (and additional case with non-public parameter) is available.
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/13285025/WinFormsApp1.zip)

### Diagnostics

```text
[20:12:22.005989] fail: StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__162.MoveNext()
                        --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
                        --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w Microsoft.DotNet.DesignTools.Client.DesignToolsClient.<SendRequestAsync>d__49`1.MoveNext()

                        Aby uzyskać informacje na temat rozwiązywania problemów z projektantem, zapoznaj się z przewodnikiem w https://aka.ms/winforms/designer/troubleshooting.
[20:12:22.125137] fail: Microsoft.DotNet.DesignTools.Client.DesignToolsClientException: Połączenie z serwerem zostało utracone.
                           w Microsoft.DotNet.DesignTools.Client.DesignToolsClient.<SendRequestAsync>d__49`1.MoveNext()
                        --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
                           w Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
                           w Microsoft.DotNet.DesignTools.Client.Proxies.ControlProxy.GetParent()
                           w Microsoft.DotNet.DesignTools.Client.Designers.ControlProxyDesigner.get_ParentComponent()
                           w Microsoft.DotNet.DesignTools.Client.Designers.ComponentProxyDesigner.System.ComponentModel.Design.ITreeDesigner.get_Parent()
                           w System.Drawing.Design.DesignerToolboxInfo.RecurseDesignerTree(IDesigner designer, Hashtable table)
                           w System.Drawing.Design.DesignerToolboxInfo.GetDesignerAttributes(IDesigner designer)
                           w System.Drawing.Design.DesignerToolboxInfo.Update()
                           w System.Drawing.Design.DesignerToolboxInfo.OnSelectionChanged(Object sender, EventArgs e)
                           w System.EventHandler.Invoke(Object sender, EventArgs e)
                           w Microsoft.VisualStudio.WinForms.DesignSurfaceService.DisconnectSession(Boolean forcibleDisconnection)
                           w Microsoft.VisualStudio.WinForms.VSDesignSurface.OnServerProcessExitedUnexpectedly()
                           w Microsoft.VisualStudio.WinForms.ProjectWatchers.ProjectWatcherService.ProjectWatcher.<>c__DisplayClass103_0.<<Client_ServerProcessExited>b__0>d.MoveNext()

                        Aby uzyskać informacje na temat rozwiązywania problemów z projektantem, zapoznaj się z przewodnikiem w https://aka.ms/winforms/designer/troubleshooting.
```

**Comment by elachlan** [comment] 2023-11-08 04:37
@Erdien what about
```csharp
private IntPtr _hWnd;
public IntPtr Hwnd { get => _hwnd; set => _hwnd = value; }
```

**Comment by Olina-Zhang** [comment] 2023-11-08 05:46
Related Winforms designer issue: https://github.com/microsoft/winforms-designer/issues/5377.

**Comment by Erdien** [comment] 2023-11-08 17:19
> @Erdien what about
> 
> ```cs
> private IntPtr _hWnd;
> public IntPtr Hwnd { get => _hwnd; set => _hwnd = value; }
> ```

Similiar error apears
```
[18:18:10.919510] fail: StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__162.MoveNext()
                        --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__151`1.MoveNext()
                        --- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
                           w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           w Microsoft.DotNet.DesignTools.Client.DesignToolsClient.<SendRequestAsync>d__49`1.MoveNext()

                        Aby uzyskać informacje na temat rozwiązywania problemów z projektantem, zapoznaj się z przewodnikiem w https://aka.ms/winforms/designer/troubleshooting.
[18:18:10.994514] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by AikawaKatsuyuki** [comment] 2024-08-08 02:46
Write the ReadOnly attribute.
It will no longer be possible to change it in the designer, but you can change it from the setter.
```
[ReadOnly(true)]
public IntPtr Hwnd { get => hwnd; set => hwnd = value; }
IntPtr hwnd;
```

**Comment by Tanya-Solyanik** [comment] 2024-10-24 23:27
tracking issue from the designer repo https://github.com/microsoft/winforms-designer/issues/5377

**Comment by Tanya-Solyanik** [comment] 2024-10-25 23:52
Closing this issue as a duplicate of an internal one, we'll update this issue when we make progress on the internal one.

**Closed by Tanya-Solyanik** 2024-10-25 23:52 UTC
Labels: area-VSDesigner, tracking
