### ISSUE TITLE
net 5 Cannot read resources that depend on serialization

### ISSUE THREAD

**Issue by LiorBanai** [dotnet/winforms#4556] opened 2021-02-11 12:28 UTC
Hi,
We moved to net 5.0.3 (from net 5) and now we are getting the above exception in Winform form in the Designer on lines like:

this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
this.btnOpenProtocolsFolder.Image = ((System.Drawing.Image)(resources.GetObject("btnOpenProtocolsFolder.Image")));

what could e the reason?

**Comment by filipnavara** [comment] 2021-02-11 12:39
The underlying reason is this: https://github.com/dotnet/winforms/issues/4528

There are mismatched assembly versions written in the .resx file by the designer and the ones compiled into the application. You can see it for yourself if you disable "Just my code" in Debugging options and then enable first chance exception for "FileNotFoundException". It will show you which assembly/version fails to load (likely `System.Windows.Forms.Primitives.dll`). The exception is wildly misleading.

**Comment by filipnavara** [comment] 2021-02-11 12:41
Additionally, if you are using VS 16.9 Preview is ships with 5.0.2xx preview SDK. This is automatically picked up as the latest one even though it contains assemblies that are older than the shipping version (5.0.3 at the moment). Workaround is to force compilation with the right SDK version through `global.json` file:

```
{
  "sdk": {
    "version": "5.0.103",
    "rollForward": "latestPatch"
  }
}
```

**Comment by LiorBanai** [comment] 2021-02-11 12:55
Thanks for the explanation  but this is still not clear to me.. I'm running inside Visual studio with 5.0.3 installed so what incorrect dll are compiled into the resx? should VS takes the currently installed?

**Comment by filipnavara** [comment] 2021-02-11 13:01
The WinForms designer runs with the latest non-preview .NET version installed on the computer (5.0.3 at the moment). When it serializes the resources into the .resx file it writes something like this:

```xml
  <assembly alias="System.Windows.Forms.Primitives" name="System.Windows.Forms.Primitives, Version=5.0.3.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="label_Title.Margin" type="System.Windows.Forms.Padding, System.Windows.Forms.Primitives">
    <value>0, 3, 3, 3</value>
  </data>
```

Notice that the `5.0.3` version now appears as part of the .resx file. Then you build your application but you may inadvertently build it with different SDK version, for example the 5.0.200-preview.21079.7 included in VS 16.9 Preview 4. This happens because the Visual Studio's default SDK policy is to use the latest version, with previews included. That SDK still ships version `5.0.1` of the `System.Windows.Forms.Primitives.dll` and thus at runtime you will end up with mismatched assembly versions. The deserialization is looking for version `5.0.3` but version `5.0.1` is already loaded.

**Comment by LiorBanai** [comment] 2021-02-11 13:11
oh I see now. Thanks!

**Comment by LiorBanai** [comment] 2021-02-11 13:13
but what is the solution for this in this case...

**Comment by filipnavara** [comment] 2021-02-11 13:15
I am hoping the team will act on #4528 and either fix the library versions or the designer. Meanwhile you can use the workaround with the `global.json` file pasted above. It forces Visual Studio and `dotnet build` to use specific SDK version while building.

**Comment by LiorBanai** [comment] 2021-02-11 13:21
OK. Thanks 🙂

**Comment by ericstj** [comment] 2021-02-11 17:11
Designer needs to serializer a version tolerant string to resx.  This is important for multi-targeting. The resx should only contain versions that match what’s in the GA ref pack.  Applications are not “targeting” servicing updates to the runtime.  @DustinCampbell

**Comment by dreddy-work** [comment] 2021-02-13 08:16
This is fixed in the latest VisualStudio version. We will be writing equivalent .NET framework type in to the Resx, wherever applicable.  Framework types are resolved in  all core versions.  And for all other ( Core only types) , We will be removing the version number from the serialized type.

**Comment by RussKie** [comment] 2021-02-15 07:47
The root cause has been fixed in the latest VS.

**Comment by RussKie** [comment] 2021-02-15 07:47
Duplicate of #4528

**Closed by RussKie** 2021-02-15 07:47 UTC
