### ISSUE TITLE
[Tracking] Remove suppressions against Obsolete methods

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#8984] opened 2023-04-12 23:57 UTC
This is tracking issue related to the [comment ](https://github.com/dotnet/winforms/pull/8967#discussion_r1164758407)  and [comment ](https://github.com/dotnet/winforms/pull/8967#discussion_r1164758407)

Obsolete suppression needs to be revisited and mark appropriate public methods obsolete.

**Comment by elachlan** [comment] 2023-11-04 00:06
Duplicate of #7308

**Closed by elachlan** 2023-11-04 00:06 UTC
