### ISSUE TITLE
TreeView freezes the IDE when added to tabpage

### ISSUE THREAD

**Issue by GrapesOfWath** [dotnet/winforms#9002] opened 2023-04-19 05:31 UTC
### Environment

Visual Studio 2022 v17.5.4

### .NET version

6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Unsure, haven't fiddled with VS in years

### Issue description

Adding a TreeView to a tabpage causes the application to hang indefinitely when swapping to a different tabpage that contains controls.

### Steps to reproduce

>New Project
>Add TabControl
>Add controls to one page
>Add treeview to another page
>Go back to page without the treeview on it
>Notice most of the controls don't render correctly
>Either you freeze here, or you switch back to the tab with the treeview on it and *then* you freeze

**Comment by GrapesOfWath** [comment] 2023-04-19 05:33
also worth noting that the cursor doesn't change correctly to the 4 arrowed cursor that indicates moving a control when adding a treeview to the form, not sure if that's related to this issue or not

**Comment by dmitrii-drobotov** [comment] 2023-04-19 12:16
Possibly a duplicate of https://github.com/dotnet/winforms/issues/4336.

**Comment by Tanya-Solyanik** [comment] 2023-04-20 01:11
Indeed a duplicate of https://github.com/dotnet/winforms/issues/4336, tracked i the designer repo by https://github.com/microsoft/winforms-designer/issues/2632

**Closed by Tanya-Solyanik** 2023-04-20 01:11 UTC
Labels: area: VS designer
