### ISSUE TITLE
Icons of maximized MDI Form are not displayed in .NET 5.0

### ISSUE THREAD

**Issue by fn2020** [dotnet/winforms#4460] opened 2021-01-13 16:01 UTC
![mdi_window_maximized_net50](https://user-images.githubusercontent.com/61822948/104476119-2bb07b00-55c0-11eb-8281-46fd76ef42f5.png)
![mdi_window_maximized_netcore31](https://user-images.githubusercontent.com/61822948/104476124-2c491180-55c0-11eb-9515-ca1b86cc0314.png)

It's easy to reproduce if you switch the target Framework in VS2019 between .NET Core 3.1 and .NET 5.0

**Comment by kirsan31** [comment] 2021-01-13 20:33
https://github.com/dotnet/winforms/issues/4388

**Comment by RussKie** [comment] 2021-01-14 00:33
Duplicate of #4388

**Closed by RussKie** 2021-01-14 00:33 UTC
