### ISSUE TITLE
An error pops up when the CheckedListBox control contains duplicate items in Accessibility Insights tool

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#4299] opened 2020-11-30 07:37 UTC
* More info:
1. This is not a regression issue, which can reproduce on .NET 6.0, 5.0, 3.1 and Framework project.
2. The issue can' t reproduce on ListBox control.

* .NET Core Version: 
.NET SDK 6.0.100-alpha.1.20574.5

* Have you experienced this same bug with .NET Framework?: 
 Yes 

**Minimal repro:**
1. Opened the attached core project.[CoreProjectTesting1.zip](https://github.com/dotnet/winforms/files/5614381/CoreProjectTesting1.zip)
2. Build and run it.
3. Open the Accessibility Insights tool, then focus on the list of the checkedListBox control.

**Expected behavior:**
No errors pops ip.

**Actual behavior:**
An error pops up in the Accessibility Insights tool that "Focusable sibling elements must not have the same Name and LocalizedControlType".
![CoreNewIssue](https://user-images.githubusercontent.com/38325459/100580934-c95a2e80-3321-11eb-86b6-b02d722ad909.gif)

**Comment by merriemcgaw** [comment] 2020-12-04 00:58
@SergeySmirnov-Akvelon can you add this to the PRs you're already doing with the ComboBox #4193 ?

**Comment by SergeySmirnov-Akvelon** [comment] 2020-12-04 06:22
Okay, I'll fix it in scope of #4193

**Comment by SergeySmirnov-Akvelon** [comment] 2020-12-16 10:31
Hi @merriemcgaw, @Zheng-Li01. We discussed this issue with Guy Barker. He thinks until we have a real user script for this case, we can resolve this bug as the behavior by design.

**Comment by merriemcgaw** [comment] 2020-12-16 16:23
After talking with Guy, he thinks we can resolve this as by design for us and really an error in Accessibility Insights. Closing our issue.

**Closed by merriemcgaw** 2020-12-16 16:23 UTC
Labels: tenet-accessibility
