### ISSUE TITLE
LinkLabels truncate when programmically disabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7341] opened 2022-06-24 03:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/LinkLabels-truncate-when-programmically-/10078592)._

---
[severity:It bothers me. A fix would be nice]
The link label truncates when it's Enabled property is set to false. Does not happen in the designer, just the program. I have set the backgound colour to highlight that it is within the control - the control itself remains the same size when disabled/enabled. Note the words "Artist" and "Album" are not complete. The controls work fine when Enabled = true;

![image.png](https://aka.ms/dc/image?name=B90d09ef412a74783913bc4576767e86c637915572989528865_20220623-143136-image.png&tid=90d09ef412a74783913bc4576767e86c637915572989528865)

---
#### Feedback Bot on 6/23/2022, 02:09 PM: 

(private comment, text removed)
#### Melon Wang [MSFT] on 6/24/2022, 09:33 AM: 

(private comment, text removed)
#### David Bailey on 6/24/2022, 09:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MelonWang1** [comment] 2022-06-24 03:20
**Repro steps:**
	1. Create a Winforms .NET Core application with a LinkLabel control
	2. Set the LinkLabel control Enabled properties is false
	3. Build and run
**More info:**
This issue is not a regression issue, it also reproduces on VS 2019.
**Actual Result:**
The last character is truncate.
![lionklabel](https://user-images.githubusercontent.com/94418985/175455463-a5fa5951-2993-4c0d-b7ab-3706da72cd85.png)
![lionklabel-1](https://user-images.githubusercontent.com/94418985/175455497-f779289f-86f7-441b-82ae-24b145c71f9b.png)
**Expected Result:**
The last character should display normal.
![linklabel-framework](https://user-images.githubusercontent.com/94418985/175455513-7221581d-ce07-4f62-8965-4bde4c76cc8c.png)

**Comment by Tanya-Solyanik** [comment] 2022-06-29 00:13
I had seen the same issue in the ,NET Framework.

**Comment by merriemcgaw** [comment] 2022-06-29 00:18
@MelonWang1 can you please try to find a workaround, like adding a space at the end of the LinkLabel for the customer, and @dreddy-work will see if there is something we can do on our end.

**Comment by MelonWang1** [comment] 2022-06-29 10:00
@merriemcgaw Adding a space at the end of the LinkLabel text properties can solve this issue. I will tell this workaround to customer to try.
![11](https://user-images.githubusercontent.com/94418985/176409604-7f23eee2-30db-47ba-82b7-5e73a54d8711.gif)

**Comment by RussKie** [comment] 2022-06-30 00:41
FWIW, there was another report for `LinkLabel` truncating the content - #3780

**Comment by merriemcgaw** [comment] 2022-06-30 22:41
We've got multiple reports of this problem with the disabled controls. I think it would be worth trying to find a fix for the issue, but it's still not the top priority on the team. We'd be more than happy to put this issue up for grabs and accept a PR from someone signficantly impacted by this issue.

**Comment by MBODM** [comment] 2022-12-02 15:19
Can confirm exactly the same issue under the following environment:

- Visual Studio 2022 17.4.1
- .NET 6 (latest) and .NET 7.0.100 and .NET Framework 4.8.1
- Windows.Forms (of course)

Test code was:
- Enable/Disable some LinkLabel programatically (clicking a button)

**Comment by merriemcgaw** [comment] 2022-12-02 21:13
@MBODM thank you so much for that suggested workaround! I am glad you found something that works for your application.

**Comment by elachlan** [comment] 2022-12-12 03:50
This comment pointed me in the right direction.
https://github.com/dotnet/winforms/issues/3780#issuecomment-855463125

When setting `UseCompatibleTextRendering=false`, it causes the issue.

The most basic reproduction is:
```csharp
using Form form = new();
using LinkLabel linkLabel = new()
{
    Text = "linkLabel12345",
    Enabled = false,
    UseCompatibleTextRendering = false,
    AutoSize = true
};
form.Controls.Add(linkLabel);
form.ShowDialog();
```

The issue stems from how `OnPaint` functions when `Enabled` and `UseCompatibleTextRendering`. The key here is around `Graphics.ExcludeClip` vs `Graphics.IntersectClip` and how Margins are included in the `_textRegion` in `EnsureRun`.

When `Enabled` is `true`, a manual paint is done via `PaintLink` and then `Graphics.ExcludeClip(_textRegion)` is called to avoid rendering that part of the graphics.

When `Enabled` is `false`, `Graphics.IntersectClip(_textRegion)` is called and then depending on `UseCompatibleTextRendering` we call a different overload of `ControlPaint.DrawStringDisabled`. `UseCompatibleTextRendering=true` will result in a `graphics.DrawString` call, where as `UseCompatibleTextRendering=false` results in a `User32.DrawTextExW` call.

When `UseCompatibleTextRendering=true` it uses `Graphics.MeasureCharacterRanges` to set the `_textRegion`. When `UseCompatibleTextRendering=false`, it uses the `ClientRectWithPadding` and then the margins returned from `hfont.GetTextMargins()`. The margins returned are then **SUBTRACTED** from the width to create a new rectangle. This is the bug, they should be ADDED to the width to account for the extra space required for the text.

https://github.com/dotnet/winforms/blob/b0e5f5b7c4698d3b39424c22d09dbce01e0ce544/src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs#L704-L707

By changing the code to the following the behaviour was fixed in all scenarios.
```csharp
Rectangle visualRectangle = new Rectangle(clientRectWithPadding.X + iLeftMargin,
                                                                  clientRectWithPadding.Y,
                                                                  textSize.Width + iRightMargin + iLeftMargin,
                                                                  textSize.Height);
```

**Comment by elachlan** [comment] 2022-12-12 03:59
Calling `_textRegion.GetBounds(g);` when `UseCompatibleTextRendering=true` gets `Width = 81 Height = 16`.

With Changes:
`visualRectangle` has `Width = 84 Height = 15`.

Without Changes:
`visualRectangle` has `Width = 77 Height = 15`.

**Comment by merriemcgaw** [comment] 2022-12-12 23:28
@elachlan - did you want to pick this up since you did the great work of finding the problem (for which we are _very_ appreciative)? If not, I can have @dmitrii-drobotov and his team get it on their backlog.

**Comment by elachlan** [comment] 2022-12-12 23:41
That was the plan, if the team is happy with my suggested explanation and fix.

You could essentially just remove the logic around accounting for margins, since the code ends up using the `clientRectWithPadding` anyway if the `visualRectangle` is larger than it. Which is always the case if the margins returned are positive (with my suggested change).

What I don't know is the edge cases.

**Comment by MBODM** [comment] 2022-12-12 23:47
This is horrible crazy good work, what @elachlan did here! Just dropped in to send some appreciative words for defining the word „community“ in such a great way @elachlan did here. this is just great work and from my point of view VERY appreciated. Thx for that great investigative work!

**Comment by elachlan** [comment] 2022-12-12 23:53
Thanks :) It took me 4-5hrs to debug it with my simple reproducible steps and the previous information helped immensely.

**Comment by elachlan** [comment] 2022-12-13 01:10
Just digging through the back log.

#6229 seems to be related and would explain the difference.

**Comment by elachlan** [comment] 2022-12-13 02:03
Just an update here: Based on the issue I found, if `TextRenderer.MeasureText` is returning a smaller size that .NET framework, then the code in LinkLabel would work.

I tested the issue in .NET Framework 4.8 and it is fixed
![image](https://user-images.githubusercontent.com/2433737/207208032-4525d0d3-914d-42d0-bf9b-94694927eb41.png)

**Comment by elachlan** [comment] 2022-12-15 01:43
From the PR:

Confirmed. I ran this on both Framework and on our latest main.

**Results**
- Framework: Width 84, Height 15
- .NET8: Width 77, Height 15

```Csharp
Font font = new Font("Segoe UI", 9);
Size size = TextRenderer.MeasureText(
    "linkLabel12345",
    font,
    new Size(int.MaxValue, int.MaxValue),
    TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix | TextFormatFlags.SingleLine);
MessageBox.Show(size.Width.ToString());
```

This is the related code in Framework.
https://referencesource.microsoft.com/#system.windows.forms/misc/GDI/WindowsGraphics2.cs,5f8d74ff4fafe0de

The same in .NET
https://github.com/dotnet/winforms/blob/f4f931118878cbbf2a90deef3440767b8f0109e3/src/System.Windows.Forms/src/System/Windows/Forms/TextExtensions.cs#L217-L276

I have been unable to find the cause as of yet.

**Comment by elachlan** [comment] 2023-01-06 08:53
@dreddy-work I might need one of the Winforms team to take over this one. I believe I'd have to debug .Net Framework to work out where the difference is.

**Comment by merriemcgaw** [comment] 2023-01-06 22:28
@elachlan - we did change the default font in Core. Have you tested with the same font set for each? If so maybe @JeremyKuhne might have some ideas around what he's done in the  GDI side of things in recent releases.

**Comment by elachlan** [comment] 2023-01-07 22:45
@merriemcgaw These are the reproduction code and results. Both use "Segoe UI 9pt". Somehow the width is coming back different.

> **Results**
> 
> * Framework: Width 84, Height 15
> * .NET8: Width 77, Height 15
> 
> ```cs
> Font font = new Font("Segoe UI", 9);
> Size size = TextRenderer.MeasureText(
>     "linkLabel12345",
>     font,
>     new Size(int.MaxValue, int.MaxValue),
>     TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix | TextFormatFlags.SingleLine);
> MessageBox.Show(size.Width.ToString());
> ```

**Comment by merriemcgaw** [comment] 2023-01-13 00:58
Checking with the team. We did some work in this space a couple years ago, but it's interesting not to see lots of complaints, just the couple we've seen so far.

**Comment by elachlan** [comment] 2023-01-13 01:06
I guess you could get the test team to see when it was introduced by testing .NET6/7 as well?

**Comment by MelonWang1** [comment] 2023-01-13 01:52
This issue also repro's on .NET5.0, .NET6.0, .NET7.0, not repro on .NET3.1.

**Comment by elachlan** [comment] 2023-01-17 23:12
@merriemcgaw could a team member debug .net framework and find out the difference in values being passed to the interop layer? I am happy to take over once I have that information.

**Comment by merriemcgaw** [comment] 2023-01-28 01:02
We made some optimizations in the way that fonts are dealt with back at the tail end of .NET 5 timeframe. @JeremyKuhne should be able to take a look and determine what might be the difference here. This is certainly something we want to take a look at. I'll chat with Jeremy and see if he can point us in the right direction.

**Comment by elachlan** [comment] 2023-02-16 05:58
@JeremyKuhne if you could spare a cycle to debug the .net framework version to identify the differences, I can take it from there.

**Comment by JeremyKuhne** [comment] 2023-03-09 01:56
@elachlan it ended up not being anything wrong with `LinkLabel`, but was an issue in `ControlPaint`. I appreciate the effort you put into this. It took me a number of hours to figure out what the heck was wrong. :)

**Comment by JeremyKuhne** [comment] 2023-03-09 02:00
And yes, this is totally my fault. 🤦‍♂️🙌 `WindowsGraphics` was so difficult to follow I missed this case when I axed it.

**Comment by elachlan** [comment] 2023-03-09 02:57
It happens. Luckily we were able to isolate it a bit.

**Closed** 2023-03-10 21:58 UTC
Labels: :beetle: bug, :construction: work in progress

**Comment by Cassie-Li01** [comment] 2023-03-23 02:10
Verified on latest .NET 8.0 version: .NET 8.0.100-preview.4.23172.16, issue is fixed, please check below screenshot:
![image](https://user-images.githubusercontent.com/96758262/227080949-1254ec4a-cf99-45dc-8211-0465cf7047c2.png)

**Comment by MandiMan** [comment] 2023-03-31 06:36
Verified this on .NET 8.0 Preview 3.0 TP build: 8.0.100-preview.3.23178.7, this issue was fixed, the last character display normal. Screenshot as same as above.
