### ISSUE TITLE
[Loc]The description under "Details" after clicking it is not localized in warning dialog

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1002] opened 2019-05-17 03:11 UTC
**.NET Core Version:** .NET Core: 3.0.100-preview6-011904 from Master branch
**Have you experienced this same bug with .NET Framework?:** No
**More info:** This issue also can reproduce with all 13 local languages: CHS, CHT, CSY, DEU, ESN, ITA, JPN, KOR, PLK, PTB, RUS, TRK, FRA

**Steps to reproduce:**
1. Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Master branch.
2. Open the attachment .NET Core app in VS: [WarningDialog.zip](https://github.com/dotnet/winforms/files/3189751/WarningDialog.zip)
3. Run it and edit the **Size** field to value '120,' in the property grid.
4. Observe a warning dialog to popup.

**Actual behavior:** 
The description under "Details" is not translated in .Net core.
![Core](https://user-images.githubusercontent.com/49627022/57900243-b0e70800-7892-11e9-93fa-63a86860f804.PNG)

**Expected behavior:**
The description under "Details" should be translated in .Net core. Following is the screenshot of .Net framework, it is translated.
![Framework](https://user-images.githubusercontent.com/49627022/57900262-b8a6ac80-7892-11e9-922b-1e7b2163e235.PNG)

**Comment by zsd4yr** [comment] 2019-05-17 18:35
@merriemcgaw can you transfer this issue to CoreFX? @karelz this is related to a conversation I had with you about whether or not CoreFX is localizing their error messages. Framework does this, and so I believe this will also need to be done in .NET Core

Our code simply elevates the existing error message https://github.com/dotnet/winforms/blob/9411ed26437905ed3d8148b73ea0dbed47704a5b/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs#L4913

**Comment by karelz** [comment] 2019-05-17 20:48
We do not plan to localize exceptions on .NET Core. We should close it as By Design / Won't Fix.
Applications should not expose exception text to users.

cc @danmosemsft @terrajobst

**Comment by karelz** [comment] 2019-05-17 20:49
Duplicate of https://github.com/dotnet/corefx/issues/17464

**Closed by karelz** 2019-05-17 20:49 UTC
Labels: bug, tenet-localization
