### ISSUE TITLE
initialize of the Settings, does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#6715] opened 2022-02-18 08:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/initialize-of-the-Settings-does-not-wor/1587266)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.10]
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName)
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at testing_settings. My.MySettings.get_Setting_1() in C:\Users\DdeGelder\OneDrive - Infrastructuur Nederland\Documents\Visual Studio 2022\Projects\testing_settings\testing_settings\My Project\Settings1.Designer.vb:line 62
   at testing_settings. Form1.Start_up(Object sender, EventArgs e) in C:\Users\DdeGelder\OneDrive - Infrastructuur Nederland\Documents\Visual Studio 2022\Projects\testing_settings\testing_settings\Form1.vb:line 12
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (C:\Users\DdeGelder\OneDrive - Infrastructuur Nederland\Documents\Visual Studio 2022\Projects\testing_settings\testing_settings\bin\Debug\net6.0-windows\testing_settings.dll.config line 8)

---
#### Feedback Bot on 11/18/2021, 11:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vritant Bhardwaj [MSFT] on 11/20/2021, 09:24 AM: 

<p>Thank you for reaching out to us with issue.</p>
<p>On looking at the stack trace you have presented, I am unable to determine the exact issue you’re encountering. From the screenshot and stacktrace, you have encountered an error in code that is currently running (as I see in the picture attached) and am not able to relate it to a problem in Visual Studio. Could you please provide more details about your issue?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Dirk Gelder on 11/22/2021, 02:37 AM: 

(private comment, text removed)
#### Dirk Gelder on 1/7/2022, 03:52 AM: 

<p>Because it has been a while and no solution has been found yet. Attached is even more information neatly according to your own suggested method.</p>
<p><strong>File only one problem or feature request per issue:</strong> It’s about de Settings-file automaticly generated like the header says:<br>
'------------------------------------------------------------------------------<br>
’ &lt;auto-generated&gt;<br>
’     This code was generated by a tool.<br>
’     Runtime Version:4.0.30319.42000<br>
’<br>
’     Changes to this file may cause incorrect behavior and will be lost if<br>
’     the code is regenerated.<br>
’ &lt;/auto-generated&gt;<br>
'------------------------------------------------------------------------------</p>
<p><strong>The more information you can provide, the easier it will be for us to reproduce and fix your issue.</strong><br>
In the not public post of 21 nov '21 is a compleet project with the same problem, without any other possible problems.<br>
Hence this post filled in with your guidelines to give even more information in a structured way.</p>
<p><strong>Include the following steps with each issue.</strong></p>
<ol>
<li><strong>Reproducible steps (1… 2… 3…) and what you expected versus what you experienced.</strong><br>
1.1. I’m starting a new project<br>
1.2. I opened the project properties<br>
1.3. Went to the settings tab<br>
There was no standard fillable table here, but I had to click on a link first to have it create standard files.<br>
1.4. So let’s create the standard files<br>
1.5. Settings_1 (as string) and Settings_2 (for integer) created<br>
1.6. In function ‘Start_up’ the value contained in a textbox and NumericUpDown<br>
In case of value change, adopt the value in the Settings<br>
Then you run into the following problems when you debug, this is just the drawing of instructions like on various websites about how it should work.<br>
This is also what I have done in previous projects.</li>
<li><strong>Images, animations, or a link to a video. Images and animations illustrate repro-steps but don’t replace them.</strong><br>
See the attachments</li>
<li><strong>As appropriate, a code snippet that demonstrates the issue or a link to a code repository we can easily pull down onto our machine to recreate the issue.</strong><br>
The code of de project I made to repreduce the problem</li>
</ol>
<hr>
<p>Public Class Form1<br>
Private Sub Check_up_settings()<br>
’ Controle of de User settings file in orde is<br>
Try<br>
My.Settings.Reload()<br>
Catch ex As Exception<br>
’ Melding maken<br>
MsgBox(ex.Message)<br>
End Try<br>
End Sub<br>
Private Sub Start_up(sender As Object, e As EventArgs) Handles MyBase.Load<br>
TextBox1.Text = My.Settings.Setting_1<br>
NumericUpDown1.Value = My.Settings.Setting_2<br>
End Sub</p>
<pre><code>Private Sub Update_setting(sender As Object, e As EventArgs) Handles TextBox1.TextChanged, NumericUpDown1.ValueChanged
    If sender.name = &quot;TextBox1&quot; Then My.Settings.Setting_1 = TextBox1.Text
    If sender.name = &quot;NumericUpDown1&quot; Then My.Settings.Setting_2 = NumericUpDown1.Value
End Sub
</code></pre>
<h2>End Class</h2>
<p>**Remember to do the following steps:</p>
<ul>
<li>Search to see if there exists a duplicate. If so, vote up the existing issue, providing additional comments or clarifications as needed.</li>
<li>Recreate the issue after disabling all extensions. If you find the issue is caused by an extension you’ve installed, file an issue on the extension respectively.</li>
<li>Simplify your code around the issue so we can better isolate the problem.**<br>
See the attachment I, like they post of 21 nov '21 will be the testproject</li>
</ul>
<p><strong>Even with issues that include rich details, we may be unable to reproduce the issue and may ask for more information!</strong><br>
No problem, only you have to reacte at leatst with a specific request for more information. As far as I know this is all that I can provide.</p>
<p>I also hope that perhapse a overactive community persone can help.</p>

#### Feedback Bot on 1/14/2022, 05:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by KlausLoeffelmann** [comment] 2022-02-19 20:18
This doesn't have to do with reading the settings, but rather that we have a problem in VB to deal with `system.diagnostics` while reading the _app.config_ at runtime.

The workaround here would be - if it's not needed - to exclude the section system.diagnostics from the app.config.
The exception should then go away at runtime.

BTW: This repos also in .NET 6 on my machine, it is not a regression.

**Comment by RussKie** [comment] 2022-02-19 21:18
https://github.com/dotnet/project-system/issues/6784#issuecomment-903071164

**Comment by RussKie** [comment] 2022-02-21 06:10
Duplicate of https://github.com/dotnet/project-system/issues/6784

**Closed by RussKie** 2022-02-21 06:10 UTC
Labels: :boom: regression
