### ISSUE TITLE
DataGridView will block all data when it's binding with DataTable and execute "DataTable.Rows.Clear()" in other thread

### ISSUE THREAD

**Issue by kkle1994** [dotnet/winforms#10951] opened 2024-02-27 06:38 UTC
### .NET version

7.0 & 8.0

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No idea

### Issue description

DataGridView will block all data when it's binding with DataTable and execute "DataTable.Rows.Clean()" in other thread.

### Steps to reproduce

1. Create DataTable named "NameDataTable" and DataGridView named "dataGridViewNames", then
```csharp
            NameDataTable = new DataTable();
            NameDataTable.Columns.Add("Selected", typeof(bool));
            NameDataTable.Columns.Add("Changelist Id");
            NameDataTable.Columns.Add("Jira Id");
            NameDataTable.Columns.Add("Submitter");
            NameDataTable.Columns.Add("Name in Resconf.json");

            dataGridViewNames.DataSource = new BindingSource() { DataSource = NameDataTable };
            dataGridViewNames.AllowUserToAddRows = false;
```

2. Add some data with whatever you wanna use, then execute code with button or any event:
```csharp
Task.Run(() => NameDataTable.Rows.Clean());
```

3. Try edit data in DataGridView, the data existing will be blocked.

**Comment by Zheng-Li01** [comment] 2024-02-27 07:25
@kkle1994, the application working well with the steps provided by you on both .NET and .NET Framework, see below reproduce GIF. and found that only have the `NameDataTable.Rows.Clear()` can be used, cannot find the "clean()" method in your steps#2, can you have a confirm with it? and provide the project created by us, please try to use it and point it out if there have any wrong steps.
![10951](https://github.com/dotnet/winforms/assets/38325459/31fc6e0d-056d-4bfa-9894-acd47a064d0f)
[WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/14415836/WindowsFormsApp6.zip)

**Comment by kkle1994** [comment] 2024-02-27 07:32
> @kkle1994, the application working well with the steps provided by you on both .NET and .NET Framework, see below reproduce GIF. and found that only have the `NameDataTable.Rows.Clear()` can be used, cannot find the "clean()" method in your steps#2, can you have a confirm with it? and provide the project created by us, please try to use it and point it out if there have any wrong steps. ![10951](https://private-user-images.githubusercontent.com/38325459/308074353-31fc6e0d-056d-4bfa-9894-acd47a064d0f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTkwMzIsIm5iZiI6MTcwOTAxODczMiwicGF0aCI6Ii8zODMyNTQ1OS8zMDgwNzQzNTMtMzFmYzZlMGQtMDU2ZC00YmZhLTk4OTQtYWNkNDdhMDY0ZDBmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZWNkN2Y2MTI3ZjViNjE3ODgyZmY0OTA0MWM0ZDU0MTM3NTA1Y2UxODRiMWE0ZjAwMzlhOTQ3NGQxZjNmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4geGO4iBl2KUHPwpifR9qBoxTDChwF_2KPjpQS2JXg) [ ](https://private-user-images.githubusercontent.com/38325459/308074353-31fc6e0d-056d-4bfa-9894-acd47a064d0f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTkwMzIsIm5iZiI6MTcwOTAxODczMiwicGF0aCI6Ii8zODMyNTQ1OS8zMDgwNzQzNTMtMzFmYzZlMGQtMDU2ZC00YmZhLTk4OTQtYWNkNDdhMDY0ZDBmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZWNkN2Y2MTI3ZjViNjE3ODgyZmY0OTA0MWM0ZDU0MTM3NTA1Y2UxODRiMWE0ZjAwMzlhOTQ3NGQxZjNmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4geGO4iBl2KUHPwpifR9qBoxTDChwF_2KPjpQS2JXg) ![10951](https://private-user-images.githubusercontent.com/38325459/308074353-31fc6e0d-056d-4bfa-9894-acd47a064d0f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTkwMzIsIm5iZiI6MTcwOTAxODczMiwicGF0aCI6Ii8zODMyNTQ1OS8zMDgwNzQzNTMtMzFmYzZlMGQtMDU2ZC00YmZhLTk4OTQtYWNkNDdhMDY0ZDBmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZWNkN2Y2MTI3ZjViNjE3ODgyZmY0OTA0MWM0ZDU0MTM3NTA1Y2UxODRiMWE0ZjAwMzlhOTQ3NGQxZjNmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4geGO4iBl2KUHPwpifR9qBoxTDChwF_2KPjpQS2JXg) [ ](https://private-user-images.githubusercontent.com/38325459/308074353-31fc6e0d-056d-4bfa-9894-acd47a064d0f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTkwMzIsIm5iZiI6MTcwOTAxODczMiwicGF0aCI6Ii8zODMyNTQ1OS8zMDgwNzQzNTMtMzFmYzZlMGQtMDU2ZC00YmZhLTk4OTQtYWNkNDdhMDY0ZDBmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZWNkN2Y2MTI3ZjViNjE3ODgyZmY0OTA0MWM0ZDU0MTM3NTA1Y2UxODRiMWE0ZjAwMzlhOTQ3NGQxZjNmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4geGO4iBl2KUHPwpifR9qBoxTDChwF_2KPjpQS2JXg) [WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/14415836/WindowsFormsApp6.zip)

Yep, `Clear()` is right sry about that, and may try it in other thread?

**Comment by kkle1994** [comment] 2024-02-27 07:34
Or I may try that by myself later after my work ( a bit busy today)

**Comment by kkle1994** [comment] 2024-02-27 07:44
I've created code which can reproduce the issue in attachment
[WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/14416066/WindowsFormsApp6.zip)

**Comment by kkle1994** [comment] 2024-02-27 07:50
I guess maybe some error messages has been hidden if I create new data in another thread. If you move adding data code out the `Task.Run` code, it will throw some data errors of DataGridView.

**Comment by Zheng-Li01** [comment] 2024-02-27 08:09
> I've created code which can reproduce the issue in attachment [WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/14416066/WindowsFormsApp6.zip)

Yes, got the below error after clicked the button1 with your project.
![image](https://github.com/dotnet/winforms/assets/38325459/814b108a-ea73-4b46-a075-c8d9aca30cb6)

**Comment by kkle1994** [comment] 2024-02-27 08:25
Yep, so if user do that in another thread, they will meet the issue without error message. It will bother them a lot like me haha

**Comment by merriemcgaw** [comment] 2024-02-28 21:39
@Zheng-Li01 can you test the behavior in .NET Framework 4.8.1? This is certainly something we want to look at, but the priority increases if it's a breaking change from Framework.

**Comment by Zheng-Li01** [comment] 2024-02-29 01:16
@merriemcgaw, there have the same exception pops up for .NET Framework project targeting 4.8.1.
![Update10951](https://github.com/dotnet/winforms/assets/38325459/67c8f428-018b-4c2d-8716-6b525c2effb4)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.DataGridViewRow.GetErrorText(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WindowsFormsApp1
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/v-zhgl/source/repos/WindowsFormsApp1/WindowsFormsApp1/bin/Debug/WindowsFormsApp1.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4443.1 built by: NETFXDEV1[TANYASOZ2-TANYASO]
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by merriemcgaw** [comment] 2024-03-05 19:56
Since this is something that hasn't regressed with .NET, I'm going to go ahead and close this issue. For new apps data processing, it is highly recommended that we don't use the legacy DataSet and DataTable, it is recommended to migrate to EF Core, which can handle many more scenarios.

**Closed by merriemcgaw** 2024-03-05 19:56 UTC
Labels: area-Controls-DataGridView, untriaged
