### ISSUE TITLE
Newly installed VS2022 craashes on me while deleting TabStrip component at design time on the form

### ISSUE THREAD

**Issue by DeerBear** [dotnet/winforms#6951] opened 2022-04-02 03:18 UTC
### Environment

Microsoft Visual Studio Community 2022
Version 17.1.3
VisualStudio.17.Release/17.1.3+32328.378
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.1.358.51495
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.1.358.51495
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.1.358.51495
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.1.358.51495
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.161+abc97ecc7d.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62203.25080
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1229.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.1.0.324 (d17-1@590ddb7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.2.0.4 (d17-1/19b97b7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a5d1934
    Java.Interop: xamarin/java.interop/d17-1@7ac33610
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.1@0893b3b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

Xamarin.iOS and Xamarin.Mac SDK   15.8.0.2 (79ddd0840)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### .NET version

.NET 6.0. This is the default that VS2022 proposed to me.

### Issue description

I created a new WinForms application and mistakenly added a TabStrip component. Then I tried to delete it. 

### Steps to reproduce

1) Fresh install of VS2022 CE
2) New WinForms solution. Use defaults.
3) Add a TabStrip.
4) Delete the TabStrip (or, better, try to!) 

VS2022 will crash and reopen automatically, but the project will be corrupted. No way to unload it, nothing.  The only way out is to create a new solution, which you have to do anyway because the project is now corrupted. 

[ArchiviaRapidoConfigurator.zip](https://github.com/dotnet/winforms/files/8401702/ArchiviaRapidoConfigurator.zip)

### Diagnostics

```text
I didn't think of looking at that and I am not reopening this because I am trying to do something productive.
```

**Comment by dreddy-work** [comment] 2022-04-04 21:49
@Olina-Zhang , can you see if we can repro this?

**Comment by Olina-Zhang** [comment] 2022-04-07 02:14
@DeerBear the sample application you provided is not a completed one, which is missing form after unzipped it. And what is TabStrip? is it TabControl?

**Comment by DeerBear** [comment] 2022-04-07 02:58
Hold up!

I zipped the folder as-is, so... what are we saying here, really? I literally just selected the folder, added to zip and posted it. 
So... if anything is missing... that might actually be the problem and the core issue. I double-checked now and, yes, I zipped the outermost folder, so if something is not there that should be... I have no idea why. 
And sorry, I misnamed it, it was the ToolStripContainer. 
So, I created a new project called "TestRepro" right now. I had a solution open, so VS asked me if I wanted to save it and I said yes please. Then VS **_flashed on me_** and now it's loading the designer.
I added the ToolStripContainer again and I cannot delete it at all, but at least it's not crashing now!
I have no idea how I made it crash and I also finally managed to get it to be deleted (I had to press "Esc" to select the whole thing as there was no other way).  
There is... something... there, I know there is, but I left it alone for a few days now and it seems to be behaving as it should. 
When I initially tried to delete the container, I was selecting what I thought were the main control's body and press "Del". I did so quite a few times but I guess way fewer than when I originally did this.

**Comment by Olina-Zhang** [comment] 2022-04-07 03:18
It seems that issue cannot reproduce now in your machine, and I tested toolStripContainer, deleted it several times, all work well. So we will close this issue now. And please file a new one if it can reproduce again.

**Closed** 2022-04-07 04:23 UTC
Labels: area: VS designer
