### ISSUE TITLE
ListView does not display icons for items added after the form has been loaded

### ISSUE THREAD

**Issue by dhrdlicka** [dotnet/winforms#4263] opened 2020-11-22 02:01 UTC
* .NET Core Version: 5.0.100

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

ListView renders items added after the form has been loaded without their icons. This happens regardless of the configured view.

The provided repro adds 50 items in the constructor, Form.Load handler and Form.Shown handler respectively. As you can see, only the first 50 items are displayed with icons, although all items are generated and added by the same function.
![image](https://user-images.githubusercontent.com/13226155/99891805-3e689c80-2c6e-11eb-96fa-7302c6af9121.png)

**Expected behavior:**
The same project built for .NET Core 3.1:
![image](https://user-images.githubusercontent.com/13226155/99891844-a7e8ab00-2c6e-11eb-9c3c-3e848842fd15.png)

**Minimal repro:**
https://github.com/dhrdlicka/ListViewRepro

**Comment by kirsan31** [comment] 2020-11-22 08:09
https://github.com/dotnet/winforms/issues/4169 the same?

**Comment by RussKie** [comment] 2020-11-23 00:58
Duplicate of #4169

**Comment by RussKie** [comment] 2020-11-23 00:59
You can you a workaround described here: https://github.com/dotnet/winforms/issues/4169#issuecomment-721465144
The fix is coming in 5.0.1.

**Closed by RussKie** 2020-11-23 00:59 UTC
