### ISSUE TITLE
WinForm class OpenFileDialog and SaveFileDialog don't support OFN_DONTADDTORECENT flag

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#5405] opened 2021-08-09 11:47 UTC
If the users don't want to save the opened file history to the Windows system, the Windows API provides the **OFN_DONTADDTORECENT** flag to achieve this, but it is currently not available in WinForm class **OpenFileDialog** and **SaveFileDialog**.

Even if the reflection method OpenFileDialog.SetOption is called and OFN_DONTADDTORECENT is passed in, it also does not work.

Tested .NET Version:

.NET Framework 4.8
.NET 5.0

**Comment by willibrandon** [comment] 2021-09-02 06:03
I think this could be important for security reasons. Sometimes I want to open and save files without my Recent files list being updated. Perhaps I was working on some sensitive documents.

![RecentFiles](https://user-images.githubusercontent.com/5017479/131790350-7ced6824-15fc-4143-b16d-94b4946fee3d.PNG)

**Comment by willibrandon** [comment] 2021-09-03 05:40
I've taken a look and it seems easy enough to implement the relevant native API.

**Is your feature request related to a problem? Please describe.**


The `FileDialog` currently does not expose all of the native options available to an Open or Save Dialog. In order to deliver all aspects of Windows, I propose we implement the FOS_DONTADDTORECENT and OFN_DONTADDTORECENT option and expose a new `FileDialog` property to allow users to get and set the new option. This would take care of both `OpenFileDialog` and `SaveFileDialog` derived classes.

The phrase "don't add to recent" is negative in nature and instead of using that I propose a positive phrase like "add to recent", and name the new `FileDialog` property `AddToRecent` with a default value of true so that the default behavior remains unchanged. Setting `AddToRecent` to false would prevent the system from adding a link to the selected file in the Recent Items folder.

**Describe the solution you'd like and alternatives you've considered**


Expose the relevant native API and add a new public `FileDialog` property named `AddToRecent`:

```cs
namespace System.Windows.Forms
{
    public partial class FileDialog
    {
        [DefaultValue(true)]
        public bool AddToRecent { get; set; }
    }
}
```

**Will this feature affect UI controls?**

Yes.

**Will VS Designer need to support the feature? If yes, describe how you expect it to funсtion.**

The VS Designer will need to support the newly exposed property at design time.

**What impact will it have on accessibility?**

None

**Will this feature need to be localized or be localizable?**

This is handled by the SRDescriptionAttribute on the new property.

**Comment by dreddy-work** [comment] 2021-09-03 18:33
@willibrandon , thank you for taking time and propose the solution. This looks reasonable to me. I will get this triaged within team and get it ready for API review coming week.

**Comment by weltkante** [comment] 2021-09-08 20:05
This needs some additional research to check if its also needed on the (Vista)FolderBrowserDialog, since it doesn't share the same base class but shares much of the same behavior (due to also being a shell dialog since Vista).

If the FolderBrowserDialog by default also adds selected folders to the "recently used" list then it also should get this new API.

**Comment by willibrandon** [comment] 2021-09-09 06:22
If I Windows-R "recent" and watch that folder I'm seeing the FolderBrowserDialog add the selected folders to Recent. Sometimes I have to refresh to see the recently selected folder(s). There must be a better way to test it.

Looks like the FolderBrowserDialog could use some AddToRecent love too.

![FolderBrowserDialog](https://user-images.githubusercontent.com/5017479/132632684-65a28880-90b1-48dd-bfa2-e7eaac55030d.PNG)

**Comment by willibrandon** [comment] 2021-09-09 06:32
Also confirmed setting the FOS.DONTADDTORECENT option prevented the FolderBrowserDialog from adding to recent.

There could be things here that I’m missing so I look forward to hearing your results.

**Comment by willibrandon** [comment] 2021-09-09 16:18
@weltkante - I've done more testing and agree that the FolderBrowserDialog should also receive this new API.

I will work on updating the proposal and should have that ready at some point today. After you get a chance to experiment, if you would like me to add any relevant information, please let me know.

Thank you.

**Comment by weltkante** [comment] 2021-09-09 17:51
Sounds good, you seem to be confirming what I'm expecting. In the shell both file selection and folder selection go through the same APIs these days, so I'm expecting both to behave similarly and needing the same API, it was the same with a few other recent additions in .NET Core. Its a bit annoying that we can't go back and change the base class of FolderBrowserDialog to be more in line with what the Windows API looks like these days, so the next best option is simply to always consider any addition to file dialogs also to be added to the folder dialog. I'll double check over the weekend, but what you're reporting seems to confirm that the same is true here, so no need to wait for me if you want to update your API proposal.

**Comment by willibrandon** [comment] 2021-09-09 22:15
If possible, can we please update the title of this issue to the following.

**Implement AddToRecent for FileDialog and FolderBrowserDialog**

**Comment by willibrandon** [comment] 2021-09-09 23:58
I've updated the proposal to include the implementation of AddToRecent for the FolderBrowserDialog. Thank you @weltkante for pointing that out.

If there are any other concerns, please let me know so they can be addressed.

**Comment by dreddy-work** [comment] 2021-09-10 01:14
Thank you @willibrandon and @weltkante. During the review of this proposal,  we looked at flags supported by native dialog [enum ](https://github.com/dotnet/winforms/blob/81774abbcbb885fe906f1c0f813e8175eef8705c/src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.OFN.cs#L10)and Winforms is missing a handful of them.
![image](https://user-images.githubusercontent.com/36968667/132781581-e8f02d97-c56a-4cd8-ac75-68a22fa6a8b8.png)

Use cases for some these flags are straight forward while other are little complicated. Did you get a chance to look at remaining flags and how they impact `FileDialog`?

**Comment by willibrandon** [comment] 2021-09-10 01:19
@dreddy-work - The thought had crossed my mind as a possible future proposal. Since this is my first one, I figured I would start small. I'll take a look now and familiarize myself with the use cases.

**Comment by dreddy-work** [comment] 2021-09-10 01:24
> @dreddy-work - The thought had crossed my mind as a possible future proposal. Since this is my first one, I figured I would start small. I'll take a look now and familiarize myself with the use cases.

Cool. We should extend the scope of this proposal and see what other flags we could/should add support for.

**Comment by RussKie** [comment] 2021-09-10 02:59
It'd be easier to take a more complete API proposal to the API Review Board. Once approved, we can implement the missing API either in one go or in a series of PRs.

**Comment by willibrandon** [comment] 2021-09-10 03:47
> 
> 
> It'd be easier to take a more complete API proposal to the API Review Board. Once approved, we can implement the missing API either in one go or in a series of PRs.

Thank you for the consideration. I'll start working on a more complete proposal which will include the remaining flags.

**Comment by willibrandon** [comment] 2021-09-10 16:39
@dreddy-work - I agree that the use cases for the remaining flags are mostly straight forward and I should have no problems proposing the solutions for those however I might need a little guidance on imagining the use case for dialog box templates in WinForms. Perhaps the team has had a similar discussion about dialog box templates in the past and could bring me up to speed on the subject?

**Comment by RussKie** [comment] 2021-09-13 00:28
> It seems like WinForms eliminates the need to support dialog box templates as it already supports the creation of custom dialog boxes by using the Windows Forms Designer.

Can you please clarify this point?

New properties will be surfaced in the property grid automatically. If those properties will contain something other than simple values (e.g. `bool`, `string`, etc.) then we'll need to discuss what'd be the best way to have those values set. But before we'll need to agree on the properties. Let's do this first, and then we can discuss any implications to the designer.

**Comment by willibrandon** [comment] 2021-09-13 03:37
> 
> 
> > It seems like WinForms eliminates the need to support dialog box templates as it already supports the creation of custom dialog boxes by using the Windows Forms Designer.
> 
> Can you please clarify this point?
> 
> New properties will be surfaced in the property grid automatically. If those properties will contain something other than simple values (e.g. `bool`, `string`, etc.) then we'll need to discuss what'd be the best way to have those values set. But before we'll need to agree on the properties. Let's do this first, and then we can discuss any implications to the designer.

I should have been more specific. What I was referring to are the flags OFN_ENABLETEMPLATE and OFN_ENABLETEMPLATEHANDLE which can be used to specify dialog template resources. The dialog templates can be created using the [Dialog Editor](https://docs.microsoft.com/en-us/cpp/windows/dialog-editor) or can be [created programmatically](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-dlgtemplate). My point was that I don't think there is a need to support these 2 flags in WinForms.

**Comment by willibrandon** [comment] 2021-09-13 06:39
Maybe a new dialog type that could run dialog templates.

**Comment by willibrandon** [comment] 2021-09-13 21:03
Another flag which is unnecessary to implement is NONETWORKBUTTON. This flag corresponds to the old Windows 3.1 style Open dialog which has a button labeled Network that appears next to the drives combo box. Clicking the Network button lets you map a new network drive.

![OldStyleOpenDialog](https://user-images.githubusercontent.com/5017479/133154815-94013068-adf9-4666-8d23-dbdbe5a7bb01.PNG)

The NONETWORKBUTTON flag allows you to hide that button.

![OldStyleOpenDialog_NoNetworkButton](https://user-images.githubusercontent.com/5017479/133155415-e769158a-b50c-48f1-8769-c971e27841cb.PNG)

With that said, since the `FileDialog` uses the new Explorer-style dialog, there is no Network button to begin with, so there is no button to hide. This behavior and possible confusion with the new Explorer-style dialog is [discussed here](https://devblogs.microsoft.com/oldnewthing/20190705-00/?p=102660).

**Comment by dreddy-work** [comment] 2021-09-13 23:07
> I should have been more specific. What I was referring to are the flags [ENABLETEMPLATE](https://github.com/dotnet/winforms/blob/81774abbcbb885fe906f1c0f813e8175eef8705c/src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.OFN.cs#L18) and [ENABLETEMPLATEHANDLE](https://github.com/dotnet/winforms/blob/81774abbcbb885fe906f1c0f813e8175eef8705c/src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.OFN.cs#L19) which can be used to enable and [specify dialog template resources](https://github.com/dotnet/winforms/blob/028ddf9a27c4748b9f19e71e8d4ebfa1d0374583/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs#L121). The dialog templates can be created using a [Dialog Editor](https://docs.microsoft.com/en-us/cpp/windows/dialog-editor) or can be [created programmatically](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-dlgtemplate). My point was that I'm not sure if there is a need for the `FileDialog` to support these 2 flags. Perhaps someone could provide some guidance on this topic. If I were to propose these 2 flags I would need help explaining the use cases.
> 
Only place in our code base i see using one of these flags is [here](https://github.com/dotnet/winforms/blob/f6349d77313bd7a1fb15d170c11d32d401909080/src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.CustomColorDialog.cs#L42) and Handle passed was the Handle to the process file. I am still digging here to understand it better but i suggest continue with rest of the proposal for now.

**Comment by weltkante** [comment] 2021-09-13 23:30
Are we even talking about the right enum here? Isn't this the enum from the legacy (non-Vista) dialog which is almost never going to be used anyways? I can't see these flags for the `IFileDialog` interface, nor can I see anything about dialog templates being supported. Am I missing something?

**Comment by willibrandon** [comment] 2021-09-14 00:05
> 
> 
> Are we even talking about the right enum here? Isn't this the enum from the legacy (pre-Vista) dialog which is almost never going to be used anyways? I can't see these flags for the [`IFileDialog`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialog) interface (seems to be a [different](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions) enum), nor can I see anything about dialog templates being supported. Am I missing something?

The IFileDialog options [are here](https://github.com/dotnet/winforms/blob/118a1682519fd8dc4db8a37d87b0cd3ba50f5b90/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FOS.cs#L10) and dialog templates are not supported.

> 
> While you probably can call the legacy API and it will get redirected to IFileDialog when available (i.e. almost always, except on "Server Core" as reported [here](https://github.com/dotnet/winforms/issues/2506)), I think many of those legacy settings no longer have a meaning. If you design new API you probably should target the actually used implementation and not the legacy API?

I agree and thank you for mentioning the Server Core exception. The IFileDialog flags haven't been explicitly mentioned yet but my plan was to propose those missing flags as well. Some of the missing legacy and Vista flags overlap so there is still some meaning there but I agree that we should probably start by focusing on the missing Vista flags, rather than the missing legacy flags.

**Comment by willibrandon** [comment] 2021-09-14 02:13
The following [Vista flags](https://github.com/dotnet/winforms/blob/118a1682519fd8dc4db8a37d87b0cd3ba50f5b90/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FOS.cs#L10) are missing:

FOS.STRICTFILETYPES
FOS.PICKFOLDERS
FOS.ALLNONSTORAGEITEMS
FOS.SHAREAWARE
FOS.NOREADONLYRETURN
FOS.NOTESTFILECREATE
FOS.HIDEMRUPLACES
FOS.HIDEPINNEDPLACES
FOS.OKBUTTONNEEDSINTERACTION
FOS.DONTADDTORECENT
FOS.FORCESHOWHIDDEN
FOS.FORCEPREVIEWPANEON
FOS.SUPPORTSTREAMABLEITEMS

**Comment by RussKie** [comment] 2021-09-14 03:32
> we should start by focusing on the missing Vista flags, rather than the missing legacy flags

👍 

> The following [Vista flags](https://github.com/dotnet/winforms/blob/118a1682519fd8dc4db8a37d87b0cd3ba50f5b90/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FOS.cs#L10) are missing:
> 
> FOS.STRICTFILETYPES
> FOS.PICKFOLDERS
> FOS.ALLNONSTORAGEITEMS
> FOS.SHAREAWARE
> FOS.NOREADONLYRETURN
> FOS.NOTESTFILECREATE
> FOS.HIDEMRUPLACES
> FOS.HIDEPINNEDPLACES
> FOS.OKBUTTONNEEDSINTERACTION
> FOS.DONTADDTORECENT
> FOS.FORCESHOWHIDDEN
> FOS.FORCEPREVIEWPANEON
> FOS.SUPPORTSTREAMABLEITEMS

Just to clarify, these are the flags that are not exposed to a user, and are up for consideration to be exposed. Do I understand this correctly?

**Comment by willibrandon** [comment] 2021-09-14 04:26
> Just to clarify, these are the flags that are not exposed to a user, and are up for consideration to be exposed. Do I understand this correctly?

Yes, those flags are currently not exposed. I'm not sure if it makes sense to expose all of them yet, going through the use cases now. So far I've looked at:

FOS.SHAREAWARE
FOS.NOREADONLYRETURN
FOS.NOTESTFILECREATE
FOS.DONTADDTORECENT
FOS.FORCESHOWHIDDEN

And those look good to me.

Now working through the rest:

FOS.STRICTFILETYPES
FOS.PICKFOLDERS
FOS.FORCEFILESYSTEM
FOS.ALLNONSTORAGEITEMS
FOS.HIDEMRUPLACES
FOS.HIDEPINNEDPLACES
FOS.OKBUTTONNEEDSINTERACTION
FOS.FORCEPREVIEWPANEON
FOS.SUPPORTSTREAMABLEITEMS

Will report back here when finished.

**Comment by willibrandon** [comment] 2021-09-28 17:13
I'm still looking at the remaining flags and their use cases and I must say that I don't feel as strongly about the rest of them as I do about FOS.DONTADDTORECENT, which makes them difficult to propose.

FOS.FORCESHOWHIDDEN and FOS.HIDEMRUPLACES I can see being useful and plan to propose those 2 flags as well but for the rest of the remaining flags, I have either found no use case or have found them to be more annoying than useful.

I'm working on summarizing my thoughts for each flag now and hope to finish that at some point today.

Thank you.

**Comment by roland5572** [comment] 2021-10-04 01:20
Yes, I think FOS.DONTADDTORECENT is more important. Other Flags can be implemented through additional programming code, but this flag can only be implemented through the underlying Windows API.

**Comment by willibrandon** [comment] 2021-10-07 05:54
> Yes, I think FOS.DONTADDTORECENT is more important.

I agree but we need to consider the other flags to make a more complete API proposal as mentioned earlier.

> 
> 
> It'd be easier to take a more complete API proposal to the API Review Board. Once approved, we can implement the missing API either in one go or in a series of PRs.

Some of the flags and use cases have been new to me so its taken some time to get familiar with them all but I'm getting close. I'm working on a list now which will include each flag, it's definition, and some thoughts. From there we can decide which flags we could/should add support for.

**Comment by willibrandon** [comment] 2021-10-09 01:28
HidePinnedPlaces

Controls whether the items shown by default in the view's navigation pane are hidden.

https://user-images.githubusercontent.com/5017479/136639032-85d68bc2-bc0f-4649-9f19-9e314f9645fd.mp4

**Comment by willibrandon** [comment] 2021-10-09 03:46
ExpandedMode, also known as DefaultNoMiniMode.

Controls whether to open the dialog box in expanded mode.

https://user-images.githubusercontent.com/5017479/136643178-0443ea54-85f4-48be-a20e-27cd6733f5af.mp4

**Comment by willibrandon** [comment] 2021-10-09 04:25
ForcePreviewPaneOn

Controls whether to always display the Open dialog box preview pane.

https://user-images.githubusercontent.com/5017479/136643896-8a15a60b-16b1-4666-87c0-219eb32b23c7.mp4

**Comment by willibrandon** [comment] 2021-10-10 22:31
AddToRecent

Controls whether to add the file being opened or saved to the recent documents list.

https://user-images.githubusercontent.com/5017479/136714819-ce38632f-7730-48b6-aac1-90de9034f0ee.mp4

**Comment by willibrandon** [comment] 2021-10-12 04:26
NoReadOnlyReturn

Controls whether read-only items are returned.

https://user-images.githubusercontent.com/5017479/136891252-367c4537-f1e8-4ed7-b66b-b8fe3097f788.mp4

**Comment by willibrandon** [comment] 2021-10-13 05:14
NoTestFileCreate

Controls whether to create a test file.

https://user-images.githubusercontent.com/5017479/137071297-7030f608-daf0-43ac-a2ca-a5cbd752db5d.mp4

**Comment by RussKie** [comment] 2021-10-13 23:07
> NoTestFileCreate
> 
> Controls whether to create a test file.

I'm a little confused by the behavior - with the flag=on a file was created (testfile1), and when the flag=off there was no file created (testfile2). [The docs](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2013/bb167321(v=vs.120)) say that the created file may be inaccessible after the create. What was your experience?

**Comment by RussKie** [comment] 2021-10-15 00:26
Thank you for the explanations 👍 

> I created a create-nonmodify folder, which means files may be created, but once they are closed, they can no longer be modified or deleted.

Ah, I must have missed "create" bit, and that's what got me confused.

**Comment by willibrandon** [comment] 2021-10-15 04:14
I need to make the demo more clear somehow. Anyways, we should move on to ShareAware. That one is way more interesting.

**Comment by willibrandon** [comment] 2021-10-15 05:12
ShareAware

Controls whether the application is called back for guidance in the case of a sharing violation.

https://user-images.githubusercontent.com/5017479/137435623-d94562f7-7c57-4e88-9464-c2b3ecfebd0a.mp4

**Comment by willibrandon** [comment] 2021-10-15 19:26
Before I forget I would like to take a moment and say thank you to the Windows Forms team for making this project available on GitHub. Regardless of what happens with this proposal, this has been a truly wonderful learning experience that I will never forget. Thank you.

**Comment by willibrandon** [comment] 2021-10-15 23:39
FolderChanging

Occurs just before the user navigates to a new folder.

Allows the application to prevent navigation to a particular location.

https://user-images.githubusercontent.com/5017479/137564634-f8f9f1f6-d3b5-4b15-937b-b98a8ec7d045.mp4

**Comment by willibrandon** [comment] 2021-10-16 06:49
Overwrite

Called from the save dialog when when the user chooses to overwrite a file.

https://user-images.githubusercontent.com/5017479/137576966-66aaa263-d061-4a06-aec3-53d4e20f5bae.mp4

**Comment by willibrandon** [comment] 2021-10-17 01:03
I have noticed more file dialog features that have not been implemented yet. [IFileDialogCustomize](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialogcustomize) exposes methods that allows the application to add custom controls to the dialogs and [IFileDialogControlEvents](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl/nn-shobjidl-ifiledialogcontrolevents) allows the application to be notified of the events that are related to the controls that have been added. Interesting.

I'm not ready to investigate this one yet but noting it here so I don't forget.

**Comment by willibrandon** [comment] 2021-10-17 04:42
I've just discovered that there is more to the ShareAware/ShareViolation feature. I need to take a closer look at [IFileIsInUse](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifileisinuse).

**Comment by willibrandon** [comment] 2021-10-19 04:57
I just updated the proposal above. If you would like me to add anything or have any questions, please let me know. Thank you for letting me take a look at this. Its been really fun.

**Comment by RussKie** [comment] 2021-10-19 23:35
Can you please add xml-docs for each new property explaining the purpose and denoting default values?

**Comment by dreddy-work** [comment] 2021-11-01 19:53
@willibrandon, This is still on our radar. Team is still wrapping few things in .NET 6.0 and VS releases and should be able to take this further by end of this month.

**Comment by willibrandon** [comment] 2021-11-02 01:46
@dreddy-work, thanks for the update, looking forward to it.

**Comment by RussKie** [comment] 2021-11-18 06:13
I've reviewed the proposal, and compared it against the existing API. I'm proposing few tweaks:

```diff
namespace System.Windows.Forms
{
    public partial class FileDialog
    {
        /// <summary>
-       ///  Controls whether to add the file being opened or saved to the recent list.
+       ///  Gets or sets a value indicating whether the dialog box adds the file being opened or saved to the recent list.
        /// </summary>
        [DefaultValue(true)]
-       public bool AddToRecent { get; set; }
+       public bool AddToRecent { get; set; } = true;

        /// <summary>
-       ///  Controls whether to include hidden and system items.
+       ///  Gets or sets a value indicating whether the dialog box displays hidden and system files.
        /// </summary>
        [DefaultValue(false)]
-       public bool ForceShowHiden { get; set; }
+       public bool ShowHiddenFiles { get; set; }

        /// <summary>
-       ///  Controls whether the items shown by default in the view's navigation pane are hidden.
+       ///  Gets or sets a value indicating whether the items shown by default in the view's navigation pane are hidden.
        /// </summary>
-       [DefaultValue(false)]
-       public bool HidePinnedPlaces { get; set; }
+       [DefaultValue(true)]
+       public bool ShowPinnedPlaces { get; set; } = true;

        /// <summary>
-       ///  Controls whether the OK button needs interaction before it is enabled.
+       ///  Gets or sets a value indicating whether the OK button of the dialog box is disabled until the user navigates the view or edits the filename (if applicable).
        /// </summary>
+       /// <remarks>
+       ///  Note: Disabling of the OK button does not prevent the dialog from being submitted by the Enter key.
+       /// </remarks>
        [DefaultValue(false)]
-       public bool OkButtonNeedsInteraction { get; set; }
+       public bool OkRequiresInteraction { get; set; }
    }
}
```

```diff
namespace System.Windows.Forms
{
    public partial class OpenFileDialog
    {
        /// <summary>
-       ///  Controls whether to always display the Open dialog box preview pane.
+       ///  Gets or sets a value indicating whether the dialog box shows a preview for selected files.
        /// </summary>
        [DefaultValue(false)]
-       public bool ForcePreviewPaneOn { get; set; }
+       public bool ShowPreview { get; set; }

        /// <summary>
-       /// Controls whether read-only items are returned.
+       ///  Gets or sets a value indicating whether the dialog box allows to select read-only files.
        /// </summary>
        [DefaultValue(true)]
-       public bool ReadOnlyReturn { get; set; }
+       public bool IgnoreReadOnly { get; set; } = true;
    }
}
```

```diff
namespace System.Windows.Forms
{
    public partial class SaveFileDialog
    {
        /// <summary>
-       ///  Controls whether to always open the Save As dialog box in expanded mode.
+       ///  Gets or sets a value indicating whether the dialog box is always opened in the expanded mode.
        /// </summary>
        [DefaultValue(true)]
-       public bool ExpandedMode { get; set; }
+       public bool ExpandedMode { get; set; } = true;

        /// <summary>
-       ///  Controls whether to create a test file.
+       ///  Gets or sets a value indicating whether the dialog box verifies whether creation of the specified file will be successful. 
+       ///  If this flag is not set, the calling application must handle errors, such as denial of access, discovered when the item is created.
        /// </summary>
        [DefaultValue(true)]    <-- what's the default behaviour now?
-       public bool TestFileCreate { get; set; } 
+       public bool CheckWriteAccess { get; set; }
    }
}
```

```diff
namespace System.Windows.Forms
{
    public partial class FolderBrowserDialog
    {
        /// <summary>
-       ///  Controls whether to add the folder being selected to the recent list.
+       ///  Gets or sets a value indicating whether the dialog box adds the folder being selected to the recent list.
        /// </summary>
        [DefaultValue(true)]
-       public bool AddToRecent { get; set; }
+       public bool AddToRecent { get; set; } = true;


        /// <summary>
-       ///  Controls whether to include hidden and system items.
+       ///  Gets or sets a value indicating whether the dialog box displays hidden and system files.
        /// </summary>
        [DefaultValue(false)]
-       public bool ForceShowHiden { get; set; }
+       public bool ShowHiddenFiles { get; set; }

        /// <summary>
-       ///  Controls whether the items shown by default in the view's navigation pane are hidden.
+       ///  Gets or sets a value indicating whether the items shown by default in the view's navigation pane are hidden.
        /// </summary>
-       [DefaultValue(false)]
-       public bool HidePinnedPlaces { get; set; }
+       [DefaultValue(true)]
+       public bool ShowPinnedPlaces { get; set; } = true;

        /// <summary>
-       ///  Controls whether the OK button needs interaction before it is enabled.
+       ///  Gets or sets a value indicating whether the OK button of the dialog box is disabled until the user navigates the view or edits the filename (if applicable).
        /// </summary>
+       /// <remarks>
+       ///  Note: Disabling of the OK button does not prevent the dialog from being submitted by the Enter key.
+       /// </remarks>
        [DefaultValue(false)]
-       public bool OkButtonNeedsInteraction { get; set; }
+       public bool OkRequiresInteraction { get; set; }
    }
}
```

I'm a little ensure about the proposed default value for the `TestFileCreate` - what's the current implementation's behaviour?
```cs
[DefaultValue(true)] 
public bool TestFileCreate { get; set; } 
```

Please let me know if you have any questions or objections. If not, please update your proposal, and then I think we'll be ready to pass it on to the API Review Board.
Thanks

**Comment by willibrandon** [comment] 2021-11-21 04:37
Those tweaks look good to me, thanks for taking a look. The proposed default value for `TestFileCreate`, or `CheckWriteAccess` should be true which is the current default behavior. I'll update the proposal with your suggestions and if you have any other thoughts on `CheckWriteAccess` please let me know.

**Comment by willibrandon** [comment] 2021-11-21 20:30
The proposal has been updated and thank you for the suggestions @RussKie.

**Comment by RussKie** [comment] 2021-11-22 00:56
Thank you. Marking as ready for review by the API Review Board. 
The review may take awhile, once the proposal is reviewed a member of the ARB will post here.

**Comment by terrajobst** [comment] 2021-11-23 18:19
* Makes sense
* Do we/should we replicate some of these in WPF's dialog (`OpenFileDialog` and `SaveFileDialog`)?

```C#
namespace System.Windows.Forms
{
    public partial class FileDialog
    {
        [DefaultValue(true)]
        public bool AddToRecent { get; set; } = true;

        [DefaultValue(false)]
        public bool ShowHiddenFiles { get; set; }

        [DefaultValue(true)]
        public bool ShowPinnedPlaces { get; set; } = true;

        [DefaultValue(false)]
        public bool OkRequiresInteraction { get; set; }
    }
    public partial class OpenFileDialog
    {
        [DefaultValue(false)]
        public bool ShowPreview { get; set; }

        [DefaultValue(false)]
        public bool SelectReadOnly { get; set; }
    }
    public partial class SaveFileDialog
    {
        [DefaultValue(true)]
        public bool ExpandedMode { get; set; } = true;

        [DefaultValue(true)]
        public bool CheckWriteAccess { get; set; } = true;
    }
    public partial class FolderBrowserDialog
    {
        [DefaultValue(true)]
        public bool AddToRecent { get; set; } = true;

        [DefaultValue(false)]
        public bool ShowHiddenFiles { get; set; }

        [DefaultValue(true)]
        public bool ShowPinnedPlaces { get; set; } = true;

        [DefaultValue(false)]
        public bool OkRequiresInteraction { get; set; }
    }
}

**Comment by RussKie** [comment] 2021-11-23 23:28
Thank you @terrajobst.
@willibrandon would you like to submit a PR with an implementation?

**Comment by willibrandon** [comment] 2021-11-23 23:45
Yes!

**Comment by willibrandon** [comment] 2021-11-28 06:03
I can investigate replicating these in WPF.

**Comment by RussKie** [comment] 2021-11-29 00:19
Great! Though I suggest to raise an issue in https://github.com/dotnet/wpf with a proposal and wait for a formal ack from the @dotnet/wpf-developers before investing too much time in this.

**Closed** 2021-12-15 00:43 UTC
Labels: api-suggestion, api-approved, :construction: work in progress, tenet-OS-compat

**Comment by willibrandon** [comment] 2021-12-15 02:11
@roland5572 - Thank you for the good idea.

**Comment by roland5572** [comment] 2021-12-16 03:08
@willibrandon Thank you. I also found a possibility to increase the speed of WPF controls and save WPF system resources. I have updated the test results in this case.

https://github.com/dotnet/wpf/discussions/5582
