### ISSUE TITLE
MDI forms lost sub control box

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3029] opened 2020-04-02 06:27 UTC
* .NET Core Version: 

* Have you experienced this same bug with .NET Framework?: 
No 

**Problem description:**

* .NET 5 current master and Preview2
![image](https://user-images.githubusercontent.com/4403806/78217022-dd396080-7506-11ea-8cfe-d3b17af582c9.png)

* .NET Core 3.1
![image](https://user-images.githubusercontent.com/4403806/78217036-e4f90500-7506-11ea-8d4b-0f60d20c8b1f.png)

**Expected behavior:**

.NET 5 variant must look like .NET Core 3.1 variant.

**Minimal repro:**

Run a repro app provided in #2979

**Comment by RussKie** [comment] 2020-04-02 08:10
Had two hours of "fun" bisecting, and it looks like we regressed back on 13 Nov 2019 in 07ae71178eda9d1e4ebf73be44879d969cea7dc5 😱 
Somewhat surprised this went unnoticed for so long... @Vino-Wang looks like we have a gap.

I still need to go through the diff (which is massive) to see what caused it. 
🤔 Not sure what to look for tbh, @JeremyKuhne @weltkante if you have any hints - they are appreciated.

**Comment by weltkante** [comment] 2020-04-02 08:15
I took a quick look over Form.cs and what stands out regarding MDI forms is the removal of the "merged menu". Might have slipped up and left a bool or other variable in the wrong default state when removing the code. I might be able to debug later today.

**Comment by weltkante** [comment] 2020-04-02 19:09
[this line](https://github.com/dotnet/winforms/commit/07ae71178eda9d1e4ebf73be44879d969cea7dc5#r38239371) is the regression. Can't seem to link directly for some reason, probably because the diff is so large? Its line 6081 in the diff of Form.cs in the commit linked above, within `UpdateMenuHandles` method an interop call for `WM_MDISETMENU` occurred even if no deprecated HMENU was configured by the user. I believe removing this interop call leads to the regression, because when I'm on a working build and skip this line I get the behavior you observe on master.

I think this can be fixed without reintroducing `MainMenu` and `Menu` classes, you just need to manufacture an appropriate `HMENU` directly via interop instead of using the WinForms convenience classes. Need to be careful to do proper cleanup though, to not introduce any leaks.

**Comment by merriemcgaw** [comment] 2020-04-02 23:12
Great investigation @weltkante! Thanks a ton!

**Comment by RussKie** [comment] 2020-06-16 06:24
I've started going through history again, and ran tests against 3.1.2, and it appears to be a regression all the way back to 3.1... So we'll need to service it.

**Comment by RussKie** [comment] 2020-06-17 06:22
I've compared net472 vs netcore3.1

<details>
<summary>Click for lots of pretty pictures...</summary>

| Parent | Child | Screenshot | Screenshot |
|--- | --- |--- | --- |
| - | - | ![image](https://user-images.githubusercontent.com/4403806/84857307-13b95d00-b0ac-11ea-9c79-fa921f61ce2e.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860225-0a32f380-b0b2-11ea-9013-e49f78784567.png) | ![image](https://user-images.githubusercontent.com/4403806/84857263-fab0ac00-b0ab-11ea-9639-a6db8f04cff4.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860154-e96a9e00-b0b1-11ea-857f-e46b6916737e.png) |
| `Controls.Add(menuStrip)`, `MainMenuStrip` = null | - | ![image](https://user-images.githubusercontent.com/4403806/84857740-0b155680-b0ad-11ea-9ed6-3cb26a48d63e.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860431-59792400-b0b2-11ea-916d-aca30e4e0f42.png) | ![image](https://user-images.githubusercontent.com/4403806/84857729-0355b200-b0ad-11ea-9356-4f320db58ae8.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860422-541bd980-b0b2-11ea-975f-c8cdd6e651b7.png) |
| `Controls.Add(menuStrip)`, `MainMenuStrip` = `menuStrip` | - | ![image](https://user-images.githubusercontent.com/4403806/84857660-e325f300-b0ac-11ea-9edc-fb84de7b7e6d.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860571-9cd39280-b0b2-11ea-97d2-79c62d4d4853.png) | ![image](https://user-images.githubusercontent.com/4403806/84857651-dacdb800-b0ac-11ea-80e7-d5b0d1dfc5cc.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860539-904f3a00-b0b2-11ea-9c4a-63e539aa1855.png) |
| - | `Controls.Add(menuStrip)`, `MainMenuStrip` = null | ![image](https://user-images.githubusercontent.com/4403806/84858292-3a789300-b0ae-11ea-829d-beaf0c54e8a0.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860742-f2a83a80-b0b2-11ea-9009-b22867cfd122.png) | ![image](https://user-images.githubusercontent.com/4403806/84858274-30ef2b00-b0ae-11ea-8478-d4bec4ce8bad.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860730-ecb25980-b0b2-11ea-9053-3ca3e74f7256.png) |
| - | `Controls.Add(menuStrip)`, `MainMenuStrip` = `menuStrip` | ![image](https://user-images.githubusercontent.com/4403806/84858434-81ff1f00-b0ae-11ea-8540-359f7d5a2992.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860806-153a5380-b0b3-11ea-97cb-41330d267ebc.png) | ![image](https://user-images.githubusercontent.com/4403806/84858445-87f50000-b0ae-11ea-981e-6ed729df8564.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84860798-11a6cc80-b0b3-11ea-9eda-4befca74d4a9.png) |
| `Controls.Add(menuStrip)`, `MainMenuStrip` = null | `Controls.Add(menuStrip)`, `MainMenuStrip` = `menuStrip` | ![image](https://user-images.githubusercontent.com/4403806/84859995-95f85000-b0b1-11ea-8b01-5d2a680d3d67.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84859877-5598d200-b0b1-11ea-8613-98574aa498f7.png) | ![image](https://user-images.githubusercontent.com/4403806/84858593-d6a29a00-b0ae-11ea-8d55-620fa5b1b8f0.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84859882-5a5d8600-b0b1-11ea-93b9-eb25daa95576.png) |
| `Controls.Add(menuStrip)`, `MainMenuStrip` = `menuStrip` | `Controls.Add(menuStrip)`, `MainMenuStrip` = null | ![image](https://user-images.githubusercontent.com/4403806/84859645-eae79680-b0b0-11ea-9648-ae822ee96539.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84859565-c2f83300-b0b0-11ea-9375-8ff3d8117918.png) | ![image](https://user-images.githubusercontent.com/4403806/84858815-3bf68b00-b0af-11ea-93b7-a5e44152670c.png)<br/>![image](https://user-images.githubusercontent.com/4403806/84859545-bc69bb80-b0b0-11ea-83c5-c2b66e0981cf.png) |
| `Controls.Add(menuStrip)`, `MainMenuStrip` = `menuStrip` | `Controls.Add(menuStrip)`, `MainMenuStrip` = `menuStrip` | ![image](https://user-images.githubusercontent.com/4403806/84859449-8f1d0d80-b0b0-11ea-9416-4378dd8c2535.png)<br />![image](https://user-images.githubusercontent.com/4403806/84859302-33eb1b00-b0b0-11ea-8829-c5af9a0c3787.png) | ![image](https://user-images.githubusercontent.com/4403806/84858845-4dd82e00-b0af-11ea-8b65-c0763496b85b.png)<br />![image](https://user-images.githubusercontent.com/4403806/84859277-2a61b300-b0b0-11ea-863d-a168c0d964c7.png) |

</details>

1. So it looks like there's only one scenario where it is severely broken - both parent and child forms don't have `MainMenuStrip` set nor have it added to the `Controls` collection. 

    | net472 | netcoreapp3.1 |
    | -- | --- |
    | ![image](https://user-images.githubusercontent.com/4403806/84857263-fab0ac00-b0ab-11ea-9639-a6db8f04cff4.png) | ![image](https://user-images.githubusercontent.com/4403806/84860154-e96a9e00-b0b1-11ea-857f-e46b6916737e.png) |

There are other smaller issues such as:

2. When a parent form doesn't have `MainMenuStrip` property  set  the child's main menu is rendered differently:

    | net472 | netcoreapp3.1 |
    | -- | --- |
    | ![image](https://user-images.githubusercontent.com/4403806/84858274-30ef2b00-b0ae-11ea-8478-d4bec4ce8bad.png) | ![image](https://user-images.githubusercontent.com/4403806/84860730-ecb25980-b0b2-11ea-9053-3ca3e74f7256.png) |

3. Different control box glyphs in net472 version depending on whether a parent has `MainMenuStrip` property set.

4. Both in net472 and netcoreapp an active child has a blank main menu which is merged with a parent's main menu:

    | net472 | netcoreapp3.1 |
    | -- | --- |
    | ![image](https://user-images.githubusercontent.com/4403806/84859449-8f1d0d80-b0b0-11ea-9416-4378dd8c2535.png) | ![image](https://user-images.githubusercontent.com/4403806/84859302-33eb1b00-b0b0-11ea-8829-c5af9a0c3787.png) |


The plan is to only fix #1 and service it in 3.1. No action for other points.

**Comment by kirsan31** [comment] 2020-06-17 07:01
@RussKie
> Somewhat surprised this went unnoticed for so long...

>So it looks like there's only one scenario where it is severely broken - both parent and child forms don't have MainMenuStrip set nor have it added to the Controls collection.

Yea, the reason of not detecting it so long is that  99% of people using the MDI with MainMenuStrip, and with MainMenuStrip everything is fine :)

**Comment by RussKie** [comment] 2020-06-17 07:13
Yep, figured as much :)

**Comment by aaronchch** [comment] 2020-12-18 03:03
I'm having this problem with .NET 5.0.1
I can't find any scenario where the minimise, restore and close buttons are shown when the MDI child is maximized.
Setting a MainMenuStrip on the parent, child or both doesn't show them

Is there any kind of workaround for this before .NET 6?

**Comment by RussKie** [comment] 2020-12-18 07:21
@aaronchch can you provide a repro to investigate?

**Comment by kirsan31** [comment] 2020-12-18 08:22
@RussKie uuuuuups 😭 It's seems like a regression from 3.1 😭😭😭 
I noticed this at the very last moment before the release of our application (3.1 -> 5.0). I will provide a repro shortly, but I think there will be nothing special...

**Comment by kirsan31** [comment] 2020-12-18 08:28
Yes, nothing special: [Mdi.zip](https://github.com/dotnet/winforms/files/5714528/Mdi.zip)

![image](https://user-images.githubusercontent.com/17767561/102592197-2cbacd80-4124-11eb-8a62-212261320264.png)

**Comment by weltkante** [comment] 2020-12-18 11:20
I already located the point of the regression earlier above. Some usage of HMENU is required, which was accidently removed. It needs to replaced by direct interop instead.

**Comment by kirsan31** [comment] 2020-12-18 11:35
@weltkante I mean that in .net5 it broken even with `MainMenuStrip`, in 3.1 only without it ([#1](https://github.com/dotnet/winforms/issues/3029#issuecomment-645176986)).

**Comment by weltkante** [comment] 2020-12-18 12:17
Yes I think thats what this issue is about.

**Comment by kirsan31** [comment] 2020-12-18 13:15
> Yes I think thats what this issue is about. Note that the top post already is talking about a .NET 5 vs 3.1 regression, not a regression in 3.1

Then I don't understand anything at all - how could this have gone into the 5.0 release ? :astonished:

**Comment by weltkante** [comment] 2020-12-18 14:50
Looking through the discussion history again I think the ".NET 5 vs 3.1" regression got mixed up with the general "net472 vs netcore3.1" issue and was probably lost track of, unfortunate.

**Comment by kirsan31** [comment] 2020-12-18 14:56
> Looking through the discussion history again I think the ".NET 5 vs 3.1" regression got mixed up with the general "net472 vs netcore3.1" issue and was probably lost track of, unfortunate.

Yea, it looks like this :(

**Comment by aaronchch** [comment] 2020-12-20 20:53
The problem I'm having is shown and described in issue #4388:

The Minimize, Restore and Close buttons are on the menu but they aren't visible. Mousing over the right hand end of the menu bar shows a narrow outline of the button which can be clicked and behaves correctly. The buttons can be used but can't be seen.

It seems like the images aren't being shown so the buttons have zero width.

Maybe #4388 isn't a duplicate of this after all.

**Comment by kirsan31** [comment] 2020-12-20 21:28
@aaronchch nope this is exactly same issue. And yeas you are right all 3 buttons are there and usable, but with 0 width:
![mdi](https://user-images.githubusercontent.com/17767561/102724793-33636380-4323-11eb-9647-291130d6834e.gif)

**Comment by RussKie** [comment] 2020-12-21 05:37
Yes, it looks like a different bug. Investigating.

**Comment by RussKie** [comment] 2020-12-21 13:24
#4388 is a dup, I just never realised the buttons were the all along. @kirsan31 I ran your sample on a 5.0-rc2, and the issue was there, so it would be the result of bad merge of 3.1->5.0.

I do kind of feel like an archeologist, dig through an ancient codebase, not really knowing where to start. Here's my understanding of how MDI control box is working. Posting here to provide more context, and so I can recall after I'm back from holidays.

Whenever an MDI windows is being maximised or minimised there's a call to update MDI parent's toolstrip:
https://github.com/dotnet/winforms/blob/4bca5b30aea871a2c1761b39f8ff8128cb155119/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L5613
If the child is being maximised - we merge its menu into the main menu of the parent (line:5671):
https://github.com/dotnet/winforms/blob/4bca5b30aea871a2c1761b39f8ff8128cb155119/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L5654-L5676
For that we create `MdiControlStrip` that contains three buttons: "Minimize", "Maximize" and "Close":
https://github.com/dotnet/winforms/blob/4bca5b30aea871a2c1761b39f8ff8128cb155119/src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs#L32-L40
These buttons get native Windows images for respective operations via `GetNativeMenuItemImage()` call, which retrieves those via 
https://github.com/dotnet/winforms/blob/4bca5b30aea871a2c1761b39f8ff8128cb155119/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs#L795-L800
...and fails. Because the default system menu doesn't have any images.

Notice the menu in .NET 5.0 version doesn't have any images:
![image](https://user-images.githubusercontent.com/4403806/102779842-08dbde00-43e9-11eb-8fd7-7639507e6876.png)

Whilst in .NET Framework does:
![image](https://user-images.githubusercontent.com/4403806/102779918-2315bc00-43e9-11eb-88ed-7751a33eb8f6.png)

Just for laughs I decided to set images manually, and voila:
![image](https://user-images.githubusercontent.com/4403806/102780082-738d1980-43e9-11eb-9ba0-0852207ca5a6.png)

#3461 addresses the issue by creating a new menu, which has images (magic?). Granted that PR isn't complete like-for-like, and needs further work.

I wouldn't be surprised and there are still things that missed, and hopefully @JeremyKuhne and @weltkante can help me filling the gaps.

**Comment by RussKie** [comment] 2020-12-22 02:04
I've been playing with .NET Framework implementation, and it appears it isn't terribly difficult to confuse the runtime into something like this:
![image](https://user-images.githubusercontent.com/4403806/102838072-5ee46c00-4451-11eb-9aaa-dcd0087794ff.png)

![mdi-controlbox](https://user-images.githubusercontent.com/4403806/102838663-e1b9f680-4452-11eb-8b46-2be366feb3f2.gif)

1. check all boxes 
5. maximise the child
6. unckeck "set child menustrip"
7. uncheck "add parent menustrip to Control"
8. uncheck "set parent menustrip"
9. uncheck "add menustrip to Control"
10. check "set parent menustrip" - this causes the child to set to "normal" style, although one could see the visual artifacts as if the title bar is covered, and the form can't be moved.
![image](https://user-images.githubusercontent.com/4403806/102839361-753ff700-4454-11eb-95ab-5a8b80ba58ae.png)
11. check all boxes again
12. set the child's mode to "normal", and see that the form has different dimensions and position
13. maximise the form
14. uncheck "add parent menustrip to Control" - observe multiple menus and control boxes


However it doesn't behave the same way in .NET Core 3.1. No matter what I tried I could never get step 7 to trigger, both forms and their behaviours remain stable.

Repro: https://github.com/RussKie/Test-MdiBehaviours

**Comment by kirsan31** [comment] 2020-12-22 07:45
This is _nice_ too:

![image](https://user-images.githubusercontent.com/17767561/102860357-bf1de280-443e-11eb-818c-8e49f62c0f7a.png)

1. check "set parent menustrip" + "add parent menustrip to Control"
2. maximize the child
3. uncheck "set parent menustrip"
4. check "set parent menustrip"

And your first screen can be obtained with fewer steps (I've optimized the scheme 🤣  ):
1. maximize the child
2. check "set parent menustrip"
3. uncheck "set parent menustrip"

Than simple cycle 2. and 3. Each uncheck of "set parent menustrip" will add one more set of icons:

![image](https://user-images.githubusercontent.com/17767561/102861945-6e5bb900-4441-11eb-8235-974d4ea0cd5a.png)

And yes .NET Core 3.1 work good. But if we look at last sequence above, I think we get the source why - becouse .NET Core 3.1 have no sub control box in case we have no menustrip at all...

**Comment by weltkante** [comment] 2020-12-29 00:38
I've looked through the regressing diff a bit more and noticed we were also losing some live code paths in `InvalidateMergedMenu` which was triggering an `UpdateMenuHandles` via `MenuChanged` even if there was no classic `Menu` in use. Restoring that refresh code path seems to fix at least some cases of the double menu icons.

[see here](https://github.com/dotnet/winforms/compare/master...weltkante:issue3029) for what I've been playing around with, its a bit different from your branch (not using a dedicated variable) and I've had no time to adapt the changeset to your branch, but I figured its better to post now rather than wait until I can get around to revisit this. Maybe you can incorporate the missing refresh logic in your branch and see if that gets you closer to .NET Core 3.1 / Desktop behavior.

**Comment by kirsan31** [comment] 2020-12-29 07:42
@weltkante 

> I've looked through the regressing diff a bit more and noticed we were also losing some live code paths in InvalidateMergedMenu which was triggering an UpdateMenuHandles via MenuChanged even if there was no classic Menu in use. Restoring that refresh code path seems to fix at least some cases of the double menu icons.

Sorry but I am a bit confuse here. How restoring of loosing code can fix double menu icons? As I understand for now:
- .NET Framework implementation can lead to duplication of menu icons.
- .NET Core 3.1 have no duplication problem but also no menu without menustrip.
- NET 5 have no visible menu at all.

**Comment by weltkante** [comment] 2020-12-29 10:19
There are probably multiple bugs, I was focusing on the regression. Whether it was a regression against .NET Core 3.0 or 3.1 I'm a bit confused, the code didn't seem to go into 3.1 but maybe I was mistaken. Anyways, fixing the regression I mentioned earlier leads to visible menus but with more cases of duplication. If I'm late and this issue is getting fixed in an entirely different way than sending `WM_MDISETMENU` then you can ignore my comment, but if you are intending to restore the regressed `WM_MDISETMENU` logic then you are missing some refreshes leading to duplicate icons even in simple cases which did not have them before. So while you can fix the duplicate icons differently to cover more cases its probably a good idea anyways to look at why these additional refreshes where necessary.

**Comment by RussKie** [comment] 2021-01-11 05:32
> Had two hours of "fun" bisecting, and it looks like we regressed back on 13 Nov 2019 in [07ae711](https://github.com/dotnet/winforms/commit/07ae71178eda9d1e4ebf73be44879d969cea7dc5) 😱

I then rolled back to 922e41002e66fb10d703705d9be700c8b30cd63d ([my branch](https://github.com/dotnet/winforms/compare/master...RussKie:investigate_3029/Last-31-can-build)), the last commit on 3.1 branch before the merge, it is working as far as the broken use case is concerned: 
![image](https://user-images.githubusercontent.com/4403806/104144226-7d1d0680-5416-11eb-921e-ca8a3d0c9b56.png)

I then rolled back to a0e12b1408ae45a3cc08dfd3e928c9ab8b5a45df ([my branch](https://github.com/dotnet/winforms/compare/master...RussKie:investigate_3029/Last-50-can-build)), the last commit on 5.0 branch before the merge, and with [global.json some trickery](https://github.com/dotnet/winforms/compare/master...RussKie:investigate_3029/Last-50-can-build#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bf) was able to build it.
The broken use case is working correctly too:
![image](https://user-images.githubusercontent.com/4403806/104143976-a8532600-5415-11eb-9ce3-58f0b82e51b6.png)

I then build 07ae71178eda9d1e4ebf73be44879d969cea7dc5 and lo and behold the icons are there:
![image](https://user-images.githubusercontent.com/4403806/104146425-c07b7300-541e-11eb-9fbd-736d7e16082b.png)

...3 hours bisecting later...

The the images disappeared in https://github.com/dotnet/winforms/pull/2659 (21821568afe4f566f2d18cfece56cff666de1955)



> There are probably multiple bugs, I was focusing on the regression.

So, yes, there are two distinct issues here:
1. the loss of icons in certain scenarios,
2. the loss of the control box in some other scenarios.

**Comment by weltkante** [comment] 2021-01-11 07:15
@RussKie the `GetNativeMenuItemImage` [forgets](https://github.com/dotnet/winforms/pull/2659/files#diff-11fe12eb7c6539c7a155fed536e0da2f3afbfc2eaa82ff4adece9f8dbb65ddf4R815-R817) to set the size of the struct (previously done in the constructor when it was still a class).

**Comment by RussKie** [comment] 2021-01-11 10:05
> he `GetNativeMenuItemImage` [forgets](https://github.com/dotnet/winforms/pull/2659/files#diff-11fe12eb7c6539c7a155fed536e0da2f3afbfc2eaa82ff4adece9f8dbb65ddf4R815-R817) to set the size of the struct (previously done in the constructor when it was still a class). All others in this PR do have the size assignment, its the only call where its missing.

Thank you, I started going mad at this point :)
I confirm the fix.

**Closed** 2021-01-14 01:44 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress

**Comment by Zheng-Li01** [comment] 2021-01-22 07:48
Verified the issue with latest 6.0 SDK 6.0.100-preview.1.21071.29 that the issue has been fixed, the MDI forms show sub control box correctly. see below screenshot.
![3029](https://user-images.githubusercontent.com/38325459/105462186-3ad2af80-5cc9-11eb-83f2-728554b4ca51.PNG)

**Comment by Zheng-Li01** [comment] 2021-01-26 10:00
Verified the issue with 5.0.103-servicing.21073.8 that the issue has been fixed, the MDI forms show sub control box correctly.
