### ISSUE TITLE
Flaky test: `RichTextBox_Text_GetWithHandle_ReturnsExpected`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4347] opened 2020-12-10 02:21 UTC
**Problem description:**

Few variations, but generally the failing point is this:
```
    System.Windows.Forms.Tests.RichTextBoxTests.RichTextBox_Text_GetWithHandle_ReturnsExpected [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: a?b
      Actual:   ?b
                 (pos 0)
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs(6918,0): at System.Windows.Forms.Tests.RichTextBoxTests.RichTextBox_Text_GetWithHandle_ReturnsExpected()
```

The test started failing repeatedly recently, in x86 and only on the public CI.

Observed:
- Reported https://github.com/dotnet/winforms/pull/4342#issuecomment-741741593
- https://dev.azure.com/dnceng/public/_build/results?buildId=913908&view=results

**Comment by JeremyKuhne** [comment] 2021-07-16 01:27
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: a b
Actual:    b
          ↑ (pos 0)
```

**Comment by dreddy-work** [comment] 2023-03-11 23:59
Dupe of #6609

**Closed by dreddy-work** 2023-03-11 23:59 UTC
Labels: test-bug
