### ISSUE TITLE
Major regression in Form.ShowDialog(IWin32Window) in .NET 7 -- ship blocker for Paint.NET 5.0

### ISSUE THREAD

**Issue by rickbrew** [dotnet/winforms#8280] opened 2022-11-24 17:37 UTC
### .NET version

7.0.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it worked fine in .NET 5 and .NET 6

### Issue description

When `Form.ShowDialog(IWin32Window)` is called with a `Control` instead of a `Form`, the dialog's parenting/ownership is not set correctly, causing the dialog to not "track" with the parent form correctly.

The most visible symptom of this is that if you switch between virtual desktops, the parent form is correctly hidden but the dialog is not. And, it is possible to interact with the main window in certain ways. In my app (Paint.NET), it is possible to switch between images by using the taskbar (kind of like how IE/Edge used to let you switch between tabs). This is normally prevented when a modal dialog is active, but right now it's not. This can result in actions affecting the wrong image, which then corrupts the state of the image's change history and causes data loss.

Another symptom is that the `Owner` for the dialog is `null`, even though it should probably be `control.FindForm()`

**This is currently a ship-blocker for Paint.NET 5.0 on .NET 7**. I cannot release the new version with this bug.

Known workaround: use `dialog.ShowDialog(control.FindForm()` instead of `dialog.ShowDialog(control)`. However, this requires changes to _many_ places in the code, and is not a fix I can apply to libraries or plugins.

I believe this regressed due to https://github.com/dotnet/winforms/pull/3394 cc @dreddy-work which changed whether `Owner` was set _or_ `SetWindowLong(..., GWL.HWNDPARENT, ...)` was called. Previously, `SetWindowLong` was always called.

### Steps to reproduce

Create a Form and do `Application.Run(form)`. Make sure the Form has at least 1 child control, like a `button`.
In some code within the form, like in the `button`'s click handler, create another Form and call `dialog.ShowDialog(button)`
While the dialog is open, switch between virtual desktops using WinKey+Shift+Left/Right

**Comment by rickbrew** [comment] 2022-11-24 17:39
A public alpha of Paint.NET 5.0 is available here: https://forums.getpaint.net/topic/121340-paintnet-50-alpha-build-8361-welcome-to-paintnet-50/

You can use the portable version of the app to reproduce this bug. Simply launch the app, and then click on Help -> About. The dialog will not track correctly with the main window if you do something like switch between virtual desktops.

"Native" windows work fine -- e.g. if you click on File -> Open.

**Comment by rickbrew** [comment] 2022-11-24 18:58
Here's a minimal repro. While it doesn't exhibit the issue I described when switching between virtual desktops, it _does_ exhibit the symptom whereby a modal dialog's `Owner` property is non-null in .NET 6, and `null` in .NET 7. You can set a breakpoint in the `Click` handler, where I've left a comment about it:

[ShowDialogBug.zip](https://github.com/dotnet/winforms/files/10086878/ShowDialogBug.zip)

**Comment by elachlan** [comment] 2022-11-24 22:00
@Olina-Zhang Will your team need to test this?

**Comment by Olina-Zhang** [comment] 2022-11-25 02:07
Tested this issue in .Net 6.0, 7.0 and the latest 8.0 builds using above sample application: can reproduce it in .Net 7.0 and 8.0.
[ShowDialogBug.zip](https://github.com/dotnet/winforms/files/10088087/ShowDialogBug.zip)

.Net 6.0:
![image](https://user-images.githubusercontent.com/26474449/203885878-1a88f67c-50f4-4462-a18a-362c112ef3ce.png)

.Net 7.0 and 8.0:
![image](https://user-images.githubusercontent.com/26474449/203885887-fe750d52-4fe3-46e0-9965-b07d0fe36710.png)

**Comment by rickbrew** [comment] 2022-11-25 17:13
What is the earliest that a fix could go out? I may need to roll back to .NET 6, as this is a massive break.

(This isn't meant as a nag -- I'm just trying to understand the possible timeline so I can plan accordingly)

**Comment by dmitrii-drobotov** [comment] 2022-11-25 18:01
Looks like the regression was introduced in https://github.com/dotnet/winforms/pull/5791:

![image](https://user-images.githubusercontent.com/102954094/204035618-412cdb53-bdf1-4ce9-aed7-89fed0c624a7.png)

Previously it meant that owner **does not** have a `TOPMOST` style, but now it checks if it **does** have it. So fix should be following
```diff
-if ((owner != null) && owner.GetExtendedStyle().HasFlag(User32.WS_EX.TOPMOST))
+if ((owner != null) && !owner.GetExtendedStyle().HasFlag(User32.WS_EX.TOPMOST))
```
at:
https://github.com/dotnet/winforms/blob/5a28fa9c294581314d5675188316fbf09882c114/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L5257-L5264


And also the same typo is present in `Form.Show` method:
https://github.com/dotnet/winforms/blob/5a28fa9c294581314d5675188316fbf09882c114/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L5184-L5191

I can confirm that with this fix, your sample app doesn't have the issue:
![image](https://user-images.githubusercontent.com/102954094/204034751-44eb5db4-fea3-4ebd-97fb-6307012a5c44.png)

**Comment by rickbrew** [comment] 2022-11-25 18:10
That's great news! Is there any chance of getting this fixed for 7.0.1?

**Comment by dmitrii-drobotov** [comment] 2022-11-25 18:27
> That's great news! Is there any chance of getting this fixed for 7.0.1?

I'm personally not sure, but I think someone from @dotnet/dotnet-winforms could clarify.

**Comment by dmitrii-drobotov** [comment] 2022-11-25 19:03
Submitted fix for .NET 8: https://github.com/dotnet/winforms/pull/8283

**Comment by rickbrew** [comment] 2022-11-25 19:24
> I'm personally not sure, but I think someone from @dotnet/dotnet-winforms could clarify.

Okay. This being a ship-blocker for me, I may have to rollback to .NET 6 if I can't get a fix of some kind soon enough.

**Comment by merriemcgaw** [comment] 2022-11-25 21:19
@dmitrii-drobotov great work getting a fix out so quickly, especially while the Redmond team is on vacation! @Olina-Zhang can you please test this as soon as possible? I'll want to be able to take this to shiproom on Monday/Tuesday.

@rickbrew - I can't make promises with 100% certainty, but what I can say is that we're well past our deadline for the December servicing release, but we can (just) get this in for the January release. I don't think we have any concerns here about business impact, etc, so we just have to get it in and tested early next week. Assuming we do well with all of that, we will be able to ship with the January patch Tuesday release.

FYI @JeremyKuhne , @lonitra, @dreddy-work

**Comment by rickbrew** [comment] 2022-11-26 17:18
I built my own version of System.Windows.Forms.dll with the fix, and I can thankfully confirm that it does fix the issues I was seeing in Paint.NET

Looks like I'll have to ship my own S.W.F.dll for the time being, but this is preferable to rolling back to .NET 6. phew!

**Comment by Amy-Li03** [comment] 2022-11-28 09:27
Hi @merriemcgaw , tested [private binaries](file://mlangfs1/public/Winforms/v-jiaol/bug/8280) built by us for PR: [#8283](https://github.com/dotnet/winforms/pull/8283) based on the latest .NET 8.0 SDK build, this issue [8280](https://github.com/dotnet/winforms/issues/8280) is fixed, we also did some exploratory testing around Form.ShowDialog, no new issue found. In addition, ran migrated automation cases with no new regression issue found too.

**Comment by dreddy-work** [comment] 2022-11-29 18:37
@dmitrii-drobotov , given PR is merged for servicing as well, can you close this issue ?

**Comment by dreddy-work** [comment] 2022-11-29 21:28
@rickbrew, would it be possible to get a private version of paint.NET targeting .NET 8.0? and possibly running in PermonV2 mode? I am working on few changes for permonV2 mode in .NET 8.0 and like to include Paint.Net in my verifications.

**Comment by dmitrii-drobotov** [comment] 2022-11-30 13:59
> @dmitrii-drobotov , given PR is merged for servicing as well, can you close this issue ?

It's not merged into main yet, so I would close the issue once that's done too.

**Closed** 2022-11-30 18:06 UTC
Labels: :boom: regression, :construction: work in progress

**Comment by rickbrew** [comment] 2022-11-30 18:19
> @rickbrew, would it be possible to get a private version of paint.NET targeting .NET 8.0? and possibly running in PermonV2 mode? I am working on few changes for permonV2 mode in .NET 8.0 and like to include Paint.Net in my verifications.

Looks like you already have access to dotnet/paint.net ... let me know via e-mail if you have any questions or problems getting it to build. Should be able to build it as-is for 7 and then modify the runtimeconfig.json/deps.json to target 8, IIUC
