### ISSUE TITLE
Add a theme changer

### ISSUE THREAD

**Issue by MichaelAgarkov** [dotnet/winforms#9917] opened 2023-09-14 09:41 UTC
### Background and motivation

It would be awesome if there would be a function that will change the Control and ControlText variables to make the whole form have different themes, like a dark theme. Maybe also make it match the system settings?

### Alternative Designs

- Specify the colours to anything.
- Make a "theme" collection, where forms can have multiple themes to switch through.

### Risks

Some programs might use a different variable for the form or text colour, in that case it will stay the same.

### Will this feature affect UI controls?

Yes, just a "Theme" selector.

**Comment by elachlan** [comment] 2023-09-14 23:23
These Links might help:
- https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/rendering-controls-with-visual-styles?view=netframeworkdesktop-4.8
- https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.enablevisualstyles?view=windowsdesktop-7.0

**Comment by merriemcgaw** [comment] 2023-09-19 18:36
Thanks for the scenario input! We're looking into this as a possibility for .NET 9. This helps clarify how folks would like to think about the scenario #5166 
I'm going to close this as a duplicate of the above.

**Closed by merriemcgaw** 2023-09-19 18:36 UTC
Labels: api-suggestion
