### ISSUE TITLE
IDesigner interface deosn't take effect in .net core

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/winforms#6186] opened 2021-11-16 02:18 UTC
* .NET Core Version: 
* 6.0.100-rc.2.21505.57

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

I can see "IDesigner" interface is available in official document
[MS document](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.idesigner?view=net-5.0)
![image](https://user-images.githubusercontent.com/51563666/141883724-10f651da-5dff-4490-b28e-d6412208d1b0.png)

![image](https://user-images.githubusercontent.com/51563666/141883467-9b29053d-b018-4a04-83a8-87dccabf817b.png)

I copy example code to a .net framework project and a .net6 project.
```
[DesignerAttribute(typeof(ExampleIDesigner))]
    public class TestControl : System.Windows.Forms.UserControl
    {				
        public TestControl()
        {	
        }
    }

 public class ExampleIDesigner : System.ComponentModel.Design.IDesigner
    {
         // ...
    }
```
When I test in Visual Studio 2022, I found .net6 designer doesn't work. Is this a bug?
Or is Visual Studio 2022 bug? Could you please help me confirm it? Thanks a lot!

**Expected behavior:**

When right click testControl1, there is a menu item "Display Component Name" shows like .NET Framework

**Minimal repro:**

![bug3](https://user-images.githubusercontent.com/51563666/141883672-cd299a05-fce2-4f2e-ba59-e2522323fe4a.gif)
[TestDesignerFeature.zip](https://github.com/dotnet/winforms/files/7542823/TestDesignerFeature.zip)

**Comment by RussKie** [comment] 2021-11-18 00:23
This is a known issue. It is on our radar, and the current plan to get it fixed in one of the upcoming 17.x release.

In general issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

**Closed by RussKie** 2021-11-18 00:23 UTC
Labels: area: VS designer

**Comment by TempeBrennan** [comment] 2021-11-18 02:47
@RussKie Thanks, I got it.
