### ISSUE TITLE
Fix UserControl.DesignMode property

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/winforms#1238] opened 2019-06-27 02:28 UTC
In Framework, there is an issue with UserControl.DesignMode property(more details [here]( https://stackoverflow.com/questions/34664/designmode-with-nested-controls) and I Quote:

> if you nest controls then DesignMode only works for the first level. The second and lower levels DesignMode will always return FALSE. The standard hack has been to look at the name of the process that is running and if it is "DevEnv.EXE" then it must be studio thus DesignMode is really TRUE. The problem with that is looking for the ProcessName works its way around through the registry and other strange parts with the end result that the user might not have the required rights to see the process name. In addition this strange route is very slow. So we have had to pile additional hacks to use a singleton and if an error is thrown when asking for the process name then assume that DesignMode is FALSE. A nice clean way to determine DesignMode is in order. Acually getting Microsoft to fix it internally to the framework would be even better!

I faced this problem just today, so, I hope you fix this in the CorFx version.

**Comment by JeremyKuhne** [comment] 2020-08-11 00:33
Duplicate of #3300

**Closed by JeremyKuhne** 2020-08-11 00:33 UTC
Labels: enhancement

**Comment by VBAndCs** [comment] 2020-08-11 01:12
@JeremyKuhne  
 #3300 is newer!

**Comment by RussKie** [comment] 2020-08-11 01:19
Yes, and there is a discussion about the issue in it.
