### ISSUE TITLE
Automation case about comboBox met an error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#6953] opened 2022-04-02 10:57 UTC
### .NET version

.Net 7.0.100-preview.4.22201.11

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in .Net SDK 7.0 Preview3 build

### Issue description

Automation case about comboBox met an error "Object reference not set to an instance of an object":
![image](https://user-images.githubusercontent.com/26474449/161380079-92c333db-b522-4732-9876-9d1dae1f09f8.png)

### Steps to reproduce

We cannot get a manual repro, just met it when running our internal automation case about ComboBox, get following calll stack:

_System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=System.Windows.Forms.Primitives
StackTrace:
at Interop.WinFormsComWrappers.AutoCompleteWrapper.SetOptions(AUTOCOMPLETEOPTIONS dwFlag)
at System.Windows.Forms.StringSource.Bind(HandleRef edit, AUTOCOMPLETEOPTIONS options)
at System.Windows.Forms.ComboBox.SetAutoComplete(Boolean reset, Boolean recreate)
at MMFComboBox.CustomSource(TParams p) in C:\Users\v-olzhan\Desktop\Automation\MMFComboBox_P1\MMFComboBox_P1\MMFComboBox\MMFComboBox.cs:line 624_

**Comment by kant2002** [comment] 2022-04-02 11:54
Are repro sample available? I think I would be responsible for fixing this one.

**Comment by kant2002** [comment] 2022-04-02 12:55
Sorry, I miss that you cannot create repo. I will take a look then more deeply.

**Comment by kant2002** [comment] 2022-04-02 14:43
From what I see https://github.com/dotnet/winforms/blob/e6eaed651fccbd44852bbf6a55403828172bfb1a/src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs#L53-L65

The issue appears due to race condition when AutoComplete source binded and released handle here https://github.com/dotnet/winforms/blob/40dd779a6ead7ef755a5fef57d38acc31d0792bb/src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs#L2550-L2570
or here 
https://github.com/dotnet/winforms/blob/40dd779a6ead7ef755a5fef57d38acc31d0792bb/src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs#L2006-L2023

so that means probable we should
1. Create combobox
2. start opening autosuggestion
3. either close it, or destroy for this issue to appear.

From my analysis I do not think this is somehow related to https://github.com/dotnet/winforms/pull/6685/files but I have to doublecheck that somehow. @Olina-Zhang does that information rings any bell?

**Comment by kant2002** [comment] 2022-04-03 12:55
[WinFormsApp6953.zip](https://github.com/dotnet/winforms/files/8404533/WinFormsApp6953.zip)
Steps to reproduce attached. I hit issue from first click.

**Comment by RussKie** [comment] 2022-04-04 05:49
> [WinFormsApp6953.zip](https://github.com/dotnet/winforms/files/8404533/WinFormsApp6953.zip)
> Steps to reproduce attached. I hit issue from first click.

:rocket:

**Closed** 2022-04-06 02:12 UTC
Labels: :boom: regression, :construction: work in progress, untriaged

**Comment by Amy-Li03** [comment] 2022-04-08 02:37
Verified this issue on .NET SDK 7.0.100-preview.4.22207.2, issue was fixed.

**Comment by RussKie** [comment] 2022-04-08 02:41
Thank you

**Comment by Olina-Zhang** [comment] 2022-04-28 06:25
Verified this issue in .Net SDK 7.0.100-preview.4.22227.3 test pass build, it was fixed
