### ISSUE TITLE
Several tests fail due to culture being nl-BE

### ISSUE THREAD

**Issue by gero3** [dotnet/winforms#4642] opened 2021-03-04 15:38 UTC
* WinForms Version: 
The main branch of the Winforms Repository

* Have you experienced this same bug with .NET Framework?: 
N/A

**Problem description:**
Multiple tests fail due to the fact that the culture is different. 
- System.Windows.Forms.Tests.LinkAreaConverterTests.LinkAreaConverter_ConvertFrom_InvalidString_ThrowsArgumentException(value: "1,2,3")
- System.Windows.Forms.Tests.LinkAreaConverterTests.LinkAreaConverter_ConvertFrom_String_ReturnsExpected
- System.Windows.Forms.Tests.LinkAreaConverterTests.LinkAreaConverter_ConvertTo_String_ReturnsExpected
- System.Windows.Forms.Tests.LinkConverterTests.LinkConverter_ConvertFrom_InvalidString_ThrowsArgumentException(value: "1,2,3")
- System.Windows.Forms.Tests.LinkConverterTests.LinkConverter_ConvertFrom_String_ReturnsExpected
- System.Windows.Forms.Tests.LinkConverterTests.LinkConverter_ConvertTo_String_ReturnsExpected
- System.Windows.Forms.Tests.OpacityConverterTests.OpacityConverter_ConvertFrom_InvalidString_ThrowsFormatException
- System.Windows.Forms.Tests.OpacityConverterTests.OpacityConverter_ConvertFrom_String_ReturnsExpected
- System.Windows.Forms.Tests.PaddingConverterTests.PaddingConverter_ConvertFrom_String_ReturnsExpected
- System.Windows.Forms.Tests.PaddingConverterTests.PaddingConverter_ConvertTo_String_ReturnsExpected
- System.Windows.Forms.Tests.TableLayoutPanelCellPositionTests.TableLayoutPanelCellPosition_ConverterConvertFrom_InvalidColumn_ThrowsArgumentOutOfRangeException
- System.Windows.Forms.Tests.TableLayoutPanelCellPositionTests.TableLayoutPanelCellPosition_ConverterConvertFrom_InvalidRow_ThrowsArgumentOutOfRangeException
- System.Windows.Forms.Tests.TableLayoutPanelCellPositionTests.TableLayoutPanelCellPosition_ConverterConvertFrom_String_ReturnsExpected
- System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_StatusText_GetWithDocument_ReturnsExpected

**Expected behavior:**
- They should work even if the default culture of a user is different. 

**Minimal repro:**
- Set cultureinfo to nl-BE
- run the tests in

**Comment by weltkante** [comment] 2021-03-04 18:09
duplicate of #2734 - I have a [branch](https://github.com/weltkante/winforms/tree/culture) which works around these issues so you can run tests locally

I'd make a PR but discussion in #2734 has not come to a conclusion yet /cc @RussKie 

(My workaround runs tests only in english but generally the discussion indicates it would be nice to run it in at least another language which differs from english. Not sure how this would look like though so everything is currently stalled there.)

**Comment by RussKie** [comment] 2021-03-04 22:35
We have constrained resources, and some work is shuffled to backburners.
When we migrate to [Helix infra](https://github.com/dotnet/winforms/issues/3140) we should have access to a matrix of build agents, including those running non-English locale (if memory serves me well those are es-ES).

**Comment by RussKie** [comment] 2021-03-04 22:36
Duplicate of #2734

**Closed by RussKie** 2021-03-04 22:36 UTC
Labels: test-bug
