### ISSUE TITLE
[AccessibilityInsight] Luminosity contrast ratio of sorting arrows of DataGridView are less than 3:1 when setting HeaderVisualStyle to false and ColumnHeader.BackColor to any color

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/winforms#6038] opened 2021-10-22 09:30 UTC
* .NET Core Version: 
.NET Core 6.0.100

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
The contrast ratio of sorting arrows are less than 3:1.
![image](https://user-images.githubusercontent.com/54019172/138429104-a30c25a3-cdce-4e8e-9fe8-2de99df341f8.png)

**Expected behavior:**
Luminosity contrast ratio of sorting arrows are greater than 3:1.

**Minimal repro:**
1.	Create a Winfroms .NET core application with a DataGridView control
2.  Add some columns for DataGridView
3.	Setting its EnableHeaderVisualStyle=false, and setting ColumnHeaderDefaultCellStyle.BackColor = ActiveCaption
4.	Build and run application
5.	Observe the contrast ration of sorting arrows

**More info:**
1.	This issue also occurs for other High contrast mode in Win11&Win10.
2.	When just setting HeaderVisualStyle property to false, only a ‘/’ for sorting arrow.
![image](https://user-images.githubusercontent.com/54019172/138429137-b2dcf7da-7634-43d9-bcfa-7bb392af1b0b.png)
![image](https://user-images.githubusercontent.com/54019172/138429149-3a15f1fb-9799-4c58-9e3b-d6feddeff990.png)

**Comment by DmitryGorokhov** [comment] 2022-01-31 08:10
We shouldn't adapt contrast rate if user change styles. It's user responsibility in this case.


>When just setting HeaderVisualStyle property to false, only a ‘/’ for sorting arrow.

This is by design instead of 3D-effect. Looks like the light sticks (horizontal and right side) and the background are the same colors. 

cc @merriemcgaw

**Comment by merriemcgaw** [comment] 2022-01-31 17:05
That seems correct to me. I don't recall why there would be a difference in the sorting arrow - perhaps if you widen the column it's better looking. However, as long as our defaults are satisfactory I think we can close this issue and look at it again if we get a customer complaint.

**Closed by merriemcgaw** 2022-01-31 17:05 UTC
Labels: tenet-accessibility
