### ISSUE TITLE
Control DataBindings do not update when using INotifyPropertyChanged.

### ISSUE THREAD

**Issue by AlanParr** [dotnet/winforms#625] opened 2019-03-22 22:35 UTC
* .NET Core Version: 3.0.100-preview3-010431
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Control bound to a property does not update when INotifyPropertyChanged is triggered. The same code works in Windows Forms on .Net Framework.
Repro example below is for a label, but also tried with a button and saw the same issue.

**Actual behavior:** 
Bound control is not updated when the property is updated.

**Expected behavior:**
Bound control should be updated when the property is updated.

**Minimal repro:**

* Repro zipped for dowload [here](https://parrstorage.blob.core.windows.net/winforms/INPCTest.zip), includes projects for WinForms (Net Framework), WinForms (Net Core), and WPF (Net Core).

* Create a Windows Forms (.Net Core) application.
* Add a class with a property to bind to, example below:

```csharp
public class TestController : INotifyPropertyChanged
    {
        private string simpleStringProperty;

        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

        public TestController()
        {
            SimpleStringProperty = "hi";
        }

        public string SimpleStringProperty
        {
            get => simpleStringProperty;
            set
            {
                simpleStringProperty = value;
                OnPropertyChanged(nameof(SimpleStringProperty));
            }
        }
    }
```
* Add code to form1 ctor
```csharp
            _controller = new TestController();
            label1.DataBindings.Add("Text", _controller, nameof(_controller.SimpleStringProperty));
```

* Add a button and add following code to Click handler
```csharp
_controller.SimpleStringProperty = "hello";
```

* Run the application. The label is set to the initial value of `SimpleStringProperty`, but when the button is clicked, the value is not updated.

* To compare to Windows Forms, carry out the above steps on a Windows Forms (.Net Framework) application and when the button is clicked, the label will update.

**Comment by mikhailovalex** [comment] 2019-03-28 07:12
Hello, I think this is similar to https://github.com/dotnet/corefx/issues/34465

**Comment by merriemcgaw** [comment] 2019-03-29 18:12
@karelz this is a pretty important WinForms scenario. Have you had a chance yet to investigate? We would totally want to have support for this by 3.0 GA.  This issue is probably a duplicate of dotnet/corefx#34465 but we'll keep this open on our side as well to help investigate the end-to-end functionality.

**Comment by karelz** [comment] 2019-03-29 18:40
@merriemcgaw I didn't plan to investigate it personally - I let area owners chime in. Let's ping them on the GH issue. BTW: Here's area owners list in CoreFX: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas

**Comment by AlanParr** [comment] 2019-04-11 21:30
I submitted a PR to dotnet/corefx#34465 to fix this which was merged yesterday

I've tested my original repro against Winforms and WPF for both .Net Core and .Net Framework and behaviour now appears to be identical.

Unless anyone else wants to verify, I think this issue can be closed.

**Comment by merriemcgaw** [comment] 2019-04-17 22:38
Great! Closing the issue in that case :)

**Closed by merriemcgaw** 2019-04-17 22:38 UTC
Labels: bug, tenet-compatibility
