### ISSUE TITLE
Size of Form and controls is bigger in WinForms .NET Core app compared to WinForms .NET Framework app

### ISSUE THREAD

**Issue by bairog** [dotnet/winforms#1948] opened 2019-09-20 10:13 UTC
* .NET Core Version: **v3.0.0-rc1**
* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**

1. Using **Visual Studio 2019 16.3 Preview 4** create a WinForms .NET Core app and a WinForms 
 .NET Framework app, which have same designer code with some controls added.
[WinFormsFrameworkApp.zip](https://github.com/dotnet/winforms/files/3635383/WinFormsFrameworkApp.zip)
[WinFormsCoreApp.zip](https://github.com/dotnet/winforms/files/3635384/WinFormsCoreApp.zip)

2. Build and run these 2 apps, and compare size of forms and controls

**Actual behavior:** 
Size of Form and controls is bigger in WinForms .NET Core app compared to WinForms .NET Framework app (for example Form is **1178x799** pixels on .NET Core 3.0 and **1010x697** pixels on .NET Framework 4.8)

**Expected behavior:**
They should have same size (pixel by pixel identical).

**Comment by 0xd4d** [comment] 2019-09-20 16:09
Duplicate of https://github.com/dotnet/winforms/issues/1122

**Comment by bairog** [comment] 2019-09-20 16:34
In all my form controls I don't use `Segoe UI 9pt`, I use `Calibri 12pt`.
Why my forms are not pixel by pixel identical  in that case?

**Comment by bairog** [comment] 2019-09-23 09:33
Let me clarify - for example in both projects:
1.  Form size in designer is set to **1028x706** (font is **Calibri 12pt**)
2.  Button size in designer is set to **70x28** (font is **Calibri 12pt**)
.NET Framework 4.8 app respects that sizes, while .NET Core 3 app is bigger than that values..

**Comment by RussKie** [comment] 2019-09-24 01:42
I believe the result is due to this line:
```cs
this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
```
If you comment it out, it renders the form in the same size.

Here's the relevant info: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.containercontrol.autoscaledimensions?redirectedfrom=MSDN&view=netframework-4.8#remarks

@oliag this may trip a few people, perhaps we need to highlight this somehow.
/cc: @merriemcgaw

**Closed by RussKie** 2019-09-24 01:42 UTC
