### ISSUE TITLE
Winforms controls diaplay as V5 mode for Visual Basic project in runtime 

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#1123] opened 2019-06-12 10:05 UTC
* .NET Core Version: .Net Core 3.0 Preview7 3.0.100.12367 build from master branch
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
	
1. Create a Winforms .Net Core VB application with some controls
2.  Build and run it

**Actual behavior:
Winforms controls in Core VB app display as V5 mode in runtime
![Actual](https://user-images.githubusercontent.com/38325459/59342137-bde50300-8d3b-11e9-965c-601919379f75.PNG)

**Expected behavior:**
Winforms controls should display as V6 mode, like Winforms framework app by default.
![Expected](https://user-images.githubusercontent.com/38325459/59342233-f2f15580-8d3b-11e9-8faa-3e9a6fa2b1dd.PNG)

**Comment by merriemcgaw** [comment] 2019-06-12 23:25
@Zheng-Li01 is this a regression from a previous build? I don't think we've done anything new.

**Comment by dreddy-work** [comment] 2019-06-13 01:37
Please also check if Application.EnableVisualStyles is set or what was its default vaalue between classic framework and core.

**Comment by Zheng-Li01** [comment] 2019-06-13 06:15
@merriemcgaw, This is not a regression issue, verified with .Net Core SDK 3.0 preview 5 & preview 6 from release branch, the issue still can reproduce. As for the Preview 3 & Preview 4,  the Windows Forms (WinForms) Application [VB] is not listed in the cmd window after running the command “dotnet new  -l”, However the Windows Forms App [VB] (.NET Core) template is appearing in Visual Studio but which can’t create project successfully. **See screenshot1.**
![Screenshot1](https://user-images.githubusercontent.com/38325459/59407867-3ce24600-8de5-11e9-9d57-8a78ebf39ff0.PNG)

@dreddy-work, Compared  the code between .NET Core(VB windows Froms App) and .NET Framework(VB windows Froms App), there’s no the “Application.EnableVisualStyles” code exist in  both type projects. But in the properties page of .Net Farmework project,  the “Enable XP visual styles” is checked by default, in this case, winforms controls displayed as V6 mode, if unchecked the option, winforms controls displayed as V5 mode. However, the “Enable XP visual styles” option is not exist in the properties page of .NET Core application, the controls will display as V6 mode after adding the code “Application.EnableVisualStyles()” manually in the file of .Net Core application.  **See screenshot2.**
![Screenshot2](https://user-images.githubusercontent.com/38325459/59407916-5aafab00-8de5-11e9-8739-050821985102.PNG)

**Comment by merriemcgaw** [comment] 2019-06-13 23:44
So it looks like the template doesn't have EnableVisualStyles to have it enabled by default. @KlausLoeffelmann can you take a quick look at the template and update?

**Comment by merriemcgaw** [comment] 2019-06-20 23:49
Moving to the designer repo and we can enable this when we say we have full support for VB in the application.

**Comment by zsd4yr** [comment] 2019-06-20 23:53
```vb
<System.STAThread()> Public Shared Sub Main()
  Application.EnableVisualStyles()
  Application.Run(New Form1)
End Sub
```

**Comment by KlausLoeffelmann** [comment] 2019-06-24 11:10
The VB Application Framework is missing completely in Core, hence the behavior.
We have discussed this, if I recall correctly, in a meeting around the time frame when SetHighDpiMode happened, but that was low prio at the time. We should schedule another meeting for this, since this - I suggest - has to be redone. I'll create a dedicated issue for that here: #1216.

**Comment by merriemcgaw** [comment] 2019-08-06 21:45
Moved to 5.0 given that 3.1 isn't really for new feature work.

**Comment by KlausLoeffelmann** [comment] 2019-10-23 07:53
@merriemcgaw: Since this is template related and the workaround is enabling `Application.EnableVisualStyles`, can we close this?

**Comment by merriemcgaw** [comment] 2019-12-04 00:48
Yeah, I think we can close this for now.

**Closed by merriemcgaw** 2019-12-04 00:48 UTC
Labels: :beetle: bug, :boom: regression, area: Visual Basic, tenet-compatibility
