### ISSUE TITLE
SendKeys.SendWait() sends wrong characters

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7945] opened 2022-10-14 09:51 UTC
### .NET version

8.0.100-alpha.1.22512.32

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, can not repro in .Net 7.0 and previous versions

### Issue description

SendKeys.SendWait() sends wrong characters for non-English characters, may be regressed from the PR change: https://github.com/dotnet/winforms/pull/7880

.Net 8.0 result:
![image](https://user-images.githubusercontent.com/26474449/195815812-39bdeedf-e928-4120-9dbf-e845934e3b3a.png)

.Net 7.0 result:
![image](https://user-images.githubusercontent.com/26474449/195817058-a1fcb98a-fc55-43ee-a30e-13dc7314412f.png)

### Steps to reproduce

Repro steps:
1. Create a new project with those 3 lines:
```
Thread.Sleep(5000);
            string test = "キ";
            SendKeys.SendWait(test);
```
2. Run the project and (during the first 5 second since the start) open notepad
3. Observe the test being written

or use attached test application:
[WinFormsApp56.zip](https://github.com/dotnet/winforms/files/9784711/WinFormsApp56.zip)

**Comment by elachlan** [comment] 2022-10-17 20:55
@Olina-Zhang did you bisect the changes to see if the issue was caused by #7880?

**Comment by Olina-Zhang** [comment] 2022-10-18 01:31
> @Olina-Zhang did you bisect the changes to see if the issue was caused by #7880?

we have automation case failed recently, and I investigated it and found these repro steps, the SendKeys.cs file was changed in PR https://github.com/dotnet/winforms/pull/7880 recently by history display, so I think it caused this issue.
![image](https://user-images.githubusercontent.com/26474449/196313993-adcf481b-e0ca-494f-92cd-1823e1e1868a.png)

**Comment by elachlan** [comment] 2022-10-18 02:42
I think its because CsWin32 isn't specifying the CharSet?

Here are the PInvokes:
Before:
```csharp
[DllImport(Libraries.User32, CharSet = CharSet.Unicode)]
public static extern short VkKeyScanW(char key);
```

After:
```csharp
[DllImport("USER32.dll", ExactSpelling = true, EntryPoint = "VkKeyScanW")]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
[SupportedOSPlatform("windows5.0")]
internal static extern short VkKeyScan(char ch);
```

CC: @AArnott

**Comment by elachlan** [comment] 2022-10-18 02:52
From the docs:
> The winuser.h header defines VkKeyScan as an alias which automatically selects the ANSI or Unicode version of this function based on the definition of the UNICODE preprocessor constant.

From the headers in Win32MetaData.
```C
WINUSERAPI
SHORT
WINAPI
VkKeyScanA(
    _In_ CHAR ch);
WINUSERAPI
SHORT
WINAPI
VkKeyScanW(
    _In_ WCHAR ch);
#ifdef UNICODE
#define VkKeyScan  VkKeyScanW
#else
#define VkKeyScan  VkKeyScanA
#endif // !UNICODE`
```

We will need to manually tag each function which is unicode maybe?

**Comment by elachlan** [comment] 2022-10-18 03:02
I have created an issue in Win32Metadata, I believe it will be an issue with all PInvokes which should have `CharSet = CharSet.Unicode`
https://github.com/microsoft/win32metadata/issues/1318

**Comment by elachlan** [comment] 2022-10-18 21:51
The latest update didn't fix it. It should be available in the next nightly build of CsWin32.

**Comment by merriemcgaw** [comment] 2022-10-19 00:00
Assigning to @lonitra to track the fix.

**Closed** 2022-10-21 02:04 UTC
Labels: :boom: regression, :construction: work in progress

**Comment by Nora-Zhou01** [comment] 2022-11-03 06:54
Verified with .NET SDK .NET 8.0.100-alpha.1.22552.10 build from main branch, this issue is fixed that the SendKeys.SendWait() sends the correct character.
![8 0](https://user-images.githubusercontent.com/104609169/199662251-2b68ece3-ce93-41a1-b9f2-9ab02fd51184.png)
