### ISSUE TITLE
Regression in .Net 5 RC1 - the PaintEventArgs.Graphics is recreated when requested and this break all the GDI-interop scenarios due to System.ArgumentException

### ISSUE THREAD

**Issue by DmitryGaravsky** [dotnet/winforms#3910] opened 2020-09-15 19:17 UTC
**Description**
For now, the GDI interop code fails with the ArgumentException:
```
System.ArgumentException: 'Parameter is not valid.'
```
Our unit tests detected this issue immediately after upgrade (we maintain unit tests for all the released and preview environments like .net core 5 in our codebase).
Thus it is an important breaking change for us because **most of our UI controls are broken now**.

**Configuration**
OS Version: Microsoft Windows [Version 10.0.18362.535]
.Net Framework Version: Microsoft (R) .NET CLR Version Tool Version 4.8.3928.0
.Net Core Version: SDK Version: 5.0.100-rc.1.20452.10

**Regression?**
Yes, this works correctly until .Net Core 5 RC1

**Other information**
Here is the code snippet which fails under .Net Core 5 RC1:

```cs
using System.Windows.Forms;

namespace WindowsFormsApp1 {
    public class Form1 : Form {
        protected override void OnPaint(PaintEventArgs e) {
            var hdc = e.Graphics.GetHdc();
            // do something with hdc
            e.Graphics.ReleaseHdc(hdc); // crash here (because of the e.Graphics not related to previously created hdc)
        }
    }
}
```
We have also detected **multiple clipping issues** related to the PaintEventArgs.Graphics recreation.

**Comment by JeremyKuhne** [comment] 2020-09-15 23:25
Looking...

**Comment by JeremyKuhne** [comment] 2020-09-15 23:54
Ugh, this is embarrassing. I've got the fix PR up- unfortunate that none of our tests hit this yet.

**Comment by JeremyKuhne** [comment] 2020-09-16 00:30
Not many options to workaround this for RC1- if possible you can create a new `PaintEventArgs` with the `.Graphics` from the other one.

**Comment by StefanKoell** [comment] 2020-09-16 09:12
@JeremyKuhne Is there a rough timeframe for RC2? Since .NET and VS Preview is tied together, you can't really continue to work once VS has been updated to 16.8 preview 3 (which includes net 5  rc1). There's no way to roll back to 16.8 preview 2.1 (which includes still working net 5 preview 8) since there's no download path. Would be nice if MS could provide a way to downgrade VS for the time being...

**Comment by RussKie** [comment] 2020-09-16 10:01
@StefanKoell you should be able to install VS 16.7 and P8.

You can also install daily RC2 builds from dotnet/installer, once the fix is approved and merged, it is usually available within a day.

**Comment by StefanKoell** [comment] 2020-09-16 10:08
@RussKie as far as I know, net 5 preview/rc doesn't work with VS 16.7 and 16.8 preview is required. Am I wrong?

**Comment by RussKie** [comment] 2020-09-16 10:32
You may be correct, P7 should work in 16.7 though.

**Comment by JeremyKuhne** [comment] 2020-09-16 18:30
I've committed the fix to RC2: https://github.com/dotnet/winforms/commit/17d3abba5f42bd7c103125174a43248660d03d45

As @RussKie mentioned, this should be in the RC2 dailies shortly. https://github.com/dotnet/installer#installers-and-binaries

I'll update the issue when I see a working drop.

**Closed** 2020-09-16 23:27 UTC
Labels: :boom: regression, Priority 1 :exclamation:

**Comment by tebeco** [comment] 2020-09-17 08:25
https://github.com/dotnet/tye/issues/660#issuecomment-693482774

Does this fixes your issue as well ?

**Comment by RussKie** [comment] 2020-09-17 08:30
@tebeco how is this relevant to this issue?

**Comment by tebeco** [comment] 2020-09-17 08:31
I was pinged on that one from another communication channel
maybe that's the wrong one when I clicked

Shuld have read before :D

**Comment by tebeco** [comment] 2020-09-17 08:32
do you want me to delete the post ?

**Comment by StefanKoell** [comment] 2020-09-21 11:50
Just an FYI: I installed a daily build of RC2 and I can confirm it's not crashing anymore. Thanks for the quick fix!

**Comment by Zheng-Li01** [comment] 2020-10-14 06:54
Verified the issue with .NET SDK 5.0.100-rtm.20513.7 that the issue has been fixed that not crashed anymore.
