### ISSUE TITLE
.net6 pre 6 exception "unable to find an entry point named ‘AdjustWindowRectExForDpi’ in DLL user32.dll"

### ISSUE THREAD

**Issue by zxbe** [dotnet/winforms#5259] opened 2021-07-17 01:01 UTC
* .NET Core Version: 

6.0 Preview6

* Have you experienced this same bug with .NET Framework?: 

No

**Problem description:**

When I Update the sdk from .net6 p 5 to p6 and run the winformapp in win7sp1 OS,I got the exception “unable to find an entry point named ‘AdjustWindowRectExForDpi’ in DLL user32.dll”.

![exception](https://i.stack.imgur.com/F1Kvo.png)

![winform](https://i.stack.imgur.com/hPccU.png)

**Expected behavior:**

winos: win7 ps1 x64
sdk: .NET SDK 6.0.100-preview.6.21355.2
app: winform app
ide: vs2022

1. New WinformApp
2. Add panel Control and set Dock to Top
3. Add label Control and set Font Bold to true
4. Build App
5. Copy Debug folder to Win7 Sp1 OS
6. Click and Run the exe file
7. Get the Exception

![win7os](https://i.stack.imgur.com/VFYk0.png)

**Minimal repro:**
![What todo to get the exception](https://i.stack.imgur.com/HONLY.gif)

**Comment by kirsan31** [comment] 2021-07-17 08:26
https://github.com/dotnet/winforms/pull/5260

**Comment by RussKie** [comment] 2021-07-19 03:00
Duplicate of #5260

**Closed by RussKie** 2021-07-19 03:00 UTC

**Comment by Ashley-Li** [comment] 2021-07-28 09:43
Verified this issue with OS(Windows-7-Enterprise-SP1)+ .NET dotnet-sdk-6.0.100-rc.1.21377.28, it is fixed. Now there's no exception error( “unable to find an entry point named ‘AdjustWindowRectExForDpi’ in DLL user32.dll”) pops up when clicking and run the exe file, and the form designer can be run successfully. Please see below gif:
![test](https://user-images.githubusercontent.com/56664234/127301164-92fbb575-5b69-49a4-b6d7-26f991cb8595.gif)

**Comment by cwing2019** [comment] 2021-07-29 09:11
any control put on groupbox or layout, will cause this problem;

System.EntryPointNotFoundException:“Unable to find an entry point named 'AdjustWindowRectExForDpi' in DLL 'user32.dll'.”
