### ISSUE TITLE
Web Services(asmx) in WinForms

### ISSUE THREAD

**Issue by gsmental** [dotnet/winforms#303] opened 2019-01-08 10:50 UTC
we are consuming web services (asmx files)  from our WebForms based projects. but these are not available in winform (i am just demanding asmx files)

**Comment by gsmental** [comment] 2019-01-09 09:50
I think, this is a similar issues which i am facing

https://github.com/dotnet/winforms/issues/306

**Comment by karelz** [comment] 2019-01-14 22:48
Duplicate of #306

**Closed by karelz** 2019-01-14 22:48 UTC
