### ISSUE TITLE
Creating a new WinForms project in .NET 6 in Version 17.3.0 Preview 2.0 breaks the designer for Form1.cs

### ISSUE THREAD

**Issue by janseris** [dotnet/winforms#7379] opened 2022-07-06 13:58 UTC
### Environment

Version 17.3.0 Preview 2.0

### .NET version

```
 Version:   6.0.400-preview.22301.10
 Commit:    25580ffe7a

Běhové prostředí:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  5.0.203 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Did this work in a previous version of Visual Studio and/or previous .NET release?

yes it worked in some previous VS 2022

### Issue description

Create a new project from template. 
![image](https://user-images.githubusercontent.com/64279914/177567500-16e9840d-f79c-4950-83db-dac103567e3f.png)

The error says ensure that the project can be built but it can.
`========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========`

It is unclear what the problem is.

Call stack is: 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<STYLE>.MainHeaderText { font:0.8em Segoe UI; color:#FFFFFF; font-weight:bold; }.MainHeaderErrorNumberText { font:0.7em Segoe UI; color:#000000; }.MainHeaderWhyText { font:0.8em Segoe UI; color:#FFFFFF; text-decoration:underline; cursor:pointer; }.MainHeaderIgnoreText { font:0.8em Segoe UI; color:#FFFFFF; text-decoration:underline; cursor:pointer; }.MainHeaderBackground { background-image:url('C:\Users\janse\AppData\Local\Temp\tmpB16F.tmp.gif'); background-repeat:repeat-x; background-color:#434E5E; }.ErrorHeaderErrorText { font:0.7em Segoe UI; color:#000000; font-weight:bold; }.ErrorHeaderGoToCodeText { font:0.7em Segoe UI; color:#000080; text-decoration:underline; cursor:pointer; }.ErrorBodyTitle { font:0.8em Segoe UI; font-weight:bold; color:#000080; }.ErrorBodyLink { font:0.8em Segoe UI; color:#007ACC; text-decoration:underline; cursor:pointer; }.ErrorBodyLinkNoSizing { color:#007ACC; text-decoration:underline; cursor:pointer; }.ErrorBodyText { font:0.8em Segoe UI; color:#000000; }.ErrorBodyCallStack { font:0.7em Segoe UI; color:#000000; }.ClickableCell { cursor:pointer; }.HasVisuallyDistinctBorder { border:none; }</STYLE>
</HEAD>
<BODY bgColor=#1a1a1a>
<TABLE role=document id=CollapseBody0 class=HasVisuallyDistinctBorder 
cellSpacing=0 cellPadding=0 width="100%" bgColor=#ffffff>
<TBODY>
<TR role=presentation>
<TD bgColor=#ffffff>
<TABLE role=document cellSpacing=0 cellPadding=0 width="100%">
<TBODY>
<TR role=presentation>
<TD><!--StartFragment-->
<TABLE role=document cellSpacing=0 cellPadding=0>
<TBODY><TR role=presentation id=CallStackBody0_1>
<TD class=ErrorBodyCallStack>at 
Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.NetCore.<GETNETCOREPROJECTINFOASYNC>d__6.MoveNext()<BR>--- 
End of stack trace from previous location where exception was thrown ---<BR>at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<BR>at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)<BR>at 
Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.<GETPROJECTINFOASYNC>d__9.MoveNext()<BR>--- 
End of stack trace from previous location where exception was thrown ---<BR>at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<BR>at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)<BR>at 
Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CREATEHOSTASYNC>d__7.MoveNext()<BR>--- 
End of stack trace from previous location where exception was thrown ---<BR>at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<BR>at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)<BR>at 
Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CREATECLIENTASYNC>d__29.MoveNext()<BR>--- 
End of stack trace from previous location where exception was thrown ---<BR>at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<BR>at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)<BR>at 
Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.&lt;&gt;c__DisplayClass25_1.&lt;&lt;-ctor&gt;b__1&gt;d.MoveNext()<BR>--- 
End of stack trace from previous location where exception was thrown ---<BR>at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<BR>at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)<BR>at 
Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<GETCLIENTASYNC>d__27.MoveNext() 
</TD></TR></TBODY></TABLE>
<TABLE role=document cellSpacing=0 cellPadding=0 width="100%">
<TBODY>
<TR role=presentation>
<TD><BR></TD></TR></TBODY></TABLE><!--EndFragment--></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></BODY></HTML>
```

### Steps to reproduce

Create a new WinForms project

### Workarounds
- open/close Visual Studio fixes the issue

**Comment by elachlan** [comment] 2022-07-23 06:16
Duplicate of https://github.com/dotnet/winforms/issues/7371?

**Comment by janseris** [comment] 2022-07-23 13:31
@elachlan not sure because it works in VS 2022 17.2.6, I just wanted to report it for the Preview version so that the error does not make it into 17.3.0

**Comment by RussKie** [comment] 2022-07-24 23:17
Could you please provide the diagnostic information as described in https://aka.ms/winforms/designer/troubleshooting

**Comment by janseris** [comment] 2022-07-25 07:05
@RussKie hi no because this is perfectly reproducible. Might be fixed in current preview though. I can't use a preview version now and this is not a priority problem for me because I can work in regular VS. I just wanted to let you know

**Comment by RussKie** [comment] 2022-07-25 07:45
If it's "perfectly reproducible" why are you unable to share the diagnostics?
I can't repro the issue.

**Comment by janseris** [comment] 2022-07-25 08:14
@RussKie 
as I wrote I don't have that version installed anymore because it's been 14+ days

>I can't use a preview version now because of lack of disk space and this is not a priority problem for me because I can work in regular VS. I just wanted to let you know

**Comment by RussKie** [comment] 2022-07-26 08:58
Without additional diagnostics there's nothing we can do further. If you see this issue occur again please ping here or raise a new issue.
Thanks.

**Closed by RussKie** 2022-07-26 08:58 UTC
Labels: area: VS designer, untriaged
