### ISSUE TITLE
DPIAwareness: ArgumentException when opening a ContextMenuStrip

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#2969] opened 2020-03-10 20:17 UTC
* .NET Core Version: 3.1.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

We are experiencing the following crashreports from some users when they open a contextMenu. All reports originate from Windows10 (version 1607 - build 14393 or later), but we are not able to simulate it on our side.

```
System.Windows.Forms.System.ArgumentException: dpiContext (Parameter 'DPI_AWARENESS_CONTEXT_UNSPECIFIED')
    at System.Windows.Forms.CommonUnsafeNativeMethods.TrySetThreadDpiAwarenessContext
    at System.Windows.Forms.DpiHelper+DpiAwarenessScope.Dispose
    at System.Windows.Forms.ToolStripManager+ModalMenuFilter.PreFilterMessage
    at System.Windows.Forms.Application+ThreadContext.ProcessFilters
    at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage
    at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage
    at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop
    at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner
    at System.Windows.Forms.Application+ThreadContext.RunMessageLoop
    at System.Windows.Forms.Application.Run
```

our app is PerMonitorV2 aware as defined in app.manifest:

```
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
	<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
	<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
```

**Comment by RussKie** [comment] 2020-03-11 01:33
@dreddy-work could you have a look at this please?

**Comment by dreddy-work** [comment] 2020-03-18 23:51
It seems when we change these constants to match with IntPtr values from native,  We did not change them everywhere. Will scan the sources to make sure they are changed everywhere.

**Comment by filipnavara** [comment] 2020-04-28 20:28
Is there any plan to fix this on release/3.1? For the particular version of Windows 10 (1607) it crashes for every single place where we use a menu. Alternatively, is there any known workaround (such as calling `Application.SetHighDpiMode(HighDpiMode.SystemAware)` or similar method)?

**Comment by RussKie** [comment] 2020-04-28 23:26
@filipnavara can you provide a repro?

**Comment by RussKie** [comment] 2020-04-28 23:28
@Vino-Wang is this something you could repro?

**Comment by merriemcgaw** [comment] 2020-04-29 00:17
The OS requires at least Windows 10 Creators Update (1703) to work. We need to be gracefully handling the case when Win10 is not at that minimum build. We need to fix this crash but there's nothing we can do as far as getting PerMonV2 to work when the underlying API is not supported.

**Comment by filipnavara** [comment] 2020-04-29 05:51
[contextmenu-repro.zip](https://github.com/dotnet/winforms/files/4549943/contextmenu-repro.zip)

This is the minimal repro. Just run it on Windows 10 1607 and right-click anywhere on the form. The key to make it crash seems to be the application manifest.

**Comment by filipnavara** [comment] 2020-04-29 06:21
> We will address this crash in servicing but there's nothing we can do as far as getting PerMonV2 to work when the underlying API is not supported.

That's fine for us. We only care about the app not crashing, not about the specific per-monitor DPI handling on older OS version.

**Comment by dreddy-work** [comment] 2020-05-14 17:34
I looked into this issue. This repro is possible on machines that has windows 10 version less than 1607 and application is targeting 'netcoreapp 5.0'. I tried to repro myself with the 1607 version and 3.1 targeting and it does not repro.  below is the gif from the machine. According to the source code that make sense. We will be working on fixing the issue for those scenarios. However, if you @filipnavara disagree with our repro scenario, can you attach screen shot for windows version ( wanted to take a look at minor version). Also, is it possible that you installed any internal builds of .NET core other than public released versions?

**Comment by filipnavara** [comment] 2020-05-14 19:19
I tested it on a virtual machine that was installed from "14393.0.161119-1705.rs1_refresh_clientpro_ret_x64fre_en-us_0c8a07f49ff047c8ec52c6a1f7b21568174a18d7" ISO. It should be the same version as on your screenshot. Unfortunately the machine has updated in the background so I would need to rebuild it to access it again. There was no .NET Core installed inside it. The only thing I did was to copy there self-published version of the sample code linked above. Otherwise it was completely clean install in a virtual machine.

**Comment by dreddy-work** [comment] 2020-05-14 21:31
@filipnavara , Is it possible to share the self contained app that you used? Also, if you get a chance to get the machine rebuild, please share the screenshot of version info.

**Comment by filipnavara** [comment] 2020-05-14 21:37
Unfortunately the self-contained output is kind of on the big side so I had to share it through external service that allows larger files. 

https://send.firefox.com/download/b48739bcf3c1097f/#4aBM9eavZZCiGZsTYQPuPg

The link will be valid for a week, or 100 downloaded, whichever comes first. I can reupload it elsewhere if it becomes an issue.

**Comment by filipnavara** [comment] 2020-05-14 21:57
My bad, looks like I sent you the publish directory after I made some local changes... at least I cannot reproduce the issue anymore with the exact same set of binaries. I managed to revert the virtual machine to earlier state at the end of Windows installation. The exact version is 10.0.14393:

![image](https://user-images.githubusercontent.com/1764393/81990009-96c73d80-963e-11ea-9e0e-a7184945e03b.png)

**Comment by dreddy-work** [comment] 2020-05-14 21:59
hmm. Okay. I will assume the repro scenario is what i described above and we try to fix it with that in mind.  I just wanted to make sure that i understand the scenario well( not just from the source code) before applying the fix.  Thank you for providing these information. We will update this issue once the fix is merged.

**Comment by filipnavara** [comment] 2020-05-14 22:01
Here's link to rebuild version of the original repro (https://github.com/dotnet/winforms/files/4549943/contextmenu-repro.zip) that crashes on 1607 (14393.447):

https://send.firefox.com/download/eadcc5b1734bbaf7/#c7qlpTGSUe-zPCAJX-q9xg

**Comment by dreddy-work** [comment] 2020-05-14 23:34
can you share what is the difference between these two applications?

**Comment by filipnavara** [comment] 2020-05-14 23:44
I wish I could but I no longer have source for the first published binaries (https://github.com/dotnet/winforms/issues/2969#issuecomment-628899985).

After I posted the repro here two weeks ago I went on to try couple of things and I found out that the problem can be triggered either with application manifest that specifies PerMonitorV2 DPI handling, or the explicit `Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);` call. I tried to make a workaround that modified the sample not to include the application manifest and then to set `HighDpiMode` to different value depending on the Windows version. This was supposed to avoid triggering the bug for us in our production app. Somewhere along this journey I published the binaries and it was some version that didn't crash. However, I don't know at what point it happened and can only use ILSpy to trace it back.

The second set of binaries I posted (https://github.com/dotnet/winforms/issues/2969#issuecomment-628909276) is exact replica of the original repro and I can verify that it crashes in the virtual machine where I reproduced it the first time.

**Comment by merriemcgaw** [comment] 2020-06-04 23:20
I think we are going to take this for .NET 5, but for 3.1 I don't think we're going to take it until/unless we can determine that there is a repro that we could expect to hit occasionally. If you could provide the binary again, if we inspect it in ILSpy and find a more common repro I'll happily reconsider this for 3.1.

**Closed** 2020-06-24 03:54 UTC
Labels: :beetle: bug, :boom: regression, :construction: work in progress
