### ISSUE TITLE
Can not raise Click event when mouse click a ToolStripButton in a inactive window

### ISSUE THREAD

**Issue by CuteLeon** [dotnet/winforms#9277] opened 2023-06-12 17:08 UTC
### .NET version

.Net 8.0 Preview 4

### Did it work in .NET Framework?

Not tested/verified

### Issue description

I can not raise a Click event when I first time click a ToolStripButton in a inactive window, have to click twice to raise above event.

### Steps to reproduce

1. Create a WinForms project.
2. Create 2 form classes, and add a ToolStrip to each of above forms.
3. Create a ToolStripButton to each of above ToolStrips.

Issues:
1. Active first form, click ToolStripButton control of another form (inactive), ToolStripButton doesn't raise a Click event.
2. Have to click twice to raise above event.

**Comment by elachlan** [comment] 2023-06-13 01:04
@Olina-Zhang can your team please verify this issue?

**Comment by Olina-Zhang** [comment] 2023-06-13 01:40
> @Olina-Zhang can your team please verify this issue?

It is a duplicate of the GH issue: https://github.com/dotnet/winforms/issues/9240.

**Comment by CuteLeon** [comment] 2023-06-13 02:04
So are we planning to support Click-Through in .Net 8.0 final version? Or I have to implement a ToolStripEx following https://learn.microsoft.com/en-us/archive/blogs/rickbrew/how-to-enable-click-through-for-net-2-0-toolstrip-and-menustrip ?

**Comment by elachlan** [comment] 2023-06-13 02:13
@merriemcgaw Would adding click through to the existing control be an API change that has to go through review?

**Comment by elachlan** [comment] 2023-06-13 02:16
@rickbrew would you like to see click-through on `ToolStrip` implemented in .NET 8? Do you still use it in Paint.NET?

**Comment by rickbrew** [comment] 2023-06-13 15:19
Yeah I still use `ToolStrip` a lot. I implement click-through myself via `WndProc` by intercepting `WM_MOUSEACTIVATE` and changing `MA_ACTIVATEANDEAT` to `MA_ACTIVATE`. I'd much rather have this built-in though, configurable with a property, as it's really how most things behave in Windows and is in-line with user expectations.

**Comment by merriemcgaw** [comment] 2023-06-13 18:53
Given that this is not really a regression, we're not able to make this an immediate priority. We will however discuss internally and make a determination if we should make a new feature here. It probably wouldn't happen until .NET 9 at the earliest given current priorities. If the community would like to make an API Proposal, we'd be happy to look at it 😉 .

**Comment by elachlan** [comment] 2023-06-14 00:40
Raised the API change request at #9288

**Comment by merriemcgaw** [comment] 2023-06-15 23:59
Thanks @elachlan!

**Closed** 2024-07-11 00:12 UTC
Labels: enhancement, :construction: work in progress

**Comment by John-Qiao** [comment] 2024-07-11 06:34
Verified this issue on 9.0.100-preview.7.24360.15 with dlls built from winforms repo of main branch, it was fixed: if set the AllowClickThrough = true for ToolStrip, the ToolStripButton mouse click can be raised in an inactive from directly(click once).

https://github.com/dotnet/winforms/assets/45864985/b64e36d5-566d-443f-a6ba-f260efa9465e
