### ISSUE TITLE
DataGridViewDesigner is missing in System.Windows.Forms.Design namespace (.NET 6/7)

### ISSUE THREAD

**Issue by dmitry-medvedev** [dotnet/winforms#9165] opened 2023-05-24 06:24 UTC
### .NET version

.NET 7 windows
.NET 6 windows

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

it does not look it was ever ported to .NET Core

### Issue description

We use .NET System.Windows.Forms.Design services for the run-time implementation of the Form designer functionality.
Under .NET Framework 4.6+ we could invoke DataGridView designer by clicking on the action item to add columns, etc.
It seems that this class completely missing in .NET 6/7

### Steps to reproduce

We have our demo projects here:
https://github.com/alternetsoft/alternet-studio-examples
The issue can be reproduced with FormDesigner demo, it can not load designer at all and displays DataGridView as a component.
If we use ControlDesigner instead of DataGridViewDesigner, it works fine, but does not display additional action items.

**Comment by merriemcgaw** [comment] 2023-05-30 18:58
duplicate of #4908, reopening that one so that we can get comments on the priorities for each of the designers for our customers.

**Closed** 2023-05-30 18:59 UTC
Labels: untriaged
