### ISSUE TITLE
[Accessibility] An element of the given controlType must support the ExpandCollapse pattern for some controls which AccessibleRole property is SplitButton

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#4427] opened 2021-01-04 09:37 UTC
* .NET Core Version: 
.Net SDK 6.0.100-alpha.1.20623.10

* More info:
 1. For most controls, this is a regression issue, it doesn't repro on .Net framework & .Net core 3.1 & .Net 5.0
 2. For some controls (MasketTextBox, TextBox, dateTimePicker, CheckListBox), this is a not regression issue, it still repro on  .Net framework & .Net core 3.1 & .Net 5.0

**Minimal repro:**
[TestApp.zip](https://github.com/dotnet/winforms/files/5764004/TestApp.zip)

1. Create a winforms .NET core project with targeting 6.0
2. Add a  TooStrip control to the form designer, then add items for toolStrip, and set Items' AccessibleRole property as **SplitButton**
3. Build and run the core project.
4. Observe item of toolStrip using the Accessibility Insight

**Actual behavior:**
AccessibilityInsights detected an error: An element of the given controlType must support the ExpandCollapse pattern.
![Actual](https://user-images.githubusercontent.com/62929087/103521025-0d0cfe80-4eb3-11eb-8190-8bec3d8cb538.PNG)

**Expected behavior:**
AccessibilityInsights should not detect this error.

**Comment by merriemcgaw** [comment] 2021-01-04 23:29
@Amy-Li03 do all the controls have the right patterns when the AccessibleRole is left to default? If a dev sets AccessibleRole to something that doesn't make sense, then the dev would be responsible for making sure the appropriate patterns are supported rather than us.

**Comment by Amy-Li03** [comment] 2021-01-05 02:52
@merriemcgaw 
The controls have right patterns when the AccessibleRole is default, this issue occurs only when setting AccessibleRole property as **SplitButton**.
But for some controls, this is a regression issue, it doesn't repro on .Net framework & .Net core 3.1 & .Net 5.0 & previous .Net 6.0 build.

**Comment by merriemcgaw** [comment] 2021-01-16 01:28
I think we can close this as by design. There are 1000 ways people can configure things to not be accessible. As long as the defaults are accessible (or it's easy to get to an accessible state) then I think we've got a good accessibility story. Closing the issue.

**Closed** 2021-01-16 01:29 UTC
Labels: tenet-accessibility
