### ISSUE TITLE
Wrong Icon Displayed windows 2003 OS and Windows 2008 server

### ISSUE THREAD

**Issue by vijayarasan** [dotnet/winforms#6415] opened 2021-12-23 10:43 UTC
**Problem description:**

We create the simple sample and set font style as “Regular”, the issue raises whereas when the font style is set to “Bold”, the icon font is drawn properly. Here I have attached the sample for your reference.

**Sample Link :**  [IconFont.zip](https://github.com/dotnet/winforms/files/7768722/IconFont.zip)

Image for your reference,

**Regular FontStyle :**

 ![RegularFont](https://user-images.githubusercontent.com/58214164/147228764-3842378c-e5f5-4528-bd45-7a238ce4cb1f.PNG)

**Bold FontStyle :**

 ![BoldFont](https://user-images.githubusercontent.com/58214164/147228854-cf5ea46c-b507-49b8-82b8-95c692c0a781.PNG)

**Minimal repro:**

Step 1: Set the Font Style as Regular
Step 2: Run the Sample in Windows 2003 OS (or Windows Server 2008)
Step 3: Note the Icons are displayed wrongly in Button

**Expected behavior:**
Icons are properly displayed in Button

**Comment by dreddy-work** [comment] 2021-12-27 19:12
@vijayarasan , These OSs are not in [support ](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide#:~:text=Capabilities%20per%20supported%20operating%20systems%20%28OS%29%20and%20platforms,%20%20Yes%20%2015%20more%20rows%20)for non-security related issues.  Do you see similar issue with latest/supported OS?

**Comment by vijayarasan** [comment] 2022-01-11 06:15
Hi @dreddy-work,

Thanks for the update.

We have checked with the latest OS version. The reported problem does not occur. The reported problem only occurs while using Windows 2003 OS and Windows 2008 servers. 

Regards,
Vijayarasan S

**Comment by RussKie** [comment] 2022-02-04 00:03
Closing as the issue is observed on the unsupported OS.

**Closed by RussKie** 2022-02-04 00:03 UTC
