### ISSUE TITLE
The return value of method Clipboard.GetImage() is null in the .NET Core 3.0 winforms application

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#493] opened 2019-02-26 10:18 UTC
**OS**: RS3 X64
**VS**: Visual Studio 2019 Version 16.0.0.0 Preview 4.0 [28625.133.d16.0]
**.NET SDK**: .NET Core 3.0 3.0.100-preview4-10523 from master branch

**More Info:**
    In .NET framework application, the return value is correct .

**Steps to Reproduce:**

1. Create a Winforms .Net Core application by command: dotnet new winforms –o “xxx”
2. Write code to Form1.cs
  ` using System.Drawing.Imaging;
    Image actual = null;
    Metafile expected = new Metafile(@"D:\MS.emf");
    Clipboard.SetImage(expected);
    actual = Clipboard.GetImage();`
3.  Debug the application (\\\mlangfs1\public\Winforms\v-jiaol\bug\MetaFileIssue.zip)

**Actual:**
When debugging to actual = Clipboard.GetImage(), the result of actual is null.
![metafileissue](https://user-images.githubusercontent.com/38325459/53404560-e1847780-39f0-11e9-9869-a80b2eb3e259.png)

**Expected**:
When debugging to actual = Clipboard.GetImage(), the result of actual should be a System.Drawing.Imaging.Metafile object.
![metafileissue_framework](https://user-images.githubusercontent.com/38325459/53404894-9323a880-39f1-11e9-92e5-c1bc6d786e72.png)

**Comment by merriemcgaw** [comment] 2019-04-17 22:44
@dreddy-work feel this may be related to a corefx issue. Looking for the right issue

**Comment by dreddy-work** [comment] 2019-04-18 20:31
@Zheng-Li01 can you share .emf file as well?

**Comment by Zheng-Li01** [comment] 2019-04-23 02:23
@dreddy-work you can get the.MS.emf file from here. \\trinlab2\BAQAFiles\v-vinwa\Picture\Icon\emf\MS.emf

**Comment by merriemcgaw** [comment] 2019-04-23 18:35
@Tanya-Solyanik can you take a peek?

**Comment by dreddy-work** [comment] 2019-06-29 16:20
@Zheng-Li01 , i tried to get it working with Framework  application but i do see getImage() there also returnign null.  can you please share your desktop framework version of this app that was working for you?

**Comment by Zheng-Li01** [comment] 2019-07-01 03:19
@dreddy-work, Just installed the latest Dev16 which have the .NET4.7.2 on RS4 x6, the getImage()  will return "system.drawing.imaging.metafile" in the framework application. 

However, Both 4.7.2 and 4.8 situations, the method getImage() will return null after installed the .NET 4.8 in framework application.

**Comment by dreddy-work** [comment] 2019-07-01 03:35
@Zheng-Li01 , is it possible to track down which build of .net4.8 regressed it?

**Comment by dreddy-work** [comment] 2019-07-02 01:04
@Zheng-Li01 @Olina-Zhang , Can you help track down the .NET 4.8 build that regressed this?

**Comment by Zheng-Li01** [comment] 2019-07-02 05:36
@dreddy-work, the issue regressed from .NET 4.8 03702.00 from NETFXRel1 branch, which previous build .NET 4.8 03698.00 is working well.

**Comment by dreddy-work** [comment] 2019-07-02 18:47
We were restricting deserialization of some of the types in Clipboard. metfile is one of them. Need to look further if we need to support this.

**Comment by dreddy-work** [comment] 2019-07-02 19:21
@merriemcgaw , this behavior was by design decision. I will let you decide on closing this issue.

**Comment by merriemcgaw** [comment] 2019-07-02 22:31
Agreed, this is by design and in that case we should update the tests.

**Closed by merriemcgaw** 2019-07-02 22:31 UTC
Labels: Regression, tenet-compatibility

**Comment by RussKie** [comment] 2019-07-03 01:01
@dreddy-work could you please update tests, if any.

Should we throw an exception of some kind advising that type is not supported?

**Comment by weltkante** [comment] 2019-07-03 14:52
I'd expect `SetImage` to throw an exception (unless you want to support write-only semantics for metafiles), `ContainsImage` return false and `GetImage` return null (to be consistent with other Get-methods when no data of the appropriate format is present)

Current behavior:
* SetImage with a metafile succeeds
* ContainsImage returns true
* GetImage returns null

IMHO thats broken. Do you want to reopen or should I file new issues? In particular the fact that ContainsImage returns true but GetImage returning no image is going to be confusing.

**Comment by dreddy-work** [comment] 2019-07-04 02:01
Agree. Please open a new issue for that.

**Comment by asklar** [comment] 2020-04-05 07:21
@russkie @merriemcgaw Hey Merrie, could you please clarify the context for dropping support for WMF/EMF? This is a format that's widespread and widely used (e.g. both within Windows and by Office apps). Removing this functionality seems problematic, I'd like to understand what security we are gaining from this, when the Win32 API is still available.
Moreover, the current state is broken because when you enumerate the formats, metafile is in there but when you ask for it, you get back null, which is a violation of the API contract.
