### ISSUE TITLE
When building winforms repo, global.json file is not fully respected

### ISSUE THREAD

**Issue by AustinWise** [dotnet/winforms#2085] opened 2019-10-15 08:09 UTC
I discovered this on the 3.1 branch. I'm not sure if this is a winforms problem or an arcade problem, or how big of a problem it really is.

To reproduce:
1. Do a build.
1. Switcher to an older branch whose global.json specifies an older SDK version.
1. Do NOT clean the repo.
1. Do a build.

Expected: the precise SDK version specified in the global.json is used.
Actual: the `latestMajor` roll forward policy is applied and a newer SDK in the `.dotnet` folder of the repo is used.

An example build, where 3.1.100-preview1-014024 is the specified version in global.json and there is also a 3.1.100-preview2-999999 SDK in the .dotnet folder of the repo. Some parts elided with dots for brevity:

```cmd
C:\externsrc\dotnet\winforms>set COREHOST_TRACE=1

C:\externsrc\dotnet\winforms>build.cmd
Processing C:\externsrc\dotnet\winforms\eng\..\global.json
..........
...........\msbuild.exe ............ C:\Users\AustinWise\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\Build.proj
Tracing enabled @ Tue Oct 15 07:11:52 2019 GMT
--- Invoked hostfxr_resolve_sdk2 [commit hash: 7d57652f33493fa022125b7f63aad0d70c52d810]
Probing path [C:\Users\AustinWise\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\global.json] for global.json
Probing path [C:\Users\AustinWise\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\global.json] for global.json
Probing path [C:\Users\AustinWise\.nuget\packages\microsoft.dotnet.arcade.sdk\global.json] for global.json
Probing path [C:\Users\AustinWise\.nuget\packages\global.json] for global.json
Probing path [C:\Users\AustinWise\.nuget\global.json] for global.json
Probing path [C:\Users\AustinWise\global.json] for global.json
Probing path [C:\Users\global.json] for global.json
Probing path [C:\global.json] for global.json
Terminating global.json search at [C:\]
Resolving SDKs with version = 'latest', rollForward = 'latestMajor', allowPrerelease = true
Searching for SDK versions in [C:\externsrc\dotnet\winforms\.dotnet\sdk]
Version [3.1.100-preview1-014024] is a better match than [none]
Version [3.1.100-preview2-999999] is a better match than [3.1.100-preview1-014024]
SDK path resolved to [C:\externsrc\dotnet\winforms\.dotnet\sdk\3.1.100-preview2-999999]
```

Note how the global.json is being search for in the Nuget packages folder.

It is possible to make the [SDK resolver respect the global.json file](https://github.com/dotnet/cli/blob/2f2f09d450887470a5f255f9496ae98b54994725/src/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs#L293) by specifying the solution path:

```cmd
C:\externsrc\dotnet\winforms>build.cmd /p:SolutionPath=%cd%\Winforms.sln
.............
...........\msbuild.exe ................. C:\Users\AustinWise\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19461.7\tools\Build.proj
Tracing enabled @ Tue Oct 15 07:27:15 2019 GMT
--- Invoked hostfxr_resolve_sdk2 [commit hash: 7d57652f33493fa022125b7f63aad0d70c52d810]
Probing path [C:\externsrc\dotnet\winforms\global.json] for global.json
Found global.json [C:\externsrc\dotnet\winforms\global.json]
--- Resolving SDK information from global.json [C:\externsrc\dotnet\winforms\global.json]
Value 'sdk/rollForward' is missing or null in [C:\externsrc\dotnet\winforms\global.json]
Value 'sdk/allowPrerelease' is missing or null in [C:\externsrc\dotnet\winforms\global.json]
Resolving SDKs with version = '3.1.100-preview1-014024', rollForward = 'patch', allowPrerelease = true
Searching for SDK versions in [C:\externsrc\dotnet\winforms\.dotnet\sdk]
Found requested SDK directory [C:\externsrc\dotnet\winforms\.dotnet\sdk\3.1.100-preview1-014024]
SDK path resolved to [C:\externsrc\dotnet\winforms\.dotnet\sdk\3.1.100-preview1-014024]
```

I have some ideas about how this might be fixed:
* Change the winforms build scripts or arcade build scripts to pass the solution path. At least for the winforms repo, it appears the file specified for `SolutionPath` does not have to exist.
* Change the arcade SDK installation logic to delete the local .dotnet folder. Currently the scripts install the .NET SDK by extracting the correct version over any existing version. This leaves incorrect SDK versions in place.
* Document that one should always do a clean build when switching branches.

**Comment by RussKie** [comment] 2019-10-15 22:58
@zsd4yr were you looking into the same issue earlier?

**Comment by merriemcgaw** [comment] 2019-10-16 23:46
@markwilkie, @livarcocc  is this the expected behavior?

**Comment by livarcocc** [comment] 2019-10-16 23:49
I believe this is a bug in arcade because it restore a project into the NuGet cache and then builds from there, therefore by-passing the repo's global.json.

@nguerrera found something like that earlier this week I believe.

**Comment by merriemcgaw** [comment] 2019-10-17 00:16
@markwilkie should we move this to the arcade repo?

**Comment by nguerrera** [comment] 2019-10-17 00:24
Duplicate of https://github.com/dotnet/arcade/issues/4102

**Comment by merriemcgaw** [comment] 2019-10-17 00:44
closing as a dupe

**Closed by merriemcgaw** 2019-10-17 00:44 UTC
