### ISSUE TITLE
'Constructor on type 'System.Drawing.Image' not found' crash occurs when trying to add Items in ImageCollection Editor in .NET Core project

### ISSUE THREAD

**Issue by BagavathiPerumalA** [dotnet/winforms#10549] opened 2023-12-29 06:08 UTC
### Environment

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.2

### .NET version

Net 7.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No

### Issue description

When attempting to add an item as an image in the ImageCollection Editor through the Properties window in the .NET Core project, a 'Constructor on type 'System.Drawing.Image' not found' crash occurs. However, this issue is not present in the .NET Framework project. Is there any way to resolve this.

![ImageCollectionEdit](https://github.com/dotnet/winforms/assets/155132856/044cc360-ad09-4520-bf18-642d0bef240f)

### Steps to reproduce

1. Run the sample.
2. Add the ImageListExt Control (UserControl) from the Toolbox to the Form.
3. On the Form designer page, right-click on the control to open the properties window.
4. Click on the MyItems ImageCollection property to edit the ImageCollection.
5. Then, click on the "Add" button to add an item to the "Image Collection Editor."
6. Note that the "Constructor on type 'System.Drawing.Image' not found" crash will occur when attempting to add the item in the "Image Collection Editor."

[ImageListExt-NetCoreIssue](https://github.com/dotnet/winforms/files/13791240/ImageListExt-NetCoreIssue.zip)

**Comment by elachlan** [comment] 2023-12-30 01:10
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment] 2024-01-02 02:52
@BagavathiPerumalA I tested the application you provided, it can repro this issue, which also reproduce in Winforms .Net framework application.
.NET 7.0 or higher version:
![image](https://github.com/dotnet/winforms/assets/26474449/a5042f90-d5b6-4fc9-8a28-180507cde405)
.Net framework 4.8.1:
![image](https://github.com/dotnet/winforms/assets/26474449/ae40980b-b908-42a5-be10-15595fddecaa)

And I did some search: make your ImageCollection editable in the Visual Studio Properties window, you need to implement a custom TypeConverter for the ImageCollection class.
Here is a sample application, please refer to.
[WinFormsApp23.zip](https://github.com/dotnet/winforms/files/13806861/WinFormsApp23.zip)

![image](https://github.com/dotnet/winforms/assets/26474449/ee588e9b-9f42-41d6-8d1f-afb567bc7259)

**Comment by elachlan** [comment] 2024-01-02 03:28
Closing this issue as @Olina-Zhang has provided the appropriate solution.

**Comment by BagavathiPerumal** [comment] 2024-01-24 12:27
We are still experiencing the same issue while using below code in your shared sample. How to resolve this issue.


`public class ImageCollection : List<MyItem>
{
    public Image this[string key]
    {
        get
        {
            Image imageInfo = null;
            IEnumerator enumerator = GetEnumerator();
            try
            {
                while (enumerator.MoveNext())
                {
                    Image imageInfo2 = (Image)enumerator.Current;
                }
            }
            finally
            {
                IDisposable disposable = enumerator as IDisposable;
                if (disposable != null)
                {
                    disposable.Dispose();
                }
            }

            Image result = null;
            if (imageInfo != null)
            {
                result = imageInfo.Clone() as Image;
            }

            return result;
        }
        set
        {
            Image imageInfo = null;
            IEnumerator enumerator = GetEnumerator();
            try
            {
                while (enumerator.MoveNext())
                {
                    Image imageInfo2 = (Image)enumerator.Current;
                }
            }
            finally
            {
                IDisposable disposable = enumerator as IDisposable;
                if (disposable != null)
                {
                    disposable.Dispose();
                }
            }

            if (imageInfo != null)
            {
                imageInfo = value;
            }
            else
            {
                //Add(key, value);
            }
        }
    }
}`


[WinFormsApp-ImageCollection.zip](https://github.com/dotnet/winforms/files/14038171/WinFormsApp-ImageCollection.zip)

**Comment by RaghavendraSudhakar** [comment] 2024-02-07 10:33
@elachlan We are still facing issue after using your code in our sample

public class ImageCollection : List<MyItem>
{
    public Image this[string key]
    {
        get
        {
            Image imageInfo = null;
            IEnumerator enumerator = GetEnumerator();
            try
            {
                while (enumerator.MoveNext())
                {
                    Image imageInfo2 = (Image)enumerator.Current;
                }
            }
            finally
            {
                IDisposable disposable = enumerator as IDisposable;
                if (disposable != null)
                {
                    disposable.Dispose();
                }
            }

            Image result = null;
            if (imageInfo != null)
            {
                result = imageInfo.Clone() as Image;
            }

            return result;
        }
        set
        {
            Image imageInfo = null;
            IEnumerator enumerator = GetEnumerator();
            try
            {
                while (enumerator.MoveNext())
                {
                    Image imageInfo2 = (Image)enumerator.Current;
                }
            }
            finally
            {
                IDisposable disposable = enumerator as IDisposable;
                if (disposable != null)
                {
                    disposable.Dispose();
                }
            }

            if (imageInfo != null)
            {
                imageInfo = value;
            }
            else
            {
                //Add(key, value);
            }
        }
    }
}

[WinFormsApp-ImageCollection.zip](https://github.com/dotnet/winforms/files/14192500/WinFormsApp-ImageCollection.zip)

**Comment by Tanya-Solyanik** [comment] 2024-02-20 00:06
@RaghavendraSudhakar -
I modified your sample program a little because it wasn't working when retargetting to .NET Framework 4.8.1 either. The main change is that I added a [CreateInstance](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.design.collectioneditor.createinstance?view=netframework-4.8.1)
override to your custom collection editor, because `Image` type indeed can't be created automatically because it's abstract, as the error in the 4.8.1 case shows. I also changed the collection type to a standard one, but that is not critical to this scenario. Here is the modified sample - [ImageCollection-Net481.zip](https://github.com/dotnet/winforms/files/14337673/ImageCollection-Net481.zip)

The same CollectionEditor code will not work with the .NET 8 or 9 designer because .NET designer runs in 2 processes. Collection editor form runs in the Visual Studio process, but images, that it creates, are instantiated in the server process in CollectionEditor responsible for the business logic. See [Custom Controls for WinForm's Out-Of-Process Designer - .NET Blog (microsoft.com)](https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/) for details. 

To support designer that runs across 2 processes, you must separate your collection editor into parts that run in the VisualStudio and parts that run the DesignToolsserver process, and then package this collection editor with your custom control into a nuget package. Here is what I did:
	1. Move your control into a control library
	2. Add designer component(binary) that loads into the VisualStudio process, add the client part of Collection editor to the new binary and re-route editor type. This binary should reference https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK and use CollectionEditor base class from there.
	3. Add designer component (binary) that loads into the DesignToolsServer, It contains part on your collection editor that creates new item instances. Reference Microsoft.DotNet.DesignTools.Editors; namespace instead of System.Component.Model. 
	4. Package the design time binaries(dlls) and the control library into a nuget package; reference that package in the test app; and set up `nuget.config` to point to the output directory where that package is built.
	5. Each time you rebuild your package, its version is updated. However becasue nuge caches the previous version, you have to manually update references in your test application (right click in the solution exploded on packages node and select "update" option)

[ImageCollection-Net9.zip](https://github.com/dotnet/winforms/files/14337744/ImageCollection-Net9.zip)

**Closed by Tanya-Solyanik** 2024-02-20 00:06 UTC
Labels: :beetle: bug, area-DesignerSupport
