### ISSUE TITLE
The value of the FileName attribute is not fully displayed when the character length is greater than 16

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3291] opened 2020-05-15 06:20 UTC
* .NET Core Version: 
.NET SDK 5.0.100-preview5.20262.6

* More info:
1. The issue also can reproduce .NET SDK 3.1.
2. The issue can't reproduce on SaveFileDialog control.

* Have you experienced this same bug with .NET Framework?: 
 Yes, this is not a regression issue, which can repro from .NET 3.5 to .NET 4.8. 

**Minimal repro:**
1. Opened the attached reproduce project.([Repo_App.zip](https://github.com/dotnet/winforms/files/4755914/Repo_App.zip))
2. Check the openFileDialog1.FileName = **"openFileDialog1"** in the Form1.cs file, totally have **15** characters.
3. Build & run the application, observer the openFileDialog1's FileName text.
4. Then changed the openFileDialog1.FileName = **"openFileDialog12"** in the Form1.cs file, totally have **16** characters.
5. Build & run the application, observer the openFileDialog1's FileName text.
6. Click anywhere out of VS instance scope, such as windows taskbar.
7. Back to the OpenFileDialog1 to click, then observer the openFileDialog1's FileName text.

**Expected behavior:**
After step5, the openFileDialog1's FileName is text **"openFileDiaog12"**.

**Actual behavior:**
After step3,the openFileDialog1's FileName is text **"openFileDiaog1"**, which is expected.
After step5, the openFileDialog1's FileName is text **"penFileDiaog12"**,not is expected **"openFileDiaog12"**.
After step7, the openFileDialog1's FileName text  is **"openFileDiaog12"**.
![UpdateCoreIssue_3291](https://user-images.githubusercontent.com/38325459/84221356-a172d680-ab07-11ea-9966-8b9ff029c761.gif)

**Comment by merriemcgaw** [comment] 2020-06-04 23:50
@Zheng-Li01 - is this designer or runtime?

**Comment by Zheng-Li01** [comment] 2020-06-05 01:52
@merriemcgaw, this should be runtime issue, due to the issue also can repro when setting the character length is grater than 16 by using code for FileName attribute.

**Comment by merriemcgaw** [comment] 2020-06-09 19:44
Ah, I see. Thanks @Zheng-Li01 - can you update repro steps to indicate that? It would be helpful since the gifs first made us think designer 🙂

**Comment by Zheng-Li01** [comment] 2020-06-10 02:50
@merriemcgaw, sure. 
> Ah, I see. Thanks @Zheng-Li01 - can you update repro steps to indicate that? It would be helpful since the gifs first made us think designer 🙂

Have update the repro steps & repro GIF/project that reproduce the issue by using code.

**Comment by elachlan** [comment] 2022-12-12 06:27
The issue does not reproduce if `AutoUpgradeEnabled = false`.

The text isn't truncated, if you press the "home" button or just the mouse to scroll the text, it shows the whole text.

@Zheng-Li01, does this reproduce in a MVC app?

**Comment by merriemcgaw** [comment] 2022-12-12 23:24
Thank you @elachlan for noting the existence of the remaining characters that don't display. I'd rather not be advising folks to just do that workaround so I like your request to see if it repros in MFC apps. @Olina-Zhang can you find someone from your team to pick that up?

**Comment by Amy-Li03** [comment] 2022-12-13 07:30
@elachlan @merriemcgaw this issue also repro in a MFC app.

**Comment by merriemcgaw** [comment] 2022-12-17 02:52
I think we're going to have to close this as an external issues, due to Windows implementation of the dialog. Given that the content is there, and user only needs to move cursor I'm not sure Windows will do much to change it at this point.

**Closed by merriemcgaw** 2022-12-17 02:52 UTC
Labels: :beetle: bug, help wanted

**Comment by elachlan** [comment] 2022-12-17 03:42
Has an issue been raised with windows? This will certainly confuse users.
