### ISSUE TITLE
System.Windows.Forms.Design.DateTimePickerDesigner is missing

### ISSUE THREAD

**Issue by Leon99** [dotnet/winforms#8501] opened 2023-01-13 03:19 UTC
### Environment

N/A

### .NET version

.NET 6

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Worked in .NET Framework.

### Issue description

We need to have DateTimePicker controls available in a WF designer that we host in our app, which is being ported from .NET Framework to .NET 6. As per https://github.com/dotnet/winforms/issues/4908, DateTimePickerDesigner hasn't been ported from .NET Framework.

Looking at the decompiled sources of `DateTimePickerDesigner`, it's not much code and the reason it wasn't ported is unclear. In fact, if we add a DateTimePicker to the designer programmatically, it appears there but is not clickable, and a clickable component is added to the component tray.

We'd really appreciate any suggestions on solving this.

### Steps to reproduce

N/A

**Comment by merriemcgaw** [comment] 2023-01-18 18:53
This is a duplicate of #8508 which will track the progress of both DataGridView and DateTimePicker.

**Closed by merriemcgaw** 2023-01-18 18:53 UTC
Labels: area: VS designer, untriaged
