### ISSUE TITLE
System.Private.Windows.Core is not included in the runtime pack

### ISSUE THREAD

**Issue by hez2010** [dotnet/winforms#11282] opened 2024-04-27 12:27 UTC
### .NET version

.NET 9 nightly

### Did it work in .NET Framework?

Yes

### Issue description

`System.Private.Windows.Core.dll` is not included in the runtime pack, and leading to the below exception while running a self-contained published app.

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.Windows.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Specified file was not found.
File name: 'System.Private.Windows.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at WinformsTest.Program.Main()
```

### Steps to reproduce

```
dotnet new winforms
dotnet publish -c Release -r win-x64 --self-contained
cd bin\Release\net9.0-windows\win-x64\publish\
.\WinformsTest.exe
```

**Comment by elachlan** [comment] 2024-04-29 02:32
@Olina-Zhang can your team confirm this please?

**Comment by Olina-Zhang** [comment] 2024-04-29 06:37
> @Olina-Zhang can your team confirm this please?

I didn't reproduce the problem with the .Net 9.0 Preview3 build machine at hand.
![image](https://github.com/dotnet/winforms/assets/26474449/3c8ae4d4-3555-424e-bf8f-ef26e1012be9)

**Comment by hez2010** [comment] 2024-04-29 07:48
Maybe it happens on the nightly build only?

**Comment by Olina-Zhang** [comment] 2024-04-29 08:50
> Maybe it happens on the nightly build only?

For the latest daily build, execute `dotnet publish -c Release -r win-x64 --self-contained` failed, I am not sure if it needs some config, cannot verify this issue.
![image](https://github.com/dotnet/winforms/assets/26474449/bdab7bb4-de7c-41ed-bf85-c60e3eed37c9)

**Comment by lonitra** [comment] 2024-04-30 19:46
Tried to repro and got same results as above. Could not repro issue with .NET 9 preview 3 and could not verify with nightly build. I suspect that we do not publish nuget package for unreleased previews which is why the errors are produced. We had previously had an [issue similar](https://github.com/dotnet/winforms/issues/10661) to this when we first introduced System.Private.Windows.Core, where the assembly was not present and needed to be, but this had since been fixed via https://github.com/dotnet/windowsdesktop/pull/4084. Looked through the history there and it doesn't seem that we had regressed this behavior.

@hez2010 to clarify, had you experienced this issue on .NET 9 Preview 3, nightly build, or both?

**Comment by hez2010** [comment] 2024-05-02 05:01
It's reproducing on the nightly build.
To publish the app with nightly build dotnet, you need to configure the nuget source:

```xml
<configuration>
  <packageSources>
    <add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

I'm using 9.0.100-preview.5.24227.1.

**Comment by lonitra** [comment] 2024-05-10 01:32
Fixed via https://github.com/dotnet/windowsdesktop/pull/4366 in main and https://github.com/dotnet/windowsdesktop/pull/4369 in preview 4

**Closed by lonitra** 2024-05-10 01:32 UTC
Labels: :boom: regression-preview, Priority:0

**Comment by MelonWang1** [comment] 2024-05-17 08:50
Verified this issue in the latest .NET 9.0 preview4 SDK build: 9.0.100-preview.4.24266.28, it was fixed. Screenshot as below.
![Untitled](https://github.com/dotnet/winforms/assets/94418985/baee90b2-6188-4069-a7e5-c9ae623f65bc)

**Comment by Olina-Zhang** [comment] 2024-05-24 03:17
Verified it in the latest .Net 9.0 Preview 5 SDK build: 9.0.100-preview.5.24273.4, it was fixed: System.Private.Windows.Core.dll is contained in application's publish folder, and app's EXE can be run.

![image](https://github.com/dotnet/winforms/assets/26474449/dd16588a-d028-4e85-b7ac-4f9cf0c56b37)
