### ISSUE TITLE
[Accessibility] Narrator announces NumericUpDown as "edit" instead of "spinbutton"

### ISSUE THREAD

**Issue by tgriff** [dotnet/winforms#6359] opened 2021-12-17 17:15 UTC
* .NET Core Version: 
None

* Have you experienced this same bug with .NET Framework?: 
Yes, .NET Framework 4.8.1

**Problem description:**
Narrator announces NumericUpDown as "edit" instead of "spinbutton". I have set the AccessibleRole = SpinButton but the control is still announced as "edit". Note that this was reported to me by our internal accessibility test team and I am filing this issue per their guidance.

**Expected behavior:**
Narrator should announce NumericUpDown as "spinbutton".

**Minimal repro:**
Here is a gif of the issue, using Narrator Buddy to show what Narrator is saying (note that it's double-logging, Narrator only says each line once).
![repro](https://user-images.githubusercontent.com/34492055/146582280-b13621b0-2dba-4898-b98e-6b069f6e3d72.gif)

Here is a .NET Framework 4.8.1 WinForms project that produces the issue:
[SpinButtonRepro.zip](https://github.com/dotnet/winforms/files/7736681/SpinButtonRepro.zip)

**Comment by SergeySmirnov-Akvelon** [comment] 2022-01-10 12:09
Hi @dreddy-work, @merriemcgaw. The issue is reproducible because when the user puts focus on the `NumericUpDown` it hits the `TextBox`. The role of `NumericUpDown` in this case does not matter, since we are announcing the state of the `TextBox`, and not the `NumericUpDown` as a whole.

We can change the `Role` of the edits field to `SpinButton`, but in this case the Narrator will announce `spinner` instead of `spinbutton`.
![image](https://user-images.githubusercontent.com/23376742/148763474-8d29f77a-bda1-4468-bdc7-9b36e55929a3.png)

We can also return `spinbutton` as the `LocalizedControlType` property, then the Narrator will announce the expected data.
![image](https://user-images.githubusercontent.com/23376742/148763624-47c12358-ad74-4ba3-bd9e-2b06861d60d4.png)

But I'm not sure if the solutions described above are correct. @dreddy-work, @merriemcgaw, could you share your opinion?

**Comment by SergeySmirnov-Akvelon** [comment] 2022-02-08 11:40
Hi @merriemcgaw, @Tanya-Solyanik, @dreddy-work. I have checked the behavior of `NVDA` and `JAWS` and they also announce the `edit` name:
![image](https://user-images.githubusercontent.com/23376742/152979925-f032f00d-ba44-46e7-839d-36257030b75b.png)

Unfortunately, `JAWS` does not display the name of the control when logging.

The `Narrator`, when using the scan mod, can focus on the `NumericUpDown` and announce the correct `Control` name:
![image](https://user-images.githubusercontent.com/23376742/152980023-175192df-c263-485a-950a-52f009d3b2c6.png)

**Comment by Tanya-Solyanik** [comment] 2022-02-08 14:01
Looks "by design" to me. WInforms distinguishes between the edit box and the full control.

**Comment by merriemcgaw** [comment] 2022-02-15 19:24
I'm going to agree. The UIA Hierarchy should show the control as a whole, and beneath that it should show each sub-control. If so, we can close this issue as by design.

**Closed** 2022-02-22 22:09 UTC
Labels: :construction: work in progress

**Comment by Amy-Li03** [comment] 2022-03-04 09:13
Verified this issue on .NET 7.0.100-preview.3.22153.11 build, this issue is fixed.
![image](https://user-images.githubusercontent.com/62929087/156734257-8779dd8c-0a31-4d34-94e2-e4bddcf83197.png)
