### ISSUE TITLE
Flaky test: `IDispatch_GetTypeInfo_Invoke_Success`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3271] opened 2020-05-13 02:45 UTC
**Problem description:**

https://dev.azure.com/dnceng/public/_build/results?buildId=641217&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c

```
    System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.IDispatchTests.IDispatch_GetTypeInfo_Invoke_Success [FAIL]
      System.Runtime.InteropServices.COMException : Error HRESULT E_FAIL has been returned from a call to a COM component.
      Stack Trace:
           at Interop.Ole32.OleCreatePictureIndirect(PICTDESC* pictdesc, Guid& refiid, BOOL fOwn)
        /_/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs(23,0): at Interop.Ole32.OleCreatePictureIndirect(PICTDESC& pictdesc, Guid& refiid, BOOL fOwn)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs(3988,0): at System.Windows.Forms.AxHost.GetIPictureDispFromPicture(Image image)
        /_/src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/IDispatchTests.cs(94,0): at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.IDispatchTests.SubAxHost.GetIPictureDispFromPicture(Image image)
        /_/src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/IDispatchTests.cs(39,0): at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.IDispatchTests.IDispatch_GetTypeInfo_Invoke_Success()
```

**Comment by weltkante** [comment] 2020-05-13 08:50
Theres at least one more of that category, `IPictureTests.GetPictureFromIPictureDisp`

https://dev.azure.com/dnceng/public/_build/results?buildId=639224&view=ms.vss-test-web.build-test-results-tab

```
System.Runtime.InteropServices.COMException : Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Interop.Ole32.OleCreatePictureIndirect(PICTDESC* pictdesc, Guid& refiid, BOOL fOwn)
   at Interop.Ole32.OleCreatePictureIndirect(PICTDESC& pictdesc, Guid& refiid, BOOL fOwn) in /_/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs:line 23
   at System.Windows.Forms.AxHost.GetIPictureDispFromPicture(Image image) in /_/src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs:line 3988
   at System.Windows.Forms.Primitives.Tests.Interop.Ole32.IPictureTests.AxHostAccess.GetIPictureDispFromPicture(Image image) in /_/src/System.Windows.Forms.Primitives/tests/Interop/Ole32/IPictureTests.cs:line 85
   at System.Windows.Forms.Primitives.Tests.Interop.Ole32.IPictureTests.GetPictureFromIPictureDisp() in /_/src/System.Windows.Forms.Primitives/tests/Interop/Ole32/IPictureTests.cs:line 67
```

Somewhere else I commented it might be related to not having OLE initialized on that thread (this is fixed in xunit.stafact already) so it'd be interesting to see if these tests stop being flaky once we can update the nuget package.

On the other hand I cannot reproduce any failures locally, including intentionally invoking it on a MTA thread without OLE initialized, so I'm confused about the cause of these failures, I'm just guessing.

If OLE initialization (done by `Application.OleRequired`) is indeed necessary then some of the tests need to be moved from `[Fact]` to `[WinFormsFact]`

**Comment by hughbe** [comment] 2020-05-13 08:59
Note that these tests already are `WinFormsFact`:
```cs
        [WinFormsFact]
        public unsafe void IDispatch_GetTypeInfo_Invoke_Success()
        {
            using var image = new Bitmap(16, 16);
            IPictureDisp picture = SubAxHost.GetIPictureDispFromPicture(image);
            IDispatch dispatch = (IDispatch)picture;

            ITypeInfo typeInfo;
            HRESULT hr = dispatch.GetTypeInfo(0, Kernel32.GetThreadLocale(), out typeInfo);
            Assert.Equal(HRESULT.S_OK, hr);
            Assert.NotNull(typeInfo);
        }
```

**Comment by weltkante** [comment] 2020-05-13 09:04
WinFormsFact without xunit.stafact doesn't do OleRequire on the STA thread

The [other](https://github.com/dotnet/winforms/blob/fde3805ea206227ad01266c7d25ce0ed2df4996f/src/System.Windows.Forms.Primitives/tests/Interop/Ole32/IPictureTests.cs#L63) flaky test is still a plan Fact and running on MTA (tested with debug output) - but its not failing locally.

So like I said I'm only guessing, the API which fails is an OLE call so my guess it needs to have initialized OLE via native OleInitialize (called through Application.OleRequired in WinForms). I have no idea if thats _actually_ the problem since the failures never happened for me locally.

**Comment by weltkante** [comment] 2020-05-13 09:46
The blocking issue for the xunit.stafact update was resolved so we can just update the nuget package and see if the flakyness goes away for `IDispatch_GetTypeInfo_Invoke_Success`
* If it does then OleInitialize was the problem and the other test should become WinFormsFact as well
* If still flaky after merging #3276 then the problem was something else

**Comment by weltkante** [comment] 2020-05-21 01:13
@RussKie note that this [may not be fixed](https://github.com/dotnet/winforms/pull/3315#issuecomment-631478269). This issue was about `OleCreatePictureIndirect` returning `E_FAIL` while the PR fixed an exception with ITypeInfo later in the same method.

You don't have to reopen if you don't see the failures again, just wanted to drop you a note that there may have been two interop issues in the same tests. (Also `OleCreatePictureIndirect` was failing in IPictureTests, unrelated to the ITypeInfo fixes.)

**Comment by RussKie** [comment] 2020-05-21 01:17
Thank you, I'll keep it open for now.

**Comment by weltkante** [comment] 2020-06-03 10:38
This needs reevaluation now that the xunit.stafact was updated. We need to know if these test failures still happen on CI. If they went away for `IPictureTests.GetPictureFromIPictureDisp` then `IPictureTests.GetPictureFromIPictureDisp` also needs to be WinFormsFact and this can be closed.

**Comment by weltkante** [comment] 2020-06-03 11:07
If #3013 is merged before this is analyzed the above assumptions no longer hold, the tests will be turned back to StaFact and OleInitialize won't be called.

**Comment by kant2002** [comment] 2022-04-08 07:52
@dreddy-work this does not appears anymore from what I know. Probably can be closed as fixed.

**Comment by dreddy-work** [comment] 2022-04-08 16:42
Thanks @kant2002 .

**Closed by dreddy-work** 2022-04-08 16:42 UTC
Labels: test-bug, area: COM, area: interop
