### ISSUE TITLE
ApplicationConfiguration source generator does not support decimal font size

### ISSUE THREAD

**Issue by daniel-lerch** [dotnet/winforms#6614] opened 2022-02-03 15:47 UTC
* .NET Core Version:  
6.0.101

* Have you experienced this same bug with .NET Framework?:  
No

**Problem description:**
The source generator for `ApplicationConfiguration.Initialize()` does not handle decimal font sizes correctly. When I tried to use the old default font settings from .NET Framework in .NET 6.0 via project file, I got a build error.

The source generator uses a decimal comma instead of a decimal point:
```csharp
//                                                                           ↓
Application.SetDefaultFont(new Font(new FontFamily("Microsoft Sans Serif"), 8,25f, (FontStyle)0, (GraphicsUnit)3));
//                                                                           ↑
```

OS: Windows 10.0.19044.1466
OS locale: **de-DE**

**Expected behavior:**
The source generator must use a decimal point for all OS locales like already written in the .csproj file:
```csharp
//                                                                           ↓
Application.SetDefaultFont(new Font(new FontFamily("Microsoft Sans Serif"), 8.25f, (FontStyle)0, (GraphicsUnit)3));
//                                                                           ↑
```

**Minimal repro:**
1. Create a new Windows Forms project `dotnet new winforms`
2. Add the following line to your `.csproj` file ([this is officially recommended](https://docs.microsoft.com/de-de/dotnet/desktop/winforms/whats-new/net60?view=netdesktop-6.0#change-the-default-font))
```xml
<ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt</ApplicationDefaultFont>
```
3. Try to build your application and watch compiler errors

**Comment by tbolon** [comment] 2022-02-03 20:34
It seems it is a duplicate of #6144, which has been fixed by #6164 and will be released in 6.0.2

**Closed** 2022-02-03 20:38 UTC
