### ISSUE TITLE
ListView Sort Throws NullReferenceException or EngineExecutionException Intermittently

### ISSUE THREAD

**Issue by athieman** [dotnet/winforms#4301] opened 2020-11-30 17:19 UTC
* .NET Core Version:
    <details>
        <summary>5.0.100</summary>

         OS Name:     Windows
         OS Version:  10.0.17763
         OS Platform: Windows
         RID:         win10-x64
         Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

         Host (useful for support):
         Version: 5.0.0
         Commit:  cf258a14b7

         .NET SDKs installed:
         5.0.100 [C:\Program Files\dotnet\sdk]

         .NET runtimes installed:
         Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
         Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
         Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
         Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
         Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
         Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
         Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
         Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
         Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
   </details>

* Have you experienced this same bug with .NET Framework?: No
 
* Problem Description:

    When sorting a ListView by a column, a NullReferenceException or EngineExecutionException is sometimes thrown.  On my computer a ListView with 2 columns and 1,000 rows will throw an exception after being sorted about 12 times.  When the number of rows is increased to 10,000, it will throw an exception on either the first or second time the ListView is sorted.  The same problem does not occur in .NET Core 3.1.

**Expected behavior:**
No exceptions should be thrown when sorting a ListView by a column when none of the subitems in the the ListView are null.

**Minimal repro:**
I have uploaded the small demo application to the following repository: [GitHub](https://github.com/athieman/ListView-Sorting-Bug/tree/main)

Increasing the size variable in the LoadData method makes it easier to reproduce, but with the default 1,000 items it usually throws either a NullReferenceException or EngineExecutionException after sorting one of the columns 12 times on my machine.

The issue does appear to be similar to #4264 ListView.Items.Add throws ExecutionEngineException with custom ListViewItemSorter, but because I am seeing a NullReferenceException much more often than the ExecutionEngineException I made a new Issue.

**Comment by kpreisser** [comment] 2020-12-01 08:13
I think the `NullReferenceException` in this case (and in #4292) has probably the same root cause as the `ExecutionEngineException` in #4264, which was caused by the callback delegate being GCed too early (which seems to have been introduced in #2800 so it didn't happen in .NET Core 3.1).

(When I tried to reproduce the issue in #4264, I also sometimes got `NullReferenceExceptions`, which is not surprising as invalid memory access can cause all sorts of random issues.)

**Comment by Olina-Zhang** [comment] 2020-12-02 06:33
Verified this issue in .Net SDK 5.0.101-servicing.20601.5 build, this issue cannot repro now using above provided sample app: 
[ListView-Sorting-Bug-main.zip](https://github.com/dotnet/winforms/files/5627384/ListView-Sorting-Bug-main.zip).
![ListViewSort_Fixed](https://user-images.githubusercontent.com/26474449/100836980-4238c200-34ab-11eb-975a-317abecfc69e.gif)

**Comment by RussKie** [comment] 2020-12-02 07:18
Thank you @Olina-Zhang. 

Presume the issue duplicate of https://github.com/dotnet/winforms/issues/4264, and fixed.

**Comment by RussKie** [comment] 2020-12-02 07:19
Duplicate of #4264

**Closed by RussKie** 2020-12-02 07:19 UTC
