### ISSUE TITLE
When dotnet5 creates a windowless program, it starts with an error 

### ISSUE THREAD

**Issue by hanjunjun** [dotnet/winforms#6843] opened 2022-03-14 14:47 UTC
* .NET Core Version: 
5.0.421.11614

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
When dotnet5 creates a windowless program, it starts with an error 
There is no error when debugging, everything is normal, and the publishing program is running with an error 
![image](https://user-images.githubusercontent.com/16394348/158196305-9e5c70c3-7511-4cd9-b765-1f1fdc8ed437.png)
![image](https://user-images.githubusercontent.com/16394348/158196823-ddbb2610-216e-4b07-9f9a-0ae8b6f2182c.png)

**Expected behavior:**
Program starts normally 

**Minimal repro:**
```static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main(string[] args)
        {
            MessageBox.Show("test");
            Application.Run();
    }

**Comment by hanjunjun** [comment] 2022-03-14 15:48
I found the reason: it is a single file packaging problem
I used the AForge.dll component

**Comment by dreddy-work** [comment] 2022-03-14 20:32
@hanjunjun , while i did not fully understand the issue here. Is this solved for you? can we close this or are you expecting a resolution from Winforms here?

**Comment by hanjunjun** [comment] 2022-03-15 05:44
> @hanjunjun , while i did not fully understand the issue here. Is this solved for you? can we close this or are you expecting a resolution from Winforms here?

sorry, i'm using google translate

**Comment by hanjunjun** [comment] 2022-03-15 05:45
> > @hanjunjun , while i did not fully understand the issue here. Is this solved for you? can we close this or are you expecting a resolution from Winforms here?
> 
> sorry, i'm using google translate

I use AForge.dll components, the released program will crash when running, but it is normal to run in debug or release mode

**Comment by hanjunjun** [comment] 2022-03-15 05:45
> @hanjunjun , while i did not fully understand the issue here. Is this solved for you? can we close this or are you expecting a resolution from Winforms here?

I use AForge.dll components, the released program will crash when running, but it is normal to run in debug or release mode

**Comment by RussKie** [comment] 2022-03-15 06:03
@hanjunjun you need to debug your program and find the root cause. If you can demonstrate the issue is caused by Windows Forms runtime we can investigate it further. If the issue is caused because you use AForge.dll you'll need to seek support from the author of that library. 

0xc0000005 error in your screenshot is a Windows level issue, which may be caused my multitude of different reasons (such as a configuration of your workstation) all of which are very unlikely to be caused by Windows Forms. You can narrow down your issues by trying to build/run your app under a different user on your workstation, or try a different workstation altogether.

**Comment by hanjunjun** [comment] 2022-03-18 03:15
> @hanjunjun you need to debug your program and find the root cause. If you can demonstrate the issue is caused by Windows Forms runtime we can investigate it further. If the issue is caused because you use AForge.dll you'll need to seek support from the author of that library.
> 
> 0xc0000005 error in your screenshot is a Windows level issue, which may be caused my multitude of different reasons (such as a configuration of your workstation) all of which are very unlikely to be caused by Windows Forms. You can narrow down your issues by trying to build/run your app under a different user on your workstation, or try a different workstation altogether.

I found the reason:
It is because AForge cannot find the dynamic library due to single-file packaging, so it crashes
thanks

**Closed** 2022-03-18 03:15 UTC
