### ISSUE TITLE
KeyUp fired many times when RDP session get focus

### ISSUE THREAD

**Issue by manuz90flw** [dotnet/winforms#11581] opened 2024-06-24 10:00 UTC
### .NET version

.NET 8 C# and Vb.net
.NET framework 4.8 

### Did it work in .NET Framework?

Yes

### Issue description

Hi,

When the old app remote desktop(blue icon) is activated or move the window, it fires many times the keyup event on winforms.
This happens on .NET core and also on .NET framework
I tried also these apps but they are not affected :
- teamviewer
- anydesk
- new remote desktop app(red icon)
- nutanix remote console(html console)

### Steps to reproduce

![Keyup](https://github.com/dotnet/winforms/assets/143181192/0d2a6ed5-088c-4f07-9e5a-767514d3fe27)

**Comment by elachlan** [comment] 2024-06-24 19:56
@Olina-Zhang can your team please test this?

**Comment by Zheng-Li01** [comment] 2024-06-25 02:01
The issue can reproduce on both .NET Framework from 4.6 ~ 4.8.1 and .NET 6.0 ~ 9.0.
![GH11581](https://github.com/dotnet/winforms/assets/38325459/cd90aa84-2e6b-448f-b122-0054eb4dc91b)

And noticed there always fired 4 Tab/2 ShiftKey/2 ControlKey/2 Menu as group every time. and not reproduce such as keydown/keypress events.
![image](https://github.com/dotnet/winforms/assets/38325459/65c87d3c-ada7-41ba-9c2c-982f5cc3b7dd)

**Comment by elachlan** [comment] 2024-06-25 02:08
@kirsan31 You have done a bit of work in conjunction with RDP. Have you run into this at all?

**Comment by kirsan31** [comment] 2024-06-25 13:18
> @kirsan31 You have done a bit of work in conjunction with RDP. Have you run into this at all?

Sorry, but - no. Bye 2 reasons:
 - We are not monitoring KeyUp event anywere.
 - In 99.9% of time we are using fullscreen rdp window.

**Comment by manuz90flw** [comment] 2024-06-25 13:41
@kirsan31 This happends also in full screen.

These steps to reproduce:

1. RDP session in fullscreen on first monitor
2. click on second monitor without RDP session(black side)
3. click on RDP session
4. the keyup event fire many times

![Keyup2](https://github.com/dotnet/winforms/assets/143181192/c456cc98-8c72-4ad0-a0f1-33d6d1604123)

**Comment by merriemcgaw** [comment] 2024-06-25 18:45
This seems to be an issue with RDP. Did this work in a previous version of RDP for your product? My strong recommendation is that you check StackOverflow and answers.microsoft.com? This appears to happen for all versions of .NET Framework, so this is likely happening with the Common Controls as well. The question is whether we've always had this issue in all versions of RDP or if this is a new situation.

**Comment by manuz90flw** [comment] 2024-06-26 09:30
Hi @merriemcgaw ,

I think it's a issue with RDP. 
I did some other tests:

1. VM with Windows 7 connect to windows server 2022 and I can replicate the issue
![KeyupWin7](https://github.com/dotnet/winforms/assets/143181192/d6a59422-2d77-4dcc-8232-b53b18f680e5)
2. VM with Windows 8.1 connect to windows server 2022 and I can replicate the issue
![KeyupWin8](https://github.com/dotnet/winforms/assets/143181192/4b9e014f-0b1c-43af-913f-84abb5a36336)
3. Windows 10 connect to VM Windows 8.1 and I can replicate the issue
4. Windows 10 connect to Windows server 2022 and I can replicate the issue with **javascript**
![KeyupWin10javascript](https://github.com/dotnet/winforms/assets/143181192/086418b8-cbe1-4ea6-acb1-c123ef685f73)

**Comment by merriemcgaw** [comment] 2024-06-28 00:09
@manuz90flw The best advice I can give you at this point is to use the Windows feedback tool to file the feedback against RDP. That will allow you to engage directly with that product team and to provide any diagnostic data they might need. Unfortunately there isn't much for WinForms to do at this point, so I'm going to close this issue.

**Closed by merriemcgaw** 2024-06-28 00:09 UTC
Labels: tracking-external-issue, untriaged
