### ISSUE TITLE
Long text causes ToolStripLabel not to display any text.

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#6362] opened 2021-12-18 07:16 UTC
If you have a long text that needs to be displayed on the ToolStripLabel control, when your form interface is not wide enough, ToolStripLabel will hide all the text instead of using ellipsis to replace the content that is not wide enough.

If no text is displayed, it looks like the entire control is missing.

Suppose the program prompts the user with an important message (The program itself may not be able to determine the length of the message to display because the content of the message is dynamically generated and may be short or long), because the message text is too long and the user might not be able to see it.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstriplabel

Test Code:
.net 6.0

```
namespace ToolStripLabelTest
{
    internal static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();
            Application.Run(CreateForm());
        }

        private static Form CreateForm()
        {
            var frm = new Form()
            {
                Width = 600,
                Height = 400,

                StartPosition = FormStartPosition.CenterScreen,
            };

            var toolStrip = new ToolStrip();

            var label = new ToolStripLabel()
            {
                Text = "long application message text long application message text long application message text long application message text long application message text",
            };

            toolStrip.Items.Add(label);
            frm.Controls.Add(toolStrip);

            return frm;
        }
    }
}
```

Test Result:

![001](https://user-images.githubusercontent.com/88176616/146634770-e45c5983-7c55-4b9b-980e-61b04e0db130.png)

![002](https://user-images.githubusercontent.com/88176616/146634771-c81152e4-7713-466b-9b7e-d1285d168345.png)

Expected effect:

When the width of ToolStripLabel is not enough, this control can use ellipsis to display content that is not wide enough.

p.s:

If you don't see the issue, it may be that your computer font is different from the font I used. Adjust the width of the Form to 500, or 400, and it can be displayed.

**Comment by Lydia-Shi** [comment] 2021-12-20 09:14
This issue also reproduce in .NET Framework. The label has been collapsed in Form designer. 
![image](https://user-images.githubusercontent.com/54019172/146741174-c3031dd0-b57c-4cdf-9c29-166a1257db17.png)

**Comment by dreddy-work** [comment] 2021-12-20 18:36
@roland5572, did you notice same in .NET framework 4.8? or earlier core versions like .NET 3.1 or 5.0?

**Comment by roland5572** [comment] 2021-12-21 02:01
@dreddy-work Yes, I just recompiled it and it appeared in .net framework 4.8 and .net 5.0

**Comment by jbhensley** [comment] 2022-01-14 20:45
I believe this is where it's happening and appears to be by design. Are there any cases where `ToolStrip` uses ellipsis to indicate overflow?

https://github.com/dotnet/winforms/blob/b25dca42b0bd1c923ab6b59de3543027e8cfd3e1/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs#L561-L605

**Comment by roland5572** [comment] 2022-01-16 10:03
@jbhensley 

This problem causes the ToolStrip to never display **long text**, because once it does, the **ToolStripLabel** control disappears.

I just did a test. Same problem with **StatusStrip**, I will create a new post about this issue.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.statusstrip

**Comment by RussKie** [comment] 2022-01-17 02:15
> If you have a long text that needs to be displayed on the ToolStripLabel control, when your form interface is not wide enough, ToolStripLabel will hide all the text instead of using ellipsis to replace the content that is not wide enough.
> If no text is displayed, it looks like the entire control is missing.
>
> Suppose the program prompts the user with an important message (The program itself may not be able to determine the length of the message to display because the content of the message is dynamically generated and may be short or long), because the message text is too long and the user might not be able to see it.

I can certainly appreciate that this can look confusing. However I'd question the UI design decision/implementation first, e.g. whether a status strip is the right control to present an "important message" to a user, and whether an important message must be long. There are other better suited controls for gaining user attention, such as [`MessageBox`](https://docs.microsoft.com/dotnet/api/system.windows.messagebox) and [`TaskDialog`](https://docs.microsoft.com/dotnet/api/system.windows.forms.taskdialog) controls.
A toolstrip and a status strip controls are designed to present [short text](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb226828(v=vs.85)) (or a graphics) to a user, but the text is never meant to be "War and Peace" long. You can certainly do this, but it doesn't mean you should.

> Are there any cases where `ToolStrip` uses ellipsis to indicate overflow?

I _personally_ doubt it. Having spent a weekend wrestling with persistence/restoration of strips in an OSS project I can only issue a warning "Here're be dragons". I would also be extremely reluctant making any changes in this space because of compat risks - the functionality is quite complicated and has been like this for a very long time.

I'm going to close this as "by design". If you can think of a clever way to address this without breaking existing customers let's continue the discussion.

**Closed by RussKie** 2022-01-17 02:15 UTC

**Comment by roland5572** [comment] 2022-01-17 03:58
@RussKie Thank you for the explanation. But I think, as a Label control, you can't ask the programmer to limit its text length, or limit the text to a very small width, because the interface width of the program and the width of the display screen may change at any time.  the text that needs to be displayed should be determined by business logic, not the width of the characters.

The current Label Control may cause the text to be displayed to **full disappear** at any time due to **insufficient width**.

In this sample program, because there are no other controls, it occupies a relatively large width. In practical applications, when there are other buttons and controls, even a **small width** may cause the Label control to disappear.

A MessageBox can display a temporary message, but it cannot display a persistent message. Sometimes you may want to display this message until the user closes the program.

**Comment by RussKie** [comment] 2022-01-17 04:22
I'm not disagreeing that the behavior of the strip controls can be questioned in some scenarios. However I am pointing out that those scenarios should be questioned, and UI/UX impacts on end users should as well be assessed and considered. For instance neither Windows nor Office dumps a ton of text on me when there's a notification or a reminder:
![image](https://user-images.githubusercontent.com/4403806/149707542-cd60e2d7-bf06-4ed1-a3c9-6f85cbb501a9.png)


I am not currently satisfied the use case you're describing warrants the change given that a) it's been like this for a very long time, and b) it doesn't align with the general Win32 design guidelines. I appreciate this will likely result in work on your end, however the risk of breaking a very large number of customer far outweighs your pain.

**Comment by roland5572** [comment] 2022-01-17 04:49
@RussKie 

Thank you.

Not only important messages, but even some ordinary texts, there will still be such problems.

I recommend adding some hints to the product documentation.
Because some programmers may not understand this feature. In some unexpected circumstances, the text that needs to be displayed may not be displayed.

**Comment by jbhensley** [comment] 2022-01-17 13:18
I agree with @RussKie. Here was my line of thinking just for the record:

This is a change to functionality as opposed to a fix. The most reasonable way to do so would be to add a new property to `ToolStrip` and/or `ToolStripLabel` so users can indicate how this type of scenario should be handled. The default behavior would match existing so as to not break compat. The options would need to be worked out, but could be something like:

- Default: current behavior
- Clip: clip text at the point of overflow
- Ellipsis: clip text, but add ellipsis to indicate overflow

I feel like the last option is troublesome. It requires finding the correct text length with ellipsis included. You also have to consider the font in use. If, say, the font were set to something like Wingdings then just appending "..." wouldn't work. The ellipsis would need to be in a font assured to represent it correctly, but that might also cause that portion of text to not match the rest. I know this is very edge case, but solving the nominal is always the easy part.

You also have to consider that `ToolStrip` already contains an overflow section and how this clipping behavior would interact with that. Presently, the long `ToolStripLabel` is pushed to overflow as seen below. However, if `CanOverFlow` is set to `false` then that section does not exist and it is simply not rendered.

![image](https://user-images.githubusercontent.com/13544395/149775288-3e1fa5b7-3dbf-469f-a12c-475a6a54966e.png)

Overall, there are a lot of scenarios here that would need to be worked out. The change isn't quite as simple as it might first appear.
