### ISSUE TITLE
C1FlexGrid needs System.Drawing.Design.UITypeEditorEditStyle in System.Drawing

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/winforms#270] opened 2018-12-26 12:58 UTC
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: No

I tried to convert one of our project to .Net Core 3.0 with WinForms, and it compiles and works fine for the most parts, but one of the external components(C1FlexGrid) we use always throws a error:
System.TypeLoadException: Could not load type 'System.Drawing.Design.UITypeEditorEditStyle' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Even if I add a different Assembly that Implements 'System.Drawing.Design.UITypeEditorEditStyle' then the Error Persists.

**Actual behavior:**
System.TypeLoadException: Could not load type 'System.Drawing.Design.UITypeEditorEditStyle' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at #s5.#m7.#R6(Int32 #j, Int32 #l)
   at #s5.#Ojb.HitTest(Int32 #zq, Int32 #rP)
   at #s5.#Ojb.#8ib(MouseEventArgs #tQ)
   at C1.Win.C1FlexGrid.C1Flex
GridBase.OnMouseMove(MouseEventArgs e)

**Expected behavior:**
No Error

**Minimal repro:**
[vbc.zip](https://github.com/dotnet/winforms/files/2710257/vbc.zip)
I have attached a Sample Project, if it doesn't work, then you could try to download a trial from https://www.grapecity.com/en/download/componentone-studio and folow these steps to recrerate the sample:
1. dotnet new winforms
2. Edit 'Form1.Designer.cs' and add these lines at the end of 'InitializeComponent':
C1.Win.C1FlexGrid.C1FlexGrid fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.Controls.Add(fg);
            fg.Dock= System.Windows.Forms.DockStyle.Fill;
            fg.BringToFront();

**Comment by KlausLoeffelmann** [comment] 2019-01-02 16:17
Hi @Lohnegrim,

the C1FlexGrid assembly you used: Is that a classic framework or a .NET Core assembly?
(If that would be a classic framework assembly/component, the behavior is expected since both assembly types core/classic are not compatible).

**Comment by Lohnegrim** [comment] 2019-01-02 18:22
Hi @KlausLoeffelmann,
>>the C1FlexGrid assembly you used: Is that a classic framework or a .NET Core assembly?
It is the classic Framework.

>> (If that would be a classic framework assembly/component, the behavior is expected since both assembly types core/classic are not compatible).
Is, or will/should/may it be compatible in the future, or a will workaround for missing types like this?

**Comment by KlausLoeffelmann** [comment] 2019-01-02 20:40
> Is, or will/should/may it be compatible in the future, or a will workaround for missing types like this?

Well, no. Those are different platforms which cannot be made compatible. It is their nature that they aren't compatible. That said, there may be a good chance that your control provider (which is Component One I assume?) might be providing a version for WinForms Core in the future. You might want to check with them.

I am closing this.

**Comment by SlavaB** [comment] 2019-01-18 19:03
> Hi @Lohnegrim,
> 
> the C1FlexGrid assembly you used: Is that a classic framework or a .NET Core assembly?
> (If that would be a classic framework assembly/component, the behavior is expected since both assembly types core/classic are not compatible).

It seems like this is very incompetent answer. C1FlexGrid uses the standard WinForms classes. In particular System.Drawing.Design.UITypeEditorEditStyle should be already ported to Microsoft.WindowsDesktop.App . But this still has not been done.

**Comment by AdamYoblick** [comment] 2019-01-18 19:10
@dreddy-work Did System.Drawing.Design ever get ported to net core 3? I'm looking at the winforms source and it looks like we only have a facade to primitives, which have moved into a package we now consume.

Are there any plans to port System.Drawing.Design.UITypeEditorEditStyle?

**Comment by IrinaPykhova** [comment] 2019-01-19 13:08
> the C1FlexGrid assembly you used: Is that a classic framework or a .NET Core assembly?
> (If that would be a classic framework assembly/component, the behavior is expected since both assembly types core/classic are not compatible).

do you need us to give you links to blog posts or videos where MS declares compatibility and support of scenarios when WinForms and WPF controls can be used as is in .Net Core 3 applications?
The most of our controls just work. System.Drawing.Design.UITypeEditorEditStyle is a very simple enumeration which we use in public API in different assemblies. In classic framework it is defined in System.Drawing.dll assembly. We are expecting that it should be supported in .Net Core 3. It is really odd to build special version of binaries due to single absent enum. Especially because there are several threads here, where .Net Core team discusses that it should be included.
We can give you sample project demonstrating the problem. 
Please open this issue and let us know when it is expected to be fixed.

**Comment by IrinaPykhova** [comment] 2019-01-19 13:11
@Lohnegrim, thank you for posting this. We think that this issue should be fixed on MS side.

**Comment by KlausLoeffelmann** [comment] 2019-01-20 11:40
@IrinaPykhova: A sample would be helpful to avoid misunderstanding - and obviously I have been answered prematurely. Sorry for that. I will reopen, and will discuss this with the team, especially with the aspect of breaking changes we need to make for future improvements, and the consequences this will have in backwards compatibility.

**Comment by SlavaB** [comment] 2019-01-21 06:53
@KlausLoeffelmann , please take a look to the attached sample.
[TestApp.zip](https://github.com/dotnet/winforms/files/2777814/TestApp.zip)

**Comment by KlausLoeffelmann** [comment] 2019-01-27 12:51
Hey guys,

thanks for your patients, here. I talked with the team, and you should see the missing method in one of the upcoming releases. When you can confirm, this issue has been resolved, quickly ping me, and I close this. If this is not resolved during next week, also ping me, and I will investigate. Thanks!

**Comment by SlavaB** [comment] 2019-01-28 13:15
@KlausLoeffelmann , thanks, I will track the changes. 
Note, the problem is that System.Drawing.Design.UITypeEditorEditStyle enum is now in System.Windows.Forms assembly. But the enum was in System.Drawing assembly earlier, in .Net Framework.

**Comment by KlausLoeffelmann** [comment] 2019-01-28 13:30
@dreddy-work?

**Comment by SlavaB** [comment] 2019-02-12 07:14
@KlausLoeffelmann, any updates on this?

**Comment by KlausLoeffelmann** [comment] 2019-02-19 14:39
@dreddy-work, @zsd4yr - shouldn't this be in by now?

**Comment by merriemcgaw** [comment] 2019-02-22 23:30
@JuditRose assigning this to you as you're working on porting a bunch of the editors in now.

**Comment by prabhakarGC** [comment] 2019-03-12 05:57
Do we know when this fix will be available?

**Comment by zsd4yr** [comment] 2019-03-12 20:20
@JuditRose can update on status

**Comment by JuditRose** [comment] 2019-03-15 00:39
This component exists in System.Windows.Forms: https://github.com/dotnet/winforms/blob/82634b7a59c5d1253fc3ee2107092868546c6f79/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditorEditStyle.cs
@Lohnegrim @IrinaPykhova @prabhakarGC Can you please double check if you reference it the right way?

**Comment by OliaG** [comment] 2019-03-15 00:47
Do we know why it was moved to the new place? @merriemcgaw @dreddy-work?

**Comment by IrinaPykhova** [comment] 2019-03-15 17:54
@JuditRose, the problem is that we don't want to rebuild all our assemblies under .Net Core 3. We are trying to use .Net 4.0 version as is in .Net Core 3 application. Almost everything else just works. But in such scenario we got runtime exception that this enum does not exist. I think the problem is that in full Framework and in .Net Core 3 it is placed in different assemblies. Don't you have some option to set mapping to workaround such problems?
You can check sample (TestApp.zip) attached by SlavaB on January 21st to see the problem

**Comment by SlavaB** [comment] 2019-03-29 06:47
It seems the issue with  UITypeEditorEditStyle had been fixed. I checked it with SDK 3.0.100-preview4-010999.

**Comment by merriemcgaw** [comment] 2019-03-29 18:58
Great! I will close this issue then.

**Closed by merriemcgaw** 2019-03-29 18:58 UTC
Labels: bug, tenet-compatibility
