### ISSUE TITLE
Graphics.DrawIcon Applies TranslateOffset Twice

### ISSUE THREAD

**Issue by pshumnov** [dotnet/winforms#11611] opened 2024-06-28 15:05 UTC
### .NET version

8.0.4
7.0.18
6.0.29

### Did it work in .NET Framework?

Yes

### Issue description

When using **Graphics.DrawIcon()** after **Graphics.TranslateTransform()**, the transformation is applied twice, as illustrated in the attached screenshot. 

An [existing issue](https://github.com/dotnet/winforms/issues/6252) on this topic was closed because it could not be reproduced in newer versions. However, I can still reproduce it in a clean project using newer .NET Core versions.

I am reporting this on behalf of the WinForms team at DevExpress, a Microsoft partner, as our users have also encountered this issue.

![image](https://github.com/dotnet/winforms/assets/65417507/708671dd-04ce-43fe-8ccf-202ff7260613)

### Steps to reproduce

Steps to Reproduce:
1. Call Graphics.TranslateTransform().
2. Call Graphics.DrawIcon().
3. Compare the icon's positioning to a rectangle's position for clarity.

A sample app is attached.
[DrawIconTranslateTransform.zip](https://github.com/user-attachments/files/16032032/DrawIconTranslateTransform.zip)

**Comment by elachlan** [comment] 2024-06-29 04:52
@Olina-Zhang can your team please test this?

**Comment by elachlan** [comment] 2024-06-30 00:04
This is my result on main branch.
![image](https://github.com/dotnet/winforms/assets/2433737/69c99193-cfff-4447-9398-1a90126cb64a)

```csharp
private void Form1_Paint(object sender, PaintEventArgs e)
{
    Rectangle bounds = new(0, 0, 64, 64);
    e.Graphics.TranslateTransform(64, 32);
    e.Graphics.DrawIcon(Icon, bounds);
    Rectangle rectangleBounds = new(4, 4, 56, 56);
    e.Graphics.FillRectangle(Brushes.Blue, rectangleBounds);
}
```

Here is the code that does the transform:
https://github.com/dotnet/winforms/blob/2a6733dc972bbe0e4bb0489385fb7ce42163bf66/src/System.Drawing.Common/src/System/Drawing/Icon.cs#L360-L375

If I comment out the transform I get:
![image](https://github.com/dotnet/winforms/assets/2433737/bb3ae194-9a86-40cf-822f-040c56d172ef)

**Comment by MandiMan** [comment] 2024-07-01 02:42
@elachlan  Verified this issue on ScratchProject of winforms repo, latest .NET 9.0.100-preview.7.24329.1 and .NET Framework, the test results are the same:
![image](https://github.com/dotnet/winforms/assets/108860782/c62695d1-a6c1-4598-a1d2-13ed2979e96c)
.NET 8.0 test result:
![image](https://github.com/dotnet/winforms/assets/108860782/a8690375-617f-4664-a992-316176912ed2)

**Comment by elachlan** [comment] 2024-07-01 03:48
Is the top result from framework on .NET9 Preview?

**Comment by MandiMan** [comment] 2024-07-01 07:18
@elachlan I used the project attached to the Issue description to verify it on the latest .NET 9.0.100-preview.7.24329.1 with the following result:
![image](https://github.com/dotnet/winforms/assets/108860782/8cadf76c-ea63-4b14-8b3a-8390872fee9d)
When I add `Rectangle rectangleBounds = new(4, 4, 56, 56); `, the test result is as follows:
![image](https://github.com/dotnet/winforms/assets/108860782/62e295b1-0c1d-4a99-86a6-895003a668f6)
Also, An [existing issue](https://github.com/dotnet/winforms/issues/6252) on this topic, mentioned in the Issue description, was verified with different results on .NET 8.0 and the latest .NET 9.0.
.NET 8.0 still doesn't reproduce:
![image](https://github.com/dotnet/winforms/assets/108860782/fcb40832-9f4e-4b99-9e79-292bbe2cabbf)
.NET 9.0 reproduces it again, but the result is different from the original issue, which was a downward offset, and is now an upward offset:
![image](https://github.com/dotnet/winforms/assets/108860782/cda6daca-07ab-4b47-97fd-580ee03a106e)

**Comment by SimonZhao888** [comment] 2024-07-03 07:51
This issue can be reproduced on .NET 6.0.
![image](https://github.com/dotnet/winforms/assets/133954995/09270e2d-f806-4832-8354-1afcbdfc6530)
Not reproducible on .NET 5.0
![image](https://github.com/dotnet/winforms/assets/133954995/1718f924-be35-464e-b3ab-8d073e422f16)

**Comment by SimonZhao888** [comment] 2024-07-03 11:06
Hi @merriemcgaw, @elachlan

After investigating, we found that these line doubles the translation of the image in the x- and y-axes.
https://github.com/dotnet/winforms/blob/8c2405af71b99011fcbb7d3f636f4700b370413f/src/System.Drawing.Common/src/System/Drawing/Icon.cs#L433-L435
![image](https://github.com/dotnet/winforms/assets/133954995/ce3ec619-6d57-4436-b05d-0899c48a66c8)

On the main branch, this issue has been fixed by https://github.com/dotnet/winforms/pull/10645.

**Comment by elachlan** [comment] 2024-07-03 11:37
@SimonZhao888 how difficult is the fix for .NET8/6?

**Comment by SimonZhao888** [comment] 2024-07-03 11:51
Hi @MandiMan,
And for the [existing issue](https://github.com/dotnet/winforms/issues/6252), I can't repo on the main branch 
![image](https://github.com/dotnet/winforms/assets/133954995/b1225409-aa91-4720-ac56-d9260cd04bad)

I found that the code in the case project has a manual offset that we need to change manually, it should be 0.
![image](https://github.com/dotnet/winforms/assets/133954995/eee77052-0b19-46ae-96bc-c056385fdc85)

**Comment by SimonZhao888** [comment] 2024-07-03 11:52
> und that the code in the case project has a manual offset that we need to change manually,

It's hard to assess, but judging from Jeremy's PR, there are a lot of changes made.

**Comment by merriemcgaw** [comment] 2024-07-05 18:43
@JeremyKuhne this is one you should take a look at as soon as you're back from vacation.

**Comment by lonitra** [comment] 2024-07-09 00:06
This regression was introduced in https://github.com/dotnet/runtime/pull/49186. Previously when `ApplyGraphicsProperties.Clipping` was passed in from `Icon.Draw` into [WindowsGraphics.FromGraphics](https://github.com/dotnet/winforms/commit/af204522fc5e94fe7e8bdec9b053d6821afa4e74#diff-9c66a1a35f5fbdb81efcd509f0aa8b5471b36178330be41b6183e6a057a9d938), we did not set the `offset` variable in that method, but after change `offset` is being changed to non default which will cause another TranslateOffset to occur later in the method. On main branch this is fixed with https://github.com/dotnet/winforms/pull/10645 since we completely removed `WindowsGraphics` class and new code is ensuring that `ApplyGraphicsProperties.TranslateTransform` is passed before applying a transform. I did a check for anywhere else this regression could be present and we did also have [another call](https://github.com/dotnet/winforms/blob/release/8.0/src/System.Drawing.Common/src/System/Drawing/Icon.cs#L443-L451) to `WindowsGraphics.FromGraphics` with `ApplyGraphicsProperties.Clipping` in `Icon.DrawUnstretched`, but again since this class was removed in main there should be no issues.

**Closed** 2024-07-10 20:59 UTC
Labels: area-System.Drawing, :boom: regression-release
