### ISSUE TITLE
Namespaces like System.Web.Services are pending for port in .net Core

### ISSUE THREAD

**Issue by gsmental** [dotnet/winforms#860] opened 2019-04-24 09:56 UTC
every time when we try to port our existing application,  we faces only these namesspaces which can not port into .net Core. technically these all are WebService (asmx) based libraries. i hope these will be also port into .net core

System.Web.Services.Protocols.HttpWebClientProtocol
System.Web.Services.WebServiceBindingAttribute
System.Web.Services.Protocols.WebClientProtocol
System.Web.Services.Protocols.SoapHeader
System.Web.Services.Protocols.SoapHeaderAttribute
System.Web.Services.Protocols.SoapDocumentMethodAttribute
System.Web.Services.Protocols.SoapHttpClientProtocol
System.Web.Services.Protocols.InvokeCompletedEventArgs
System.Web.Services.Protocols.SoapParameterStyle
System.Web.Services.Description.SoapBindingUse

**Comment by RussKie** [comment] 2019-04-24 13:19
Web stuff is really outside the realms of WinForms.
Besides I don't believe WS are supported in .NET Core. IIRC there are few 3rd packages available, google is your friend.

**Comment by gsmental** [comment] 2019-04-25 02:00
@RussKie you are right bro, google is our friend, after spending 15 years in MS, now i am thinking to move with NodeJs,Mongo,react...

**Comment by 199621616** [comment] 2019-04-25 22:02
这也是我们在迁移桌面程序时，遇到的主要问题之一。希望早日解决。

**Comment by OliaG** [comment] 2019-05-02 02:02
@gsmental  thanks for your issue. We don't support SOAP in .NET Core.  You can try using WebAPI (for hosting) and HttpClient (for consumption).

cc @terrajobst

**Comment by OliaG** [comment] 2019-05-02 02:08
For better web experience you can use ASP.NET Core. WinForms does not cover web functionality. I am going to close this issue here, but feel free to reach out to @terrajobst for more details regarding APIs in .NET Core.

**Closed by OliaG** 2019-05-02 02:08 UTC
Labels: question

**Comment by gsmental** [comment] 2019-05-02 02:18
madam, every time, when Microsoft released new technology, they forgot about existing applications and investment of time and money. 

first our projects were in VB6, then we spent time and money to convert into c#. now in the name of new technology, again a big task is standing against us. we are fed up with Microsoft based technology.

approx spending 15  years in Microsoft, now we feels, we should move to another non-MS technology for new projects.

bye

**Comment by RussKie** [comment] 2019-05-11 02:53
https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/

**Comment by TanVal** [comment] 2020-05-26 05:53
> every time when we try to port our existing application, we faces only these namesspaces which can not port into .net Core. technically these all are WebService (asmx) based libraries. i hope these will be also port into .net core
> 
> System.Web.Services.Protocols.HttpWebClientProtocol
> System.Web.Services.WebServiceBindingAttribute
> System.Web.Services.Protocols.WebClientProtocol
> System.Web.Services.Protocols.SoapHeader
> System.Web.Services.Protocols.SoapHeaderAttribute
> System.Web.Services.Protocols.SoapDocumentMethodAttribute
> System.Web.Services.Protocols.SoapHttpClientProtocol
> System.Web.Services.Protocols.InvokeCompletedEventArgs
> System.Web.Services.Protocols.SoapParameterStyle
> System.Web.Services.Description.SoapBindingUse

Hi, I am also facing same issue. may I know if the issue is resolved and how was it resolved? Also please let me know how much was the effort.
