### ISSUE TITLE
Disabling a focused TextBox draws TextBox wrong

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#4856] opened 2021-04-29 09:11 UTC
**.NET Core Version:**

SDK: 5.0.202 (db7cc87d51)
Runtime: 5.0.5 (2f740adc14)

**Problem description:**

If a focused textbox is disabled while having the focus, it does not display correctly:

Here are 2 textboxes where the top one has focus:
![image](https://user-images.githubusercontent.com/80055480/116527782-573f4300-a8db-11eb-9d28-ae798ec93b96.png)

The top one is now disabled, notice the weird looking border, it should look like the bottom one:
![image](https://user-images.githubusercontent.com/80055480/116527560-17785b80-a8db-11eb-866c-2c332ff02235.png)

**Repro:**

I have attached a sample project showing the problem. There are 2 textboxes and a button. The button disables both textboxes. The textbox with the focus shows the problem:
[TestDisableTextBox.zip](https://github.com/dotnet/winforms/files/6397707/TestDisableTextBox.zip)

**Comment by RussKie** [comment] 2021-04-29 09:19
Please provide a repro.

**Comment by Balkoth** [comment] 2021-04-29 09:56
I have added a repro to the original comment.

**Comment by merriemcgaw** [comment] 2021-04-30 00:13
Is this a regression from a previous version?

**Comment by Balkoth** [comment] 2021-04-30 06:28
I don't think this has ever worked.

**Comment by RussKie** [comment] 2021-05-11 11:20
@Olina-Zhang would you be able to check whether this issue only affects the `TextBox` control, or other controls [derived from `TextBoxBase`](https://docs.microsoft.com/dotnet/api/system.windows.forms.textboxbase) as well?
Thank you

**Comment by Olina-Zhang** [comment] 2021-05-12 06:21
@RussKie @Balkoth, I tested this issue using that provided app, cannot repro in .Net 3.1/5.0 /6.0. After disabled textboxs with focused and unfocused, they have same states. See following GIF:
![disabledTextBox](https://user-images.githubusercontent.com/26474449/117927796-4b1ca200-b32d-11eb-992c-bd1ad1502e5a.gif)

**Comment by Balkoth** [comment] 2021-05-12 06:46
I don't know why this works for @Olina-Zhang, because to my knowlegde this problem exists in all versions of Windows and .NET:
![image](https://user-images.githubusercontent.com/80055480/117930598-79cf5400-b2fe-11eb-96ad-c5357a101bda.png)

**Comment by RussKie** [comment] 2021-05-13 00:00
I confirm the issue:
![4856](https://user-images.githubusercontent.com/4403806/118058210-0b0efb00-b3d1-11eb-9c16-b1eca4a6fbcd.gif)

Also [`MaskedTextBox`](https://docs.microsoft.com/dotnet/api/system.windows.forms.maskedtextbox) suffers the same issue:
![image](https://user-images.githubusercontent.com/4403806/118058643-fd0daa00-b3d1-11eb-9534-72461777eb06.png)


Setting the issue as up for grabs.

**Comment by willibrandon** [comment] 2021-07-10 04:59
I see the same behavior in Win32.

![TextBoxDisabledBorderIssue1](https://user-images.githubusercontent.com/5017479/125152325-c4076280-e100-11eb-942c-6156f6cc0bea.gif)

**Comment by Balkoth** [comment] 2022-05-05 08:25
As this seems to be a Win32 Bug in the common controls, how do you think anyone else than Microsoft can fix this?

**Comment by RussKie** [comment] 2022-05-05 09:53
We can bump it to the Windows team, however it will very-very likely get rejected... So if you or anyone else in the community feel strongly about it - you're welcome to propose a fix.
In a way, this is similar to https://github.com/dotnet/winforms/issues/3533.

**Comment by Balkoth** [comment] 2022-05-05 11:56
It's sad that we will see no fixes to bugs in the common controls anymore. But i am more than happy that winforms went the open source route and has a working process for accepting community fixes (looking at you WPF).

So i did a quick check and tried the two approaches mentioned in #4374. While recreating the handle does indeed correctly draw the TextBox after it was disabled and had focus, the final implementaion looking at the styles and re-setting them does not.

I am not an expert on this, so any help is welcome. If we can solve this, i can provide the PRs to get this merged into winforms.

**Comment by Balkoth** [comment] 2022-05-05 12:11
What also works is calling `BufferedPaintStopAllAnimations` directly before changing the enabled state:

```cs
namespace TestDisableTextBox
{
  public partial class Form1 : Form
  {
    public Form1()
    {
      InitializeComponent();
    }

    private void button1_Click(object sender, EventArgs e)
    {
      //this.textBox1.Enabled = !this.textBox1.Enabled;
      this.textBox1.Enable(!this.textBox1.Enabled);
      this.textBox2.Enabled = !this.textBox2.Enabled;

      // This is just here to not have to do it manually!
      if (this.textBox1.Enabled)
        this.textBox1.Focus();
    }
  }

  public static class Extensions
  {
    internal static void Enable(this TextBox textBox, bool enabled)
    {
      BufferedPaintStopAllAnimations(textBox.Handle);
      textBox.Enabled = enabled;
    }

    [DllImport("UxTheme.dll")]
    private static extern int BufferedPaintStopAllAnimations(IntPtr hwnd);
  }
}
```

**Comment by RussKie** [comment] 2022-05-06 02:11
Have you checked if the fix applied in #4374 and #4855 addressed this issue? If - yes, we can apply the same here.

**Comment by Balkoth** [comment] 2022-05-06 06:10
I have tried it like this (64-bit build on 64-bit machine, so 32-bit GetWindowLong is omitted), unfortunately it does not work:

```cs
internal class TestTextBox : TextBox
{
  protected override void OnEnabledChanged(EventArgs e)
  {
    base.OnEnabledChanged(e);

    if (this.IsHandleCreated && Application.RenderWithVisualStyles)
    {
      SetWindowLong(this, GWL.STYLE, GetWindowLong(this, GWL.STYLE));
    }
  }

  [DllImport("user32.dll", ExactSpelling = true, SetLastError = true)]
  public static extern IntPtr SetWindowLongPtrW(IntPtr hWnd, GWL nIndex, IntPtr dwNewLong);

  public static IntPtr SetWindowLong(IntPtr hWnd, GWL nIndex, IntPtr dwNewLong)
  {
    return SetWindowLongPtrW(hWnd, nIndex, dwNewLong);
  }

  public static IntPtr SetWindowLong(Control control, GWL nIndex, IntPtr dwNewLong)
  {
    IntPtr result = SetWindowLong(control.Handle, nIndex, dwNewLong);
    GC.KeepAlive(control.Handle);
    return result;
  }

  [DllImport("user32.dll", ExactSpelling = true, SetLastError = true)]
  public static extern IntPtr GetWindowLongPtrW(IntPtr hWnd, GWL nIndex);

  public static IntPtr GetWindowLong(IntPtr hWnd, GWL nIndex)
  {
    return GetWindowLongPtrW(hWnd, nIndex);
  }

  public static IntPtr GetWindowLong(Control control, GWL nIndex)
  {
    IntPtr result = GetWindowLong(control.Handle, nIndex);
    GC.KeepAlive(control.Handle);
    return result;
  }

  public enum GWL : int
  {
    WNDPROC = (-4),
    HWNDPARENT = (-8),
    STYLE = (-16),
    EXSTYLE = (-20),
    ID = (-12),
  }
}
```

**Comment by RussKie** [comment] 2022-05-06 06:17
Thank you for checking.

> While recreating the handle does indeed correctly draw the TextBox after it was disabled and had focus

Then we can go this route.

**Comment by Tanya-Solyanik** [comment] 2022-05-20 00:50
We had re-triaged this issue. The fix can be breaking to the existing applications because it raises HandleCreated event unexpectedly. On the other hand, a workaround can be applied on the application level. Closing this issue unless a solution that does not require re-creation of the control can be found.

**Closed** 2022-05-20 00:51 UTC
Labels: :beetle: bug, up-for-grabs, :mailbox_with_no_mail: waiting-author-feedback
