### ISSUE TITLE
update codegen naming rules to be complaint with current guidelines

### ISSUE THREAD

**Issue by Varorbc** [dotnet/winforms#178] opened 2018-12-06 12:12 UTC
When I double-click a button on the form, vs automatically adds a click method, such as `button1_click`, but this naming is currently suggested and is not meet specifications.

**Comment by jnm2** [comment] 2018-12-06 14:36
Duplicate of https://github.com/dotnet/roslyn/issues/20999?

**Comment by zsd4yr** [comment] 2018-12-06 15:34
@Tanya-Solyanik is this code gen? Does this live in the runtime?

**Comment by KlausLoeffelmann** [comment] 2018-12-06 16:34
It is related to the Classic Framework Designer, I assume

**Comment by zsd4yr** [comment] 2018-12-06 16:58
@klausloeffelmann does code gen live in design time? I think it isn’t in the runtime

**Comment by KlausLoeffelmann** [comment] 2018-12-06 17:05
The CodeDomSerializer lives in the Core runtime, I think, but is triggered by the designtime, but Tanya should confirm.

**Comment by zsd4yr** [comment] 2018-12-10 18:32
perhaps @JuditRose could take this issue on? It sounds familiar

**Comment by Tanya-Solyanik** [comment] 2018-12-17 21:21
Duplicate of an issue from Developer community:
https://developercommunity.visualstudio.com/content/problem/286625/naming-rule-violation-these-words-must-begin-with-1.html
Please monitor status there.

**Closed by Tanya-Solyanik** 2018-12-17 21:21 UTC
Labels: enhancement
