### ISSUE TITLE
MDI children look different than the main forms

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/winforms#3891] opened 2020-09-13 03:59 UTC
* .NET Core Version: 
I am using .net framework 4.6.1 but it also seem to happen with 4.7.2

* Have you experienced this same bug with .NET Framework?: 
Yes I am not using .net core

**Problem description:**
MDI children do not obey the theme of the parent window
![image](https://user-images.githubusercontent.com/2453707/93009849-8c5c7800-f53a-11ea-8872-e4d2b2897ebc.png)

**Expected behavior:**
I would expect that the titlebar and border would look the same even if its a mdi child

**Minimal repro:**
- make a mdi form
- make a mdi child 
- add the mdi child to the mdi form
- run it
- see that it looks like windows 7 still

**Comment by kirsan31** [comment] 2020-09-13 06:58
https://github.com/dotnet/winforms/issues/3691

**Comment by RussKie** [comment] 2020-09-14 02:21
Duplicate of #3691

**Closed by RussKie** 2020-09-14 02:21 UTC

**Comment by PhilippKoehler** [comment] 2020-12-18 18:07
This problem (error!!) has existed since Windows 10.
Unbelievable that Microsoft Visual Studio Team has not solved this problem yet. I personally have been waiting for a solution for years!

**Comment by RussKie** [comment] 2020-12-19 07:17
Making such comments is not helpful in any way. Let along posting your vents multiple times.
