### ISSUE TITLE
Use ApiCompat to eusure public API compatibility with previous releases

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#580] opened 2019-03-12 21:17 UTC
Eric's feedback in PR: https://github.com/dotnet/winforms/pull/237

> "Use https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.ApiCompat to make sure your assemblies are compatible with desktop. @dreddy-work should have some familiarity with this, I helped him set it up on some of the facades previously on the internal codebase."

**Comment by dreddy-work** [comment] 2019-04-15 23:35
Dupe of issue #407

**Closed by dreddy-work** 2019-04-15 23:35 UTC
Labels: enhancement, tenet-compatibility
