### ISSUE TITLE
ListView ListViewGroupCollection.Insert not working properly (incorrect location)

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#8536] opened 2023-01-29 13:06 UTC
### .NET version

.net 7.0

### Did it work in .NET Framework?

No

### Issue description

ListViewGroupCollection.Insert not working properly.

Users can use ListViewGroupCollection.Insert to insert new data. But currently it doesn't work properly (**incorrect location**).
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewgroupcollection.insert

How to test:
1.  Copy the full test code to Visual Studio (see Steps to reproduce).
2. Add a breakpoint to this line.
```(sender as Button).Enabled = false;```

Picture 1.
Run the test code, click this button to start test.

![000](https://user-images.githubusercontent.com/88176616/215327609-77d76064-8d6d-422d-910f-4ef7506178aa.png)

Picture 2.
If you have set breakpoint, the "Watch 1" dialog shows the position of the inserted object in relation to other elements.
If you haven't set a breakpoint, Add a breakpoint to this line, and then add "view.Groups" to "Watch 1" dialog.
```(sender as Button).Enabled = false;```

![001](https://user-images.githubusercontent.com/88176616/215327623-8fe5b13c-7a96-4765-a1c1-6536d0e36ffd.png)

Picture 3.
In the actual running UI, the display effect of ListView is not consistent with the relationship in the previous "Watch 1" dialog box.

![0021](https://user-images.githubusercontent.com/88176616/215327646-0eda3e86-3d76-46e2-80da-e67c1ac7543c.png)

### Steps to reproduce

Full C# Test code with Visual Studio 2022 and .net 7.0

```
using System;
using System.Drawing;
using System.Windows.Forms;

namespace ListViewGroupInsertTest
{
    internal static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();
            Application.Run(CreateForm());
        }

        private static Form CreateForm()
        {
            var form = new Form()
            {
                Width = 600,
                Height = 480,

                StartPosition = FormStartPosition.CenterScreen,
            };

            var control = _listView = CreateListView();
            form.Controls.Add(control);

            var button = new Button()
            {
                Text = "Click to insert Group and Item",
                AutoSize = true,

                MaximumSize = new Size(0, 45),
                Dock = DockStyle.Right
            };

            button.Click += Button_Click;

            form.Controls.Add(button);
            return form;
        }

        private static ListView CreateListView()
        {
            var control = new ListView()
            {
                Dock = DockStyle.Fill,
                View = View.Details,

                FullRowSelect = true,
            };

            CreteListViewContent(control);
            return control;
        }

        private static ListView _listView;

        private static ListViewGroup _group_new;
        private static ListViewItem _item_new;

        private static void CreteListViewContent(ListView view)
        {
            ListViewGroup group_1;
            ListViewGroup group_2;
            ListViewGroup group_3;
            ListViewGroup group_4;

            view.Groups.Add(group_1 = new ListViewGroup() { Header = "Group 1" });
            view.Groups.Add(group_2 = new ListViewGroup() { Header = "Group 2" });
            view.Groups.Add(group_3 = new ListViewGroup() { Header = "Group 3" });
            view.Groups.Add(group_4 = new ListViewGroup() { Header = "Group 4" });

            view.Columns.Add(new ColumnHeader() { Text = "Column 1", Width = 300 });
            view.Columns.Add(new ColumnHeader() { Text = "Column 2", Width = -2 });

            view.Items.Add(new ListViewItem("ListView Item 1") { Group = group_1 });
            view.Items.Add(new ListViewItem("ListView Item 2") { Group = group_2 });
            view.Items.Add(new ListViewItem("ListView Item 3") { Group = group_3 });
            view.Items.Add(new ListViewItem("ListView Item 4") { Group = group_4 });

            _group_new = new ListViewGroup() { Header = "Group (New)" };
            _item_new = new ListViewItem("ListView Item (New)") { Group = _group_new };
        }

        private static void Button_Click(object sender, EventArgs e)
        {
            var view = _listView;

            view.Groups.Insert(3, _group_new);
            view.Items.Add(_item_new);

            (sender as Button).Enabled = false;
        }
    }
}
```

**Comment by elachlan** [comment] 2023-01-29 23:03
@Olina-Zhang your team might want to test this?

**Comment by Amy-Li03** [comment] 2023-01-30 01:43
@elachlan verified this issue on .NET 8.0 latest build, we can repro it.
![image](https://user-images.githubusercontent.com/62929087/215370482-9b64a0e0-326e-4cd2-8827-274183a09812.png)

**Comment by elachlan** [comment] 2023-01-30 02:05
Is it a regression? Does it work in .net 6/7?

**Comment by Amy-Li03** [comment] 2023-01-30 02:51
> Is it a regression? Does it work in .net 6/7?

It is not a regression, it repro on .NET 5.0, 6.0, 7.0 and 8.0.

**Comment by elachlan** [comment] 2023-02-01 02:18
When I tried to write this into the `ListViewTest` form in `WinformsControlsTest`, It inserted at index 3 in `groups` and added the group at position 4.

```csharp
int index = 3;
ListViewGroup lvgroup = new()
{
    Header = $"Group {listView1.Groups.Count} (new)"
};
ListViewItem lvitem = new()
{
    Text = "Item6",
    Group = lvgroup
};
listView1.Groups.Insert(index, lvgroup);
listView1.Items.Add(lvitem);
```

@roland5572 does it look like I am doing anything wrong here for your issue reproduction?

**Comment by roland5572** [comment] 2023-02-01 06:00
@elachlan 
You can make a breakpoint to your last code, this line, and see your "Watch 1"dialog.
```listView1.Items.Add(lvitem);```

You can see my screenshot.
The actual storage location relationship is completely different from what is displayed on the UI.

![001](https://user-images.githubusercontent.com/88176616/215963677-5d429f3b-4e27-4854-a992-f64e0fe9602b.png)
![002](https://user-images.githubusercontent.com/88176616/215963684-66b3ac36-e519-4a02-b602-ec0ff848916c.png)

**Comment by elachlan** [comment] 2023-02-01 06:33
Can you explain clearly what you expect to happen on insert?

**Comment by roland5572** [comment] 2023-02-01 06:38
> Can you explain clearly what you expect to happen on insert?

The order of Groups Items displayed by the UI should be **consistent** with the order in ListView.Groups Array.
Now when the program thinks its Insert is in the correct position, it is actually displayed in another position.

**Comment by elachlan** [comment] 2023-02-01 06:43
ok, So if we insert an item at index 1 it should exist at groups[1] and be the second group in the listview?

**Comment by roland5572** [comment] 2023-02-01 07:20
> ok, So if we insert an item at index 1 it should exist at groups[1] and be the second group in the listview?

Yes, users can specify the appearance order of groups according to their own needs. Important groups are displayed in the **front**, and unimportant data can be displayed in the back.

If a group is randomly displayed on the UI when a group is inserted, users may not be able to quickly find important data.

**Comment by lonitra** [comment] 2023-02-03 19:13
Did a quick investigation. ListView has an internal default group we use to display `ListViewItem`s that have no specified group in. It is not included in the `ListView.Groups` list because it is not something the user created, but we are including it when redrawing regardless of if user has `ListViewItem`s that have no specified group, causing this discrepancy between the `ListView.Groups` list and what is displayed on the UI. 
I _think_ this could be fixed by incrementing the index before inserting the group user requested to be inserted in this method
https://github.com/dotnet/winforms/blob/980d4c4eaa0a2ef1ae6c88a000c4239c4355a8b6/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L4023-L4033
but this needs to be discussed with team first.

**Comment by roland5572** [comment] 2023-02-04 06:11
@lonitra ,

The source code has this line from `public int Add(ListViewGroup group) `: 
```_listView.InsertGroupInListView(List.Count, group); ```

And this line from `public void Insert(int index, ListViewGroup group)`:
```_listView.InsertGroupInListView(index, group); ```

In method `public int Add(ListViewGroup group)`, it does not use variable `index`, it use `List.Count` as the `InsertGroupInListView` function parameter.

That's why the **Add** function works fine, but the **Insert** function doesn't.

https://github.com/dotnet/winforms/blob/980d4c4eaa0a2ef1ae6c88a000c4239c4355a8b6/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs#L114-L135

https://github.com/dotnet/winforms/blob/980d4c4eaa0a2ef1ae6c88a000c4239c4355a8b6/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs#L240-L258

**Comment by lonitra** [comment] 2023-02-09 00:00
We discussed this as a team and decided that given that this has been the behavior since Framework, it is too risky to fix as it could break existing apps with unwanted UI changes. 
The workaround here is if the issue is that the group does not show up in the desired position in the UI, this can be worked around by incrementing the index or using the `Add` method for new groups wanting to be placed at the end. 
If the issue is that the UI and `ListView.Group` list do not match up, this can be worked around by removing groups starting from the index user wants to add new group in, then re-adding the groups in correct order using the `Add` method.

**Closed by lonitra** 2023-02-09 00:00 UTC
