### ISSUE TITLE
Flaky test: `DataGridView_RowHeadersWidth_SetWithParentWithHandle_GetReturnsExpected`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4736] opened 2021-03-29 01:08 UTC
Keeps intermittently failing on the public CI leg in all configs/bitness

```
    System.Windows.Forms.Tests.DataGridViewTests.DataGridView_RowHeadersWidth_SetWithParentWithHandle_GetReturnsExpected(rowHeadersWidthSizeMode: DisableResizing, rowHeadersVisible: True, autoSize: False, value: 4, expectedValue: 4, expectedInvalidatedCallCount: 1, expectedLayoutCallCount: 0, expectedParentLayoutCallCount: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   3
      Stack Trace:
        D:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\DataGridViewTests.cs(1213,0): at System.Windows.Forms.Tests.DataGridViewTests.DataGridView_RowHeadersWidth_SetWithParentWithHandle_GetReturnsExpected(DataGridViewRowHeadersWidthSizeMode rowHeadersWidthSizeMode, Boolean rowHeadersVisible, Boolean autoSize, Int32 value, Int32 expectedValue, Int32 expectedInvalidatedCallCount, Int32 expectedLayoutCallCount, Int32 expectedParentLayoutCallCount)
    System.Windows.Forms.Tests.DataGridViewTests.DataGridView_RowHeadersWidth_SetWithParentWithHandle_GetReturnsExpected(rowHeadersWidthSizeMode: DisableResizing, rowHeadersVisible: True, autoSize: False, value: 32768, expectedValue: 32768, expectedInvalidatedCallCount: 1, expectedLayoutCallCount: 0, expectedParentLayoutCallCount: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   3
      Stack Trace:
        D:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\DataGridViewTests.cs(1213,0): at System.Windows.Forms.Tests.DataGridViewTests.DataGridView_RowHeadersWidth_SetWithParentWithHandle_GetReturnsExpected(DataGridViewRowHeadersWidthSizeMode rowHeadersWidthSizeMode, Boolean rowHeadersVisible, Boolean autoSize, Int32 value, Int32 expectedValue, Int32 expectedInvalidatedCallCount, Int32 expectedLayoutCallCount, Int32 expectedParentLayoutCallCount)


```

**Comment by dreddy-work** [comment] 2023-03-11 23:58
Dupe of #6609

**Closed** 2023-03-11 23:59 UTC
Labels: test-bug
