### ISSUE TITLE
Disabled DateTimePicker at Design-Time does not have the correct border color when enabled when running

### ISSUE THREAD

**Issue by tbolon** [dotnet/winforms#3533] opened 2020-07-02 08:38 UTC
* .NET Core Version: 3.1.400-preview-015178
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**

When using a DateTimePicker which is initialized as `Enabled = false` in the designer, enabling the control later when the app is running does not change the border color, which stays with a "disabled gray" color.

![bug](https://user-images.githubusercontent.com/127185/86336016-8c451f80-bc4f-11ea-8420-ba3c9af0226f.gif)

Note: if the control is enabled by default, and you disable/enable it, the border is changed correctly.

**Expected behavior:**

When enabling the control, the border should change to use the standard border color instead of keeping the disabled one.

**Minimal repro:**

- Create a new Form
- Drop a `DateTimePicker` control
- Set `Enabled` to `false`
- Add a button which change the `Enabled` state to `true`
- Start the project
- Click the button to enable the control.

## Edit based on following comments

**There seems to be a bug in the way the border color of the control is set and drawn by the .net control or the native control.**

* The border color which will be used for the entire existence of the control seems to be set when the handle is created.
* If the control is in an enabled state, a dark gray color will be used. If it is disabled a light gray color will be used instead.
* Once the handle is created, the border color will never change again, despite changing the Enabled property (or sending WM_ENABLE messages)
* The only way to update the border color of the control is to force the recreation of the handle, which will change the border color according to the control state.
* (Not necessary related: there is a strange extended style WS_EX.CLIENTEDGE set on the control, which seems to be useless and break `UpdateStyles()` calls)

**Comment by tbolon** [comment] 2020-07-06 16:20
I would gladly help, but based on my understanding of the code, this behavior is not coded in the .net control, but is certainly the default behavior of the native control.

Maybe we could force some style message to the native control to force border color check when enabled... But I will need some hints about what to change and how.

**Comment by RussKie** [comment] 2020-07-07 06:03
I inspected the "correct" and "incorrect" versions via spy++ hoping to see something obvious, alas there wasn't anything.
You can certainly see a difference in borders for a control disabled in design time and runtime:
![image](https://user-images.githubusercontent.com/4403806/86722737-86de3f80-c06a-11ea-8de2-2c1d27c478ac.png)

@JeremyKuhne @weltkante any thoughts?

**Comment by weltkante** [comment] 2020-07-07 14:06
Desktop Framework designer treated the enabled property specially, basically ignores it in design time, I assume to not interfere with user interactions. Not sure what is happening in the new .NET Core designer.

As far as the actual bug is concerned, I wasn't aware of this one, I can confirm there is nothing obvious to see in WinForms source or spy++. Could be a bug in the native control not updating some internal state when switching the enabled flag.

It is possible to work around the problem by subclassing DateTimePicker and calling `RecreateHandle` when Enabled changes. Not sure if WinForms should integrate that as a general-purpose workaround for everyone and do it automatically. Might be hard to trigger correctly if the enabled state changes indirectly (e.g. disable a parent panel) ? Not sure if there is any hook for child controls to know that they are disabled indirectly and need to recreate their handle to work around a bug.

Also the bug happens in both directions, i.e. you can end up with an enabled control with a disabled border, and a disabled control with an enabled border. Basically the border is stuck in the state it was when the handle was last recreated.

**Comment by tbolon** [comment] 2020-07-08 15:05
> As far as the actual bug is concerned, I wasn't aware of this one, I can confirm there is nothing obvious to see in WinForms source or spy++. Could be a bug in the native control not updating some internal state when switching the enabled flag.

Could it be a bug in the native control? Does the native control still receive updates?

> It is possible to work around the problem by subclassing DateTimePicker and calling `RecreateHandle` when Enabled changes. Not sure if WinForms should integrate that as a general-purpose workaround for everyone and do it automatically. Might be hard to trigger correctly if the enabled state changes indirectly (e.g. disable a parent panel) ? Not sure if there is any hook for child controls to know that they are disabled indirectly and need to recreate their handle to work around a bug.

The OnEnabledChanged() protected method is called even when the enabled state changes indirectly. I have tested adding a custom MyDateTimePicker in a groupbox and modified the Enabled property on the groupbox: the OnEnabledChanged() method was called and I was able to fix the border color by calling RecreateHandle().

Do you have any hints about the cost of recreating the handle each time this property is changed? We have a lot of forms where this property is used when switching from Read/Edit view.

**Comment by tbolon** [comment] 2020-07-08 15:19
It seems that the problem is not only in the design-time/run-time state.

I have created a custom DateTimePicker with the following properties:

```csharp
public class MyDateTimePicker : DateTimePicker
{
    public bool RecreateHandleOnEnabledChanged { get; set; }

    protected override void OnEnabledChanged(EventArgs e)
    {
        base.OnEnabledChanged(e);

        if (RecreateHandleOnEnabledChanged)
        {
            RecreateHandle();
        }
    }
}
```

And created a form which allows me to toggle the Enabled state and Recreate (or not) the handle.

In the following capture, I can show that it's the border color behavior which is buggy: it is never updated by the change of state. If the control was created with the Enabled state, the border will keep the default color. It will receive the disabled border color only on Handle creation.

![bug2](https://user-images.githubusercontent.com/127185/86937084-1ce39a00-c13f-11ea-9462-022a5c37705d.gif)

The bug I observed is just that I could display the correct border color for the Disabled state. But this color is never applied if the control is created in an Enabled state then disabled afterwards

**Comment by RussKie** [comment] 2020-07-09 00:45
> Does the native control still receive fixes as part of OS servicing?

There is a very little chance of this, unfortunately.
Can you try sending [`WM_ENABLE`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-enable) message to the control, and see if it makes any difference?

**Comment by tbolon** [comment] 2020-07-09 07:13
No change observed:

```csharp
public class MyDateTimePicker : DateTimePicker
{
    public bool RecreateHandleOnEnabledChanged { get; set; }

    public bool SendWmEnable { get; set; }

    protected override void OnEnabledChanged(EventArgs e)
    {
        base.OnEnabledChanged(e);

        if (RecreateHandleOnEnabledChanged)
        {
            RecreateHandle();
        }

        if (SendWmEnable)
        {
            SendMessageW(this.Handle, 0x000A /* WM_ENABLE */, this.Enabled);
        }
    }

    [DllImport("user32.dll")]
    public static extern IntPtr SendMessageW(IntPtr hWnd, uint msg, bool wParam = default, IntPtr lParam = default);
}
```

![bug3](https://user-images.githubusercontent.com/127185/87008658-60ccb280-c1c4-11ea-9a09-94cabe06b7c0.gif)

**Comment by weltkante** [comment] 2020-07-09 07:19
You might want to do that outside `OnEnabledChanged` (i.e. send `WM_ENABLE` instead of setting `Control.Enabled`) - just to test behavior I assume. Doing it inside means the state already has been changed so you are setting it to the value it already has, which probably ends up returning early in native code and not doing anything.

**Comment by tbolon** [comment] 2020-07-09 07:29
Thanks weltkante, I will change my code.

I also found something fishy: I tried calling `UpdateStyles()` which should be a noop with this code:

```csharp
var method = typeof(Control).GetMethod("UpdateStyles", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
method.Invoke(dateTimePicker3, null);
```

I added a textbox and tried calling this code on both controls. Here are my results:

![bug4](https://user-images.githubusercontent.com/127185/87010259-98d4f500-c1c6-11ea-9b9a-a85c01ab4bc1.gif)

There seems to be something wrong in the way the border is initialized.

**Comment by tbolon** [comment] 2020-07-09 07:35
@weltkante the behavior is the same as using the `Enabled` property (the border color stays the same)

```csharp
public class MyDateTimePicker : DateTimePicker
{
    public bool RecreateHandleOnEnabledChanged { get; set; }

    public bool SendWmEnable { get; set; }

    public bool CallUpdateStyles { get; set; }

    public void ForceSendWmEnable(bool enable)
    {
        SendMessageW(this.Handle, 0x000A /* WM_ENABLE */, enable);
    }

    protected override void OnEnabledChanged(EventArgs e)
    {
        base.OnEnabledChanged(e);

        if (RecreateHandleOnEnabledChanged)
        {
            RecreateHandle();
        }

        if (SendWmEnable)
        {
            SendMessageW(this.Handle, 0x000A /* WM_ENABLE */, this.Enabled);
        }

        if (CallUpdateStyles)
        {
            UpdateStyles();
        }
    }

    [DllImport("user32.dll")]
    public static extern IntPtr SendMessageW(IntPtr hWnd, uint msg, bool wParam = default, IntPtr lParam = default);
}
```

![bug5](https://user-images.githubusercontent.com/127185/87010838-72fc2000-c1c7-11ea-8326-0c0b3dd44682.gif)

**Comment by weltkante** [comment] 2020-07-09 08:02
Thanks for doing the tests

> Do you have any hints about the cost of recreating the handle each time this property is changed? We have a lot of forms where this property is used when switching from Read/Edit view.

Its comparable to opening the form (which also needs to create all handles, obviously even more than just the DateTimePickers). If opening the form is an issue for you and you have a lot of DateTimePickers on the form then switching the Enabled state may have similar performance. If opening the form is fine with you then switching Enabled state with this workaround won't be any issue at all.

WinForms already has handle recreation as workaround in other control wrappers, and since `OnEnabledChanged` is called even on implicit changes, I'd consider it appropriate to add the workaround to WinForms itself if it isn't going to be fixed on the native side.

**Comment by tbolon** [comment] 2020-07-09 10:37
Why not perhaps just try to call the UpdateStyles() method ?

I am trying to understand why the border change (see my previous comment) when calling the method for the DateTimePicker.

Perhaps there is something missing in the initialization of the control in the library to set the BorderStyle of the native control which prevent the control from working correctly (and may be the cause of the border style error when calling UpdateStyles()).

**Comment by tbolon** [comment] 2020-07-09 11:05
I was able to remove the UpdateStyles which change the border style to SunkenEdge by overriding CreateParams and removing the Extended Flag WS_EX.CLIENTEDGE : `cp.ExStyle &= ~(int)0x00000200; // WS_EX.CLIENTEDGE;`

It's explicitly set by the CreateParams of the DateTimePicker control: [line 457](https://github.com/dotnet/winforms/blob/d8a362e4983a49aa04aa28096aca537840e2ca72/src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs#L457)

Saldy, it did not fix the problem of the border color.

**Comment by tbolon** [comment] 2020-07-09 11:37
I am now clueless about how to fix this bug without relying on a `RecreateHandle` call...

> WinForms already has handle recreation as workaround in other control wrappers, and since `OnEnabledChanged` is called even on implicit changes, I'd consider it appropriate to add the workaround to WinForms itself if it isn't going to be fixed on the native side.

If you want me to submit a PR for that, feel free to ask.

**Comment by RussKie** [comment] 2020-07-09 11:40
I pinged the control area owner, will update if I get any response. At this stage I think we should work under an assumption that the native control won't get fixed.

@JeremyKuhne what do you think about calling `RecreateHandle` upon changing the enable state?

**Comment by tbolon** [comment] 2020-07-09 12:49
I updated the first post with a summary of what we have found for now.

**Comment by JeremyKuhne** [comment] 2020-07-09 16:20
> what do you think about calling RecreateHandle upon changing the enable state?

I'm not opposed to it, given we're doing the same thing elsewhere. Before we do it would be good to get the response from the comctl folks. I don't suspect that it would be too outrageous of a perf impact- but it would be nice to know what the cost is. Additionally it would be good to test with visual styles enabled and disabled.

**Comment by RussKie** [comment] 2020-07-10 00:44
@tbolon we had an internal discussion about this and agreed that `RecreateHandle` is an acceptable solution for .NET 5.0, given there are other controls doing the same or similar things already. Unfortunately this bug won't meet a servicing bar for 3.1.
You're welcome to send a PR with a fix.

**Comment by tbolon** [comment] 2020-07-10 12:14
I won't be able to work on this issue until end of next week. I will submit a PR then.

**Closed** 2021-04-06 04:51 UTC
Labels: :beetle: bug, :construction: work in progress, up-for-grabs

**Comment by Zheng-Li01** [comment] 2021-04-08 02:28
Verified the issue with latest .NET 6.0.100-preview.4.21207.18, the issue has been fixed that DateTimePicker control's border working well after enabled/disable it when running the application.
![Issue3533](https://user-images.githubusercontent.com/38325459/113959291-2b3d1e80-9855-11eb-800a-18d06dc50cae.gif)
