### ISSUE TITLE
Winforms Designer Not Working with .NET Core 3.1 SDK

### ISSUE THREAD

**Issue by nirzaf** [dotnet/winforms#3307] opened 2020-05-20 08:46 UTC
* .NET Core Version:   3.1 LTS Version

* Have you experienced this same bug with .NET Framework?:  No

**Problem description:**

    Winform Designer looks like in a screenshot given below 

![image](https://user-images.githubusercontent.com/18024930/82425619-63543b00-9aa4-11ea-9532-bae05883afa1.png)
Could not do any designing in Winforms
I am using Visual Studio 16.6.0 Version Last Updated 20/05/2020

**Comment by Tanya-Solyanik** [comment] 2020-05-21 00:28
@nirzaf - we had seen similar issues in multi-monitor setup, where the primary monitor has resolution other than 100%. What screen resolutions do you have?
Why do you think this is related to the Core SDK version? What version is your application targeting?

**Comment by nirzaf** [comment] 2020-05-21 14:09
I am using a single monitor in my laptop ThinkPad i7, with resolution 1366 X 768 (Recommended by Windows 10) My targeting .NET Core SDK Version is  3.1 LTS Version

**Comment by Tanya-Solyanik** [comment] 2020-05-21 14:28
I'm sorry, I meant to ask what your scale on the primary monitor was, could you please lookup it as well:
![image](https://user-images.githubusercontent.com/15823268/82569030-84fd0300-9b34-11ea-82ce-183ce17291c8.png)

Why do you think the issue is related to .NET SDK, what happens when you switch to NET 5.0?

**Comment by nirzaf** [comment] 2020-05-21 14:33
I couldn't find any options called Scale & Layout in my windows settings 
![image](https://user-images.githubusercontent.com/18024930/82569549-050b8300-9b9e-11ea-8c29-94aeed92b508.png)
![image](https://user-images.githubusercontent.com/18024930/82569675-31bf9a80-9b9e-11ea-96b7-5479b9645021.png)

**Comment by Tanya-Solyanik** [comment] 2020-05-22 00:31
Hm, had you tried typing "scale" in the search box on the upper left? Had you looked in the "Advanced" link?

**Comment by nirzaf** [comment] 2020-05-22 04:59
Yes, I tried all the possible way to find that option but could not find it,
I am using Windows 10 Enterprise Version 2016 LTSB, Updated always, I had this problem in previous visual studio versions as well, but Previously I didn't even get that white blank screen After updated to 16.6 I get this white blank screen

**Comment by RussKie** [comment] 2022-02-18 02:58
Closing due to age. 
The designer in VS 2022 is significantly more robust and stable. If you still experiences issues with the designer in VS 2022 please raise those via a VS Feedback.

**Closed by RussKie** 2022-02-18 02:58 UTC
Labels: area: VS designer
