### ISSUE TITLE
WinForms Designer fails to load Form in Visual Studio 2022 (Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0)

### ISSUE THREAD

**Issue by PascalWillems** [dotnet/winforms#10508] opened 2023-12-20 12:14 UTC
### Environment

Visual Studio Version 17.8.3

### .NET version

.NET 5

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes, the same form does open without issue in Visual Studio 2019.
And I believe it also worked in an older update of Visual Studio 2022. But I can't test that to be sure, since I can't install older Visual Studio 2022 versions?

### Issue description

In a .NET 5 project that has a (transitive) reference to nuget package System.Text.Json 7.0.2, opening the designer of a form fails to load the form. The "Loading designer..." message is never replaced with the actual Form.

PS: I am aware that System.Text.Json 7.0.2 is not guaranteed to work .NET 5, but this did actually work correctly up until (assuming) a change in the WinForms designer/Visual Studio.

### Steps to reproduce

1. Create a .NET 5 windows forms project
2. Notice the default Form opens correctly
3. Install Nuget package System.Text.Json 7.0.2 in this project
4. Notice the default Form does NOT open anymore

### Diagnostics

```text
11:16:35:047	[11:16:34.744529] info: Creating VsDesignerLoader
11:16:35:047	[11:16:34.747529] info: [Thread 1] Creating design-time ITypeResolutionService.
11:16:35:117	[11:16:34.869527] info: Start processing enqueued assemblies
11:16:35:117	[11:16:34.869527] trce: Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000292 [thread 217]
11:16:35:117	[11:16:34.869527] trce: Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.0001794
11:16:35:117	[11:16:34.871527] info: Added 'Microsoft.WinForms.DesignTools.Protocol'
11:16:35:117	[11:16:34.872528] trce: Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000348 [thread 224]
11:16:35:117	[11:16:34.872528] trce: Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.0007083
11:16:35:117	[11:16:34.875529] info: Added 'Microsoft.WinForms.DesignTools.Client'
11:16:35:117	[11:16:34.996532] info: [Thread 11] Launching server...
11:16:41:666	[11:16:41.591105] info: Shadow cache base directory: [removed for privacy]
11:16:41:666	[11:16:41.592058] info: [MyApp]: Preparing shadow cache folder.
11:16:41:666	[11:16:41.592058] info: [MyApp]: NetCoreServerLayout - Platform: AnyCPU, Normalized PlatformName: x64
11:16:41:666	[11:16:41.592058] info: [MyApp]: Copying design tools server common files from: 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\Common'.
11:16:41:666	[11:16:41.652143] info: [MyApp]: Copying design tool server platform-specific files from: 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\x64'.
11:16:41:666	[11:16:41.655144] info: [MyApp]: Copying project output file: '[removed for privacy]'.
11:16:41:666	[11:16:41.656143] info: [MyApp]: Copying '[removed for privacy].designer.deps.json' to 'DesignToolsServer.deps.json'
11:16:41:666	[11:16:41.657142] info: [MyApp]: Copying '[removed for privacy].designer.runtimeconfig.json' to 'DesignToolsServer.runtimeconfig.json'
11:16:41:666	[11:16:41.658142] info: [MyApp]: Copying project reference: '[removed for privacy].dll'.
.
.
.
11:16:41:779	[11:16:41.752646] info: Shadow caching completed.
11:16:41:779	[11:16:41.752646] info: Obtained ServerConnectionTimeout value: 120000.
11:16:41:779	[11:16:41.752646] info: Obtained OutputWindowLoggingService.
11:16:41:779	[11:16:41.752646] info: [MyApp]: Launching design tools server process...
11:16:42:980	[11:16:42.951715] info: [MyApp]: Connected to named pipe: DesignToolsServer.13bc3de1-6fd7-4cfc-9aee-8b24f0a05642
11:16:43:088	[11:16:42.984542] info: [MyApp]: Connecting to pipe: DesignToolsServer.13bc3de1-6fd7-4cfc-9aee-8b24f0a05642... 
11:16:43:088	[11:16:42.986537] info: [MyApp]: Successfully connected to pipe: DesignToolsServer.13bc3de1-6fd7-4cfc-9aee-8b24f0a05642
11:16:43:088	[11:16:43.008260] info: [MyApp]: Creating DesignToolsServer [thread 1]
11:16:43:088	[11:16:43.013263] info: [MyApp]: Starting UI thread [thread 1]
11:16:43:088	[11:16:43.025780] info: [MyApp]: Performing start up tasks [thread 4]
11:16:43:196	[11:16:43.156594] info: [MyApp]: UI thread started
11:16:43:304	[11:16:43.223847] info: [MyApp]: Wait for start up tasks to complete... [thread 4]
11:16:43:304	[11:16:43.223847] info: [MyApp]: Disposing DesignToolsServer [thread 4]
11:16:43:420	[11:16:43.359171] fail: [MyApp]: Failed to launch design tools server process process
11:16:43:420	                        System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
11:16:43:420	                        File name: 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
11:16:43:420	                           at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
11:16:43:420	                           at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
11:16:43:420	                           at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
11:16:43:420	                           at System.Text.Json.JsonSerializerOptions.GetOrCreateDefaultOptionsInstance()
11:16:43:420	                           at System.Text.Json.JsonSerializerOptions.get_Default()
11:16:43:420	                           at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
11:16:43:420	                           at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
11:16:43:420	                           at Microsoft.WinForms.Utilities.Desktop.Manifest.ServerManifest.NetCore.TryLoadFromFileAsync(String sourceDirectory)
11:16:43:420	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.StartUpAsync(Boolean testMode, CancellationToken cancellationToken)
11:16:43:420	                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.StartListeningAsync(Stream stream, TraceListener traceListener)
11:16:43:420	                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()
11:16:43:420	
11:16:43:420	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
11:16:43:420	[11:16:43.360129] fail: Microsoft.DotNet.DesignTools.Client.ServerException: Failed to launch the design tools server process.
11:16:43:420	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:16:43:420	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:16:43:420	                           at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
11:16:43:420	                        --- End of stack trace from previous location where exception was thrown ---
11:16:43:420	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:16:43:420	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:16:43:420	                           at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<LaunchAsync>d__28.MoveNext()
11:16:43:420	                        --- End of stack trace from previous location where exception was thrown ---
11:16:43:420	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:16:43:420	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:16:43:420	                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
11:16:43:420	                        --- End of stack trace from previous location where exception was thrown ---
11:16:43:420	                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
11:16:43:420	                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
11:16:43:420	                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()
11:16:43:420	
11:16:43:420	                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
11:16:43:527	[11:16:43.487182] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by elachlan** [comment] 2023-12-20 23:33
@PascalWillems does it work with .NET 6, 7, or 8?

**Comment by PascalWillems** [comment] 2023-12-21 07:33
@elachlan Yes, it works with .NET 6, 7 and 8. 
It seems as if the Designer is picking up the project reference to (presumably) a newer version of the System.Text.Json package than the one .NET 5 normally references in Visual Studio WinForms designer. Which is fine in itself, but fails to also gather the required subdependencies of this System.Text.Json package. Specifically the Microsoft.Bcl.AsyncInterfaces 7.0.0.0 package, which .NET versions 6 and above do reference by default? But that just makes me wonder what changed in one of the previous Visual Studio 2022 updates that made this issue appear, as it did work in Visual Studio 2022 before.

**Comment by merriemcgaw** [comment] 2023-12-21 22:54
@Shyam-Gupta do you have any ideas what changed here?

**Comment by Shyam-Gupta** [comment] 2023-12-22 00:20
@PascalWillems @merriemcgaw I can repro the issue with the steps mentioned in this bug. However, it appears that `System.Text.Json 7.0.2` version doesn't support `net5.0-windows`. AFAIK there are no changes in the designer which could impact loading of NuGet package assemblies.

On referencing this version of nuget package I see following warning in VS error list:
```System.Text.Json 7.0.2 doesn't support net5.0-windows and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.```

**Comment by merriemcgaw** [comment] 2024-02-02 21:45
Given that System.Text.Json doesn't support .NET 5, I think we're going to have to close this. The designer opens the designtoolsserver.exe process in the target framework specified by the app. If the target framework isn't supported I can see why the form would not load in the designer. I'd call this by design.

**Comment by PascalWillems** [comment] 2024-02-06 11:26
@merriemcgaw I understand that it is difficult to put time into issues of unsupported functionality.
It is just a shame that this makes the Windows Forms designer unusable giving the .NET 5 constraint I have at the moment.

As one last side note though, System.Text.Json 7.0.2 actually **works** fully under .NET 5 (from our use case). It just seems that dependency resolving inside the Windows Forms designer/Visual Studio 2022 changed in a way that it now breaks the designer only.

**Comment by Shyam-Gupta** [comment] 2024-02-12 23:00
I guess it worked earlier in WinForms designer because earlier the designer's child process wasn't using `System.Text.Json`. It was using `Newtonsoft.Json` instead. However, due to technical limitations we cannot revert to `Newtonsoft.Json`.

**Comment by elachlan** [comment] 2024-02-12 23:13
@PascalWillems based on @Shyam-Gupta's comment above. I suggest maybe trying to use `Newtonsoft.Json` instead if you cannot upgrade to a newer version of .NET.

**Comment by PascalWillems** [comment] 2024-02-13 07:41
@elachlan indeed that is also what I would expect. And for certainty sake I tested this quickly, replacing `System.Text.Json` with `Newtonsoft.Json` does work and could provide a workaround in some scenario's.

@Shyam-Gupta Is there a recommended path for us "outsiders" to research changes and found out that the Windows Forms designer process switched to `System.Text.Json` in this case, using something like the WinForms GitHub repo, .NET Reference Source or similar?
Often if there is an issue like this, having the ability to investigate this on your own can produce a solution or workaround sooner (and with more insight into what is actually happening).

Assuming we can conclude this issue (being an unsupported configuration), is something that won't get fixed, it may be closed for me.

**Comment by Shyam-Gupta** [comment] 2024-02-13 19:16
@PascalWillems Since WinForms designer source code is not open source, it is not available on GitHub or .NET Reference.
Only way I can think of is through VS Feedback channel or through issues like these.

FYI: @merriemcgaw

**Closed** 2024-02-14 21:11 UTC
Labels: area-VSDesigner, untriaged
