### ISSUE TITLE
Font size of Form and controls are changed a little bigger by default

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#1122] opened 2019-06-12 09:45 UTC
* .NET Core Version: .Net Core 3.0 Preview7 3.0.100.12367 build from master branch
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
1.	Create 2 apps, one is  a .Net Core Winforms app and another is a .Net framework Winforms app, which have same designer code with some controls added.
[FrameworkApp.zip](https://github.com/dotnet/winforms/files/3280698/FrameworkApp.zip)
[CoreApp.zip](https://github.com/dotnet/winforms/files/3280699/CoreApp.zip)

2.	Build and run these 2 apps, and compare size of forms and controls 

**Actual behavior:** 
Size of Form and controls are different for .Net Core and .Net framework, .Net Core app is a little bigger. This is a regression issue in Core.
![image](https://user-images.githubusercontent.com/26474449/59341037-f5ac6600-8cbb-11e9-92c2-dfb72f7040d9.png)

**Expected behavior:**
They should have same size.

**Comment by merriemcgaw** [comment] 2019-06-12 19:15
I believe these should now be different because of the new default font work in #656 that was recently merged. We had to do this before we shipped our Go-Live so that customers would adjust their apps if needed based on this new more modern default.

**Comment by merriemcgaw** [comment] 2019-06-12 23:28
We're going to close this as by design due to #656

**Closed by merriemcgaw** 2019-06-12 23:28 UTC
