### ISSUE TITLE
UserControls inside another UserControl are not scaled in PerMonitorV2 HDPI mode

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#6440] opened 2021-12-29 14:19 UTC
* .NET Core Version: 
6

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

If you place UserControl with AutoScaleMode = Inherit inside another UserControl with AutoScaleMode = Inherit, the control will not be scaled when moving the form to another screen with different dpi.

**Expected behavior:**
scale the control, including any child controls

**Minimal repro:**
Sample project attached. My screen setup is 100% primary screen and 150% secondary screen.
The project consists of a single Form with AutoScaleMode = Dpi and a UserControl with AutoScaleMode = Inherit. Inside this UserControl is another UserControl with AutoScaleMode = Inherit, too
Application.SetHighDpiMode is called in Program.cs
The screenshot shows the form on a non-primary screen and a primary one. On the non-primary screen, only the outer UserControl is scaled, not the inner one

![image](https://user-images.githubusercontent.com/3384955/147671362-08471a29-400a-4171-b852-d34013045fb2.png)

[DpiTest2.zip](https://github.com/dotnet/winforms/files/7789237/DpiTest2.zip)

**Comment by filipnavara** [comment] 2022-01-03 15:37
I think this is duplicate of https://github.com/dotnet/winforms/issues/6152 and it's been fixed both on `main` branch and in servicing (still unreleased?).

**Closed** 2022-06-21 09:35 UTC
Labels: area: HDPI PMv2
