### ISSUE TITLE
TreeNodeCollection.AddRange has been broken in .NET 8 and no longer results in TreeNodes being drawn at the correct location

### ISSUE THREAD

**Issue by rossgurbutt** [dotnet/winforms#11243] opened 2024-04-19 14:52 UTC
### .NET version

8.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 7 and previous

### Issue description

When adding a collection of `TreeNode`s to a `TreeNodeCollection `(as part of a `TreeView`) using `AddRange`, the nodes are added correctly to the collection of nodes on the `TreeView `object, but are assigned y-positions on the underlying control that do not correspond to their indices within the collection. This then results in the `TreeNode`s being drawn in a different position within the control to the location they were added at in the `TreeNodeCollection`.

Potentially related to part of #8768, although different because this behaviour used to work as recently as NET 7 and is unrelated to sorting.

### Steps to reproduce

For a `TreeView `that starts with an expanded root and child node.
- Call `AddRange `with nodes {"a0", "b0", "c0"}
- Call `AddRange `with nodes {"a1", "b1", "c1"}

The result in NET 7 and previous versions was a control that looked like this:
![image](https://github.com/dotnet/winforms/assets/47542151/3c13fc70-05e2-429c-b614-4f51876b9281)

The result in Net 8 is a control that looks like this:
![image](https://github.com/dotnet/winforms/assets/47542151/c7285c5e-b422-4627-8d5d-620a49d5cb81)

Attached: A simple application that reproduces the problem:
[TreeView ordering bug.zip](https://github.com/dotnet/winforms/files/15042027/TreeView.ordering.bug.zip)

**Comment by elachlan** [comment] 2024-04-21 22:46
I went digging through it a few months ago in #10493, I wasn't able to get anywhere. 

@lonitra this bug has been filed again, I am unable to take it on due to work.

**Comment by Tanya-Solyanik** [comment] 2024-04-24 21:32
@Epica3055  - had you verified that this is a regression?

**Comment by Epica3055** [comment] 2024-04-25 02:05
@Tanya-Solyanik 

Yes, this issue was introduced by [PR 9078](https://github.com/dotnet/winforms/pull/9078)

**Comment by gpetrou** [comment] 2024-05-01 04:32
Wasn't this fixed by https://github.com/dotnet/winforms/pull/10398?
How did you reproduce this issue in current main branch?
I used the following:

```csharp
using TreeView treeView = new();
treeView.Size = new Size(80, 200);

TreeNode child = new("child");
TreeNode root = new("root", [child]);
treeView.Nodes.AddRange(root);
treeView.ExpandAll();

TreeNode a0 = new("a0");
TreeNode b0 = new("b0");
TreeNode c0 = new("c0");
root.Nodes.AddRange([a0, b0, c0]);

TreeNode a1 = new("a1");
TreeNode b1 = new("b1");
TreeNode c1 = new("c1");
root.Nodes.AddRange([a1, b1, c1]);
```

![image](https://github.com/dotnet/winforms/assets/4172445/87133c86-47a5-4c87-8fec-673a6b973d0c)

**Comment by Tanya-Solyanik** [comment] 2024-05-01 22:10
@gpetrou  - I guess that this repros only when add range is called after the native list view control had been initialized, move AddRange into the Load event handler - https://github.com/Tanya-Solyanik/winforms/commit/41ce02505c3ff703ce5f91b7f3b75d5aeceade9c

**Closed** 2024-05-09 19:21 UTC
Labels: :boom: regression-release

**Comment by MelonWang1** [comment] 2024-05-10 03:00
Verified this issue on 9.0.100-preview.5.24258.8 with dlls built from winforms repo of main branch, the issue has been fixed. TreeNodeCollection.AddRange draws the tree nodes at the correct position.
![Screenshot 2024-05-10 024607](https://github.com/dotnet/winforms/assets/94418985/0dbc6d68-59d3-4bcc-aac7-9cdc4ca37911)

**Comment by Philip-Wang01** [comment] 2024-05-24 06:33
Verified this issue on 8.0.301 with dlls built from Release/8.0 branch of WinForms repo, the issue has been fixed, test result is same as above.

**Comment by MandiMan** [comment] 2024-06-05 02:28
Verified the issue on 9.0.0-preview.5.24280.3 Test Pass build, the issue has been fixed that have the same results as above.

**Comment by rossgurbutt** [comment] 2024-06-12 08:44
@Epica3055 Thank you very much for the prompt fix for this.
@Tanya-Solyanik Do you know when the next 8.0.x release of winforms is likely to be that would therefore include the fix? It looks like no winforms releases have been made for the runtimes since April 9th.

**Comment by MelonWang1** [comment] 2024-06-20 09:01
Verified with .NET SDK 8.0.7 test pass build, this issue was fixed. Test result is same as above.
