### ISSUE TITLE
[Regression] NullReferenceException on maximized MDI child icon changes with 150% DPI

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#6535] opened 2022-01-22 08:45 UTC
* .NET Core Version: 6.0.1

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

`NullReferenceException` in `System.Windows.Forms.ToolStripItem.InvalidateItemLayout` when you try to change Icon on maximized child form (**only with 150% DPI**):

https://user-images.githubusercontent.com/17767561/150631131-044884bc-7fcf-41c0-9ebb-6f76820ccbc6.mp4

<details>
  <summary>Exception details</summary>
 
  ```
************** Текст исключения **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.ToolStripItem.InvalidateItemLayout(String affectedProperty)
   at System.Windows.Forms.ToolStripItem.set_Image(Image value)
   at System.Windows.Forms.MdiControlStrip.updateIcon()
   at System.Windows.Forms.Form.UpdateWindowIcon(Boolean redrawFrame)
   at System.Windows.Forms.Form.set_Icon(Icon value)
   at WinFormsCoreTest.Form2.button2_Click(Object sender, EventArgs e) in D:\save\projects\core tests\WinFormsCoreTest_MDI_Icon\Form2.cs:line 33
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Загруженные сборки **************
System.Private.CoreLib
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.CoreLib.dll
----------------------------------------
WinFormsCoreTest
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase (база кода): file:///C:/Users/Shapiro/Desktop/net6.0-windows/WinFormsCoreTest.dll
----------------------------------------
System.Runtime
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Numerics.Vectors.dll
----------------------------------------
System.Memory
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Memory.dll
----------------------------------------
System.Resources.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ObjectModel.dll
----------------------------------------
System.Linq
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Linq.dll
----------------------------------------
System.Collections.NonGeneric
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Runtime.Loader
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/ru/System.Windows.Forms.resources.dll
----------------------------------------
System.Private.Uri
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.StackTrace
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Immutable.dll
----------------------------------------
  ```
  
</details>

It's obvious that the regression was somehow introduced [here](https://github.com/dotnet/winforms/pull/4650).
Interesting thing to note that despite the exception, the icon changes successfully.

**Expected behavior:**
No Exception.

**Minimal repro:**
[WinFormsCoreTest_MDI_Icon.zip](https://github.com/dotnet/winforms/files/7948411/WinFormsCoreTest_MDI_Icon.zip)

**Comment by RussKie** [comment] 2022-01-24 00:03
Win7 or Win7SP1?

**Comment by RussKie** [comment] 2022-01-24 00:07
@Olina-Zhang are you able to repro the issue?

**Comment by kirsan31** [comment] 2022-01-24 05:44
> Win7 or Win7SP1?

Win7SP1 of course, sorry.
It's 100% reproducible on our machine.

**Comment by Lydia-Shi** [comment] 2022-01-25 03:02
@RussKie Verified this issue with new latest .NET 7.0.100-alpha.1.22071.3, we cannot reproduce it on Win7SP1, and it also cannot reproduce in NET 6.0, please see below GIF:
![NotReproInWin7](https://user-images.githubusercontent.com/54019172/150899294-f028ae23-59ab-4a95-96d0-6241e870f023.gif)

**Comment by RussKie** [comment] 2022-01-25 04:07
Thank you @Lydia-Shi.
@kirsan31 are you able to debug this?

**Comment by kirsan31** [comment] 2022-01-25 07:32
I've created a fresh VM with Win7SP1 and can not repro it too :( I will try to do remote debug or may be to create a full dump...

**Comment by kirsan31** [comment] 2022-01-25 14:00
It's something not trivial happens here after `LayoutTransaction.DoLayout` call:

![image](https://user-images.githubusercontent.com/17767561/150988914-f1e16239-c930-4c86-b103-25fbfd3350df.png)

😕

**Comment by dreddy-work** [comment] 2022-01-27 01:26
@kirsan31 , is this consistent repro? I remember some other user pointed to same code in a different issue.

**Comment by Lydia-Shi** [comment] 2022-01-27 02:06
Verified this issue on 150%, 200%, 300%, there is no exception thrown and we can change Form icon successfully on maximized MDI Form.

**Comment by kirsan31** [comment] 2022-01-27 07:43
@dreddy-work 

> is this consistent repro? I remember some other user pointed to same code in a different issue.

Yes it's 100% repro on 4 tested machines (see my comments below).

@Lydia-Shi 

> Verified this issue on 150%, 200%, 300%, there is no exception thrown and we can change Form icon successfully on maximized MDI Form.

The problem is in DPI awareness of original repro. It was originally set through `App.config` and works not on all systems. The video in 1 post (Win7) was made with original repro and as you can see the app is DPI aware. If we add this to `Program.cs`:
```cs
#if NETCOREAPP
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
#endif
```

then bug will be repro everywhere. I've updated repro app in first post. Sorry for confusion here :blush:

P.s. the bug exist on latest 7.0 too.

**Comment by Lydia-Shi** [comment] 2022-01-27 08:25
@kirsan31 Yeah, you are right, we can reproduce this issue on 150%, 175% when setting HighDpiMode to SystemAware, and cannot repro on 200%, 225%, 250%. [CallStack.txt](https://github.com/dotnet/winforms/files/7948810/CallStack.txt)

**Comment by kirsan31** [comment] 2022-01-29 10:34
@dreddy-work 
I've spend some time on this problem and found some interesting things.
NullReference of course just getting fixed with this : `Owner.Invalidate();` -> `Owner?.Invalidate();`. After this all seems working as expected, but it's not true (at least on 175% DPI) - see below.
The root of the problem lies in changing the height of the `MenuStrip` during icon change.

Icon containers in this repro contain two sizes of icons - 16 and 32. Now see videos below:
 
125% DPI (16x16 icon is used in both cases):

https://user-images.githubusercontent.com/17767561/151656285-4009ffcc-016c-416a-8189-557a376365b4.mp4

200% DPI (32x32 icon is used in both cases):


https://user-images.githubusercontent.com/17767561/151656801-cbd09ddb-e407-44bd-a3f0-ddff8104cf47.mp4

Now 150% DPI (with `Owner?.Invalidate();` fix):

https://user-images.githubusercontent.com/17767561/151656839-2adeb6e4-08f5-4923-9bc1-a77f3fd7f385.mp4

As you can see red icon is 16x16 and pause icon is 32x32.
Then I looked into my icons:
![image](https://user-images.githubusercontent.com/17767561/151656919-02f00676-e907-4c19-bbb3-f76bc40dbff9.png)

After I edited the pause icon like this: 
![image](https://user-images.githubusercontent.com/17767561/151656966-a061cdc5-44a8-4322-8217-e417a2ee965f.png)
The problem at 150% is expected to go away. And I was completely sure that the source of the problem was the wrong choice of icons for the border dpi... But this is where 175% dpi comes into play.

175% DPI (with `Owner?.Invalidate();` fix):

https://user-images.githubusercontent.com/17767561/151657067-3e01bf54-f891-4217-aef7-c48ad060ca32.mp4

As you can see both icons are 32x32 but `MenuStrip` still slightly change it's height - NullReference will throw any way.

Let's summarize, we have 3 problems here:

1. NullReference itself. Can be fixed with `Owner?.Invalidate();` or maybe owner shouldn't become null anyway?
2. Wrong icon size selecting with some DPI (150% in our case). It depends on the order of the icons in the container, which is wrong.
3. At some DPI (175% in our case) `MenuStrip` height calculating differently with different icons of same size.

**Comment by jbhensley** [comment] 2022-01-29 14:35
I found this issue curious and started to look into it yesterday. I discovered exactly what you have found. Namely that DPI isn't really the problem. It will repro on 100% DPI if you use an overly large image. Unfortunately, I haven't had time to do any further research. 

Here is where my debugger is sitting this morning. I'm on a breakpoint where `Owner` is about to be set to `null`. Now, somewhere between `ToolStripItem.InvalidateItemLayout` (highlighted at the bottom of the call stack in the image below) and `SetOwner` (at the top of the stack) we have a place where the code deviates in what it does between the "good" case and the "bad" case. My plan of attack was to isolate exactly where that is, which will hopefully be enlightening. I might not get to this for a few days, but maybe it helps you.

![image](https://user-images.githubusercontent.com/13544395/151664797-f549aef8-c075-4ade-bdf7-8fb3b12323f3.png)

**Comment by RussKie** [comment] 2022-01-29 20:02
@kirsan31 @jbhensley thanks for looking further into this, assigning to you for now. Please holler back if you get stuck. 

If this issue does not repro on .NET Framework 4.6, 4.7 and 4.8, it is probably a good idea to bisect and try to establish which commit has introduced the regression.

**Comment by kirsan31** [comment] 2022-01-29 20:21
@RussKie this issue physically can't repro on .NET Framework because [this](https://github.com/dotnet/winforms/issues/4621) was [fixed](https://github.com/dotnet/winforms/pull/4650) only in .Net6. And as I said in [1 post](https://github.com/dotnet/winforms/issues/6535#:~:text=It%27s%20obvious%20that%20the%20regression%20was%20somehow%20introduced%20here.):

> It's obvious that the regression was somehow introduced [here](https://github.com/dotnet/winforms/pull/4650).

But as far as i can tell #4650 not introduced new bugs, but uncovered old ones.

**Comment by jbhensley** [comment] 2022-01-31 20:01
I've submitted a fix for the NRE. It's a doozy.

As for slight variations in icon size of two originally same-sized icons at different DPI, I did not investigate that further but suspect we're dealing with rounding differentials in the scaling logic. I'm not sure if that rises to the level of being an actual concern.

I think that covers everything, but let me know if I'm overlooking something.

**Comment by RussKie** [comment] 2022-02-01 05:00
Great discussions. I'm not sure what else we can do except ignoring the size discrepancy and rendering the given icon.

**Closed** 2022-02-02 00:12 UTC
Labels: :beetle: bug, area: HDPI SA, :construction: work in progress, area: MDI

**Comment by Lydia-Shi** [comment] 2022-02-08 06:53
Verified this issue with latest .NET 7.0.100-preview.2.22103.2 from main branch, this issue is fixed. There is no exception when changing Form icon on 150%&175%.

**Comment by Lydia-Shi** [comment] 2022-02-23 09:14
Verified this issue with .NET 6.0.3 TP, this issue is fixed.

**Comment by Olina-Zhang** [comment] 2022-03-08 03:22
Verified with .NET SDK 7.0.100-preview.2.22152.5 test pass build, this issue is fixed.
