### ISSUE TITLE
Korean localization font issue

### ISSUE THREAD

**Issue by shaoht** [dotnet/winforms#10774] opened 2024-01-31 07:33 UTC
### Description

In 200 dpi mode, I set default font to old font that framework used, `Application.SetDefaultFont(new Font(new FontFamily("Microsoft Sans Serif"), 8.25F, FontStyle.Regular, GraphicsUnit.Point, 0))`, the font of toolstrip and datagridview is different in Korean. If set default font to "Segoe UI", the font of toolstrip and datagridview is same in Korean.
Sample code: [TestKoreanWinform.zip](https://github.com/dotnet/runtime/files/14108547/TestKoreanWinform.zip)

BTW, "Microsoft Sans Serif" seems ok in 100 dpi mode.
![image](https://github.com/dotnet/runtime/assets/42145457/94994bfc-5cc0-4cc0-91df-4bf5f085f5e8)
![image](https://github.com/dotnet/runtime/assets/42145457/0f30dfb9-bfd1-4cfe-8722-84e7370d2e99)

### Reproduction Steps

In 200 dpi mode, build TestKoreanWinform project and run TestKoreanWinform.exe.

### Expected behavior

The font of toolstrip and datagridview is same in Korean.

### Actual behavior

The font of toolstrip and datagridview is different in Korean.

### Known Workarounds

set ToolStrip.Font to the desired font for each toolstrip (or define a base class for all your toolstrips that sets the desired font).

**Comment by elachlan** [comment] 2024-02-01 03:10
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment] 2024-02-02 06:03
We can repro it with different .Net Versions. Is it a duplicate of GH issue: https://github.com/dotnet/winforms/issues/5391?

**Comment by elachlan** [comment] 2024-02-02 06:09
@merriemcgaw might need to chime in here if its a duplicate of #5391

**Comment by Tanya-Solyanik** [comment] 2024-02-03 22:40
Yes, this is a duplicate of #5391 
@shaoht  - as a workaround you could set ToolStrip.Font to the desired font for each toolstrip (or define a base class for all your toolstrips that sets the desired font).

**Comment by shaoht** [comment] 2024-02-05 02:46
Thanks @Tanya-Solyanik, I'll have a try.

**Comment by merriemcgaw** [comment] 2024-02-07 22:02
We will leave this open, rather than reopening the old one (#5391) since we've got a discussion going on this now. I think this is workaround-able, but it is something we want to address due to the user feedback. I'll circle back with my team and get someone assigned to get it sometime in .NET 9, unless a community member jumps in first.

**Comment by merriemcgaw** [comment] 2024-02-07 22:04
@Tanya-Solyanik assign as you see fit.

**Comment by Tanya-Solyanik** [comment] 2024-02-11 23:51
@LeafShi1 , @Epica3055 , @SimonZhao888 , @ricardobossan  - when you have time, please extend Application font to apply to ToolStrips. We would code this fix under a new AppContext switch (for example - ApplyApplicationFontToMenus).

**Comment by LeafShi1** [comment] 2024-02-18 07:56
> @LeafShi1 , @Epica3055 , @SimonZhao888 , @ricardobossan - when you have time, please extend Application font to apply to ToolStrips. We would code this fix under a new AppContext switch (for example - ApplyApplicationFontToMenus).

I will investigate this issue.

**Closed** 2024-03-01 01:50 UTC
Labels: tenet-compatibility, :construction: work in progress, area-Controls-StripControls, Font

**Comment by Nora-Zhou01** [comment] 2024-03-07 07:10
Verified this issue in the latest .Net 9.0 SDK build: 9.0.100-preview.3.24156.5, it was fixed. The font of toolstrip and datagridview is same in Korean.

https://github.com/dotnet/winforms/assets/104609169/e6cf44c3-4f61-4559-817c-9e0c5c96993a

**Comment by Philip-Wang01** [comment] 2024-03-27 07:05
Verified this issue with 9.0.0-preview.3.24175.24 test pass build, it was fixed. Test result is same as above.
