### ISSUE TITLE
RichTextBox `LinkClicked` event doesn't work for "friendly named" hyperlinks

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1631] opened 2019-08-14 13:04 UTC
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**

With the removal of the quirk `Switch.System.Windows.Forms.DoNotLoadLatestRichEditControl` (https://github.com/dotnet/winforms/pull/1139/commits/3f2ca8a2a3e19ea7431279defcebec14e2ca59ea) we may regress because we will use newer RTB controls (4.0+) and users will no longer be able to load older RTB controls that handled some hyperlinks differently.

Please refer to https://stackoverflow.com/q/56936777/2338036

**Actual behavior:** 

**Expected behavior:**

**Minimal repro:**

**Comment by weltkante** [comment] 2019-08-14 14:58
Title might need a fix? The linked article talks about a regression in hyperlinks, not about images.

> users will no longer be able to load older RTB controls that handled some hyperlinks differently

The linked article suggests that only as a workaround for a regression in WinForms, not because the RTB handles hyperlinks differently. RTB 5.0 has a "friendly name hyperlink" feature which WinForms apparently doesn't understand.

So while your argument that downgrading to older RTB controls is no longer possible is true, for the linked problem the "right thing to do" would be to fix the bug in WinForms, not having people work around it by using older RTB versions.

**Comment by r-aghaei** [comment] 2019-08-14 15:11
@RussKie The linked SO question is about `LinkClicked` event. 

I also tried editing an image (PBrush object class) in `RichTextBox` which worked as expected in both .NET Core and .NET Framework.

**Comment by RussKie** [comment] 2019-08-14 16:08
Yes, thank you - looked at the wrong title in the original ticket.

**Comment by zsd4yr** [comment] 2019-08-16 17:23
@RussKie @weltkante It sounds to me like we now use RTB 5.0 and that there is additional work to support functionality new to 5.0 that we have not wrapped appropriately; does that sound right?

**Comment by weltkante** [comment] 2019-08-16 17:46
@zsd4yr thats what the linked stackoverflow article says in the reseponse marked as answer, it's pretty detailed in outlining the problem in the WinForms implementation leading to events not firing.

**Comment by RussKie** [comment] 2019-08-16 19:30
Right now we have a broader issue of link clicked events not working at all - https://github.com/dotnet/winforms/issues/1644

**Comment by weltkante** [comment] 2019-08-16 20:00
#1644 works when initialization is moved from constructor to load event, so its not related to hyperlinks, it seems to be a general pattern that in .NET Core there's a problem when things are initialized in the constructor

**Comment by weltkante** [comment] 2019-08-19 13:30
Should be tested again once PR #1661 is in.

**Comment by weltkante** [comment] 2019-08-19 13:32
~~Should be tested again once PR #1661 is in.~~

[edit] posted this on the wrong issue, this one is not related, sorry. Can't seem to remove the issue link by deleting the post, so I'll mark it hidden instead.

**Comment by RussKie** [comment] 2019-08-20 06:00
Duplicate of #1520

**Comment by weltkante** [comment] 2019-08-20 07:04
@RussKie this is not a duplicate, #1520 is not about friendly name links at all, it is about Process.Start having changed semantics.

**Comment by RussKie** [comment] 2019-08-20 14:59
We've discussed it with our testers, who have submitted #1520, and it was resolved as reporting the same issue.
The screenshot is misleading indeed, and it threw few people off the right track.

**Comment by weltkante** [comment] 2019-08-20 16:11
@RussKie considering you said in PR #1661 that Issue #1520 will be fixed by said PR, this issue can't be a duplicate.

This repros on Desktop Framework and I'd assume it also repros in .NET Core. It is the problem the stackoverflow article was about, a regression in the Desktop Framework long ago (by updating to a newer version of the RTF control which supported features WinForms doesn't understand).

Of course you are free to repriorize, it might not be necessary to fix for 3.0 since it repros on Desktop Framework by default and the only thing you took away is the known workaround to downgrade the RTF control.

```C#
using System;
using System.Drawing;
using System.Windows.Forms;

public class Form1 : Form
{
    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.Run(new Form1());
    }

    private RichTextBox richTextBox1;

    public Form1()
    {
        richTextBox1 = new RichTextBox();
        richTextBox1.Dock = DockStyle.Fill;
        richTextBox1.LinkClicked += richTextBox1_LinkClicked;
        ClientSize = new Size(640, 480);
        Controls.Add(richTextBox1);
        Load += Form1_Load;
    }

    private void Form1_Load(object sender, EventArgs e)
    {
        richTextBox1.Rtf = @"{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang4105{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
{\*\generator Riched20 10.0.17134}\viewkind4\uc1 
{\field{\*\fldinst { HYPERLINK ""http://www.google.com"" }}{\fldrslt {Click here}}}
\pard\sa200\sl276\slmult1\f0\fs22\lang9  for more information.\par
}";
    }

    private void richTextBox1_LinkClicked(object sender, LinkClickedEventArgs e)
    {
        MessageBox.Show($"link {e.LinkText} clicked");
    }
}
```

**Comment by RussKie** [comment] 2019-08-20 17:43
@weltkante thank you for being persistent.
I have run this scenario locally and, you're right, it is still broken.

**Comment by RussKie** [comment] 2019-08-22 19:26
@JeremyKuhne @Tanya-Solyanik  can you think of any implications if we remove the following check?
https://github.com/dotnet/winforms/blob/d98947638f53765c79a2436cce2d9445e865a331/src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs#L3498-L3501

I have run few tests with few different rtfs and everything seemed to work.

This check was presumably added in response to "VSWhidbey 504502" bug, but I don't know where to find it.

**Closed** 2019-09-04 20:27 UTC
Labels: Regression, bug, tenet-compatibility

**Comment by Marie-Shi** [comment] 2019-09-10 08:13
Verified this bug with .Net core 3.0.100-rc1-014190 from release branch, RichTextBox `LinkClicked` event can work for "friendly named" hyperlinks. Please see the following Gif:
![RichTextBox_LinkClicked](https://user-images.githubusercontent.com/45864017/64596012-b50cd780-d3e5-11e9-9f48-7306391db4cd.gif)

**Comment by liquidboy** [comment] 2020-05-21 04:46
just like to chime in and say how much of a pain this is, just encountered it

**Comment by merriemcgaw** [comment] 2020-05-21 17:14
Have you tried adding the setting which reverts back to the older RTB in .NET 4.8?
`<runtime>
  <AppContextSwitchOverrides value="Switch.System.Windows.Forms.DoNotLoadLatestRichEditControl=true" />
</runtime>`

If this is a significant problem that the apps config file I would suggest you use VS Feedback to report the problem and tell us how this is impacting the Autodesk app in particular. We can look into what can be done. Though to set expectations, .NET Framework 4.8 is in servicing only mode and the bar for fixes is quite high. It would be good to get this reported though so we can keep track of the impact.
