### ISSUE TITLE
WinForms Designer Hangs on a form with a large number of controls as of VS 17.5

### ISSUE THREAD

**Issue by alwilton** [dotnet/winforms#8758] opened 2023-03-07 16:09 UTC
### Environment

VS 17.5.1

### .NET version

.NET 6

### Did this work in a previous version of Visual Studio and/or previous .NET release?

The problem does not exist in VS 17.4

### Issue description

When opening a form with 2700+ Telerik controls and simply trying to save the form, VS hangs. The CPU varies but goes to 90%+ and the memory used climbs to use all available (64 GB), The form never saves (tried up to 8 hours). This did not happen under VS 17.4.

### Steps to reproduce

create a form with 2700+ Telerik controls and open in the designer then try to save the form

### Diagnostics

```text
unable due to the hang.
```

**Comment by RussKie** [comment] 2023-03-08 10:22
> create a form with 2700+ Telerik controls and open in the designer then try to save the form

But why?

**Comment by alwilton** [comment] 2023-03-09 01:51
But why does it hang? That is a great question.

But why 2700+ controls? Because I am not finished porting over a legacy Delphi application that has 3200+ controls. That form loads in Delphi instantly and does not crash when adding and moving controls which it also does instantly. The application loads 10x faster and runs faster. Why port it over? To gain a current support team as Delphi developers are scarce.

Why not convert to user controls? I see that as the tail wagging the dog. If I go back to .NET Framework, the current application  can be worked on OK (very slow, but it can be worked on). Why should I be forced to change things because of .NET? Shouldn't it support existing applications? Sorry to be blunt, but with current programming and 64 bit shouldn't this be handled easily and gracefully? The fact that we are in .NET 7 going on .NET 8 and VS cannot handle a moderately complex WinForms is shameful. 

One might say that I don't understand the complexities of converting VS over to .NET WinForms designer? One thing that I have learned in my life both professionally and personally is that in the end no one cares about how hard something is and how much work it is, the only thing that matters is results.

At this time the efficiency and stability of the WinForms designer is far from satisfactory. Again, I apologize for being blunt. It is very frustrating to work in such an unstable environment. It is even more frustrating to have a "new and better" VS 17.5 which comes out and breaks what kind of worked in 17.4

**Comment by elachlan** [comment] 2023-03-09 03:18
Is it even possible to have a form with 3200 controls? Winforms has a handle per control, you will run into handle starvation and receive OOM errors if you add much more controls. Moving your app to lazy load controls would massively reduce your memory/handle usage.

.net framework had the same issue, I moved to lazy loading because the designer was painfully slow for some of the larger forms with 10+ tabs.

That being said, it would be nice if the designer could handle it. What is the minimum number of controls that causes the issue?

**Comment by alwilton** [comment] 2023-03-09 22:35
I’m away from the office until Monday. Rather than estimate I’ll give you the exact number then. I could also upload the form if there is a way to do it privately. The form itself has no binding or events, that is all done in code so the form can load with an empty code file. The form has about 20 tab pages, many with sub tabs. Taken one tab at a time, it is not all that busy. There are just a great many data points that are related and need to be shown on one form.

**Comment by merriemcgaw** [comment] 2023-03-10 20:48
Please file a VS Feedback ticket and post the link here. When you use that system you can upload your files privately. If you post the link to me I'll take it over immediately.

**Comment by alwilton** [comment] 2023-03-13 15:03
this is posted as [WinForms Designer Hangs on a form with a large number of controls as of VS 17.5](https://developercommunity.visualstudio.com/t/WinForms-Designer-Hangs-on-a-form-with-a/10308304)

**Comment by Philip-Wang01** [comment] 2023-03-14 08:34
Changed the status of the feedback to under investigation and verified this in a different environment.
In VS 17.4.5, opening the MainForm about 90 seconds and then saving the Form after resizing it takes about **30** seconds.
In VS 17.5.1, opening the MainForm about 90 seconds and then saving the Form after resizing it, VS is not responding.
In VS 17.5.1 + vsix, opening the MainForm about 90 seconds and then saving the Form after resizing it takes about **300** seconds.

**Comment by KlausLoeffelmann** [comment] 2023-08-29 00:47
We have improved the performance in this area in 17.6 and then again in 17.8 (current in Preview).
If you still see considerable performance regressions going forward, please create a new issue with your scenario description. Please test any new scenarios first with at least Visual Studio 17.8 Preview 2.

Closing this as fixed.

**Closed by KlausLoeffelmann** 2023-08-29 00:47 UTC
Labels: area-VSDesigner
