### ISSUE TITLE
The default value is not displayed in the correct position after setting SelectedObject property for PropertyGird control

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#4593] opened 2021-02-23 08:33 UTC
* .NET Core Version: .Net SDK 6.0.100-preview.2.21120.3, .Net SDK 5.0.104 from March 2021 Update Test Pass

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
The default value is not displayed in the correct position after setting SelectedObject property for PropertyGird control. It seems to be displayed in the upper left corner of the propertygrid.
![image](https://user-images.githubusercontent.com/45864649/108816650-81316c00-75f1-11eb-8acf-606c391b87d7.png)
![step1](https://user-images.githubusercontent.com/45864649/108818313-24838080-75f4-11eb-9558-d09cb32590ea.gif)

**Expected behavior:**
After setting the SelectedObject property for the PropertyGird control, it should display correct default values.
![image](https://user-images.githubusercontent.com/45864649/108818177-faca5980-75f3-11eb-86c2-e69ca43bd755.png)

**More Info:**
This is a regression issue, it cannot reproduce on .Net SDK 5.0.103 and .Net SDK 6.0.100-preview.2.21111.1, but can reproduce on **.Net SDK 5.0.104 from March 2021 Update Test Pass and .Net SDK 6.0.100-preview.2.21112.1**.

**Minimal repro:**

1. Create a WinForms .Net Core application.
2. Add a PropertyGird control to Form.
3. Press F4 to go to the Property Browser Window, set its SelectedObject property to Form1.
4. Build and run the application, observe the PropertyGrid.

Or

1. Extract the attached project and open it.
[Test.zip](https://github.com/dotnet/winforms/files/6027544/Test.zip)

2. Build and run this application, observe the PropertyGrid.

**Comment by RussKie** [comment] 2021-02-24 08:01
This is a regression surfaced by https://github.com/dotnet/winforms/pull/4525. Before #4525 any modifications to a `Graphics` object would be correctly applied, as the code would follow this path:
https://github.com/dotnet/winforms/blob/7b6d43368dbfd7a40fd0d3e336e46418f780ee59/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs#L52-L55
Since #4525 we rely on `flags` passed into `DrawTextInternal` completely side-stepping any modifications applied to a `Graphics` object. `PropertyGrid` performs clipping and transformations when rendering values:
https://github.com/dotnet/winforms/blob/7b6d43368dbfd7a40fd0d3e336e46418f780ee59/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs#L1395-L1438

It looks like an oversight (or a sad omission during the `WindowsGraphics`-related cleanups) that the value-rendering procedure doesn't explicitly request to preserve the  graphics modifications:
https://github.com/dotnet/winforms/blob/7b6d43368dbfd7a40fd0d3e336e46418f780ee59/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs#L2365-L2366
https://github.com/dotnet/winforms/blob/7b6d43368dbfd7a40fd0d3e336e46418f780ee59/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs#L2385-L2392

...whilst the label rendering code does:
https://github.com/dotnet/winforms/blob/7b6d43368dbfd7a40fd0d3e336e46418f780ee59/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs#L2085
https://github.com/dotnet/winforms/blob/7b6d43368dbfd7a40fd0d3e336e46418f780ee59/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L5322-L5326


This looks a fix:
```diff
diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs b/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
index 75b07f49c..41f095bd6 100644
--- a/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
+++ b/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
@@ -2389,7 +2389,7 @@ namespace System.Windows.Forms.PropertyGridInternal
                 textRectangle,
                 textColor,
                 backColor,
-                (TextFormatFlags)format);
+                (TextFormatFlags)format | PropertyGrid.MeasureTextHelper.GetTextRendererFlags());
 
             ValueToolTipLocation = doToolTip ? new Point(rect.X + 2, rect.Y - 1) : InvalidPoint;
         }
```

Before | After
--|--
![image](https://user-images.githubusercontent.com/4403806/108966678-9500cf00-76d2-11eb-9d9d-16a2370d9790.png) |  ![image](https://user-images.githubusercontent.com/4403806/108966178-fb392200-76d1-11eb-812e-e00d302e4dcd.png)


May also worth adding this as a guard:
```diff
diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs b/src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
index d05a1e8f5..05272586f 100644
--- a/src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
+++ b/src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
@@ -2,6 +2,7 @@
 // The .NET Foundation licenses this file to you under the MIT license.
 // See the LICENSE file in the project root for more information.
 
+using System.Diagnostics;
 using System.Drawing;
 using System.Drawing.Text;
 using static Interop;
@@ -603,7 +604,7 @@ namespace System.Windows.Forms
         /// </summary>
         private static ApplyGraphicsProperties GetApplyStateFlags(IDeviceContext deviceContext, TextFormatFlags textFormatFlags)
         {
-            if (deviceContext is not Graphics)
+            if (deviceContext is not Graphics graphics)
             {
                 return ApplyGraphicsProperties.None;
             }
@@ -619,6 +620,16 @@ namespace System.Windows.Forms
                 apply |= ApplyGraphicsProperties.TranslateTransform;
             }
 
+            Debug.Assert(apply.HasFlag(ApplyGraphicsProperties.Clipping)
+                || graphics.Clip is null
+                || graphics.Clip.GetHrgn(graphics) == IntPtr.Zero,
+                "Must preserve Graphics clipping region!");
+
+            Debug.Assert(apply.HasFlag(ApplyGraphicsProperties.TranslateTransform)
+                || graphics.Transform is null
+                || graphics.Transform.IsIdentity,
+                "Must preserve Graphics transformation!");
+
             return apply;
         }
     }
```

**Comment by JeremyKuhne** [comment] 2021-02-24 19:10
Your fix looks right, and I like the assert.

**Comment by merriemcgaw** [comment] 2021-02-24 23:02
Agreed - we should get this in 5.0.5 for sure.

**Comment by kirsan31** [comment] 2021-02-25 08:25
Am I understand right, that this regression will be introduced in 5.0.**4** anyway?

**Comment by RussKie** [comment] 2021-02-25 09:47
5.0.4 has been snapped few weeks ago, and is about to be released. Unfortunately it is too late in the cycle to undo or fix it in this release.
Sadly we messed it up, sorry.

________________________________

**Comment by kirsan31** [comment] 2021-02-25 09:51
Thanks for the info (forewarned is forearmed). We need to stick with 5.0.**3** then...

**Comment by RussKie** [comment] 2021-02-25 09:54
This issue will noted in the release notes, I just hadn't have a chance to add it yet.
________________________________

**Comment by RussKie** [comment] 2021-02-25 23:07
I've updated the known issues docs, these will be published when 5.0.4 and 6.0p2 are released

**Closed** 2021-03-02 23:37 UTC
Labels: :boom: regression, :construction: work in progress, Priority 0 :fire:

**Comment by RussKie** [comment] 2021-03-10 07:25
The changelog is updated to reflect the state of the current release.

**Comment by kirsan31** [comment] 2021-03-10 07:29
> The changelog is updated to reflect the state of the current release.

Forgot to post link of the doc - sorry :( I meant this: https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-known-issues.md
![image](https://user-images.githubusercontent.com/17767561/110592584-882cb280-818b-11eb-8908-6bdd1dadfa1c.png)

**Comment by kirsan31** [comment] 2021-03-10 10:27
@RussKie Any advice how to specify **exact runtime version** with framework-dependent applications?
[`RuntimeFrameworkVersion`](https://docs.microsoft.com/en-us/dotnet/core/versions/selection) doesn't work :(((

> For framework-dependent applications, the `RuntimeFrameworkVersion` specifies the minimum required runtime framework version.

**Comment by RussKie** [comment] 2021-03-17 00:18
I'm afraid I don't know enough about the .NET deployments via the WU. Manually it is possible to install the runtimes side-by-side. 
Please direct any questions about the WU to the dotnet/sdk repo.

You can define how you wish the runtime to be resolved, please check https://github.com/dotnet/runtime/blob/main/docs/design/features/framework-version-resolution.md
You may also find this useful: https://docs.microsoft.com/dotnet/core/deploying/runtime-patch-selection

**Comment by Zheng-Li01** [comment] 2021-03-22 07:22
Verified the issue with latest 6.0.100-preview.3.21169.6, the issue has been fixed that the PropertyGird control display correctly as below screenshot.
![image](https://user-images.githubusercontent.com/38325459/111953850-27559080-8b22-11eb-9822-3ec44c3520d7.png)

**Comment by Jessie-Zhang01** [comment] 2021-03-22 08:13
Verified the issue with .Net SDK 5.0.202 from April 2021 Update Test Pass, this issue is fixed. 
![image](https://user-images.githubusercontent.com/45864649/111959477-794de480-8b29-11eb-83b5-b8792439e545.png)
