### ISSUE TITLE
CopyPaste of button copies events too (designer)

### ISSUE THREAD

**Issue by PasaOpasen** [dotnet/winforms#3515] opened 2020-06-26 13:45 UTC
1. create botton

2. double click to create event

3. copy and paste this button

4. double click -- u will see old event

**Comment by weltkante** [comment] 2020-06-26 15:29
I think thats working as intended, that also happened in Desktop Framework and for what its worth very useful behavior, otherwise you couldn't move controls form one panel into another using the clipboard. We even use this feature to copy controls from one form into another (just have to make sure we copy code-behind first, if the events aren't already there they are dropped.)

**Comment by PasaOpasen** [comment] 2020-06-28 09:12
@weltkante The main problem is that I cannot create event of new button by double click (by desiner). I think it's inconvenient

**Comment by Zheng-Li01** [comment] 2020-06-29 01:39
@PasaOpasen, thanks for raising the issue, and  have a [Designer Issue](https://github.com/dotnet/winforms-designer/issues/1769) to track it.

**Comment by merriemcgaw** [comment] 2020-11-03 19:48
@Zheng-Li01 please confirm that this is working now - it should have made it into 16.8 release. You can close this issue when you confirm it.

**Comment by Zheng-Li01** [comment] 2020-11-04 02:15
Verified the issue with Dev16 16.8.0 Preview 6.0 installed from https://visualstudio.microsoft.com/vs/preview/, the issue has been fixed. so closed it.
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/98061333-976ebd00-1e86-11eb-89a7-05b0236da5e9.gif)

**Closed by Zheng-Li01** 2020-11-04 02:15 UTC
Labels: :beetle: bug, area: VS designer
