### ISSUE TITLE
ListView CustomDraw does not fire OnDrawSubItem with non-default column display order

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7687] opened 2022-08-29 10:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ListView-CustomDraw-does-not-fire-OnDraw/10129868)._

---
[severity:It's more difficult to complete my work]
A winforms ListView control with custom drawing enabled does not fire OnDrawSubItem for subitems which it incorrectly believes are off screen because it is ignoring the column DisplayIndex in GetSubItemRect as called from ListView.CustomDraw.

Additionally, the DrawListViewSubItemEventArgs.Bounds rect in the event is incorrect for columns which have been reordered (at least for column 0. I'm not sure about other columns)

Repro:
Create a ListView with owner drawn set true in Details view
Set the DisplayIndex for column 0 to 3. 
Horizontally scroll the list view such that column zero would be off the screen if the DisplayIndex were 0.
Note that the OnDrawSubItem is not fired for column 0, even though it is visible.

---
#### Feedback Bot on 8/25/2022, 09:57 AM: 

(private comment, text removed)
#### Amy Li [MSFT] on 8/25/2022, 04:36 PM: 

(private comment, text removed)
#### Tom Mason on 8/25/2022, 04:50 PM: 

(private comment, text removed)
#### Tom Mason on 8/25/2022, 05:42 PM: 

(private comment, text removed)
#### Amy Li [MSFT] on 8/26/2022, 05:47 PM: 

(private comment, text removed)
#### Tom Mason on 8/26/2022, 07:41 PM: 

(private comment, text removed)
#### Tom Mason on 8/26/2022, 07:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Amy-Li03** [comment] 2022-08-29 10:48
### .NET Core Version:
.NET SDK 8.0.100-alpha.1.22423.9

### Have you experienced this same bug with .NET Framework?
Yes

### Minimal repro:
[ListViewNoCustomDraw.zip](https://github.com/dotnet/winforms/files/9443818/ListViewNoCustomDraw.zip)
1. Create a WinForms .NET core project.
2. Add a ListView with OwnerDraw set true in Details view.
3. Set the DisplayIndex of column1 from 0 to 3.
4. Build and run project.
5. Shrink the window at run time such that the list view has a horizontal scroll bar.
6. Scroll the window to the Right to make sure column1 is invisible.
![ReproSteps](https://user-images.githubusercontent.com/62929087/187183357-01e62978-6faa-41fb-ace8-a0c199d02957.gif)

### More info:
1. This is a not regression issue.
2. This issue occurs on both .NET Framework and .NET Core project.

### Actual behavior:
The OnDrawSubItem is not fired for column4, even though it is visible.

### Expected behavior:
The OnDrawSubItem shoule be fired for column4.

**Comment by merriemcgaw** [comment] 2022-08-30 23:33
@Amy-Li03 can you work with the customer to understand impact and whether it is a blocking issue or if it is just annoyance. Then if it is blocking advice the customer to go the CSS route so that we can investigate a .NET Framework issue.  This does seem like resizing and scrolling does eventually allow the end user to see everything.

**Comment by Amy-Li03** [comment] 2022-08-31 01:39
@merriemcgaw got it, will get this information from customer.

**Comment by Amy-Li03** [comment] 2022-08-31 09:13
**Reply from customer:**
It’s just an annoyance. I’ve been able to work around it and other bug I found (https://developercommunity.visualstudio.com/t/Winforms-ListView-ColumnWidthChanging-ev/10129947#T-ND10135004) by adding a zero width column 0 and preventing width and column reordering changes for column 0.

**Comment by merriemcgaw** [comment] 2022-08-31 18:26
Then let's go ahead and "Won't Fix" this issue and close the feedback ticket as Low Priority. We've got much more impactful things to manage at the moment. We can always reopen if it becomes important for other customers.

**Comment by Amy-Li03** [comment] 2022-09-01 02:38
@merriemcgaw thank you!
I will close this issue as "Won't Fix", for the initial feedback ticket, due to this is a .NET runtime issue, customer can comment at here, I have closed it as duplicated to this GH issue.

**Closed by Amy-Li03** 2022-09-01 02:38 UTC
