### ISSUE TITLE
Support abstract base class in designer 

### ISSUE THREAD

**Issue by nawfalhasan** [dotnet/winforms#3329] opened 2020-05-22 09:08 UTC
**Is your feature request related to a problem? Please describe.**
Problem: Unable to open up a form that inherits from an abstract form class.

**Description:**
When a form inherits from a abstract class, the designer of the more derived type cant be opened.

**Example:**

    public abstract class FormBase : Form
    {
        protected FormBase()
        {
        }
    }

    public class FormDerived : FormBase
    {
        public FormDerived()
        {
        }
    }
 
Now `FormDerived` in the designer wouldn't open up. 

**Error when I try today:**
From the designer: 
> The designer must create an instance of type 'Xxx.Common.Presentation.Mvvm.FormBase' but it cannot because the type is declared as abstract. 

Call stack:

>at System.ComponentModel.Design.Serialization.CodeDomSerializerBase.Error(IDesignerSerializationManager manager, String exceptionText, String helpLink)
at System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager manager, CodeTypeDeclaration declaration)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host) 

**Solution I would like**: 
Opening up the form designer should work any time from VS. Just like it opens up if base class is a regular class. The designer should design the first base class which can be instantiated (walking up the inheritance chain). In the above example it would be `Form`.

**What I tried:**
This is the most commonly seen hack on internet:

    [TypeDescriptionProvider(typeof(GenericControlDescriptionProvider))]
    public abstract class FormBase : Form
    {
        protected FormBase()
        {
        }
    }

    class GenericControlDescriptionProvider : TypeDescriptionProvider
    {
        public GenericControlDescriptionProvider()
            : base(TypeDescriptor.GetProvider(typeof(ContainerControl)))
        {
        }

        public override Type GetReflectionType(Type objectType, object instance)
        {
            Type designerType = GetTypeForDesigner(objectType);
            if (designerType != null)
            {
                return designerType;
            }

            return base.GetReflectionType(objectType, instance);
        }

        public override object CreateInstance(IServiceProvider provider, Type objectType, Type[] argTypes, object[] args)
        {
            Type designerType = GetTypeForDesigner(objectType);
            if (designerType != null)
            {
                objectType = designerType;
            }

            return base.CreateInstance(provider, objectType, argTypes, args);
        }

        static Type GetTypeForDesigner(Type actualTypeVsIsTryingToDesign)
        {
            if (actualTypeVsIsTryingToDesign.IsSubclassOf(typeof(UserControl)))
            {
                return typeof(UserControl);
            }

            if (actualTypeVsIsTryingToDesign.IsSubclassOf(typeof(Form)))
            {
                return typeof(Form);
            }

            return null;
        }
    }

But then again it doesn't work flawlessly. Project has to be rebuilt sometimes, sometimes VS has to be restarted etc. Doesn't work always

**Comment by weltkante** [comment] 2020-05-22 09:30
The designer needs to instantiate the base class. It can't instantiate your subclass because that would mean baking the code you are trying to edit in the designer (i.e. recompiling after _every single edit_)

**Comment by nawfalhasan** [comment] 2020-05-22 11:03
>It may be doable if the designer instantiated a dummy-subclass of the abstract base class.

Either that, or let us have an option to control what designer should be designed. E.g. via an attribute like TypeDescriptionProvider. Unfortunately it doesnt always cleanly work.

**Comment by merriemcgaw** [comment] 2020-05-28 02:39
We'll consider an addition like this once we're fully at parity with the Framework designer.

**Comment by nawfalhasan** [comment] 2020-05-28 03:29
@merriemcgaw thanks, can't wait! :)

**Comment by StevenBonePgh** [comment] 2021-04-14 19:18
I believe this is somewhat related [to a Developer Community issue that I raised recently](https://developercommunity.visualstudio.com/t/net-5-winforms-designer-load-error-does-not-load-p/1384393). In my experiences shown there, this does _sometimes_ work in that the designer loads, but requires doing a build, then a restart of Visual Studio for the designer to be able to load the derived control successfully. So I think it is fairly close to working, but not quite there (almost a year later).

**Comment by merriemcgaw** [comment] 2021-04-30 20:37
@Olina-Zhang can your team walk through the scenario and get us an issue in the designer repo to triage soon. You can also link @StevenBonePgh's Feedback ticket he raised for more details to the team. Thanks!

**Comment by John-Qiao** [comment] 2021-05-06 06:32
@merriemcgaw I have filed the GitHub issue: [3142 ](https://github.com/dotnet/winforms-designer/issues/3142)in designer repo based on details in StevenBonePgh's Feedback ticket. And the issue still occurs in the latest VS 2019 from main branch + latest .NET 6.0 SDK from main branch environment.

**Comment by LuciferSam86** [comment] 2022-02-04 15:17
Amazing : 2022 and

- The problem is still present
- The ticket is still open
- The ticket #3142 gives 404
Is WinForms deprecated?

**Comment by RussKie** [comment] 2022-02-21 06:01
I acknowledge that the issue is known to the team, and it is on our backlog (https://github.com/dotnet/winforms-designer/issues/3142). I am afraid there is nothing else I can add to this at this point.

As a _possible_ workaround you can add pragmas, to make the base form concrete during the development:
```cs
#if DEBUG
    public class FormBase : Form
#else
    public abstract class FormBase : Form
#endif
    {
        protected FormBase()
        {
        }
    }
```

Closing due to age.

**Closed by RussKie** 2022-02-21 06:01 UTC
Labels: api-suggestion, area: VS designer, Priority 3

**Comment by nawfalhasan** [comment] 2022-02-21 06:12
https://github.com/dotnet/winforms-designer/issues/3142 can't be opened. I get a 404.

![image](https://user-images.githubusercontent.com/2478860/154899015-a80a5afc-58e9-4a61-904f-ca93e672a0c0.png)

**Comment by weltkante** [comment] 2022-02-21 07:35
> https://github.com/dotnet/winforms-designer/issues/3142 can't be opened. I get a 404.

The winforms designer is not a public repo, the team probably linked it for internal usage.
