### ISSUE TITLE
TextBox height differs when adding in .NET core and in .NET framework project.

### ISSUE THREAD

**Issue by BhaskarSuresh22** [dotnet/winforms#10989] opened 2024-03-04 15:07 UTC
### Environment

Version 17.8.5

### .NET version

.NET Core 8.0 and .NET Framework 4.8

### Issue description

When TextBox is dragged from the toolbox, the height of the TextBox control in .NET Core project differs from the .NET Framework project. In Core project, the height is 23 but in Framework project, the height is 20. Please refer to the attached samples.

In Framework sample:
![image](https://github.com/dotnet/winforms/assets/102359766/bf8342ec-f358-458f-9670-ccdc1ee9c401)

In Core sample:
![image](https://github.com/dotnet/winforms/assets/102359766/fb7b64b3-ba9b-42db-a141-e135d2d62f9f)

Samples:
[TextBox_NET_Framework.zip](https://github.com/dotnet/winforms/files/14483354/TextBox_NET_Framework.zip)
[TextBox_NET_Core.zip](https://github.com/dotnet/winforms/files/14483356/TextBox_NET_Core.zip)

### Steps to reproduce

1. Create a Windows Forms Framework project.
2. Drag the TextBox control from the toolbox and note the height.
3. Create a Windows Forms Core project.
4. Drag the TextBox control from the toolbox and notice that the height is different from the Framework sample.

**Comment by Zheng-Li01** [comment] 2024-03-05 01:59
@BhaskarSuresh22 @elachlan this is not a real issue, the root cause is that the Default Font property value of TextBox is **"Segoe UI, 9pt"** in the .NET project, and the Default Font property value of TextBox is **"Microsoft Sans Serif, 8.25pt**" in .NET Framework project, see below screenshot.
![image](https://github.com/dotnet/winforms/assets/38325459/697c67e0-5f20-4d49-8774-5dd4720bb4fe)

![10989](https://github.com/dotnet/winforms/assets/38325459/f9fc8622-32d5-4658-b6dd-af88225aa66d)

**Comment by paul1956** [comment] 2024-03-05 03:03
This is a “real issue” because customers keep tripping on it, it not something that engineering can fix at this point or even should. What is needed is a way to point someone at the available solutions when they move a project to .Net from Framework like used to exist when projects were upgraded between earlier versions of Frameworks or languages and you got an issue report or maybe just a pinned comment on new issue form with a link to explanation. While I have upgraded many projects I run into this every time and need to search for solution because I am old with a very bad memory. On Mar 4, 2024, at 4:00 PM, v-zhgl ***@***.***> wrote:﻿
@BhaskarSuresh22 @elachlan this is not a real issue, the root cause is that the Default Font property value of TextBox is "Segoe UI, 9pt" in the .NET project, and the Default Font property value of TextBox is "Microsoft Sans Serif, 8.25pt" in .NET Framework project, see below screenshot.
image.png (view on web)
10989.gif (view on web)

**Comment by kirsan31** [comment] 2024-03-05 06:37
https://learn.microsoft.com/en-us/dotnet/core/compatibility/fx-core#default-control-font-changed-to-segoe-ui-9-pt

But I think this article need to be updated with latest things like app wide font.

**Comment by merriemcgaw** [comment] 2024-03-05 19:20
@kirsan31 is 100% correct - we created the Application.DefaultFont in order to help developers migrating from Framework to Core keep the same UI they've always had without the adjsuted height based on a new default font. I am going to close this issue, but @Zheng-Li01 can you please file an issue in the docs repo to update this with information about Application.DefaultFont?

**Closed by merriemcgaw** 2024-03-05 19:20 UTC
Labels: tenet-compatibility, area-VSDesigner, untriaged

**Comment by Zheng-Li01** [comment] 2024-03-06 02:13
Filed the https://github.com/dotnet/docs/issues/39824 in the dotnet/docs repo to track.
